### ISSUE TITLE
Serbian language bug

### ISSUE THREAD

**Issue by djevrek** [morpheus65535/bazarr#100]
Got this bug when i select serbian language in subtitle languages, save, and click on any movie in "movies" tab.

`Error: 500 Internal Server Error
Sorry, the requested URL 'http://10.0.50.50:6767/movie/197' caused an error:

Internal Server Error
Exception:
LookupError("Could not find a record for 'sr-latn'",)
Traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/bazarr/bazarr.py", line 464, in movie
    return template('movie', __file__=__file__, bazarr_version=bazarr_version, no=no, details=movies_details, languages=languages, url_radarr_short=url_radarr_short, base_url=base_url, tmdbid=tmdbid)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/bazarr/views/movie.tpl", line 124, in <module>
    <td><div class="ui tiny inverted label" style='background-color: #777777;'>{{pycountry.languages.lookup(str(subtitles_file[0])).name}}</div></td>
  File "/usr/lib/python2.7/site-packages/pycountry/db.py", line 45, in load_if_needed
    return f(self, *args, **kw)
  File "/usr/lib/python2.7/site-packages/pycountry/db.py", line 128, in lookup
    raise LookupError('Could not find a record for %r' % value)
LookupError: Could not find a record for 'sr-latn'`

**Comment by morpheus65535** [comment]
Can you give me the complete filename of the subtitles of the movie you're having with?

**Comment by djevrek** [comment]
No movie, its in general settings

**Comment by morpheus65535** [comment]
The error you’ve reported here is about an error when trying to render movie.tpl which is the details page for a single movie. If you got an error with general settings, I’m not aware of this one.

**Comment by morpheus65535** [comment]
Is this still an issue? please confirm which page is in problem and give an update stack trace.

**Comment by morpheus65535** [comment]
If you still have an issue, re-open it.
