### ISSUE TITLE
Manual import dosent work

### ISSUE THREAD

**Issue by babos123** [morpheus65535/bazarr#1006]
Bazarr Version:0.9
Sonarr Version:3.0.3.834
Radarr Version:3.0.0.3009
Operating System:Linux-4.15.0-99-genericx86_64-with
Python Version:3.8.2

Trying to manual import subs dosent work. Just stuck without doing anything.
In logs i see this:
Message
Exception on /api/movie_subtitles_upload [POST]
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/init.py", line 458, in wrapper
  resp = resource(*args, kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/init.py", line 573, in dispatch_request
  resp = meth(args, kwargs)
 File "/app/bazarr/bazarr/api.py", line 54, in wrapper
  return actual_method(*args, kwargs)
 File "/app/bazarr/bazarr/api.py", line 954, in post
  result = manual_upload_subtitle(path=moviePath,
TypeError: manual_upload_subtitle() missing 1 required positional argument: \audio_language\

**Comment by morpheus65535** [comment]
Should be fixed now. Thanks for reporting!
