### ISSUE TITLE
Exception on /api/movie_search_missing [GET]

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1019]
Bazarr doesn't download subtitles for movies since last version i guess. Qnap docker setup from linuxserver.io from development branch

Bazarr Version:
0.9
Sonarr Version:
3.0.3.892
Radarr Version:
0.2.0.1480
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.3
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

log:
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 55, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 1037, in get
  movies_download_subtitles(radarrid)
 File "/app/bazarr/bazarr/get_subtitle.py", line 760, in movies_download_subtitles
  result = download_subtitle(path_mappings.path_replace_movie(movie[\path\]),
 File "/app/bazarr/bazarr/get_subtitle.py", line 244, in download_subtitle
  command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,
TypeError: pp_replace() missing 1 required positional argument: \score\

**Comment by morpheus65535** [comment]
Sorry, merging conflict error. It should be fixed now. Can you confirm?

**Comment by lukjod** [comment]
All ok now, thank You
