### ISSUE TITLE
Bazarr cannot start

### ISSUE THREAD

**Issue by evripidesk** [morpheus65535/bazarr#1025]
**Describe the bug**
After from upgrade to latest dev version bazarr service cannot start I get the below error when I am trying to start the service on rpi4 with dietpi

I run this command `python3 bazarr.py`

```
`Bazarr starting...
2020-07-03 19:34:34,615 - root                             (b6c7ead0) :  DEBUG (logger:89) - Bazarr version: 0.9
2020-07-03 19:34:34,616 - root                             (b6c7ead0) :  DEBUG (logger:90) - Bazarr branch: development
2020-07-03 19:34:34,619 - root                             (b6c7ead0) :  DEBUG (logger:91) - Operating system: Linux-4.19.118-v7l+-armv7l-with-debian-10.4
2020-07-03 19:34:34,620 - root                             (b6c7ead0) :  DEBUG (logger:92) - Python version: 3.7.3
2020-07-03 19:34:34,634 - root                             (b6c7ead0) :  INFO (init:56) - BAZARR installing requirements...
2020-07-03 19:34:38,431 - root                             (b6c7ead0) :  INFO (init:60) - BAZARR requirements installed.
2020-07-03 19:34:39,013 - engineio.server                  (b6c7ead0) :  INFO (server:149) - Server initialized for threading.
2020-07-03 19:34:41,769 - root                             (b6c7ead0) :  INFO (init:65) - BAZARR unable to restart. Please do it manually.
2020-07-03 19:34:41,778 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_shows ADD COLUMN "year" "text": []: duplicate column name: year
2020-07-03 19:34:41,779 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_shows ADD COLUMN "alternateTitles" "text": []: duplicate column name: alternateTitles
2020-07-03 19:34:41,780 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_shows ADD COLUMN "forced" "text" DEFAULT "False": []: duplicate column name: forced
2020-07-03 19:34:41,781 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "format" "text": []: duplicate column name: format
2020-07-03 19:34:41,782 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "resolution" "text": []: duplicate column name: resolution
2020-07-03 19:34:41,784 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "video_codec" "text": []: duplicate column name: video_codec
2020-07-03 19:34:41,785 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "audio_codec" "text": []: duplicate column name: audio_codec
2020-07-03 19:34:41,786 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "episode_file_id" "integer": []: duplicate column name: episode_file_id
2020-07-03 19:34:41,787 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "sortTitle" "text": []: duplicate column name: sortTitle
2020-07-03 19:34:41,789 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "year" "text": []: duplicate column name: year
2020-07-03 19:34:41,790 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "alternativeTitles" "text": []: duplicate column name: alternativeTitles
2020-07-03 19:34:41,792 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "format" "text": []: duplicate column name: format
2020-07-03 19:34:41,793 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "resolution" "text": []: duplicate column name: resolution
2020-07-03 19:34:41,794 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "video_codec" "text": []: duplicate column name: video_codec
2020-07-03 19:34:41,795 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "audio_codec" "text": []: duplicate column name: audio_codec
2020-07-03 19:34:41,795 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "imdbId" "text": []: duplicate column name: imdbId
2020-07-03 19:34:41,796 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "forced" "text" DEFAULT "False": []: duplicate column name: forced
2020-07-03 19:34:41,796 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "movie_file_id" "integer": []: duplicate column name: movie_file_id
2020-07-03 19:34:41,797 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history ADD COLUMN "video_path" "text": []: duplicate column name: video_path
2020-07-03 19:34:41,798 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history ADD COLUMN "language" "text": []: duplicate column name: language
2020-07-03 19:34:41,799 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history ADD COLUMN "provider" "text": []: duplicate column name: provider
2020-07-03 19:34:41,799 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history ADD COLUMN "score" "text": []: duplicate column name: score
2020-07-03 19:34:41,800 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history_movie ADD COLUMN "video_path" "text": []: duplicate column name: video_path
2020-07-03 19:34:41,802 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history_movie ADD COLUMN "language" "text": []: duplicate column name: language
2020-07-03 19:34:41,804 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history_movie ADD COLUMN "provider" "text": []: duplicate column name: provider
2020-07-03 19:34:41,806 - sqlite3worker                    (b2da9460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history_movie ADD COLUMN "score" "text": []: duplicate column name: score
2020-07-03 19:34:41,869 - root                             (b6c7ead0) :  DEBUG (init:160) - Using UnRAR from: /usr/bin/unrar
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/root/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/root/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bazarr/main.py", line 34, in <module>
    from get_episodes import *
  File "/opt/bazarr/bazarr/get_episodes.py", line 9, in <module>
    from get_subtitle import episode_download_subtitles
  File "/opt/bazarr/bazarr/get_subtitle.py", line 30, in <module>
    from subsyncer import subsync
  File "/opt/bazarr/bazarr/subsyncer.py", line 3, in <module>
    from ffsubsync.ffsubsync import run
  File "/opt/bazarr/bazarr/../libs/ffsubsync/__init__.py", line 21, in <module>
    from .ffsubsync import main  # noqa
  File "/opt/bazarr/bazarr/../libs/ffsubsync/ffsubsync.py", line 10, in <module>
    import numpy as np
  File "/root/.local/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/root/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.19.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

Bazarr exited.
```

**Comment by morpheus65535** [comment]
Can you remove numpy: `python3 -m pip uninstall numpy`

and install this specific version: `python3 -m install numpy==1.18.4`

Please confirm if you still have the issue.

**Comment by evripidesk** [comment]
Unistalled succesfull but when I am trying to run `python3 -m install numpy==1.18.4` I get `/usr/bin/python3: No module named install`

**Comment by evripidesk** [comment]
I tried this command `python3 -m pip install numpy==1.18.4` and installed it successful but when I tried to run bazarr I get the same error

`
Bazarr starting...
2020-07-04 09:36:23,421 - root                             (b6c96ad0) :  DEBUG (logger:89) - Bazarr version: 0.9
2020-07-04 09:36:23,422 - root                             (b6c96ad0) :  DEBUG (logger:90) - Bazarr branch: development
2020-07-04 09:36:23,427 - root                             (b6c96ad0) :  DEBUG (logger:91) - Operating system: Linux-4.19.118-v7l+-armv7l-with-debian-10.4
2020-07-04 09:36:23,427 - root                             (b6c96ad0) :  DEBUG (logger:92) - Python version: 3.7.3
2020-07-04 09:36:23,439 - root                             (b6c96ad0) :  INFO (init:56) - BAZARR installing requirements...
2020-07-04 09:36:26,661 - root                             (b6c96ad0) :  INFO (init:60) - BAZARR requirements installed.
2020-07-04 09:36:27,191 - engineio.server                  (b6c96ad0) :  INFO (server:149) - Server initialized for threading.
2020-07-04 09:36:29,536 - root                             (b6c96ad0) :  INFO (init:65) - BAZARR unable to restart. Please do it manually.
2020-07-04 09:36:29,543 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_shows ADD COLUMN "year" "text": []: duplicate column name: year
2020-07-04 09:36:29,544 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_shows ADD COLUMN "alternateTitles" "text": []: duplicate column name: alternateTitles
2020-07-04 09:36:29,544 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_shows ADD COLUMN "forced" "text" DEFAULT "False": []: duplicate column name: forced
2020-07-04 09:36:29,545 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "format" "text": []: duplicate column name: format
2020-07-04 09:36:29,545 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "resolution" "text": []: duplicate column name: resolution
2020-07-04 09:36:29,546 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "video_codec" "text": []: duplicate column name: video_codec
2020-07-04 09:36:29,546 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "audio_codec" "text": []: duplicate column name: audio_codec
2020-07-04 09:36:29,546 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_episodes ADD COLUMN "episode_file_id" "integer": []: duplicate column name: episode_file_id
2020-07-04 09:36:29,547 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "sortTitle" "text": []: duplicate column name: sortTitle
2020-07-04 09:36:29,547 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "year" "text": []: duplicate column name: year
2020-07-04 09:36:29,548 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "alternativeTitles" "text": []: duplicate column name: alternativeTitles
2020-07-04 09:36:29,548 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "format" "text": []: duplicate column name: format
2020-07-04 09:36:29,549 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "resolution" "text": []: duplicate column name: resolution
2020-07-04 09:36:29,549 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "video_codec" "text": []: duplicate column name: video_codec
2020-07-04 09:36:29,549 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "audio_codec" "text": []: duplicate column name: audio_codec
2020-07-04 09:36:29,550 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "imdbId" "text": []: duplicate column name: imdbId
2020-07-04 09:36:29,550 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "forced" "text" DEFAULT "False": []: duplicate column name: forced
2020-07-04 09:36:29,550 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_movies ADD COLUMN "movie_file_id" "integer": []: duplicate column name: movie_file_id
2020-07-04 09:36:29,551 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history ADD COLUMN "video_path" "text": []: duplicate column name: video_path
2020-07-04 09:36:29,551 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history ADD COLUMN "language" "text": []: duplicate column name: language
2020-07-04 09:36:29,551 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history ADD COLUMN "provider" "text": []: duplicate column name: provider
2020-07-04 09:36:29,552 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history ADD COLUMN "score" "text": []: duplicate column name: score
2020-07-04 09:36:29,552 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history_movie ADD COLUMN "video_path" "text": []: duplicate column name: video_path
2020-07-04 09:36:29,552 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history_movie ADD COLUMN "language" "text": []: duplicate column name: language
2020-07-04 09:36:29,553 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history_movie ADD COLUMN "provider" "text": []: duplicate column name: provider
2020-07-04 09:36:29,553 - sqlite3worker                    (b2dc1460) :  ERROR (sqlite3worker:151) - Query returned error: ALTER TABLE table_history_movie ADD COLUMN "score" "text": []: duplicate column name: score
2020-07-04 09:36:29,606 - root                             (b6c96ad0) :  DEBUG (init:160) - Using UnRAR from: /usr/bin/unrar
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bazarr/main.py", line 34, in <module>
    from get_episodes import *
  File "/opt/bazarr/bazarr/get_episodes.py", line 9, in <module>
    from get_subtitle import episode_download_subtitles
  File "/opt/bazarr/bazarr/get_subtitle.py", line 30, in <module>
    from subsyncer import subsync
  File "/opt/bazarr/bazarr/subsyncer.py", line 3, in <module>
    from ffsubsync.ffsubsync import run
  File "/opt/bazarr/bazarr/../libs/ffsubsync/__init__.py", line 21, in <module>
    from .ffsubsync import main  # noqa
  File "/opt/bazarr/bazarr/../libs/ffsubsync/ffsubsync.py", line 10, in <module>
    import numpy as np
  File "/usr/local/lib/python3.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

Bazarr exited.
`

**Comment by morpheus65535** [comment]
You can try this: https://github.com/numpy/numpy/issues/14772

**Comment by evripidesk** [comment]
perfect this worked 
`sudo apt-get install libatlas-base-dev`

**Comment by morpheus65535** [comment]
Thanks for reporting! I've added it to the wiki.
