### ISSUE TITLE
bad magic number in 'cloudscraper'

### ISSUE THREAD

**Issue by dkids** [morpheus65535/bazarr#1056]
MacOS 11 beta 3
Radarr 3.0.0.3357
Sonarr 3.0.3.905
Bazaar latest (not loading to get version number)

It looks like my copy of Bazaar updated yesterday and crashed.  I can't restart it.

 python3 ~/src/bazarr/bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "/Users/kids/src/bazarr/bazarr/main.py", line 22, in <module>
    from init import *
  File "/Volumes/SSD/src/bazarr/bazarr/init.py", line 178, in <module>
    init_binaries()
  File "/Volumes/SSD/src/bazarr/bazarr/init.py", line 159, in init_binaries
    from utils import get_binary
  File "/Volumes/SSD/src/bazarr/bazarr/utils.py", line 16, in <module>
    from list_subtitles import store_subtitles, store_subtitles_movie
  File "/Volumes/SSD/src/bazarr/bazarr/list_subtitles.py", line 8, in <module>
    from subliminal_patch import core, search_external_subtitles
  File "/Volumes/SSD/src/bazarr/bazarr/../libs/subliminal_patch/__init__.py", line 8, in <module>
    from .providers import Provider
  File "/Volumes/SSD/src/bazarr/bazarr/../libs/subliminal_patch/providers/__init__.py", line 9, in <module>
    from subliminal_patch.extensions import provider_registry
  File "/Volumes/SSD/src/bazarr/bazarr/../libs/subliminal_patch/extensions.py", line 61, in <module>
    subliminal.refiner_manager.register('sz_omdb = subliminal_patch.refiners.omdb:refine')
  File "/Volumes/SSD/src/bazarr/bazarr/../libs/subliminal/extensions.py", line 65, in register
    ext = self._load_one_plugin(ep, False, (), {}, False)
  File "/Volumes/SSD/src/bazarr/bazarr/../libs/stevedore/extension.py", line 203, in _load_one_plugin
    plugin = ep.resolve()
  File "/Volumes/SSD/src/bazarr/bazarr/../libs/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Volumes/SSD/src/bazarr/bazarr/../libs/subliminal_patch/refiners/omdb.py", line 9, in <module>
    from subliminal_patch.http import TimeoutSession
  File "/Volumes/SSD/src/bazarr/bazarr/../libs/subliminal_patch/http.py", line 25, in <module>
    from cloudscraper import CloudScraper
ImportError: bad magic number in 'cloudscraper': b'\x03\xf3\r\n'

**Comment by morpheus65535** [comment]
Sorry, my bad for a bad commit to dev branch. You can run a `git pull` to get the fix I made last night.
