### ISSUE TITLE
BAZARR Error trying to get video information for this file:

### ISSUE THREAD

**Issue by Suiziide** [morpheus65535/bazarr#1072]
**Describe the bug**
I get this error in log on some of my video files, not all:

  | BAZARR  Error trying to get video information for this file:  /*/*/*/TV Shows/Entourage/Season 6/Entourage - S06E11 -  Scared Straight.mkv
-- | --

**To Reproduce**
I think it does it when it tries to update episodes and movies on disk

**Software (please complete the following information):**
Bazarr Version:
0.9.0.1
Sonarr Version:
3.0.3.905
Radarr Version:
0.2.0.1450
Operating System:
Linux-4.15.0-112-generic-x86_64-with-debian-buster-sid
Python Version:
3.7.7

**Additional context**

more complete logs, if you need debug let me know and i will try to turn it on

´´´
Traceback (most recent call last):
 File "/opt/bazarr/bazarr/../libs/knowit/api.py", line 64, in know
  result = provider.describe(video_path, context)
 File "/opt/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe
  data = self.executor.extract_info(video_path)
 File "/opt/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info
  json_dump = self._execute(filename)
 File "/opt/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 124, in _execute
  \-show_format\, \-show_streams\, \-sexagesimal\, filename]))
 File "/opt/pyenv/versions/3.7.7/lib/python3.7/subprocess.py", line 411, in check_output
  **kwargs).stdout
 File "/opt/pyenv/versions/3.7.7/lib/python3.7/subprocess.py", line 512, in run
  output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command \[\/opt/bazarr/bin/Linux/x86_64/ffmpeg/ffprobe\, \-v\, \quiet\, \-print_format\, \json\, \-show_format\, \-show_streams\, \-sexagesimal\, \/home/suiziide/gmedia/TV Shows/Entourage/Season 6/Entourage - S06E11 - Scared Straight.mkv\]\ returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/opt/bazarr/bazarr/get_subtitle.py", line 67, in get_video
  refine_from_ffprobe(original_path, video)
 File "/opt/bazarr/bazarr/get_subtitle.py", line 1039, in refine_from_ffprobe
  data = api.know(path)
 File "/opt/bazarr/bazarr/../libs/knowit/api.py", line 70, in know
  raise KnowitException(debug_info(context=context, exc_info=True))
knowit.api.KnowitException: +-------------------------------------------------------+

´´´

**Comment by morpheus65535** [comment]
Did you tried to install ffmpeg? Maybe the one embedded in Bazarr isn't wrking on your OS.

What is the output from that command?
`/opt/bazarr/bin/Linux/x86_64/ffmpeg/ffprobe, -v quiet -print_format json -show_format -show_streams -sexagesimal "/home/suiziide/gmedia/TV Shows/Entourage/Season 6/Entourage - S06E11 - Scared Straight.mkv"`

**Comment by Suiziide** [comment]
output is:
{

}

**Comment by morpheus65535** [comment]
Is this media file even playable with VLC or other?

**Comment by Suiziide** [comment]
Ok, no, as i just wrote in discord, I had a lot of files in the log act up, and i picked one at random, and that one, among a few others are not even playable, so that might be the problem, but the main part of them gives another error, and the play fine.
´´´
Traceback (most recent call last):
 File "/opt/bazarr/bazarr/get_subtitle.py", line 61, in get_video
  hash_from=hash_from)
 File "/opt/bazarr/bazarr/../libs/subzero/video.py", line 62, in parse_video
  skip_hashing=skip_hashing, hash_from=hash_from)
 File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 529, in scan_video
  video = Video.fromguess(path, guessed_result)
 File "/opt/bazarr/bazarr/../libs/subliminal/video.py", line 94, in fromguess
  return Episode.fromguess(name, guess)
 File "/opt/bazarr/bazarr/../libs/subliminal/video.py", line 171, in fromguess
  raise ValueError(\Insufficient data to process the guess\)
ValueError: Insufficient data to process the guess
´´´

Sorry about that.

**Comment by morpheus65535** [comment]
Give me the complete file path for one of those file.

**Comment by Suiziide** [comment]
one example is 

/home/suiziide/gmedia/TV Shows/The Daily Show/Season 22/The Daily Show - 2016-12-15 - Rob Corddry.mkv

**Comment by morpheus65535** [comment]
Provide a complete debug log while reproducing the issue.

**Comment by Suiziide** [comment]
Unable to reproduce now. This can be closed for now
