### ISSUE TITLE
Error trying to get movies from Radarr. Connection Error.

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1078]
Bazarr Version: 0.9.0.3
Sonarr Version: 3.0.3.911
Radarr Version: 3.0.0.3433

From 'Bazarr > Settings > Radarr' the TEST says: Test Successful: Radarr v3.0.0.3433

The log says:
* BAZARR Error trying to get movies from Radarr. Connection Error.

Logfile: 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5083698/bazarr.log)

Exception

Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 600, in urlopen
  httplib_response = self._make_request(conn, method, url,
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 387, in _make_request
  six.raise_from(e, None)
 File "", line 2, in raise_from
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 383, in _make_request
  httplib_response = conn.getresponse()
 File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
  response.begin()
 File "/usr/lib/python3.8/http/client.py", line 307, in begin
  version, status, reason = self._read_status()
 File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
  line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
 File "/usr/lib/python3.8/socket.py", line 669, in readinto
  return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/requests/adapters.py", line 439, in send
  resp = conn.urlopen(
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 640, in urlopen
  retries = retries.increment(method, url, error=e, _pool=self,
 File "/app/bazarr/bazarr/../libs/urllib3/util/retry.py", line 368, in increment
  raise six.reraise(type(error), error, _stacktrace)
 File "/app/bazarr/bazarr/../libs/urllib3/packages/six.py", line 685, in reraise
  raise value.with_traceback(tb)
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 600, in urlopen
  httplib_response = self._make_request(conn, method, url,
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 387, in _make_request
  six.raise_from(e, None)
 File "", line 2, in raise_from
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 383, in _make_request
  httplib_response = conn.getresponse()
 File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
  response.begin()
 File "/usr/lib/python3.8/http/client.py", line 307, in begin
  version, status, reason = self._read_status()
 File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
  line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
 File "/usr/lib/python3.8/socket.py", line 669, in readinto
  return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: (\Connection aborted.\, ConnectionResetError(104, \Connection reset by peer\))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_movies.py", line 50, in update_movies
  r = requests.get(url_radarr_api_movies, timeout=60, verify=False)
 File "/app/bazarr/bazarr/../libs/requests/api.py", line 75, in get
  return request(\get\, url, params=params, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/api.py", line 60, in request
  return session.request(method=method, url=url, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 533, in request
  resp = self.send(prep, **send_kwargs)
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 646, in send
  r = adapter.send(request, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/adapters.py", line 498, in send
  raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (\Connection aborted.\, ConnectionResetError(104, \Connection reset by peer\))

**Comment by morpheus65535** [comment]
Did you try to restart Radarr?

**Comment by cphmichael** [comment]
I have restarted Radarr and bazarr.
Maybe that have solved the problem :-)

**Comment by morpheus65535** [comment]
`Connection reset by peer` means that Radarr dropped the http request made by Bazarr. Nothing related to Bazarr, it just happen sometime.
