### ISSUE TITLE
Error when accessing bazarr

### ISSUE THREAD

**Issue by dimitrov-adrian** [morpheus65535/bazarr#108]
Got error when trying to access bazarr

Exception:
`NameError("name 'page_size' is not defined",)`

Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/bazarr/bazarr.py", line 205, in series
    c.close()
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/bazarr/views/series.tpl", line 131, in <module>
    %if page_size != -1:
NameError: name 'page_size' is not defined
```

**Comment by morpheus65535** [comment]
Yeah sorry, just restart bazarr and you wont see it again.

**Comment by dimitrov-adrian** [comment]
Yeah, the restart fix it, but I just report :)
