### ISSUE TITLE
Bazarr not Updating Movie list from Radarr

### ISSUE THREAD

**Issue by jpalenz77** [morpheus65535/bazarr#1080]
**Describe the bug**
For the past couple of days I just noticed Bazarr it is not pulling the movie list from Radarr

**To Reproduce**
1. Go to system-tasks
2. Click on Update Movie list from Radarr
error:

2020-08-18 17:01:39,737 - apscheduler.executors.default    (7f0c77d03b20) :  ERROR (base:131) - Job "Update Movie list from Radarr (trigger: interval[1:00:00], next run at: 2020-08-18 18:01:28 CEST)" raised an exception

Traceback (most recent call last):

  File "/app/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/app/bazarr/get_movies.py", line 154, in update_movies

    audio_language = movie['movieFile']['languages'][0]['name']

TypeError: 'NoneType' object is not subscriptable

2020-08-18 17:01:39,741 - socketio.server                  (7f0c77d03b20) :  INFO (server:283) - emitting event "event" to all [/]

2020-08-18 17:01:39,741 - engineio.server                  (7f0c77d03b20) :  INFO (socket:92) - 265d52afde4944eab403fddc86c81f7b: Sending packet MESSAGE data 2["event","{\"type\": \"task\", \"action\": null, \"series\": null, \"episode\": null, \"movie\": null, \"task\": \"update_movies\"}"]

2020-08-18 17:01:49,571 - engineio.server                  (7f0c8a6e4b20) :  INFO (socket:49) - 265d52afde4944eab403fddc86c81f7b: Received packet PING data None

2020-08-18 17:01:49,572 - engineio.server                  (7f0c8a6e4b20) :  INFO (socket:92) - 265d52afde4944eab403fddc86c81f7b: Sending packet PONG data None

2020-08-18 17:01:55,201 - engineio.server                  (7f0c796f7b20) :  INFO (socket:75) - d2ff59909e324850a338b0666b148a83: Client is gone, closing socket

2020-08-18 17:01:55,201 - engineio.server                  (7f0c796f7b20) :  INFO (socket:75) - d2ff59909e324850a338b0666b148a83: Client is gone, closing socket

**Expected behavior**
It should update the movie list

**Software (please complete the following information):**
 - Bazarr: [docker v0.9.0.2 ]
 - Radarr version [docker 3.0.0.3442]
 - OS: [ubuntu 18.04]

**Comment by morpheus65535** [comment]
It's working properly with Radarr v3.0.0.3445. They made a breaking changes to their API and we had to move quickly.
