### ISSUE TITLE
BAZARR an exception occurs during the synchronization process

### ISSUE THREAD

**Issue by pippotaz** [morpheus65535/bazarr#1091]
Subtitle sync failed for 2 movies (no speech found) 

I'm running Bazarr on Qnap nas (Qbazarr) version V0.9.0.2, all other subs synced correctly so might be a general problem with the app ?

The movie audio is:  .AVC.DTS-HD.MA.5.1

Traceback (most recent call last):
 File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/subsyncer.py", line 46, in sync
  result = run(self.args)
 File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/ffsubsync/ffsubsync.py", line 275, in run
  reference_pipe.fit(args.reference)
 File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/ffsubsync/sklearn_shim.py", line 214, in fit
  self._final_estimator.fit(Xt, y, **fit_params)
 File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/ffsubsync/speech_transformers.py", line 250, in fit
  raise ValueError(
ValueError: Unable to detect speech. Perhaps try specifying a different stream / track, or a different vad.

**Comment by morpheus65535** [comment]
For issue with subtitles synchronization, open an issue on https://github.com/smacke/ffsubsync on which we rely.
