### ISSUE TITLE
Post Processing seems broken

### ISSUE THREAD

**Issue by RikP** [morpheus65535/bazarr#1111]
I have a post processing command for subsync:
subsync --cli sync --ref-lang '{{episode_language_code3}}'  --sub '{{subtitles}}' --ref '{{episode}}' --out '{{subtitles}}' --overwrite

i found out that since a week this doesn't work anymore and it gives an exception:
```
File "/app/bazarr/bazarr/helper.py", line 108, in pp_replace
pp_command = pp_command.replace(\{{episode_language}}\, episode_language)
TypeError: replace() argument 2 must be str, not None
```

After doing some more research i found that with just post-processing enabled without any post-processing command set this same issue comes up. So it seems a bug in bazarr itself?

Running bazarr 0.9.0.3

full traceback log:
```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 62, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 652, in post
  result = manual_download_subtitle(episodePath, language, audio_language, hi, forced, subtitle,
 File "/app/bazarr/bazarr/get_subtitle.py", line 504, in manual_download_subtitle
  command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,
 File "/app/bazarr/bazarr/helper.py", line 108, in pp_replace
  pp_command = pp_command.replace(\{{episode_language}}\, episode_language)
TypeError: replace() argument 2 must be str, not None
```

**Comment by morpheus65535** [comment]
Fixed by https://github.com/morpheus65535/bazarr/commit/35ee6fb6f61dd79b8289b70bef6054708e499b4d in dev branch right now. Will be in v0.9.0.4.
