### ISSUE TITLE
Exception on /api/episodes_subtitles_download [POST]

### ISSUE THREAD

**Issue by ricardovr22** [morpheus65535/bazarr#1118]
I am using version 0.9.0.2 of Bazarr in docker. After changing Sonarr and Radarr to container versions (I used to use packages) I get the following error:

Message:
Exception on /api/episodes_subtitles_download [POST]
Exception:
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 59, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 547, in post
  result = download_subtitle(episodePath, language, audio_language, hi, forced, providers_list, providers_auth, sceneName,
 File "/app/bazarr/bazarr/get_subtitle.py", line 237, in download_subtitle
  sonarr_series_id=episode_metadata[\sonarrSeriesId\],
TypeError: \NoneType\ object is not subscriptable

I deleted the container and all the configuration and reinstalled it from scratch, but I still have the same error.

**Comment by morpheus65535** [comment]
Update to v0.9.0.3 and confirm if the issue is still there.
