### ISSUE TITLE
Bug - Error 500 when set none for all series subtitles

### ISSUE THREAD

**Issue by Rodrigueztb** [morpheus65535/bazarr#112]
If i click in "Series Editor", select all series and set the subtitles to none i get a Error 500 on /series page.

I fix it going manually to /serieseditor and add a language to at least one series.

**Comment by morpheus65535** [comment]
Stack trace of 500 error please?

**Comment by Rodrigueztb** [comment]
Error: 500 Internal Server Error
Sorry, the requested URL 'http://192.168.1.5:6767/series' caused an error:

Internal Server Error
Exception:
NameError("name 'total_subs' is not defined",)
Traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/bazarr/bazarr.py", line 206, in series
    output = template('series', __file__=__file__, bazarr_version=bazarr_version, rows=data, missing_subtitles_list=missing_subtitles_list, total_subtitles_list=total_subtitles_list, languages=languages, missing_count=missing_count, page=page, max_page=max_page, base_url=base_url, single_language=single_language, page_size=page_size)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/bazarr/views/series.tpl", line 108, in <module>
    <div class="ui progress" data-value="{{total_subs - missing_subs}}" data-total="{{total_subs}}">
NameError: name 'total_subs' is not defined

**Comment by morpheus65535** [comment]
Should be all good now, thanks for reporting!

You can update from System-->Tasks.
