### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'basename

### ISSUE THREAD

**Issue by stevezau** [morpheus65535/bazarr#1122]
**Describe the bug**
Running latest dev build. Hit search for all missing movies. Get the following in debug logs..

Stop halts the search all function.

```2020-09-29 08:58:36,443 - chardet.charsetprober            (7fef0916eb20) :  DEBUG (charsetgroupprober:100) - EUC-JP Japanese confidence = 0.01
2020-09-29 08:58:36,443 - chardet.charsetprober            (7fef0916eb20) :  DEBUG (charsetgroupprober:100) - GB2312 Chinese confidence = 0.01
2020-09-29 08:58:36,443 - chardet.charsetprober            (7fef0916eb20) :  DEBUG (charsetgroupprober:100) - EUC-KR Korean confidence = 0.01
2020-09-29 08:58:36,444 - chardet.charsetprober            (7fef0916eb20) :  DEBUG (charsetgroupprober:100) - CP949 Korean confidence = 0.01
2020-09-29 08:58:36,444 - chardet.charsetprober            (7fef0916eb20) :  DEBUG (charsetgroupprober:100) - Big5 Chinese confidence = 0.01
2020-09-29 08:58:36,444 - chardet.charsetprober            (7fef0916eb20) :  DEBUG (charsetgroupprober:100) - EUC-TW Taiwan confidence = 0.01
2020-09-29 08:58:36,448 - subliminal_patch.core            (7fef0a5edb20) :  DEBUG (core:356) - <SuperSubtitlesSubtitle 'Peppermint Soda (2015) [720p-EA, 1080p-EA]' [hu]>: Skipping, language not searched for
2020-09-29 08:58:36,449 - subliminal_patch.core            (7fef0a5edb20) :  DEBUG (core:356) - <SuperSubtitlesSubtitle 'The Belko Experiment (2015) [BRRip-RARBG, BDRip-COCAIN, 480p-RMTeam, BRRip.720p-RARBG, 720p-BLOW, 720p-RARBG, 720p-RMTeam, 1080p-BLOW, 1080p-RARBG]' [hu]>: Skipping, language not searched for
2020-09-29 08:58:36,450 - subliminal_patch.core            (7fef0a5edb20) :  DEBUG (core:356) - <SuperSubtitlesSubtitle 'The Paramedic (2015) [WEBRip-VXT, WEBRip.1080p-VXT, NF.WEB-DL.1080p-CMRG]' [hu]>: Skipping, language not searched for
2020-09-29 08:58:36,450 - subliminal.core                  (7fef0a5edb20) :  DEBUG (core:311) - Terminating initialized providers
2020-09-29 08:58:36,450 - subliminal_patch.core            (7fef0a5edb20) :  INFO (core:115) - Terminating provider supersubtitles
2020-09-29 08:58:36,456 - app                              (7fef0a5edb20) :  ERROR (app:1890) - Exception on /api/search_wanted_movies [GET]
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/bazarr/bazarr/api.py", line 62, in wrapper
    return actual_method(*args, **kwargs)
  File "/app/bazarr/bazarr/api.py", line 1728, in get
    wanted_search_missing_subtitles_movies()
  File "/app/bazarr/bazarr/get_subtitle.py", line 997, in wanted_search_missing_subtitles_movies
    wanted_download_subtitles_movie(movie['path'], i, count_movies)
  File "/app/bazarr/bazarr/get_subtitle.py", line 933, in wanted_download_subtitles_movie
    result = download_subtitle(path_mappings.path_replace_movie(movie['path']),
  File "/app/bazarr/bazarr/get_subtitle.py", line 168, in download_subtitle
    downloaded_subtitles = download_best_subtitles({video}, language_set, int(min_score), hi,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 796, in download_best_subtitles
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 355, in download_best_subtitles
    if s.language.basename not in languages:
AttributeError: 'NoneType' object has no attribute 'basename'```

**Comment by morpheus65535** [comment]
I've just pushed changes to supersubtitles provider in dev branch, can you test it and see if its still an issue?

**Comment by morpheus65535** [comment]
Is this still an issue?

**Comment by morpheus65535** [comment]
No news, good news. Re-open the issue if you still need it.
