### ISSUE TITLE
Bazarr unexpectedly stopped 

### ISSUE THREAD

**Issue by evripidesk** [morpheus65535/bazarr#1129]
Hello

Today bazarr stopped running on dietpi and cannot start

Bazarr starting...
Traceback (most recent call last):
  File "bazarr/main.py", line 22, in <module>
    from init import *
  File "/opt/bazarr/bazarr/init.py", line 181, in <module>
    init_binaries()
  File "/opt/bazarr/bazarr/init.py", line 162, in init_binaries
    from utils import get_binary
  File "/opt/bazarr/bazarr/utils.py", line 16, in <module>
    from list_subtitles import store_subtitles, store_subtitles_movie
  File "/opt/bazarr/bazarr/list_subtitles.py", line 461
    continue
    ^
SyntaxError: 'continue' not supported inside 'finally' clause
Bazarr exited.

Do we have any solution?

**Comment by morpheus65535** [comment]
Unfortunately we made a bad commit that was fix within an hour. Those running Python 3.7 could experience this. You just have to run a `git pull` to get the fix.
