### ISSUE TITLE
Exception on /api/episodes_subtitles_manual_download [POST]

### ISSUE THREAD

**Issue by salsa2k** [morpheus65535/bazarr#1131]
**Describe the bug**
Exception on /api/episodes_subtitles_manual_download [POST]

**To Reproduce**
1. Go to the TV show series
2. Click in manual download
3. Select the subtitle

**Software (please complete the following information):**
 - Bazarr: v0.9.0.4
 - Sonarr version: 2.0.0.5344
 - OS: docker

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 62, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 652, in post
  result = manual_download_subtitle(episodePath, language, audio_language, hi, forced, subtitle,
 File "/app/bazarr/bazarr/get_subtitle.py", line 504, in manual_download_subtitle
  command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,
 File "/app/bazarr/bazarr/helper.py", line 108, in pp_replace
  pp_command = pp_command.replace(\{{episode_language}}\, episode_language)
TypeError: replace() argument 2 must be str, not None
```

**Comment by morpheus65535** [comment]
```
 File "/app/bazarr/bazarr/get_subtitle.py", line 504, in manual_download_subtitle
  command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,
```

Here's the content of line 504 in v0.9.0.4:

https://github.com/morpheus65535/bazarr/blob/f9efae57171508231e1d45b9d7a9c9ee7e73657e/bazarr/get_subtitle.py#L504

Make sure you are using the latest docker image.

**Comment by salsa2k** [comment]
Hey, now looks like its working... thanks a lot ;)
