### ISSUE TITLE
Job "Update Movie list from Radarr" raised an exception

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1143]
As title says.
Bazarr 0.9.0.5 from Docker 

log:
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_movies.py", line 276, in update_movies
  movies_download_subtitles(data[\radarrId\])
TypeError: \NoneType\ object is not subscriptable

**Comment by morpheus65535** [comment]
Should be fixed in dev branch. Can you test it?

**Comment by lukjod** [comment]
No more errors on new release. I think its ok now
Thank You
