### ISSUE TITLE
Exception on /api/movies [GET]

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1145]
on newest Bazarr from docker dev branch i had this error twice
log:
`Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 62, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 877, in get
  desired_languages = database.execute("SELECT languages FROM table_movies WHERE radarrId=?",
TypeError: \NoneType\ object is not subscriptable`

**Comment by morpheus65535** [comment]
You have something fucked up in your database. Please send me your bazarr.db in private on Discord.

**Comment by morpheus65535** [comment]
Your DB seems to be good but this error is caused by a call to the `/api/movies` API with a Radarr movie id that doesn't exist in bazarr.db.
