### ISSUE TITLE
Unable to launch Bazarr 

### ISSUE THREAD

**Issue by davinci-klod** [morpheus65535/bazarr#1149]
**Describe the bug**

Hi, 
Since couple of weeks, I'm not able to launch Bazarr using 'python3 bazarr.py' or my service 'service start bazarr'.
When I type the address : 192.168.1.6:6767/, Chrome returns to me this message : "This site is inaccessible". I trying updating Bazarr using 'sudo git clone https://github.com/morpheus65535/bazarr.git /opt/bazarr' but doesn't work. When I use 'pythong3 bazarr.py', it does an infinite loop : BAZARR installing / BAZARR is being restarted ... An use git pull doesn't fix my problem.

Did you have an idea to help me please ? Thanks you in advance :-)
**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1]
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: Raspbian

**Comment by morpheus65535** [comment]
Your user doesn't have a home directory.

Duplicate #1061

**Comment by davinci-klod** [comment]
Hi,

**Comment by davinci-klod** [comment]
Hi, 

I read this thread but doesn't fix my issue.
I have a home directory in /home/bazarr.

When I try to launch Bazarr using the Pi User, I get some errors : 

`Bazarr starting...
2020-10-15 06:34:22,714 - root                             (76cb6ad0) :  INFO (init:57) - BAZARR installing requirements...
--- Logging error ---
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/bazarr/bazarr/init.py", line 50, in <module>
    import lxml, numpy
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 69, in emit
    self.doRollover()
  File "/usr/lib/python3.7/logging/handlers.py", line 393, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib/python3.7/logging/handlers.py", line 110, in rotate
    os.rename(source, dest)
PermissionError: [Errno 13] Permission denied: '/home/pi/bazarr/data/log/bazarr.log' -> '/home/pi/bazarr/data/log/bazarr.log.2020-10-14'
Call stack:
  File "bazarr/main.py", line 22, in <module>
    from init import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/bazarr/bazarr/init.py", line 57, in <module>
    logging.info('BAZARR installing requirements...')
Message: 'BAZARR installing requirements...'
Arguments: ()
2020-10-15 06:34:35,544 - root                             (76cb6ad0) :  INFO (init:61) - BAZARR requirements installed.
--- Logging error ---
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/bazarr/bazarr/init.py", line 50, in <module>
    import lxml, numpy
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 69, in emit
    self.doRollover()
  File "/usr/lib/python3.7/logging/handlers.py", line 393, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib/python3.7/logging/handlers.py", line 110, in rotate
    os.rename(source, dest)
PermissionError: [Errno 13] Permission denied: '/home/pi/bazarr/data/log/bazarr.log' -> '/home/pi/bazarr/data/log/bazarr.log.2020-10-14'
Call stack:
  File "bazarr/main.py", line 22, in <module>
    from init import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/bazarr/bazarr/init.py", line 61, in <module>
    logging.info('BAZARR requirements installed.')
Message: 'BAZARR requirements installed.'
Arguments: ()
2020-10-15 06:34:35,554 - root                             (76cb6ad0) :  ERROR (init:65) - BAZARR Cannot create bazarr.restart file: PermissionError(13, 'Permission denied')
--- Logging error ---
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/bazarr/bazarr/init.py", line 50, in <module>
    import lxml, numpy
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/bazarr/bazarr/init.py", line 63, in <module>
    restart_file = io.open(os.path.join(args.config_dir, "bazarr.restart"), "w", encoding='UTF-8')
PermissionError: [Errno 13] Permission denied: '/home/pi/bazarr/data/bazarr.restart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 69, in emit
    self.doRollover()
  File "/usr/lib/python3.7/logging/handlers.py", line 393, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib/python3.7/logging/handlers.py", line 110, in rotate
    os.rename(source, dest)
PermissionError: [Errno 13] Permission denied: '/home/pi/bazarr/data/log/bazarr.log' -> '/home/pi/bazarr/data/log/bazarr.log.2020-10-14'
Call stack:
  File "bazarr/main.py", line 22, in <module>
    from init import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/bazarr/bazarr/init.py", line 65, in <module>
    logging.error('BAZARR Cannot create bazarr.restart file: ' + repr(e))
Message: "BAZARR Cannot create bazarr.restart file: PermissionError(13, 'Permission denied')"
Arguments: ()
Traceback (most recent call last):
  File "bazarr/main.py", line 22, in <module>
    from init import *
  File "/home/pi/bazarr/bazarr/init.py", line 83, in <module>
    with open(os.path.join(args.config_dir, 'config', 'config.ini'), 'w+') as handle:
PermissionError: [Errno 13] Permission denied: '/home/pi/bazarr/data/config/config.ini'
Bazarr exited.`

**Comment by morpheus65535** [comment]
No need to reinstall. I would simply try this: https://github.com/numpy/numpy/issues/14772
