### ISSUE TITLE
Exception on /api/movie_subtitles_download [POST]

### ISSUE THREAD

**Issue by brandonludwick** [morpheus65535/bazarr#1159]
**Describe the bug**
Exception on /api/movie_subtitles_download [POST]

**To Reproduce**
1. Go to Wanted -> Movies
2. Search for missing subtitles
3. Go to Logs

**Software (please complete the following information):**
 - Bazarr: v 0.9.0.5
 - Radarr version v 3.0.0.3954
 - OS: Docker on unRAID

**Additional context**

> Traceback (most recent call last):
 File "/app/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/api.py", line 62, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/api.py", line 1125, in post
  result = download_subtitle(moviePath, language, audio_language, hi, forced, providers_list,
 File "/app/bazarr/get_subtitle.py", line 255, in download_subtitle
  episode_id = movie_metadata[\radarrId\]
TypeError: \NoneType\ object is not subscriptable

**Comment by morpheus65535** [comment]
Fixed in dev branch.
