### ISSUE TITLE
Can't switch to dev branch

### ISSUE THREAD

**Issue by secret-liar** [morpheus65535/bazarr#116]
Hi,

When I select "development" as the branch for updates in Settings, I then go to System, update source from github.
Nothing happens and log shows that :

Message
```
Job "Update bazarr from source on Github (trigger: interval[6:00:00], next run at: 2018-08-03 02:56:13 EDT)" raised an exception
```
Exception
```
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/bazarr/check_update.py", line 31, in check_and_apply_update
  result = g.diff(\--shortstat\, \origin/\ + branch)
 File "/usr/lib/python2.7/site-packages/git/cmd.py", line 550, in 
  return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
 File "/usr/lib/python2.7/site-packages/git/cmd.py", line 1009, in _call_process
  return self.execute(call, **exec_kwargs)
 File "/usr/lib/python2.7/site-packages/git/cmd.py", line 820, in execute
  raise GitCommandError(command, status, stderr_value, stdout_value)
GitCommandError: Cmd(\git\) failed due to: exit code(128)
 cmdline: git diff --shortstat origin/development
 stderr: \fatal: ambiguous argument \origin/development\: unknown revision or path not in the working tree.
Use \--\ to separate paths from revisions, like this:
\git [...] -- [...]\\
```

Am I not doing it properly?

Thanks!

(Bazarr Ver. 0.5.6, in a docker on Synology NAS)

**Comment by morpheus65535** [comment]
I cannot reproduce. I suggest you recreate the container after pulling latest image. Your settings are going to be preserved.

**Comment by secret-liar** [comment]
Thanks! You can close the ticket ;)
