### ISSUE TITLE
2 Errors: episodes_subtitles_download and Search for wanted Series Subtitles

### ISSUE THREAD

**Issue by salsa2k** [morpheus65535/bazarr#1164]
Describe the bug
Exception on /api/episodes_subtitles_download [POST]

1. Go to the TV show series
2. Click in missing subtitles download button (automatic not manual)

Obs.
I see that the subtitle downloads complete, but my Post-Processing is not running (automatic only).
For manual download button, the post-processing it's working, so I don't think that it's a problem with the script.

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 62, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 610, in post
  result = download_subtitle(episodePath, language, audio_language, hi, forced, providers_list, providers_auth, sceneName,
 File "/app/bazarr/bazarr/get_subtitle.py", line 269, in download_subtitle
  pp_threshold = int(settings.general.postprocessing_threshold)
ValueError: invalid literal for int() with base 10: \\
```

I'm also getting this error:
```
Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2020-10-22 01:10:50 EDT)" raised an exception
```

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 979, in wanted_search_missing_subtitles_series
  wanted_download_subtitles(episode[\path\], i, count_episodes)
 File "/app/bazarr/bazarr/get_subtitle.py", line 871, in wanted_download_subtitles
  result = download_subtitle(path_mappings.path_replace(episode[\path\]),
 File "/app/bazarr/bazarr/get_subtitle.py", line 269, in download_subtitle
  pp_threshold = int(settings.general.postprocessing_threshold)
ValueError: invalid literal for int() with base 10: \\
```

Software:

Bazarr: v0.9.0.5
Sonarr version: 2.0.0.5344
OS: unraid docker

**Comment by halali** [comment]
Did you play with your config file?
Go to settings and change random setting and save it... You have damaged value in your confit file... 

Than restart bazarr. If that doesnt help then remove your config.ini file and configure bazarr again

**Comment by salsa2k** [comment]
AS far I remember, the only thing that I changed was UNCHECK the "Download a single Subtitles file without adding the language code to the filename." in Settings ->Languages.

* I already have tried to check again, and I get the same problem.
I don't want configure everything again, just if this is my last option :/

**Comment by salsa2k** [comment]
was not the best thing do to... but I did what you suggest and looks like its working now.

**Comment by xus2** [comment]
I just had the same problem and found out the problem was this line in config file;
`days_to_upgrade_subs = `
It was somehow set as empty, set it to 7 and problem solved.
`days_to_upgrade_subs = 7`
