### ISSUE TITLE
Error saving subtitle file to disk

### ISSUE THREAD

**Issue by expostarv2** [morpheus65535/bazarr#1166]
**Describe the bug**
Either through automatic scan or manual download, some subtitles return an error preventing them from being saved

**To Reproduce**
1. Go to 'Wanted'
2. Click on 'Series'
3. Click on 'Search All'
4. See error in log

**Expected behavior**
Expected subtitle to save to disk

**Screenshots**
Below are detail from log

MESSAGE
BAZARR Error saving Subtitles file to disk for this file:D:\TV Shows\South Park\S13\South.Park.S13E14.720p.BluRay.x265-HETeam.mkv: ValueError('Invalid IPv6 URL')

EXCEPTION
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\get_subtitle.py", line 198, in download_subtitle
  saved_subtitles = save_subtitles(video.original_path, subtitles, single=single,
 File "c:\\bazarr\\bazarr\\../libs\\subliminal_patch\\core.py", line 894, in save_subtitles
  content = subtitle.get_modified_content(format=format, debug=debug_mods)
 File "c:\\bazarr\\bazarr\\../libs\\subliminal_patch\\subtitle.py", line 389, in get_modified_content
  submods.modify(*self.mods)
 File "c:\\bazarr\\bazarr\\../libs\\subzero\\modification\\main.py", line 232, in modify
  self.apply_line_mods(new_entries, line_mods)
 File "c:\\bazarr\\bazarr\\../libs\\subzero\\modification\\main.py", line 304, in apply_line_mods
  line = mod.modify(line.strip(), entry=t, debug=self.debug, parent=self, index=index,
 File "c:\\bazarr\\bazarr\\../libs\\subzero\\modification\\mods\\__init__.py", line 81, in modify
  new_content = self._process(new_content, getattr(self, "%sors" % method),
 File "c:\\bazarr\\bazarr\\../libs\\subzero\\modification\\mods\\__init__.py", line 52, in _process
  new_content = processor.process(new_content, debug=debug, **kwargs)
 File "c:\\bazarr\\bazarr\\../libs\\subzero\\modification\\processors\\re_processor.py", line 27, in process
  return self.pattern.sub(self.replace_with, content)
 File "c:\\bazarr\\bazarr\\../libs\\subzero\\modification\\mods\\common.py", line 120, in 
  lambda match: u"%s%s %s" % (match.group(2), match.group(3), match.group(4)) if not get_tld(match.group(1), fail_silently=True, fix_protocol=True) else match.group(1),
 File "c:\\bazarr\\bazarr\\../libs\\tld\\utils.py", line 490, in get_tld
  domain_parts, non_zero_i, parsed_url = process_url(
 File "c:\\bazarr\\bazarr\\../libs\\tld\\utils.py", line 315, in process_url
  parsed_url = urlsplit(url)
 File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\urllib\\parse.py", line 464, in urlsplit
  raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

**Software (please complete the following information):**
Bazarr Version: 0.9.0.5
Sonarr Version: 3.0.4.986
Radarr Version: 0.2.0.1504
Operating System: Windows-10-10.0.18362-SP0
Python Version: 3.8.0

PS. Excellent software and support, thank you

**Comment by expostarv2** [comment]
A possible issue as a result of this error and perhaps other errors, is the 'search all, feature under the wanted section will break after failing a few times on a show. Tried after several restarts and provider changes. This forced me to go to the individual series and search in order to bypass the series returning an error.

**Comment by morpheus65535** [comment]
What subtitles mods have you enabled in Settings-->Subtitles?

**Comment by expostarv2** [comment]
Thank you for pointing me in the right direction. I disabled individual settings one at a time and tested. After disabling 'common fixes' files that previously reported the error were successful in saving to disk.

**Comment by morpheus65535** [comment]
Good, I'll keep in mind to take a look at it in the future.

**Comment by wieluk** [comment]
Hey, having the same problem after disabling 'common fixes' the file can be saved to disk.

**Comment by morpheus65535** [comment]
> Hey, having the same problem after disabling 'common fixes' some of the files can be saved to disk. For others the problem still exists I will try to disable the settings one by one and see what will fix it for the other files

Please provide a debug log once you're able to reproduce.

**Comment by wieluk** [comment]
Sorry I am not able to reproduce apparently it was just for one file that got fixed by disabling 'common fixes' for the other file/s it is another issue ((BAZARR Error trying to get video information for this file) (ValueError: Insufficient data to process the guess))

**Comment by halali** [comment]
Also need debug log...

**Comment by wieluk** [comment]
sorry was not sure if I should post it here because it is not really related to the issue I think

`BAZARR Error trying to get video information for this file: /media/WgNas/Film&Serien/Serien/Attack on Titan (2013)/Season 4/[Tsundere-Raws] Shingeki no Kyojin S4 - 02 VOSTFR [WEBRIP 1080p].mp4 `

`Traceback (most recent call last):
 File "/opt/bazarr/bazarr/get_subtitle.py", line 61, in get_video
  hash_from=hash_from)
 File "/opt/bazarr/bazarr/../libs/subzero/video.py", line 62, in parse_video
  skip_hashing=skip_hashing, hash_from=hash_from)
 File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 534, in scan_video
  video = Video.fromguess(path, guessed_result)
 File "/opt/bazarr/bazarr/../libs/subliminal/video.py", line 94, in fromguess
  return Episode.fromguess(name, guess)
 File "/opt/bazarr/bazarr/../libs/subliminal/video.py", line 171, in fromguess
  raise ValueError(\Insufficient data to process the guess\)
ValueError: Insufficient data to process the guess `

**Comment by halali** [comment]
No this error is bacuse of poor filename guessit can't determinate episode probably. S4. - 02 is not standard convention of naming.

**Comment by wieluk** [comment]
Wouldn‘t it be good to fall back to filename changed by sonarr instead of downloaded name ?
