### ISSUE TITLE
Unexpected error in provider 'supersubtitles': KeyError: 'title'

### ISSUE THREAD

**Issue by stevezau** [morpheus65535/bazarr#1179]
**Describe the bug**
I'm getting the following on supersubtitles.

Running latest dev via linuxserver container.

```
2020-11-03 11:37:35,095 - urllib3.connectionpool           (7fbc68f0ab20) :  DEBUG (connectionpool:394) - https://www.feliratok.info:443 "GET /index.php?term=The%20Dictator's%20Playbook&nyelv=0&action=autoname HTTP/1.1" 200 None
2020-11-03 11:37:35,124 - subliminal_patch.core            (7fbc68f0ab20) :  ERROR (core:199) - Unexpected error in provider 'supersubtitles': Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 396, in list_subtitles
    subs = self.query(title, languages, video=video)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 256, in query
    series_id = self.find_id(series, year, series)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 236, in find_id
    if sanitize(original_title) == sanitize(guess['title']) and year and guess['year'] and \
KeyError: 'title'
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 396, in list_subtitles
    subs = self.query(title, languages, video=video)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 256, in query
    series_id = self.find_id(series, year, series)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 236, in find_id
    if sanitize(original_title) == sanitize(guess['title']) and year and guess['year'] and \
KeyError: 'title'
2020-11-03 11:37:35,125 - root                             (7fbc68f0ab20) :  INFO (get_providers:201) - Throttling supersubtitles for 10 minutes, until 20/11/03 11:47, because of: KeyError. Exception info: 'title'```

**Comment by morpheus65535** [comment]
Is this happening only with one single movie/series or not?

**Comment by stevezau** [comment]
i'm not sure, ill try debug to find out what's going on.

**Comment by morpheus65535** [comment]
Thanks!
