### ISSUE TITLE
 Unexpected error in provider 'subscene` subliminal.exceptions.ProviderError: Something went wrong when trying to log in #1

### ISSUE THREAD

**Issue by stevezau** [morpheus65535/bazarr#1180]
**Describe the bug**
I am getting errors with subscene.

Can you advice on how i troubelshoot this issue? Not much to go on  in the debug log.

```
2020-11-03 11:37:33,767 - subliminal_patch.core            (7fbc68f0ab20) :  ERROR (core:199) - Unexpected error in provider 'subscene': Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__
    provider.initialize()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 152, in initialize
    self.login()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 200, in login
    raise ProviderError("Something went wrong when trying to log in #1")
subliminal.exceptions.ProviderError: Something went wrong when trying to log in #1
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__
    provider.initialize()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 152, in initialize
    self.login()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 200, in login
    raise ProviderError("Something went wrong when trying to log in #1")
subliminal.exceptions.ProviderError: Something went wrong when trying to log in #1
2020-11-03 11:37:33,768 - root                             (7fbc68f0ab20) :  INFO (get_providers:201) - Throttling subscene for 10 minutes, until 20/11/03 11:47, because of: ProviderError. Exception info: 'Something went wrong when trying to log in #1'```

**Comment by morpheus65535** [comment]
What anti-captcha provider are you using?

**Comment by stevezau** [comment]
Hi, i'm using anti-captcha

**Comment by stevezau** [comment]
It's weird as https://anti-captcha.com/clients/reports/stats/spendings shows no calls/spending.

**Comment by morpheus65535** [comment]
I've just tested subscene with anti-captcha and it seems to be working fine for me. Could be related to some specific captcha protection specific to your country. Are you behind a VPN? Can you try without?

**Comment by stevezau** [comment]
I'm not behind a VPN. Is there anyway i can t-shoot/see the html that is returned?

**Comment by morpheus65535** [comment]
Not without using a Python debugger.

**Comment by stevezau** [comment]
Are you able to point me to the code where it makes the request? I can exec into the docker container, edit the .py and insert a print(html)?

**Comment by morpheus65535** [comment]
Something want wrong in: https://github.com/morpheus65535/bazarr/blob/master/libs/subliminal_patch/providers/subscene.py#L154-L199

That raised ProviderError here: https://github.com/morpheus65535/bazarr/blob/7c5839ab0dfdd49d76c59c10ae157ae162f13066/libs/subliminal_patch/providers/subscene.py#L200

**Comment by stevezau** [comment]
@morpheus65535, when  i log manually via chrome it does not show the captcha so that is not posted in the http form post. Also, it has a field called idsrv.xsrf: which looks like a session key..

Curious, do  you see that on yours? 

![image](https://user-images.githubusercontent.com/6075483/98053215-2cc08000-1e8c-11eb-8439-5cb2153232f8.png)

**Comment by stevezau** [comment]
Think it was an issue on my side with my account. closing will reopen if required,
