### ISSUE TITLE
query failing due to db locked

### ISSUE THREAD

**Issue by Zeusy123** [morpheus65535/bazarr#12]
Sorry, the requested URL 'http://127.0.0.1:6767/search_missing_subtitles/653' caused an error:

Internal Server Error
Exception:

OperationalError('database is locked',)
Traceback:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, ka)
  File "D:\Appz\bazarr\bazarr.py", line 172, in search_missing_subtitles
    series_download_subtitles(no)
  File "D:\Appz\bazarr\get_subtitle.py", line 48, in series_download_subtitles
    store_subtitles(path_replace(episode[0]))
  File "D:\Appz\bazarr\list_subtitles.py", line 63, in store_subtitles
    conn_db.commit()
OperationalError: database is locked

**Comment by morpheus65535** [comment]
Issue resolved in:
679813efa4a6f21cfd5b83332a836568be33cd05
669b1a8b926ffe39c98c20fce5b750a3d08a9e88

**Comment by Zeusy123** [comment]
great work!! ;)
