### ISSUE TITLE
BAZARR Error trying to get video information for this file:

### ISSUE THREAD

**Issue by ssafhi** [morpheus65535/bazarr#1220]
**Describe the bug**
when I tried to search for a subtitle I got the following error:

BAZARR Error trying to get video information for this file: /home/USER/data/tvs/American Dad!/Season 15/American Dad! - S15E10 - Railroaded.mkv

**To Reproduce**
1. Go to 'wanted'
2. Click on 'search all'

**Expected behavior**
Traceback (most recent call last):
 File "/opt/USER/Bazarr/bazarr/../libs/knowit/api.py", line 64, in know
  result = provider.describe(video_path, context)
 File "/opt/USER/Bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe
  data = self.executor.extract_info(video_path)
 File "/opt/USER/Bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info
  json_dump = self._execute(filename)
 File "/opt/USER/Bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute
  return ensure_text(check_output([self.location, \-v\, \quiet\, \-print_format\, \json\,
 File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
  return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
 File "/usr/lib/python3.8/subprocess.py", line 512, in run
  raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command \[\/opt/USER/Bazarr/bin/Linux/x86_64/ffmpeg/ffprobe\, \-v\, \quiet\, \-print_format\, \json\, \-show_format\, \-show_streams\, \-sexagesimal\, \/home/USER/data/tvs/American Dad!/Season 15/American Dad! - S15E10 - Railroaded.mkv\]\ returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/opt/USER/Bazarr/bazarr/get_subtitle.py", line 67, in get_video
  refine_from_ffprobe(original_path, video)
 File "/opt/USER/Bazarr/bazarr/get_subtitle.py", line 1089, in refine_from_ffprobe
  data = api.know(path)
 File "/opt/USER/Bazarr/bazarr/../libs/knowit/api.py", line 70, in know
  raise KnowitException(debug_info(context=context, exc_info=True))
knowit.api.KnowitException: +-------------------------------------------------------+

**Screenshots**
https://i.ibb.co/hcDBszY/Capture.png

**Software (please complete the following information):**
 - Bazarr: v0.9.0.7 
 - Radarr version 3.0.1.4302
 - Sonarr version 3.0.4.1033
 - OS: Ubuntu Server 20.04

**Additional context**
N/A

**Comment by halali** [comment]
Hello, this is guessit issue and your poor naming scheme not an bazarr.

If you want help im sure someone on our siscord support channel will help you with your renaming scheme.

Thank you.

**Comment by colinjacques** [comment]
IF this is a naming convention issue, could you elaborate on why it is that way? Or which naming convention works?

**Comment by morpheus65535** [comment]
@colinjacques a good naming convention can be found on Trash guides: https://trash-guides.info/Radarr/V3/Radarr-recommended-naming-scheme/

**Comment by colinjacques** [comment]
Same error occurs under new renaming scheme provided for me....

trying to analyze this .mkv file: H:\Movies\Arkansas (2020)\Arkansas (2020) [imdb-tt9139586][Bluray-1080p][10bit][x265][AAC 5.1].mkv
Exception
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\api.py", line 64, in know
  result = provider.describe(video_path, context)
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\providers\\ffmpeg.py", line 230, in describe
  data = self.executor.extract_info(video_path)
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\providers\\ffmpeg.py", line 89, in extract_info
  json_dump = self._execute(filename)
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\providers\\ffmpeg.py", line 123, in _execute
  return ensure_text(check_output([self.location, \-v\, \quiet\, \-print_format\, \json\,
 File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\subprocess.py", line 411, in check_output
  return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
 File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\subprocess.py", line 512, in run
  raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command \[\C:\\\\Bazarr\\\\bin\\\\Windows\\\\i386\\\\ffmpeg\\\\ffprobe.exe\, \-v\, \quiet\, \-print_format\, \json\, \-show_format\, \-show_streams\, \-sexagesimal\, \H:\\\\Movies\\\\Arkansas (2020)\\\\Arkansas (2020) [imdb-tt9139586][Bluray-1080p][10bit][x265][AAC 5.1].mkv\]\ returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\list_subtitles.py", line 125, in store_subtitles_movie
  subtitle_languages = embedded_subs_reader.list_languages(reversed_path)
 File "c:\\bazarr\\bazarr\\embedded_subs_reader.py", line 19, in list_languages
  data = api.know(file)
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\api.py", line 70, in know
  raise KnowitException(debug_info(context=context, exc_info=True))
knowit.api.KnowitException: +-------------------------------------------------------+

**Comment by halali** [comment]
Open log file and post full tracelog. This is only part of it.

**Comment by colinjacques** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5751332/bazarr.log)

**Comment by halali** [comment]
Come to discord. This is not an bazarr issue... You have something bad with your environment... And hard to help you on GitHub.
