### ISSUE TITLE
BAZARR Error trying to get video information for this file

### ISSUE THREAD

**Issue by colinjacques** [morpheus65535/bazarr#1222]
BAZARR Error trying to get video information for this file appearing on multiple files while searching. Happens every time i search. 

Windows 10 build.

Maybe able to download 2 or 3 subtitle files per hour at most.

Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\api.py", line 64, in know
  result = provider.describe(video_path, context)
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\providers\\ffmpeg.py", line 230, in describe
  data = self.executor.extract_info(video_path)
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\providers\\ffmpeg.py", line 89, in extract_info
  json_dump = self._execute(filename)
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\providers\\ffmpeg.py", line 123, in _execute
  return ensure_text(check_output([self.location, \-v\, \quiet\, \-print_format\, \json\,
 File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\subprocess.py", line 411, in check_output
  return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
 File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\subprocess.py", line 512, in run
  raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command \[\C:\\\\Bazarr\\\\bin\\\\Windows\\\\i386\\\\ffmpeg\\\\ffprobe.exe\, \-v\, \quiet\, \-print_format\, \json\, \-show_format\, \-show_streams\, \-sexagesimal\, \H:\\\\Movies\\\\Zodiac (2007)\\\\Zodiac - 2007 - Bluray-1080p.mkv\]\ returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\get_subtitle.py", line 67, in get_video
  refine_from_ffprobe(original_path, video)
 File "c:\\bazarr\\bazarr\\get_subtitle.py", line 1089, in refine_from_ffprobe
  data = api.know(path)
 File "c:\\bazarr\\bazarr\\../libs\\knowit\\api.py", line 70, in know
  raise KnowitException(debug_info(context=context, exc_info=True))
knowit.api.KnowitException: +-------------------------------------------------------+

**Comment by halali** [comment]
Duplicate #1220

**Comment by morpheus65535** [comment]
Seems to me like an issue with a non existant path. Is drive H: a mapped drive? You're running Bazarr service as Local System account? Take a look at the wiki: https://github.com/morpheus65535/bazarr/wiki/FAQ#this-path-doesnt-seems-to-be-valid
