### ISSUE TITLE
Exception on /api/wanted_series [GET]

### ISSUE THREAD

**Issue by kSotin** [morpheus65535/bazarr#1238]
An exception occurs when I start an API request. 

> Traceback (most recent call last):
 File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/opt/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/opt/bazarr/bazarr/api.py", line 62, in wrapper
  return actual_method(*args, **kwargs)
 File "/opt/bazarr/bazarr/api.py", line 1661, in get
  data = database.execute("SELECT table_shows.title as seriesTitle, table_episodes.monitored, "
TypeError: can only concatenate str (not "int") to str

**Comment by kSotin** [comment]
This should be an easy one. I'll create a Pull Request later.

**Comment by morpheus65535** [comment]
Thanks for the fix!
