### ISSUE TITLE
bazarr using ffprobe on file each time it search for subtitle for this file

### ISSUE THREAD

**Issue by xfouloux** [morpheus65535/bazarr#1243]
**Describe the bug**
Bazarr seems to ffprobe a file that needs a subtitle on each scan, instead of caching the ffprobe result in database or somewhere

This is really problematic for gdrive remote with rclone, doing a lot of api calls, moreover, the ffprobe is needed only once to see if there is included subs in the file i guess ?

So is it really necessary ? Or i'm missing something ?
also i've followed the wiki and i'm following everything that is said to minimize disk request, like not having Use Embedded Subtitles ticked

**To Reproduce**
1. Go to System/Tasks
2. Click on Search for wanted Series Subtitles task
3. check logs

Right now i'm having the google ban and it looks like this

```
24/01/2021 04:45:35|ERROR   |root                            |BAZARR Error trying to get video information for this file: /mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.214.dvdrip-lol.avi|'Traceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.214.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/get_subtitle.py", line 67, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/app/bazarr/get_subtitle.py", line 1089, in refine_from_ffprobe\n    data =
api.know(path)\n  File "/app/bazarr/../libs/knowit/api.py", line 70, in know\n    raise KnowitException(debug_info(context=context, exc_info=True))\nknowit.api.KnowitException: +-------------------------------------------------------+\n|                   KnowIt 0.3.0-dev                    |\n+-------------------------------------------------------+\n|                   /usr/bin/ffprobe                    |\n|                        v4.3.1                         |\n|
                                                      |\n|                        enzyme                         |\n|                         0.4.1                         |\n+-------------------------------------------------------+\n|
                 profile: default                    |\n+-------------------------------------------------------+\nTraceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.214.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\n+-------------------------------------------------------+\n|      Please report any bug or feature request at      |\n|       https://github.com/ratoaq2/knowit/issues.       |\n+-------------------------------------------------------+'|
24/01/2021 04:45:36|ERROR   |root                            |BAZARR Error trying to get video information for this file: /mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.215.dvdrip-lol.avi|'Traceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.215.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/get_subtitle.py", line 67, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/app/bazarr/get_subtitle.py", line 1089, in refine_from_ffprobe\n    data =
api.know(path)\n  File "/app/bazarr/../libs/knowit/api.py", line 70, in know\n    raise KnowitException(debug_info(context=context, exc_info=True))\nknowit.api.KnowitException: +-------------------------------------------------------+\n|                   KnowIt 0.3.0-dev                    |\n+-------------------------------------------------------+\n|                   /usr/bin/ffprobe                    |\n|                        v4.3.1                         |\n|
                                                      |\n|                        enzyme                         |\n|                         0.4.1                         |\n+-------------------------------------------------------+\n|
                 profile: default                    |\n+-------------------------------------------------------+\nTraceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.215.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\n+-------------------------------------------------------+\n|      Please report any bug or feature request at      |\n|       https://github.com/ratoaq2/knowit/issues.       |\n+-------------------------------------------------------+'|
24/01/2021 04:45:38|ERROR   |root                            |BAZARR Error trying to get video information for this file: /mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.216.dvdrip-lol.avi|'Traceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.216.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/get_subtitle.py", line 67, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/app/bazarr/get_subtitle.py", line 1089, in refine_from_ffprobe\n    data =
api.know(path)\n  File "/app/bazarr/../libs/knowit/api.py", line 70, in know\n    raise KnowitException(debug_info(context=context, exc_info=True))\nknowit.api.KnowitException: +-------------------------------------------------------+\n|                   KnowIt 0.3.0-dev                    |\n+-------------------------------------------------------+\n|                   /usr/bin/ffprobe                    |\n|                        v4.3.1                         |\n|
                                                      |\n|                        enzyme                         |\n|                         0.4.1                         |\n+-------------------------------------------------------+\n|
                 profile: default                    |\n+-------------------------------------------------------+\nTraceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.216.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\n+-------------------------------------------------------+\n|      Please report any bug or feature request at      |\n|       https://github.com/ratoaq2/knowit/issues.       |\n+-------------------------------------------------------+'|
24/01/2021 04:45:39|ERROR   |root                            |BAZARR Error trying to get video information for this file: /mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.217.dvdrip-lol.avi|'Traceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.217.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/get_subtitle.py", line 67, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/app/bazarr/get_subtitle.py", line 1089, in refine_from_ffprobe\n    data =
api.know(path)\n  File "/app/bazarr/../libs/knowit/api.py", line 70, in know\n    raise KnowitException(debug_info(context=context, exc_info=True))\nknowit.api.KnowitException: +-------------------------------------------------------+\n|                   KnowIt 0.3.0-dev                    |\n+-------------------------------------------------------+\n|                   /usr/bin/ffprobe                    |\n|                        v4.3.1                         |\n|
                                                      |\n|                        enzyme                         |\n|                         0.4.1                         |\n+-------------------------------------------------------+\n|
                 profile: default                    |\n+-------------------------------------------------------+\nTraceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.217.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\n+-------------------------------------------------------+\n|      Please report any bug or feature request at      |\n|       https://github.com/ratoaq2/knowit/issues.       |\n+-------------------------------------------------------+'|
24/01/2021 04:45:41|ERROR   |root                            |BAZARR Error trying to get video information for this file: /mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.218.dvdrip-lol.avi|'Traceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.218.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/get_subtitle.py", line 67, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/app/bazarr/get_subtitle.py", line 1089, in refine_from_ffprobe\n    data =
api.know(path)\n  File "/app/bazarr/../libs/knowit/api.py", line 70, in know\n    raise KnowitException(debug_info(context=context, exc_info=True))\nknowit.api.KnowitException: +-------------------------------------------------------+\n|                   KnowIt 0.3.0-dev                    |\n+-------------------------------------------------------+\n|                   /usr/bin/ffprobe                    |\n|                        v4.3.1                         |\n|
                                                      |\n|                        enzyme                         |\n|                         0.4.1                         |\n+-------------------------------------------------------+\n|
                 profile: default                    |\n+-------------------------------------------------------+\nTraceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.218.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\n+-------------------------------------------------------+\n|      Please report any bug or feature request at      |\n|       https://github.com/ratoaq2/knowit/issues.       |\n+-------------------------------------------------------+'|
24/01/2021 04:45:42|ERROR   |root                            |BAZARR Error trying to get video information for this file: /mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.219.dvdrip-lol.avi|'Traceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.219.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/get_subtitle.py", line 67, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/app/bazarr/get_subtitle.py", line 1089, in refine_from_ffprobe\n    data =
api.know(path)\n  File "/app/bazarr/../libs/knowit/api.py", line 70, in know\n    raise KnowitException(debug_info(context=context, exc_info=True))\nknowit.api.KnowitException: +-------------------------------------------------------+\n|                   KnowIt 0.3.0-dev                    |\n+-------------------------------------------------------+\n|                   /usr/bin/ffprobe                    |\n|                        v4.3.1                         |\n|
                                                      |\n|                        enzyme                         |\n|                         0.4.1                         |\n+-------------------------------------------------------+\n|
                 profile: default                    |\n+-------------------------------------------------------+\nTraceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.219.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\n+-------------------------------------------------------+\n|      Please report any bug or feature request at      |\n|       https://github.com/ratoaq2/knowit/issues.       |\n+-------------------------------------------------------+'|
24/01/2021 04:45:44|ERROR   |root                            |BAZARR Error trying to get video information for this file: /mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.220.dvdrip-lol.avi|'Traceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.220.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/get_subtitle.py", line 67, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/app/bazarr/get_subtitle.py", line 1089, in refine_from_ffprobe\n    data = api.know(path)\n  File "/app/bazarr/../libs/knowit/api.py", line 70, in know\n    raise KnowitException(debug_info(context=context, exc_info=True))\nknowit.api.KnowitException: +-------------------------------------------------------+\n|                   KnowIt 0.3.0-dev                    |\n+-------------------------------------------------------+\n|                   /usr/bin/ffprobe                    |\n|                        v4.3.1                         |\n|                                                       |\n|                        enzyme                         |\n|                         0.4.1                         |\n+-------------------------------------------------------+\n|                   profile: default                    |\n+-------------------------------------------------------+\nTraceback (most recent call last):\n  File "/app/bazarr/../libs/knowit/api.py", line 64, in know\n    result = provider.describe(video_path, context)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe\n    data = self.executor.extract_info(video_path)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info\n    json_dump = self._execute(filename)\n  File "/app/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute\n    return ensure_text(check_output([self.location, \'-v\', \'quiet\', \'-print_format\', \'json\',\n  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/usr/lib/python3.8/subprocess.py", line 512, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/ffprobe\', \'-v\', \'quiet\', \'-print_format\', \'json\', \'-show_format\', \'-show_streams\', \'-sexagesimal\', \'/mnt/unionfs/Media/TV/Hercules- The Legendary Journeys/Season 02/hercules.220.dvdrip-lol.avi\']\' returned non-zero exit status 1.\n\n+-------------------------------------------------------+\n|      Please report any bug or feature request at      |\n|       https://github.com/ratoaq2/knowit/issues.       |\n+-------------------------------------------------------+'|
```

**Software (please complete the following information):**
 - Bazarr: v0.9.0.7
 - Radarr version : not using
 - Sonarr version : 3.0.4.1077
 - OS: docker hotio/bazarr (pulled in the last week) on ubuntu 20.04

**Comment by halali** [comment]
Disable daily scan for existing subtitles will fix your issue as its mentioned in wiki page that Trash send you on discord.

**Comment by xfouloux** [comment]
But i'm already having this setting set to manual !

**Comment by morpheus65535** [comment]
I guess this happen during search for subtitles. In that case, it normal behavior for Bazarr to ffprobe the file during that search process. Currently we don't cache the ffprobe for media file. This could be possible using [cache_on_arguments](https://dogpilecache.sqlalchemy.org/en/latest/api.html#dogpile.cache.region.CacheRegion.cache_on_arguments) decorator on [refine_from_ffprobe](https://github.com/morpheus65535/bazarr/blob/master/bazarr/get_subtitle.py#L1093-L1132) function.

**Comment by ArabCoders** [comment]
@morpheus65535 any plans to cache the results? it seems unreasonable to run ffprobe on all items specially with cloud content without caching the result, and the ffprobe should be tied to item 'name|size' as cache item key and only recheck if it does not match.

**Comment by morpheus65535** [comment]
> @morpheus65535 any plans to cache the results? it seems unreasonable to run ffprobe on all items specially with cloud content without caching the result, and the ffprobe should be tied to item 'name|size' as cache item key and only recheck if it does not match.

Although I found "unreasonable" a little hard, yes I agree this can be improved and I have plan for it. It's just not my first priority right now.

It's quite high on the feature requests page: https://bazarr.featureupvote.com/suggestions/158694/cache-video-file-attributes-to-prevent-running-ffprobe-on-every-subtitles-search

**Comment by ArabCoders** [comment]
@morpheus65535 are you open to pull request if i somehow manage to make it work? i have little experience with python but i should be able to get it working hopefully.

**Comment by morpheus65535** [comment]
I have in mind to add episodeFile table and movieFile table from Sonarr/Radarr API and reuse that. I'm still not sure how I'm gonna manage cache expiration. Still have to think about it. Of course, I'm open to PR but I suggest we talk about it before you get into it. Come see me on Discord dev community channel if you want to.

**Comment by ArabCoders** [comment]
> I have in mind to add episodeFile table and movieFile table from Sonarr/Radarr API and reuse that. I'm still not sure how I'm gonna manage cache expiration. Still have to think about it. Of course, I'm open to PR but I suggest we talk about it before you get into it. Come see me on Discord dev community channel if you want to.

sorry for late response, i was thinking of expanding the episodes and movie table by adding two new columns, one as cache key and the other one for JSON encoded payload of either the direct ffprobe or the data from sonarr/radarr, the cache expiration can be tied to 

'Filename|size', as it's unlikely for the file to be changed and still retain the same exact size no? we very well could hash the content but that also is very expensive operation which is why im trying to avoid running ffprobe in the first place. 

for reference i added my own local content to bazarr with 46669 local files, and it took around 18hrs to finish scanning them.

**Comment by morpheus65535** [comment]
Of course, I'll look to your PR once the kids and wife are asleep.

**Comment by ArabCoders** [comment]
This can be closed as changes are pushed to dev branch.
