### ISSUE TITLE
Job Upgrade previously downloaded Subtitles raised an exception

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1253]
Recently on newest dev version from docker:

Bazarr Version:
0.9.1
Sonarr Version:
3.0.4.1091
Radarr Version:
3.0.2.4504
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.5
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

i got problem with not upgrading previously downloaded subs
log
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 1333, in upgrade_subtitles
  if episode[\language\].endswith(\forced\):
UnboundLocalError: local variable \episode\ referenced before assignment

**Comment by morpheus65535** [comment]
I've just pushed a fix for this one. Thanks for reporting! Please confirm if it's fixed or not.

**Comment by lukjod** [comment]
Nope, not good now it has some error in 
/api/series

Log:

Exception on /api/series [GET]

Details

Message Exception on /api/series [GET] Exception Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 60, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 334, in get
  item.update({"audio_language": get_audio_profile_languages(series_id=item[\sonarrSeriesId\])})
 File "/app/bazarr/bazarr/database.py", line 319, in get_audio_profile_languages
  audio_languages_list = ast.literal_eval(audio_languages_list_str)
 File "/usr/lib/python3.8/ast.py", line 99, in literal_eval
  return _convert(node_or_string)
 File "/usr/lib/python3.8/ast.py", line 98, in _convert
  return _convert_signed_num(node)
 File "/usr/lib/python3.8/ast.py", line 75, in _convert_signed_num
  return _convert_num(node)
 File "/usr/lib/python3.8/ast.py", line 66, in _convert_num
  _raise_malformed_node(node)
 File "/usr/lib/python3.8/ast.py", line 63, in _raise_malformed_node
  raise ValueError(f\malformed node or string: {node!r}\)
ValueError: malformed node or string: <_ast.Name object at 0x7f2e9cdee430>

**Comment by morpheus65535** [comment]
Can you show me a screenshot of your languages profiles?

**Comment by lukjod** [comment]
Here it is![Screenshot_20210201-074653_Firefox.jpg](https://user-images.githubusercontent.com/1781446/106423975-b7038a80-6461-11eb-9326-dadc13fff824.jpg)

**Comment by morpheus65535** [comment]
I've push a fix to prevent this error. Also, I added info level logging after upgrade process completion. It's normal if you didn't see anything prior to that fix. Let it run for a day or two and confirm if everything is ok.

**Comment by lukjod** [comment]
All seems to be OK now, no more errors valid info on logs

As usual Perfect Job!

Big Thx

**Comment by morpheus65535** [comment]
Thanks for the feedback!
