### ISSUE TITLE
Exception: ValueError('Invalid IPv6 URL')

### ISSUE THREAD

**Issue by ak2k** [morpheus65535/bazarr#1264]
**Describe the bug**

Exception: BAZARR Error saving Subtitles file to disk for this file:/tv/The Show/Season 10/The Show - S10E04 - Episode Title [DVD ].avi: ValueError('Invalid IPv6 URL')

Traceback (most recent call last):
 File "/app/bazarr/get_subtitle.py", line 199, in download_subtitle
  saved_subtitles = save_subtitles(video.original_path, subtitles, single=single,
 File "/app/bazarr/../libs/subliminal_patch/core.py", line 894, in save_subtitles
  content = subtitle.get_modified_content(format=format, debug=debug_mods)
 File "/app/bazarr/../libs/subliminal_patch/subtitle.py", line 389, in get_modified_content
  submods.modify(*self.mods)
 File "/app/bazarr/../libs/subzero/modification/main.py", line 232, in modify
  self.apply_line_mods(new_entries, line_mods)
 File "/app/bazarr/../libs/subzero/modification/main.py", line 304, in apply_line_mods
  line = mod.modify(line.strip(), entry=t, debug=self.debug, parent=self, index=index,
 File "/app/bazarr/../libs/subzero/modification/mods/__init__.py", line 81, in modify
  new_content = self._process(new_content, getattr(self, "%sors" % method),
 File "/app/bazarr/../libs/subzero/modification/mods/__init__.py", line 52, in _process
  new_content = processor.process(new_content, debug=debug, **kwargs)
 File "/app/bazarr/../libs/subzero/modification/processors/re_processor.py", line 27, in process
  return self.pattern.sub(self.replace_with, content)
 File "/app/bazarr/../libs/subzero/modification/mods/common.py", line 120, in 
  lambda match: u"%s%s %s" % (match.group(2), match.group(3), match.group(4)) if not get_tld(match.group(1), fail_silently=True, fix_protocol=True) else match.group(1),
 File "/app/bazarr/../libs/tld/utils.py", line 490, in get_tld
  domain_parts, non_zero_i, parsed_url = process_url(
 File "/app/bazarr/../libs/tld/utils.py", line 315, in process_url
  parsed_url = urlsplit(url)
 File "/usr/lib/python3.8/urllib/parse.py", line 464, in urlsplit
  raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

**Software (please complete the following information):**
 - Bazarr: 0.9.0.8
 - Radarr version 3.0.2.4552
 - Sonarr version 3.0.4.1100
 - OS: Linux-5.4.0-65-generic-x86_64-with
 - Python: 3.8.7

**Additional context**
Perhaps the issue is that urlsplit is not appropriately handling files with brackets, instead thinking that they are IPV6 addresses?

**Comment by morpheus65535** [comment]
That's a bug in CommonFixes. You can disable it in Settings-->Subtitles.

**Comment by ak2k** [comment]
Thank you!
