### ISSUE TITLE
Unable to auto or manually download a sub from BetaSeries

### ISSUE THREAD

**Issue by hergonoway** [morpheus65535/bazarr#1273]
**Describe the bug**
Unable to auto or manually download a sub from BetaSeries. In auto, each attempt results like nothing is found, and if searched manually and clicked the download button the manual search window close but the sub is not downloaded. I've got the same issue for any episode of this show.

**Screenshots**
Example in the logs: searching an FR sub for Prodigal Son S02E01
In the sreenshot you see the release chosen while trying to download manually

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/8405448/108135905-3d9ea580-70b9-11eb-8e6f-55a22497cb1f.png">

**Software (please complete the following information):**
 - Bazarr: v0.9.1
 - Radarr version 3.1.0.4634
 - Sonarr version 3.0.4.1129
 - OS: docker under linux

LOGS of what happens when I try to download the file manually (cf screenshot):
```
17/02/2021 00:30:36|DEBUG   |root                            |BAZARR Manually downloading Subtitles for this file: /tv/Prodigal Son (2019)/Season 02/Prodigal Son (2019) - S02E01 - [x264][WEBDL-1080p] -CAKES.mkv|
17/02/2021 00:30:36|INFO    |subliminal_patch.providers.tvsubtitles|Found subtitle <TVsubtitlesSubtitle 'http://www.tvsubtitles.net/subtitle-286174.html' [pt:None]>|
17/02/2021 00:30:36|DEBUG   |subzero.video                   |Parsing video: Prodigal.Son.S02E01.1080p.WEB.H264-CAKES.mkv, hints: {'title': 'Prodigal Son', 'type': 'episode'}|
17/02/2021 00:30:36|INFO    |subliminal_patch.providers.tvsubtitles|Found subtitle <TVsubtitlesSubtitle 'http://www.tvsubtitles.net/subtitle-286205.html' [pt:None]>|
17/02/2021 00:30:36|INFO    |subliminal_patch.core           |Determining basic video properties for 'Prodigal.Son.S02E01.1080p.WEB.H264-CAKES.mkv' in '/tv/Prodigal Son (2019)/Season 02'|
17/02/2021 00:30:36|INFO    |subliminal_patch.providers.tvsubtitles|Found subtitle <TVsubtitlesSubtitle 'http://www.tvsubtitles.net/subtitle-286300.html' [pt:None]>|
17/02/2021 00:30:36|INFO    |subliminal_patch.providers.tvsubtitles|Found subtitle <TVsubtitlesSubtitle 'http://www.tvsubtitles.net/subtitle-286301.html' [pt:None]>|
17/02/2021 00:30:36|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Prodigal Son",
    "year": 2019,
    "season": 2,
    "episode": 1,
    "screen_size": "1080p",
    "source": "Web",
    "video_codec": "H.264",
    "release_group": "CAKES",
    "container": "mkv",
    "type": "episode"
}|
17/02/2021 00:30:36|DEBUG   |subliminal_patch.core           |Size is 1634053062|
17/02/2021 00:30:36|DEBUG   |subliminal_patch.core           |Computed hashes {}|
17/02/2021 00:30:36|DEBUG   |root                            |BAZARR returning this binary: /usr/bin/ffprobe|
17/02/2021 00:30:36|DEBUG   |root                            |BAZARR FFprobe used is /usr/bin/ffprobe|
17/02/2021 00:30:37|DEBUG   |root                            |FFprobe found: OrderedDict([('path', '/tv/Prodigal Son (2019)/Season 02/Prodigal Son (2019) - S02E01 - [x264][WEBDL-1080p] -CAKES.mkv'), ('duration', datetime.timedelta(seconds=2608, microseconds=890000)), ('size', 1634053062), ('bit_rate', 5010722), ('container', 'mkv'), ('video', [OrderedDict([('id', 0), ('width', 1920), ('height', 1080), ('scan_type', 'Progressive'), ('aspect_ratio', 1.778), ('pixel_aspect_ratio', 1.0), ('resolution', '1080p'), ('frame_rate', 23.976), ('bit_depth', 8), ('codec', 'H.264'), ('profile', 'High'), ('default', True)])]), ('audio', [OrderedDict([('id', 1), ('language', <Language [en]>), ('codec', 'AAC'), ('profile', 'High Efficiency'), ('channels_count', 2), ('channels', '2.0'), ('sampling_rate', 48000), ('default', True)])]), ('subtitle', [OrderedDict([('id', 2), ('language', <Language [en]>), ('format', 'SubRip')])]), ('provider', {'name': 'ffmpeg', 'version': {'/usr/bin/ffprobe': 'v4.3.1'}})])|
17/02/2021 00:30:37|DEBUG   |root                            |BAZARR is using these video object properties: {'name': '/tv/Prodigal Son (2019)/Season 02/Prodigal.Son.S02E01.1080p.WEB.H264-CAKES.mkv', 'source': 'Web', 'release_group': 'CAKES', 'resolution': '1080p', 'video_codec': 'H.264', 'audio_codec': 'AAC', 'imdb_id': None, 'hashes': {}, 'size': 1634053062, 'subtitle_languages': set(), 'original_name': 'Prodigal Son (2019) - S02E01 - [x264][WEBDL-1080p] -CAKES.mkv', 'plexapi_metadata': {}, 'hints': {'title': 'Prodigal Son', 'type': 'episode', 'single_value': True, 'expected_title': ['Prodigal Son']}, 'audio_languages': {'eng'}, 'external_subtitle_languages': set(), 'series': 'Prodigal Son', 'season': 2, 'episode': 1, 'title': 'It’s All in the Execution', 'year': 2019, 'original_series': False, 'tvdb_id': None, 'series_tvdb_id': 352883, 'series_imdb_id': 'tt10327354', 'alternative_series': [], 'used_scene_name': True, 'original_path': '/tv/Prodigal Son (2019)/Season 02/Prodigal Son (2019) - S02E01 - [x264][WEBDL-1080p] -CAKES.mkv', 'fps': 23.976}|
17/02/2021 00:30:37|INFO    |subliminal_patch.core           |Using 1 threads for 1 providers ({'betaseries'})|
17/02/2021 00:30:37|INFO    |subliminal_patch.core           |Downloading subtitle <BetaSeriesSubtitle 'https://www.betaseries.com/srt/881629' [fr:None]> with score 355|
17/02/2021 00:30:37|INFO    |subliminal_patch.core           |Downloading subtitle <BetaSeriesSubtitle 'https://www.betaseries.com/srt/881629' [fr:None]>|
17/02/2021 00:30:37|INFO    |subliminal_patch.core           |Initializing provider betaseries|
17/02/2021 00:30:37|INFO    |subliminal_patch.providers.betaseries|Downloading subtitle <BetaSeriesSubtitle 'https://www.betaseries.com/srt/881629' [fr:None]>|
17/02/2021 00:30:37|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.betaseries.com:443|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.betaseries.com|
17/02/2021 00:30:37|DEBUG   |urllib3.connectionpool          |https://www.podnapisi.net:443 "GET /subtitles/search/old?sXML=1&sL=en&sK=the+100&sTS=2&sTE=16&sY=2014 HTTP/1.1" 200 8402|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.providers.podnapisi|Found subtitle <PodnapisiSubtitle 'https://www.podnapisi.net/en/subtitles/en-the-100-2014-S02E16-O/a8Y_' [en:None]>|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.providers.podnapisi|Found subtitle <PodnapisiSubtitle 'https://www.podnapisi.net/en/subtitles/en-the-100-2014-S02E16-O/aMY_' [en:None]>|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.providers.podnapisi|Found subtitle <PodnapisiSubtitle 'https://www.podnapisi.net/en/subtitles/en-the-100-2014-S02E16-O/S_s-' [en:None]>|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.providers.podnapisi|Found subtitle <PodnapisiSubtitle 'https://www.podnapisi.net/en/subtitles/en-the-100-2014-S02E16-O/Gm87' [en:None]>|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.providers.podnapisi|Found subtitle <PodnapisiSubtitle 'https://www.podnapisi.net/en/subtitles/en-the-100-2014-S02E16-O/Clw7' [en:None]>|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.providers.podnapisi|Found subtitle <PodnapisiSubtitle 'https://www.podnapisi.net/en/subtitles/en-the-100-2014-S02E16-O/nVw7' [en:None]>|
17/02/2021 00:30:37|DEBUG   |urllib3.connectionpool          |https://www.betaseries.com:443 "GET /srt/881629 HTTP/1.1" 302 None|
17/02/2021 00:30:37|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): subtitles.betaseries.com:443|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on subtitles.betaseries.com|
17/02/2021 00:30:37|DEBUG   |urllib3.connectionpool          |https://subtitles.betaseries.com:443 "GET /uploaded/Prodigal%20Son%20-%20S02E01%20-%20It%E2%80%99s%20All%20In%20The%20Execution?%20(WEB.H264-CAKES).srt HTTP/1.1" 200 149|
17/02/2021 00:30:37|INFO    |subliminal_patch.subtitle       |Guessing encoding for language fr|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.subtitle       |Trying encodings ['utf-8', 'windows-1252', 'iso-8859-15', 'iso-8859-9', 'iso-8859-4', 'iso-8859-1']|
17/02/2021 00:30:37|INFO    |subliminal_patch.subtitle       |Guessed encoding utf-8|
17/02/2021 00:30:37|ERROR   |subliminal_patch.subtitle       |PySRT-parsing failed, trying pysubs2|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.subtitle       |Trying parsing with PySubs2|
17/02/2021 00:30:37|ERROR   |subliminal_patch.subtitle       |Couldn't convert subtitle <BetaSeriesSubtitle 'https://www.betaseries.com/srt/881629' [fr:utf-8]> to .srt format: Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats|
17/02/2021 00:30:37|ERROR   |subliminal_patch.core           |Invalid subtitle|
17/02/2021 00:30:37|DEBUG   |subliminal.core                 |Terminating initialized providers|
17/02/2021 00:30:37|INFO    |subliminal_patch.core           |Terminating provider betaseries|
17/02/2021 00:30:37|DEBUG   |root                            |BAZARR Subtitles file downloaded for this file:/tv/Prodigal Son (2019)/Season 02/Prodigal Son (2019) - S02E01 - [x264][WEBDL-1080p] -CAKES.mkv|
17/02/2021 00:30:37|ERROR   |subliminal_patch.subtitle       |PySRT-parsing failed, trying pysubs2|
17/02/2021 00:30:37|DEBUG   |subliminal_patch.subtitle       |Trying parsing with PySubs2|
17/02/2021 00:30:37|ERROR   |subliminal_patch.subtitle       |Couldn't convert subtitle <BetaSeriesSubtitle 'https://www.betaseries.com/srt/881629' [fr:utf-8]> to .srt format: Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats|
17/02/2021 00:30:37|ERROR   |root                            |BAZARR No valid Subtitles file found for this file: /tv/Prodigal Son (2019)/Season 02/Prodigal Son (2019) - S02E01 - [x264][WEBDL-1080p] -CAKES.mkv|NoneType: None|
17/02/2021 00:30:39|DEBUG   |chardet.charsetprober           |SHIFT_JIS Japanese prober hit error at byte 2228|
17/02/2021 00:30:39|DEBUG   |chardet.charsetprober           |EUC-JP Japanese prober hit error at byte 2226|
17/02/2021 00:30:39|DEBUG   |chardet.charsetprober           |GB2312 Chinese prober hit error at byte 2228|
17/02/2021 00:30:39|DEBUG   |chardet.charsetprober           |EUC-KR Korean prober hit error at byte 2226|
17/02/2021 00:30:39|DEBUG   |chardet.charsetprober           |CP949 Korean prober hit error at byte 2226|
17/02/2021 00:30:39|DEBUG   |chardet.charsetprober           |Big5 Chinese prober hit error at byte 2227|
17/02/2021 00:30:39|DEBUG   |chardet.charsetprober           |EUC-TW Taiwan prober hit error at byte 2226|
17/02/2021 00:30:40|DEBUG   |urllib3.connectionpool          |https://www.sous-titres.eu:443 "GET /search.html?q=The+100 HTTP/1.1" 200 None|
17/02/2021 00:30:40|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
17/02/2021 00:30:41|INFO    |socketio.server                 |emitting event "event" to all [/]|
```

**Comment by morpheus65535** [comment]
That's an issue on their side. If you download the .srt file referred in your log file: https://subtitles.betaseries.com/uploaded/Prodigal%20Son%20-%20S02E01%20-%20It%E2%80%99s%20All%20In%20The%20Execution?%20(WEB.H264-CAKES).srt

You get a text file with the path to the subtitles file on their server: `/mnt/nfs/betaseries/production/releases/20210127101252/www/data/srt/uploads/Prodigal Son - S02E01 - It’s All In The Execution? (WEB.H264-CAKES).srt`
