### ISSUE TITLE
Trying to get subtitles for my movies and it is erroring out

### ISSUE THREAD

**Issue by thezak48** [morpheus65535/bazarr#1288]
**Describe the bug**
Trying to get subtitles for my movies and it is erroring out, error is below

**Expected behavior**
Find Subtitles for movies

**Screenshots**
```
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\get_subtitle.py", line 62, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
 File "c:\\bazarr\\bazarr\\../libs\\subzero\\video.py", line 61, in parse_video
  return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
 File "c:\\bazarr\\bazarr\\../libs\\subliminal_patch\\core.py", line 552, in scan_video
  video.size = os.path.getsize(hash_path)
 File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\genericpath.py", line 50, in getsize
  return os.stat(filename).st_size
FileNotFoundError: [WinError 3] The system cannot find the path specified: \Z:\\\\Films\\\\I Care a Lot (2021)\\\\I Care a Lot (2021) WEBRip-1080p.mp4\
```

**Software (please complete the following information):**
Bazarr Version: 0.9.1
Sonarr Version: 3.0.4.1130
Radarr Version: 3.0.2.4552
Operating System: Windows-10-10.0.17763-SP0

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/FAQ#this-path-doesnt-seems-to-be-valid

For support, come to Discord support channel.
