### ISSUE TITLE
Bazarr Can't Update to latest 

### ISSUE THREAD

**Issue by jplobao** [morpheus65535/bazarr#1301]
Hi,

Bazarr can't Update no new version, it stucked in Bazarr Version: 0.8.4
This instalation is in windows. Tried to run with and without Windows Administrator user, with no sucess.
Can you help?

Here are error log:
Message
Job "Update Bazarr from source on Github (trigger: interval[6:00:00], next run at: 2021-03-02 07:58:50 GMT)" raised an exception
Exception
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "c:\\bazarr\\bazarr\\check_update.py", line 44, in check_and_apply_update
  g.fetch(\origin\)
 File "c:\\bazarr\\bazarr\\../libs\\git\\cmd.py", line 548, in
  return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
 File "c:\\bazarr\\bazarr\\../libs\\git\\cmd.py", line 1014, in _call_process
  return self.execute(call, **exec_kwargs)
 File "c:\\bazarr\\bazarr\\../libs\\git\\cmd.py", line 825, in execute
  raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd(\git\) failed due to: exit code(128)
 cmdline: git fetch origin
 stderr: \fatal: \origin\ does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.\

**Comment by jplobao** [comment]
Reinstalled Bazarr
