### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by rodalpho** [morpheus65535/bazarr#1319]
Bazarr is crashing on startup with the following error in syslog. Any way to fix this?

```
Mar 14 12:13:52 bazarrhost systemd[1]: Started Bazarr Daemon.
Mar 14 12:13:54 bazarrhost bazarr[1900545]: Traceback (most recent call last):
Mar 14 12:13:54 bazarrhost bazarr[1900545]:   File "/opt/Bazarr/bazarr/main.py", line 36, in <module>
Mar 14 12:13:54 bazarrhost bazarr[1900545]:     from get_episodes import *
Mar 14 12:13:54 bazarrhost bazarr[1900545]:   File "/opt/Bazarr/bazarr/get_episodes.py", line 10, in <module>
Mar 14 12:13:54 bazarrhost bazarr[1900545]:     from get_subtitle import episode_download_subtitles
Mar 14 12:13:54 bazarrhost bazarr[1900545]:   File "/opt/Bazarr/bazarr/get_subtitle.py", line 30, in <module>
Mar 14 12:13:54 bazarrhost bazarr[1900545]:     from get_providers import get_providers, get_providers_auth, provider_throttle, provider_pool
Mar 14 12:13:54 bazarrhost bazarr[1900545]:   File "/opt/Bazarr/bazarr/get_providers.py", line 301, in <module>
Mar 14 12:13:54 bazarrhost bazarr[1900545]:     tp = eval(str(get_throttled_providers()))
Mar 14 12:13:54 bazarrhost bazarr[1900545]:   File "<string>", line 1
Mar 14 12:13:54 bazarrhost bazarr[1900545]:     {'tvsubtitles': ('TypeError', datetime.datetime(2021, 3, 14, 4, 3, 59, 536400), '10 minutes')} 'opensubtitles': ('TypeError', datetime.datetime(2021, 3, 14, 4, 3, 59, 537008), '10 minutes')}
Mar 14 12:13:54 bazarrhost bazarr[1900545]:                                                                                                    ^
Mar 14 12:13:54 bazarrhost bazarr[1900545]: SyntaxError: invalid syntax
Mar 14 12:13:55 bazarrhost bazarr[1900544]: Bazarr starting...
Mar 14 12:13:55 bazarrhost bazarr[1900544]: Bazarr exited.
Mar 14 12:13:55 bazarrhost systemd[1]: bazarr.service: Succeeded.
```

**Comment by morpheus65535** [comment]
Delete the file `config/config/throttled_providers.dat` and restart Bazarr.

**Comment by rodalpho** [comment]
Thank you, that worked perfectly!
