### ISSUE TITLE
Exception on /api/series [PATCH]

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1339]
Such error appears on
Bazarr Version
0.9.4-beta.7
Sonarr Version
3.0.5.1144
Radarr Version
3.1.0.4799
Operating System
Linux-4.14.24-qnap-x86_64-with
Python Version
3.8.8
Bazarr Directory
/app/bazarr
Bazarr Config Directory
/config
log
`Traceback (most recent call last):

  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper

    resp = resource(*args, **kwargs)

  File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request

    resp = meth(*args, **kwargs)

  File "/app/bazarr/bazarr/api.py", line 84, in wrapper

    return actual_method(*args, **kwargs)

  File "/app/bazarr/bazarr/api.py", line 661, in patch

    wanted_search_missing_subtitles_series()

  File "/app/bazarr/bazarr/get_subtitle.py", line 1071, in wanted_search_missing_subtitles_series

    wanted_download_subtitles(episode[\'path\'], i, count_episodes)

  File "/app/bazarr/bazarr/get_subtitle.py", line 957, in wanted_download_subtitles

    result = download_subtitle(path_mappings.path_replace(episode[\'path\']),

  File "/app/bazarr/bazarr/get_subtitle.py", line 150, in download_subtitle

    lang_obj = Language(l)

  File "/app/bazarr/bazarr/../libs/subzero/language.py", line 87, in __init__

    super(Language, self).__init__(language, country=country, script=script, unknown=unknown)

  File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 81, in __init__

    raise ValueError(\'%r is not a valid language\' % language)

ValueError: None is not a valid language`

**Comment by morpheus65535** [comment]
How can I reproduce?

**Comment by morpheus65535** [comment]
You have an issue with one of your languages profiles that doesn't have a language. Fix that.
