### ISSUE TITLE
Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2021-03-26 11:03:28 CET)" raised an exception

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1342]
Bazarr Version
0.9.4-beta.7
Sonarr Version
3.0.5.1144
Radarr Version
3.1.0.4799
Operating System
Linux-4.14.24-qnap-x86_64-with
Python Version
3.8.8
Bazarr Directory
/app/bazarr
Bazarr Config Directory
/config

log:
`Traceback (most recent call last):

  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/app/bazarr/bazarr/get_subtitle.py", line 1071, in wanted_search_missing_subtitles_series

    wanted_download_subtitles(episode[\'path\'], i, count_episodes)

  File "/app/bazarr/bazarr/get_subtitle.py", line 957, in wanted_download_subtitles

    result = download_subtitle(path_mappings.path_replace(episode[\'path\']),

  File "/app/bazarr/bazarr/get_subtitle.py", line 150, in download_subtitle

    lang_obj = Language(l)

  File "/app/bazarr/bazarr/../libs/subzero/language.py", line 87, in __init__

    super(Language, self).__init__(language, country=country, script=script, unknown=unknown)

  File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 81, in __init__

    raise ValueError(\'%r is not a valid language\' % language)

ValueError: None is not a valid language`

**Comment by morpheus65535** [comment]
Duplicate #1339
