### ISSUE TITLE
Job "Search for wanted Movies Subtitles (trigger: interval[3:00:00], next run at: 2021-03-26 15:34:26 CET)" raised an exception

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1344]
After roll back to main version still problem althought I have corrected lang profile

Bazarr Version:
0.9.3
Sonarr Version:
3.0.5.1144
Radarr Version:
3.1.0.4799
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.8
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

log:
`Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 1075, in wanted_search_missing_subtitles_movies
  wanted_download_subtitles_movie(movie[\path\], i, count_movies)
 File "/app/bazarr/bazarr/get_subtitle.py", line 1011, in wanted_download_subtitles_movie
  result = download_subtitle(path_mappings.path_replace_movie(movie[\path\]),
 File "/app/bazarr/bazarr/get_subtitle.py", line 177, in download_subtitle
  downloaded_subtitles = download_best_subtitles({video}, language_set, int(min_score), hi,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 820, in download_best_subtitles
  subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 462, in list_subtitles
  for provider, provider_subtitles in executor.map(self.list_subtitles_provider, self.providers,
 File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
  yield fs.pop().result()
 File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
  return self.__get_result()
 File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
  raise self._exception
 File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 448, in list_subtitles_provider
  provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 148, in list_subtitles_provider
  if not provider_registry[provider].check(video):
AttributeError: \NoneType\ object has no attribute \check\`

**Comment by mvanbaak** [comment]
This happens if you upgraded to a 0.9.4 beta, then go back to 0.9.3.
The provider configuration is lost, so it errors out.

Remove the bazarr database etc and start over, or go back to a backup from before you upgraded to 0.9.4-beta.*

**Comment by lukjod** [comment]
ok thx for clarify

**Comment by mvanbaak** [comment]
You're welcome. I had the same error after exactly doing this. But it's expected as 0.9.4 saves the providers configuration in a different format.

**Comment by morpheus65535** [comment]
You can also just set `enabled_provides` to nothing (empty string) in config.ini.
