### ISSUE TITLE
Bazarr doesn't like change of daylight savings 

### ISSUE THREAD

**Issue by Magikarplvl4** [morpheus65535/bazarr#1350]
**Describe the bug**
Docker container won't start the day before there is a daylight saving change.

**To Reproduce**
1. Start docker the day before a daylight change
2. Open docker logs in Unraid

**Expected behavior**

**Screenshots**

logs:

```
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=99
PGID=100

2
TZ=Europe/Berlin
----------------------------------------------------------------------

Executing usermod...
usermod: no changes
Applying permissions to /config
Migrating files from "/config/app" to "/config"...
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
File "/app/bazarr/main.py", line 40, in <module>
from server import app, webserver
File "/app/bazarr/server.py", line 16, in <module>
from api import api_bp
File "/app/bazarr/api.py", line 34, in <module>
from scheduler import scheduler
File "/app/bazarr/scheduler.py", line 254, in <module>
scheduler = Scheduler()
File "/app/bazarr/scheduler.py", line 51, in __init__
self.update_configurable_tasks()
File "/app/bazarr/scheduler.py", line 63, in update_configurable_tasks
self.__randomize_interval_task()
File "/app/bazarr/scheduler.py", line 247, in __randomize_interval_task
self.aps_scheduler.modify_job(job.id, next_run_time=datetime.now() + timedelta(seconds=randrange(job.trigger.interval.total_seconds()*0.75, job.trigger.interval.total_seconds())))
File "/app/bazarr/../libs/apscheduler/schedulers/base.py", line 480, in modify_job
job._modify(**changes)
File "/app/bazarr/../libs/apscheduler/job.py", line 221, in _modify
approved['next_run_time'] = convert_to_datetime(value, self._scheduler.timezone,
File "/app/bazarr/../libs/apscheduler/util.py", line 156, in convert_to_datetime
return tz.localize(datetime_, is_dst=None)
File "/app/bazarr/../libs/pytz/tzinfo.py", line 341, in localize
raise NonExistentTimeError(dt)
pytz.exceptions.NonExistentTimeError: 2021-03-28 02:18:33.861391
Bazarr starting...
Bazarr exited.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Software (please complete the following information):**
 - Bazarr: 0.9.3 (Hotio docker)
 - Radarr version
 - Sonarr version
 - OS: Unraid 6.9.0

**Additional context**

**Comment by morpheus65535** [comment]
Should be fixed in 0.9.4-beta.10. Be aware that moving to 0.9.4 will update your config file and it's not backward compatible after that.

**Comment by morpheus65535** [comment]
So, is it fixed?

**Comment by morpheus65535** [comment]
No news, good news!
