### ISSUE TITLE
AttributeError: \'NoneType\' object has no attribute \'check\`

### ISSUE THREAD

**Issue by Panderine** [morpheus65535/bazarr#1400]
**Describe the bug**
Since a month ago I cannot find subtitles for movies

`Traceback (most recent call last):

  File "/app/bin/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "/app/bin/bazarr/../libs/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/app/bin/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper

    resp = resource(*args, **kwargs)

  File "/app/bin/bazarr/../libs/flask/views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "/app/bin/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request

    resp = meth(*args, **kwargs)

  File "/app/bin/bazarr/api.py", line 66, in wrapper

    return actual_method(*args, **kwargs)

  File "/app/bin/bazarr/api.py", line 916, in patch

    result = download_subtitle(moviePath, language, audio_language, hi, forced, providers_list,

  File "/app/bin/bazarr/get_subtitle.py", line 182, in download_subtitle

    downloaded_subtitles = download_best_subtitles({video}, language_set, int(min_score), hi,

  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 820, in download_best_subtitles

    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),

  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 462, in list_subtitles

    for provider, provider_subtitles in executor.map(self.list_subtitles_provider, self.providers,

  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator

    yield fs.pop().result()

  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result

    return self.__get_result()

  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result

    raise self._exception

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 448, in list_subtitles_provider

    provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages)

  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 148, in list_subtitles_provider

    if not provider_registry[provider].check(video):

AttributeError: \'NoneType\' object has no attribute \'check\`

**Software (please complete the following information):**

Bazarr Version
v0.9.5-beta.13
Sonarr Version
3.0.6.1219
Radarr Version
3.2.0.4976
Operating System
Linux-5.12.1-xanmod2-cacule-x86_64-with
Python Version
3.8.8
Bazarr Directory
/app/bin
Bazarr Config Directory
/config

**Additional context**
Docker!

**Comment by Panderine** [comment]
Same error for movies and series. Searching for spanish subs.

**Comment by Panderine** [comment]
I can't seem to. I have removed all providers from settings, but still see "subtitulamostv" on the stats page.
