### ISSUE TITLE
Unable to manually upload

### ISSUE THREAD

**Issue by xloooolx** [morpheus65535/bazarr#1429]
**Describe the bug**

**To Reproduce**
1. Go to series, the series you wan to upload from
2. Click on the season and episode you want to upload
3. push manual upload button and fill out pop up window, hit submit

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.9.6-beta.19]
 - Sonarr version [e.g. v 3.0.6.1262]
 - OS: [e.g. Windows Server 2019]

**Additional context**
```
Exception on /api/episodes/subtitles [POST]

Traceback (most recent call last):

  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 458, in wrapper

    resp = resource(*args, **kwargs)

  File "c:\\bazarr\\bazarr\\../libs\\flask\\views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 573, in dispatch_request

    resp = meth(*args, **kwargs)

  File "c:\\bazarr\\bazarr\\api.py", line 71, in wrapper

    return actual_method(*args, **kwargs)

  File "c:\\bazarr\\bazarr\\api.py", line 821, in post

    result = manual_upload_subtitle(path=episodePath,

  File "c:\\bazarr\\bazarr\\get_subtitle.py", line 648, in manual_upload_subtitle

    custom = Language.from_value(language)

  File "c:\\bazarr\\bazarr\\../libs\\subzero\\language.py", line 76, in inner

    instance = f(cls, base, *args, **kwargs)

  File "c:\\bazarr\\bazarr\\../libs\\subzero\\language.py", line 140, in fromcode

    return Language(*Language_.fromcode(code, converter).__getstate__())

  File "c:\\bazarr\\bazarr\\../libs\\babelfish\\language.py", line 109, in fromcode

    return cls(*language_converters[converter].reverse(code))

  File "c:\\bazarr\\bazarr\\../libs\\babelfish\\converters\\__init__.py", line 253, in __getitem__

    raise KeyError(name)

KeyError: \'_value\
```

**Comment by morpheus65535** [comment]
Shoudl be fixed in upcoming beta.20. Can you test and confirm please?

**Comment by xloooolx** [comment]
yes it's fixed 

thank you
