### ISSUE TITLE
Error trying to extract information from this filename:

### ISSUE THREAD

**Issue by thyeestes** [morpheus65535/bazarr#143]
I have a lot of these messages in my logfile.

This is a more detailed message:
Traceback (most recent call last): File "/volume1/@appstore/bazarr/get_subtitle.py", line 50, in download_subtitle video = Video.fromname(sceneName) File "/usr/local/bazarr/libs/subliminal/video.py", line 107, in fromname return cls.fromguess(name, guessit(name)) File "/volume1/@entware/lib/python2.7/site-packages/guessit/api.py", line 69, in guessit return default_api.guessit(string, options) File "/volume1/@entware/lib/python2.7/site-packages/guessit/api.py", line 182, in guessit raise GuessitException(string, options)GuessitException: An internal error has occured in guessit.

**Comment by leo91000** [comment]
Same issue here ! 

`ERROR:root:Error trying to extract information from this filename: E:\Media\Series\Game of Thrones\Season 3\Game of Thrones - S03E01 - Valar Dohaeris.mkv
Traceback (most recent call last):
  File "E:\Programmes\bazarr\get_subtitle.py", line 50, in download_subtitle
    video = Video.fromname(sceneName)
  File "libs/subliminal\video.py", line 107, in fromname
    return cls.fromguess(name, guessit(name))
  File "E:\Programmes\Python2.7\lib\site-packages\guessit\api.py", line 69, in guessit
    return default_api.guessit(string, options)
  File "E:\Programmes\Python2.7\lib\site-packages\guessit\api.py", line 182, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.0.0
string=None
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Programmes\Python2.7\lib\site-packages\guessit\api.py", line 170, in guessit
    matches = self.rebulk.matches(string, options)
  File "E:\Programmes\Python2.7\lib\site-packages\rebulk\rebulk.py", line 286, in matches
    self._matches_patterns(matches, context)
  File "E:\Programmes\Python2.7\lib\site-packages\rebulk\rebulk.py", line 349, in _matches_patterns
    pattern_matches = pattern.matches(matches.input_string, context)
  File "E:\Programmes\Python2.7\lib\site-packages\rebulk\pattern.py", line 206, in matches
    for match in self._match(pattern, input_string, context):
  File "E:\Programmes\Python2.7\lib\site-packages\rebulk\pattern.py", line 445, in _match
    ret = call(pattern, input_string, context, **self._kwargs)
  File "E:\Programmes\Python2.7\lib\site-packages\rebulk\loose.py", line 50, in call
    return function(*call_args, **call_kwargs)
  File "E:\Programmes\Python2.7\lib\site-packages\guessit\rules\markers\path.py", line 35, in mark_path
    indices = list(find_all(input_string, '/'))
  File "E:\Programmes\Python2.7\lib\site-packages\rebulk\utils.py", line 49, in find_all
    start = string.find(sub, start, end)
AttributeError: 'NoneType' object has no attribute 'find'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.`

**Comment by morpheus65535** [comment]
I think I found the issue. Thanks for reporting. I'm going to merge this to master tonight.

**Comment by morpheus65535** [comment]
Done
