### ISSUE TITLE
Manual search fails for both Radarr and Sonarr.

### ISSUE THREAD

**Issue by biship** [morpheus65535/bazarr#1431]
Providers all report "Good".

```
Health
No issues with your configuration
About
Bazarr Version 0.9.6-beta.20
Sonarr Version 3.0.6.1196
Radarr Version 4.0.0.5079
Operating System Windows-10-10.0.21390-SP0
Python Version 3.9.5

```
Exception on /bazarr/api/providers/movies [GET]
```
Traceback (most recent call last):

  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 458, in wrapper

    resp = resource(*args, **kwargs)

  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 573, in dispatch_request

    resp = meth(*args, **kwargs)

  File "c:\\programdata\\bazarr\\bazarr\\api.py", line 71, in wrapper

    return actual_method(*args, **kwargs)

  File "c:\\programdata\\bazarr\\bazarr\\api.py", line 1155, in get

    data = manual_search(moviePath, profileId, providers_list, providers_auth, sceneName, title,

  File "c:\\programdata\\bazarr\\bazarr\\get_subtitle.py", line 326, in manual_search

    language_items = get_profiles_list(profile_id=int(profileId))[\'items\']

TypeError: \'NoneType\' object is not subscriptable
```

**Comment by morpheus65535** [comment]
Maybe this movie have a deleted languages profile assigned? I would look in that direction.
