### ISSUE TITLE
Not grabbing movies from Radarr

### ISSUE THREAD

**Issue by Reen68** [morpheus65535/bazarr#1432]
**Describe the bug**
Bazarr can't connect to Radarr. Sonarr connection works, API Key is right

**Software (please complete the following information):**
 - Bazarr: 0.9.5
 - Radarr version  4.0.0.5079 
 - OS: Docker on RPI4

**Additional context**

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 2446, in wsgi_app

    response = self.full_dispatch_request()

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/app/bazarr/bin/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router

    return original_handler(e)

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "/app/bazarr/bin/bazarr/../libs/flask/_compat.py", line 39, in reraise

    raise value

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/app/bazarr/bin/bazarr/main.py", line 186, in proxy

    return dict(status=False, error=result.raise_for_status())

  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 940, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.178.50:7878/api/system/status?apikey=0fb40b9b8ca342cda62fa7f43d5852c9

**Comment by morpheus65535** [comment]
Duplicate #1424
