### ISSUE TITLE
Provider zimuku not working due to KeyError

### ISSUE THREAD

**Issue by kkycble** [morpheus65535/bazarr#1459]
I'm running Bazarr 0.9.5 on Windows 10. 

Log: 
```
02/07/2021 11:44:28|INFO    |subliminal_patch.core           |Initializing provider zimuku|
02/07/2021 11:44:28|INFO    |subliminal_patch.providers.zimuku|Downloading subtitle <ZimukuSubtitle 'http://www.zmk.pw/detail/155300.html' [zh-TW:None]>|
02/07/2021 11:44:28|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): www.zmk.pw:80|
02/07/2021 11:44:28|DEBUG   |urllib3.connectionpool          |http://www.zmk.pw:80 "GET /detail/155300.html HTTP/1.1" 301 0|
02/07/2021 11:44:28|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): zimuku.org:80|
02/07/2021 11:44:30|DEBUG   |urllib3.connectionpool          |http://zimuku.org:80 "GET /detail/155300.html HTTP/1.1" 200 None|
02/07/2021 11:44:30|DEBUG   |urllib3.connectionpool          |http://www.zmk.pw:80 "GET /dld/155300.html HTTP/1.1" 301 0|
02/07/2021 11:44:31|DEBUG   |urllib3.connectionpool          |http://zimuku.org:80 "GET /dld/155300.html HTTP/1.1" 200 None|
02/07/2021 11:44:31|DEBUG   |urllib3.connectionpool          |http://www.zmk.pw:80 "GET /download/MTU1MzAwfGVlNGI0YTdmYjViNGQ3YWVlZmY1NGI0MHwxNjI1MTk3NDc1fDgwODdiODc0fHJlbW90ZQ%3D%3D/svr/dx1 HTTP/1.1" 301 0|
02/07/2021 11:44:32|DEBUG   |urllib3.connectionpool          |http://zimuku.org:80 "GET /download/MTU1MzAwfGVlNGI0YTdmYjViNGQ3YWVlZmY1NGI0MHwxNjI1MTk3NDc1fDgwODdiODc0fHJlbW90ZQ%3D%3D/svr/dx1 HTTP/1.1" 302 None|
02/07/2021 11:44:32|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): zmk.pw:80|
02/07/2021 11:44:33|DEBUG   |urllib3.connectionpool          |http://zmk.pw:80 "GET /detail/155300.html HTTP/1.1" 301 0|
02/07/2021 11:44:34|DEBUG   |urllib3.connectionpool          |http://zimuku.org:80 "GET /detail/155300.html HTTP/1.1" 200 None|
02/07/2021 11:44:34|ERROR   |subliminal_patch.core           |Unexpected error in provider 'zimuku', Traceback: Traceback (most recent call last):  File "c:\bazarr\bazarr\../libs\subliminal_patch\core.py", line 266, in download_subtitle    self[subtitle.provider_name].download_subtitle(subtitle)  File "c:\bazarr\bazarr\../libs\subliminal_patch\providers\zimuku.py", line 265, in download_subtitle    filename = r.headers["Content-Disposition"]  File "c:\bazarr\bazarr\../libs\requests\structures.py", line 52, in __getitem__    return self._store[key.lower()][1]KeyError: 'content-disposition'|Traceback (most recent call last):  File "c:\bazarr\bazarr\../libs\subliminal_patch\core.py", line 266, in download_subtitle    self[subtitle.provider_name].download_subtitle(subtitle)  File "c:\bazarr\bazarr\../libs\subliminal_patch\providers\zimuku.py", line 265, in download_subtitle    filename = r.headers["Content-Disposition"]  File "c:\bazarr\bazarr\../libs\requests\structures.py", line 52, in __getitem__    return self._store[key.lower()][1]KeyError: 'content-disposition'|
02/07/2021 11:44:34|INFO    |root                            |Throttling zimuku for 10 minutes, until 21/07/02 11:54, because of: KeyError. Exception info: 'content-disposition'|
02/07/2021 11:44:34|INFO    |socketio.server                 |emitting event "event" to all [/]|
02/07/2021 11:44:34|DEBUG   |subliminal.core                 |Terminating initialized providers|
02/07/2021 11:44:34|INFO    |subliminal_patch.core           |Terminating provider zimuku|
02/07/2021 11:44:34|DEBUG   |root                            |BAZARR Subtitles file downloaded for this file:C:\TV Shows\The Rookie\Season 03\The Rookie - S03E14 - Threshold.mkv|
```

**Comment by kkycble** [comment]
Could it be that the site switched to zimuku.org, making zmk.pw the backup domain that causes this problem?

**Comment by morpheus65535** [comment]
> Could it be that the site switched to [zimuku.org](http://zimuku.org), making [zmk.pw](http://zmk.pw) the backup domain that causes this problem?

From time to time there's a fall back to the old URL but I guess it's only if there's an issue with the site.

I've made some improvements that should help to prevent throttling the provider when the reported exception is raised. I also updated some module to support newer SSA format version.

Can you test the upcoming beta.42 and confirm if it helps? Thanks!

**Comment by kkycble** [comment]
Sure thing :)

**Comment by kkycble** [comment]
I updated to beta.42 and the problem seems fixed. Searching subtitles successfully and download is completed almost instantly.
