### ISSUE TITLE
M1 Mac loops with Python 3.8.2

### ISSUE THREAD

**Issue by dkids** [morpheus65535/bazarr#1461]
I wasn't able to get numpy to compile until recently.   I tried with Homebrew Python, which is 3.9.5.   Somebody reported the looping and it was closed because 3.9 was not supported.

I'm using the system Python, which is version 3.8.2.   

I've installed all requirements in requirements.txt

Requirement already satisfied: gevent>=21 in /Library/Python/3.8/site-packages (from -r ./requirements.txt (line 1)) (21.1.2)
Requirement already satisfied: gevent-websocket>=0.10.1 in /Library/Python/3.8/site-packages (from -r ./requirements.txt (line 2)) (0.10.1)
Requirement already satisfied: lxml>=4.3.0 in /Library/Python/3.8/site-packages (from -r ./requirements.txt (line 3)) (4.6.3)
Requirement already satisfied: numpy>=1.12.0 in /Library/Python/3.8/site-packages (from -r ./requirements.txt (line 4)) (1.21.0)
Requirement already satisfied: webrtcvad-wheels>=2.0.10 in /Library/Python/3.8/site-packages (from -r ./requirements.txt (line 5)) (2.0.10.post2)
Requirement already satisfied: zope.interface in /Library/Python/3.8/site-packages (from gevent>=21->-r ./requirements.txt (line 1)) (5.4.0)
Requirement already satisfied: greenlet<2.0,>=0.4.17 in /Library/Python/3.8/site-packages (from gevent>=21->-r ./requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: zope.event in /Library/Python/3.8/site-packages (from gevent>=21->-r ./requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: setuptools in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from gevent>=21->-r ./requirements.txt (line 1)) (41.2.0)

Bazarr says it's installing requirements and then restarts.   This loops and loops.   

/usr/bin/python3 ./bazarr.py --debug
Bazarr starting...
2021-07-03 11:10:47,426 - root                             (1056ce300) :  DEBUG (logger:101) - Bazarr version: 0.9.6-beta.35
2021-07-03 11:10:47,427 - root                             (1056ce300) :  DEBUG (logger:102) - Bazarr branch: master
2021-07-03 11:10:47,433 - root                             (1056ce300) :  DEBUG (logger:103) - Operating system: macOS-11.4-arm64-arm-64bit
2021-07-03 11:10:47,433 - root                             (1056ce300) :  DEBUG (logger:104) - Python version: 3.8.2
2021-07-03 11:10:47,436 - root                             (1056ce300) :  INFO (init:58) - BAZARR installing requirements...
2021-07-03 11:10:47,722 - root                             (1056ce300) :  INFO (init:68) - BAZARR requirements installed.
2021-07-03 11:10:47,722 - root                             (1056ce300) :  INFO (init:75) - Bazarr is being restarted...
Bazarr is restarting...
2021-07-03 11:10:48,976 - root                             (1033ea300) :  DEBUG (logger:101) - Bazarr version: 0.9.6-beta.35
2021-07-03 11:10:48,976 - root                             (1033ea300) :  DEBUG (logger:102) - Bazarr branch: master
2021-07-03 11:10:48,981 - root                             (1033ea300) :  DEBUG (logger:103) - Operating system: macOS-11.4-arm64-arm-64bit
2021-07-03 11:10:48,982 - root                             (1033ea300) :  DEBUG (logger:104) - Python version: 3.8.2
2021-07-03 11:10:48,983 - root                             (1033ea300) :  INFO (init:58) - BAZARR installing requirements...
2021-07-03 11:10:49,201 - root                             (1033ea300) :  INFO (init:68) - BAZARR requirements installed.
2021-07-03 11:10:49,202 - root                             (1033ea300) :  INFO (init:75) - Bazarr is being restarted...

**Comment by morpheus65535** [comment]
I've already seen that issue on Debian too. Backup your config directory and delete the whole Bazarr directory. Download latest zip, unzip it and restore your config directory. You can now start Bazarr and it shouldn't be in this requirements installation loop. Please confirm if it fixes your issue.

**Comment by dkids** [comment]
Thank you.   Wiped directory, downloaded latest version, put config.ini back in data/config.   Still same issue, unfortunately.

Looks like the issue is how numpy and webcrtcvad-wheels are installed.   That's something that I'll dig into but numpy having the wrong architecture is an ongoing issue with M1.   So this seems like a M1 issue, not a Bazarr issue, and can be closed.

/usr/bin/python3                    
Python 3.8.2 (default, Apr  8 2021, 23:19:18) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
>>> import gevent
>>> import geventwebsocket
>>> import numpy
Traceback (most recent call last):
  File "/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so: mach-o, but wrong architecture
	/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so: mach-o, but wrong architecture

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/Library/Developer/CommandLineTools/usr/bin/python3"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so: mach-o, but wrong architecture
	/Users/kids/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so: mach-o, but wrong architecture


>>> import webrtcvadwheels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'webrtcvadwheels'
>>> import webcrtcvad-wheels
  File "<stdin>", line 1
    import webcrtcvad-wheels
                     ^
SyntaxError: invalid syntax
>>> import webrtcvadwheels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'webrtcvadwheels'

**Comment by morpheus65535** [comment]
It seems that installing Python 3.8 using brew could help: https://github.com/apple/tensorflow_macos/issues/146#issuecomment-787429443

**Comment by dkids** [comment]
Installed Python3.8 via HomeBrew but I'm getting errors compiling anything because of architecture issues.

I tried installing MiniConda because it was referenced as being compatible with the M1 Macs but I'm hung up on getting webrtcvad installed with conda.   The other modules install fine.    If I install webrtcvad-wheels via conda's pip, I get the install/restart loop.

I don't have the Python knowledge to go further right now.   Thank you for your suggestion.  I'm marking this as closed.

**Comment by morpheus65535** [comment]
Sorry to ear that. You make me feel happy to have bought the last generation of Intel Macbook! ;-)
