### ISSUE TITLE
Anti-captcha.com seems not solving captchas with subs4series provider

### ISSUE THREAD

**Issue by intersector** [morpheus65535/bazarr#1470]
**Describe the bug**
Hello,
I have recently acquired anti-captcha account and topped up 10$.  I have entered my key from anti-capatcha.com and selected the right provider.
However I try to download a subtitle, this error arises:

```
Throttling subs4series for 10 minutes, until 21/07/15 20:01, because of: Exception. Exception info: 'Subs4series: captcha expired waiting to be solved.'

Unexpected error in provider 'subs4series', Traceback: Traceback (most recent call last): File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 266, in download_subtitle self[subtitle.provider_name].download_subtitle(subtitle) File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/subs4series.py", line 265, in download_subtitle raise Exception("Subs4series: captcha expired waiting to be solved.")Exception: Subs4series: captcha expired waiting to be solved.
```

 
 
thanks

**Software (please complete the following information):**
 - Bazarr: 0.9.6-beta.42 (docker)

 - Sonarr version v 3.0.6.1265
 - OS: Windows 10

**Comment by morpheus65535** [comment]
You should see on anti-captcha website the status of this specific captcha solving. They should inform you why it didn't work.

AFAIK, it's unrelated to Bazarr but to the availability of solver on AC side.

**Comment by intersector** [comment]
As i see in my AC dashboard , there is no activity... Like never sent request.. It's very odd

**Comment by morpheus65535** [comment]
Ok I'll look into it.

**Comment by intersector** [comment]
Hello,
After I opened ticket to the AC support they told it that everything is fine with my account and from their end... They are willing to give me even a refund and they told me that something is wrong with my software provider. 
I am just updating with my latest info.

Thanks again

**Comment by morpheus65535** [comment]
I can reproduce the issue. They're trying to block us an adapt frequently. I'll try to fix it later.

**Comment by morpheus65535** [comment]
Ok after trying to fix it for a couple of hours, I drop the towel. I've put a couple of days to fix the new requirement for captcha before downloading 3 weeks ago and they have change it again.

If someone is willing to put some time into this, it's fine but for me, it's enough. They just don't want us and I won't fight it.

**Comment by littlerooster** [comment]
it's a lost cause. Opensubtitles and Greeksubs are great alternatives, they fill almost everything. Make sure to use those @intersector . Subs4series/free, deliberaterly has made the website inaccessible so they can have the ad revenue.

**Comment by intersector** [comment]
> 
> 
> Ok after trying to fix it for a couple of hours, I drop the towel. I've put a couple of days to fix the new requirement for captcha before downloading 3 weeks ago and they have change it again.
> 
> If someone is willing to put some time into this, it's fine but for me, it's enough. They just don't want us and I won't fight it.

Thanks for the effort and I really appreciate it. @littlerooster  yes i am using them , thanks though!

**Comment by greatvc** [comment]
> it's a lost cause. Opensubtitles and Greeksubs are great alternatives, they fill almost everything. Make sure to use those @intersector . Subs4series/free, deliberaterly has made the website inaccessible so they can have the ad revenue.

for me Greeksubs is awful, it is full of google translated subtitles. Subs4series is WAY better but yes the methods that and the subs4movies are using for downlod and anticaptcha is totally terrible. I cannot even do it manually many times.
