### ISSUE TITLE
Throws jinja2.exceptions.TemplateNotFound: index.html

### ISSUE THREAD

**Issue by she11sh0cked** [morpheus65535/bazarr#1473]
**Describe the bug**
The application throws the following exception when accessing `/bazarr`:

```py
Exception on /bazarr/ [GET]|'Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/bazarr/bazarr/main.py", line 119, in catch_all
    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/bazarr/bazarr/../libs/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
```

**To Reproduce**
1. Go to `/bazarr`
2. See error

**Expected behavior**
Should render the index page.

**Software (please complete the following information):**
 - Bazarr: 80ffdc91b7221c75b73efb49dd5ec33a0587bcff
 - Radarr: v3.2.2.5080
 - Sonarr: v3.0.6.1196
 - OS: Ubuntu 20.04

**Additional context**
<details>
  <summary>config.ini</summary>
  
  ```ini
[general]
ip = 127.0.0.1
port = 6767
base_url = /bazarr
path_mappings = []
debug = False
branch = master
auto_update = True
single_language = False
minimum_score = 90
use_scenename = True
use_postprocessing = False
postprocessing_cmd =
postprocessing_threshold = 90
use_postprocessing_threshold = False
postprocessing_threshold_movie = 70
use_postprocessing_threshold_movie = False
use_sonarr = True
use_radarr = True
path_mappings_movie = []
serie_default_enabled = False
serie_default_profile =
movie_default_enabled = False
movie_default_profile =
page_size = 25
page_size_manual_search = 10
minimum_score_movie = 70
use_embedded_subs = True
embedded_subs_show_desired = True
utf8_encode = True
ignore_pgs_subs = False
ignore_vobsub_subs = False
ignore_ass_subs = False
adaptive_searching = False
enabled_providers = []
multithreading = True
chmod_enabled = False
chmod = 0640
subfolder = current
subfolder_custom =
upgrade_subs = True
upgrade_frequency = 12
days_to_upgrade_subs = 7
upgrade_manual = True
anti_captcha_provider = None
wanted_search_frequency = 3
wanted_search_frequency_movie = 3
subzero_mods = []
dont_notify_manual_actions = False
flask_secret_key = !!!SECRET!!!

[auth]
type = None
username =
password =
apikey = !!!SECRET!!!

[sonarr]
ip = 127.0.0.1
port = 8989
base_url = /sonarr
ssl = False
apikey = !!!SECRET!!!
full_update = Daily
full_update_day = 6
full_update_hour = 4
only_monitored = False
series_sync = 60
episodes_sync = 60
excluded_tags = []
excluded_series_types = []

[radarr]
ip = 127.0.0.1
port = 7878
base_url = /radarr
ssl = False
apikey = !!!SECRET!!!
full_update = Daily
full_update_day = 6
full_update_hour = 5
only_monitored = False
movies_sync = 60
excluded_tags = []

[proxy]
type = None
url =
port =
username =
password =
exclude = ["localhost","127.0.0.1"]

[opensubtitles]
username =
password =
use_tag_search = False
vip = False
ssl = False
timeout = 15
skip_wrong_fps = False

[opensubtitlescom]
username =
password =
use_hash = True

[addic7ed]
username =
password =

[legendasdivx]
username =
password =
skip_wrong_fps = False

[legendastv]
username =
password =

[xsubs]
username =
password =

[assrt]
token =

[anticaptcha]
anti_captcha_key =

[deathbycaptcha]
username =
password =

[napisy24]
username =
password =

[subscene]
username =
password =

[betaseries]
token =

[analytics]
enabled = True

[titlovi]
username =
password =

[subsync]
use_subsync = False
use_subsync_threshold = False
subsync_threshold = 90
use_subsync_movie_threshold = False
subsync_movie_threshold = 70
debug = False

[series_scores]
hash = 359
series = 180
year = 90
season = 30
episode = 30
release_group = 15
source = 7
audio_codec = 3
resolution = 2
video_codec = 2
hearing_impaired = 1
streaming_service = 0
edition = 0

[movie_scores]
hash = 119
title = 60
year = 30
release_group = 15
source = 7
audio_codec = 3
resolution = 2
video_codec = 2
hearing_impaired = 1
streaming_service = 0
edition = 0
  ```
</details>

**Comment by morpheus65535** [comment]
My guess is that you updated using git. This isn't supported anymore as the templates are included in an asset and not committed to repo. You can see the updated instructions there: https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/

**Comment by she11sh0cked** [comment]
Ah! Then that's probably more a problem with Swizzin. I'll cross-reference this issue on their repository then!
