### ISSUE TITLE
Exception while configuring Sonarr connection

### ISSUE THREAD

**Issue by DevMan01** [morpheus65535/bazarr#1474]
_Fresh install of Bazarr on MacOS, 10.15.7. Using Python 3.8.2. Using Brave 1.26.77 / Chromium 91.0.4472.164:_

**Observing a failure to complete the connection / configuration to the Sonarr server. Note, Sonarr is running on the same host.**

Debug logs:
`2021-07-19 11:33:19,620 - urllib3.connectionpool           (1170edbf0) :  DEBUG (connectionpool:394) - http://192.168.1.108:8989 "GET /signalr/negotiate?connectionData=%5B%7B%22name%22%3A+%22%22%7D%5D&apikey=<API KEY REDACTED>&clientProtocol=1.5 HTTP/1.1" 200 None
2021-07-19 11:33:19,643 - app                              (1170edbf0) :  ERROR (app:1890) - Exception on /api/system/settings [POST]
Traceback (most recent call last):
  File "/Applications/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/Applications/bazarr/bazarr/../libs/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Applications/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Applications/bazarr/bazarr/api.py", line 73, in wrapper
    return actual_method(*args, **kwargs)
  File "/Applications/bazarr/bazarr/api.py", line 535, in post
    save_settings(zip(request.form.keys(), request.form.listvalues()))
  File "/Applications/bazarr/bazarr/config.py", line 445, in save_settings
    sonarr_signalr_client.restart()
  File "/Applications/bazarr/bazarr/signalr_client.py", line 73, in restart
    self.start()
  File "/Applications/bazarr/bazarr/signalr_client.py", line 45, in start
    self.connection.start()
  File "/Applications/bazarr/bazarr/../libs/signalr/_connection.py", line 52, in start
    listener = self.__transport.start()
  File "/Applications/bazarr/bazarr/../libs/signalr/transports/_auto_transport.py", line 28, in start
    return self.__transport.start()
  File "/Applications/bazarr/bazarr/../libs/signalr/transports/_ws_transport.py", line 35, in start
    self.ws = create_connection(ws_url,
  File "/Applications/bazarr/bazarr/../libs/websocket/_core.py", line 599, in create_connection
    websock.connect(url, **options)
  File "/Applications/bazarr/bazarr/../libs/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/Applications/bazarr/bazarr/../libs/websocket/_handshake.py", line 59, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Applications/bazarr/bazarr/../libs/websocket/_handshake.py", line 145, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request`

**User experience screenshot below:**
<img width="1656" alt="Screen Shot 2021-07-19 at 11 36 38 AM" src="https://user-images.githubusercontent.com/24305516/126203178-98106931-457c-4e93-ac17-ef5940f309e9.png">

**Comment by morpheus65535** [comment]
Do not use Brave, it's messing with legit Javascript. Use Chrome or Firefox. They've been tested.

**Comment by DevMan01** [comment]
Good call. I attempted again using out of the box Chrome, in incognito mode, Version 91.0.4472.164 (Official Build) (x86_64) and I experienced the same results:

`2021-07-19 13:29:44,512 - urllib3.connectionpool           (1172c6260) :  DEBUG (connectionpool:394) - http://192.168.1.108:8989 "GET /signalr/negotiate?connectionData=%5B%7B%22name%22%3A+%22%22%7D%5D&apikey=<API Key Redacted>&clientProtocol=1.5 HTTP/1.1" 200 None
2021-07-19 13:29:44,534 - app                              (1172c6260) :  ERROR (app:1890) - Exception on /api/system/settings [POST]
Traceback (most recent call last):
  File "/Applications/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/Applications/bazarr/bazarr/../libs/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Applications/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Applications/bazarr/bazarr/api.py", line 73, in wrapper
    return actual_method(*args, **kwargs)
  File "/Applications/bazarr/bazarr/api.py", line 535, in post
    save_settings(zip(request.form.keys(), request.form.listvalues()))
  File "/Applications/bazarr/bazarr/config.py", line 445, in save_settings
    sonarr_signalr_client.restart()
  File "/Applications/bazarr/bazarr/signalr_client.py", line 73, in restart
    self.start()
  File "/Applications/bazarr/bazarr/signalr_client.py", line 45, in start
    self.connection.start()
  File "/Applications/bazarr/bazarr/../libs/signalr/_connection.py", line 52, in start
    listener = self.__transport.start()
  File "/Applications/bazarr/bazarr/../libs/signalr/transports/_auto_transport.py", line 28, in start
    return self.__transport.start()
  File "/Applications/bazarr/bazarr/../libs/signalr/transports/_ws_transport.py", line 35, in start
    self.ws = create_connection(ws_url,
  File "/Applications/bazarr/bazarr/../libs/websocket/_core.py", line 599, in create_connection
    websock.connect(url, **options)
  File "/Applications/bazarr/bazarr/../libs/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/Applications/bazarr/bazarr/../libs/websocket/_handshake.py", line 59, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Applications/bazarr/bazarr/../libs/websocket/_handshake.py", line 145, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request`

**Comment by DevMan01** [comment]
What is interesting, however, is that somehow series have been snagged into Bazaar. Even though this page freezes, and the settings don't seem to take. Which makes me wonder that maybe one of the background jobs / CRON'd jobs are picking it up and processing the Sonarr series.

**Comment by morpheus65535** [comment]
What version of Sonarr are you using?

**Comment by DevMan01** [comment]
Version: 3.0.6.1265
Mono Version: 6.12.0.122

**Comment by morpheus65535** [comment]
I would look at Sonarr logs as it is the one who return an http 400 error...

**Comment by morpheus65535** [comment]
Or maybe just try to restart Sonarr first to see if it clear the issue.

**Comment by RemiG26** [comment]
I have the exact same issue, I tried to reinstall bazarr (by using the release zip) but same problem again.
Maybe the issue comes from sonarr cause radarr works fine (i also tried to update sonarr in last version without any changes). My sonarr uses the mono version 5.10.1.57 which is deprecated but Radarr uses the same version and works.

**Comment by morpheus65535** [comment]
@RemiG26 I haven't test with this deprecated version of mono. BTW, even if Radarr run under mono, it's using the same version of SignalR protocol so there's no conclusion that can be drawn from that.

**Comment by morpheus65535** [comment]
@DevMan01 did restarting Sonarr made the trick? If not, can you test latest 0.9.7-beta where I've made some changes to Sonarr SignalR feed exception handling?

**Comment by morpheus65535** [comment]
It looks like an issue with Sonarr running on Mono. The SignalR feed isn't properly working and you can confirm it in your browser dev console while browsing Sonarr UI.

I'll add a `try` to the next beta to prevent settings saving from completing properly.

**Comment by mvanbaak** [comment]
beta-6 now completes saving the sonarr settings and shows the inactive save icon after saving the page.

Since this is a bug in sonarr and will be fixed as soon as the platforms migrate from mono to dotnet, I think this ticket can now be closed.

Thanks for the 'fix'
