### ISSUE TITLE
Bazarr returns 500s and can't connect to Sonarr websocket service

### ISSUE THREAD

**Issue by Kreeblah** [morpheus65535/bazarr#1476]
**Describe the bug**
Bazarr is unable to connect to Sonarr's web service, and returns 500s for page views in 0.9.6.  0.9.5, however, works just fine.

Note that this is not going through a reverse proxy, and that these services are all running on the same host.
```
Bazarr starting...
2021-07-19 13:23:14,908 - root                             (80173c930) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:7700
2021-07-19 13:23:14,911 - root                             (84b0f8ae0) :  INFO (signalr_client:100) - BAZARR trying to connect to Radarr SignalR feed...
2021-07-19 13:23:14,918 - root                             (84b0f89d0) :  INFO (signalr_client:124) - BAZARR SignalR client for Radarr is connected and waiting for events.
2021-07-19 13:23:14,955 - root                             (84b0f88c0) :  INFO (signalr_client:41) - BAZARR trying to connect to Sonarr SignalR feed...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/share/bazarr/bazarr/signalr_client.py", line 45, in start
    self.connection.start()
  File "/usr/local/share/bazarr/bazarr/../libs/signalr/_connection.py", line 52, in start
    listener = self.__transport.start()
  File "/usr/local/share/bazarr/bazarr/../libs/signalr/transports/_auto_transport.py", line 28, in start
    return self.__transport.start()
  File "/usr/local/share/bazarr/bazarr/../libs/signalr/transports/_ws_transport.py", line 35, in start
    self.ws = create_connection(ws_url,
  File "/usr/local/share/bazarr/bazarr/../libs/websocket/_core.py", line 599, in create_connection
    websock.connect(url, **options)
  File "/usr/local/share/bazarr/bazarr/../libs/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/share/bazarr/bazarr/../libs/websocket/_handshake.py", line 59, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/share/bazarr/bazarr/../libs/websocket/_handshake.py", line 145, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request
2021-07-19T20:23:15Z <Greenlet at 0x84b0f88c0: <bound method SonarrSignalrClient.start of <signalr_client.SonarrSignalrClient object at 0x84b08f850>>> failed with WebSocketBadStatusException
```
In the log, I see this, which look like they relate to the 500s:
```
19/07/2021 13:13:45|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:7700|
19/07/2021 13:13:45|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
19/07/2021 13:13:45|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
19/07/2021 13:13:45|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
19/07/2021 13:14:31|ERROR   |app                             |Exception on /system/status [GET]|'Traceback (most recent call last):\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise\n    raise value\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/share/bazarr/bazarr/main.py", line 119, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 138, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 869, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 830, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 804, in _load_template\n    template = self.loader.load(self, name, globals)\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/loaders.py", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 60, in get_source\n    return self._get_source_fast(environment, template)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 89, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
19/07/2021 13:14:31|ERROR   |app                             |Exception on /favicon.ico [GET]|'Traceback (most recent call last):\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise\n    raise value\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/share/bazarr/bazarr/main.py", line 119, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 138, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 869, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 830, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 804, in _load_template\n    template = self.loader.load(self, name, globals)\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/loaders.py", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 60, in get_source\n    return self._get_source_fast(environment, template)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 89, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
19/07/2021 13:14:37|ERROR   |app                             |Exception on / [GET]|'Traceback (most recent call last):\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise\n    raise value\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/share/bazarr/bazarr/main.py", line 119, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 138, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 869, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 830, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 804, in _load_template\n    template = self.loader.load(self, name, globals)\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/loaders.py", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 60, in get_source\n    return self._get_source_fast(environment, template)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 89, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
19/07/2021 13:14:38|ERROR   |app                             |Exception on /favicon.ico [GET]|'Traceback (most recent call last):\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise\n    raise value\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/share/bazarr/bazarr/main.py", line 119, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 138, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 869, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 830, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/environment.py", line 804, in _load_template\n    template = self.loader.load(self, name, globals)\n  File "/usr/local/share/bazarr/bazarr/../libs/jinja2/loaders.py", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 60, in get_source\n    return self._get_source_fast(environment, template)\n  File "/usr/local/share/bazarr/bazarr/../libs/flask/templating.py", line 89, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
19/07/2021 13:18:13|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:7700|
19/07/2021 13:18:13|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
19/07/2021 13:18:13|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
19/07/2021 13:18:13|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
19/07/2021 13:20:48|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:7700|
19/07/2021 13:20:48|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
19/07/2021 13:20:48|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
19/07/2021 13:20:48|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
19/07/2021 13:23:14|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:7700|
19/07/2021 13:23:14|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
19/07/2021 13:23:14|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
19/07/2021 13:23:14|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
```
**To Reproduce**
1. Install Sonarr and Radarr from the quarterly packages
2. Install the python dependencies from the quarterly packages
3. Clone Bazarr from GitHub into /usr/local/share/bazarr and check out tags/v0.9.6
4. Put together a config pointing at the local Sonarr and Radarr instance and put it in /usr/local/bazarr
5. Create a bazarr user and a bazarr group, and recursively change ownership of the /usr/local/bazarr and /usr/local/share/bazarr directories to them
6. Run Bazarr: `sudo -u bazarr /usr/local/bin/python3 /usr/local/share/bazarr/bazarr.py --no-update -c /usr/local/bazarr`

At this point, the errors in the Python output should show up, and attempting to connect to Bazarr on the port it's configured to run on should return 500s.

**Expected behavior**
I would expect Bazarr to start and be ready for use.

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 0.9.6
 - Radarr version 3.0.2.4552
 - Sonarr version 3.0.6.1196
 - OS: FreeBSD 13.0-RELEASE-p3
 - Python: 3.8.10

**Additional context**
Switching back to tags/v0.9.5 works just fine.

**Comment by morpheus65535** [comment]
You can't install Bazarr using GIT anymore as the template are included in bazarr.zip asset for each releases. Please follow the instructions on the wiki: https://wiki.bazarr.media/Getting-Started/Installation/FreeBSD/freebsd/

Alternatively, you should be able to use the native FreeBSD packages: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243967#c19

**Comment by morpheus65535** [comment]
I'll close this one. Re-open it if required.
