### ISSUE TITLE
<Model: TableShows> instance matching query does not exist

### ISSUE THREAD

**Issue by dtcabrerizo** [morpheus65535/bazarr#1479]
I installed Bazarr and connected to Sonarr, it imported all episodes the first time. Sometime later I found out that the episodes were not being updated, checking the logs I found the error below:

Job "Sync episodes with Sonarr (trigger: interval[1:00:00], next run at: 2021-07-22 00:44:46 -03)" raised an exception

Those were the details on the error:
```
Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/peewee.py", line 6884, in get    return clone.execute(database)[0]  File "/opt/bazarr/bazarr/../libs/peewee.py", line 4275, in __getitem__    return self.row_cache[item]IndexError: list index out of rangeDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/opt/bazarr/bazarr/get_episodes.py", line 91, in sync_episodes    episodes_to_update.append(episodeParser(episode))  File "/opt/bazarr/bazarr/get_episodes.py", line 301, in episodeParser    audio_language = TableShows.get(TableShows == episode['seriesId']).audio_language  File "/opt/bazarr/bazarr/../libs/peewee.py", line 6438, in get    return sq.get()  File "/opt/bazarr/bazarr/../libs/peewee.py", line 6889, in get    (clone.model, sql, params))database.TableShowsDoesNotExist: <Model: TableShows> instance matching query does not exist:SQL: SELECT "t1"."tvdbId", "t1"."alternateTitles", "t1"."audio_language", "t1"."fanart", "t1"."imdbId", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."seriesType", "t1"."sonarrSeriesId", "t1"."sortTitle", "t1"."tags", "t1"."title", "t1"."year" FROM "table_shows" AS "t1" WHERE ("t1"."tvdbId" = ?) LIMIT ? OFFSET ?Params: [0, 1, 0]
```

What I found odd was the last part of the error on the query, using the key tvdbid = 0, I located the error on the code and this line was causing the problem:

```python
295                        audio_language = TableShows.get(TableShows == episode['seriesId']).audio_language
```

When adding a Try Except clause around this line with a default fallback value for audio_language the episodes were updated. What I think is wrong here is the key being used to query the table table_shows, episode['seriesId'] is the ID of the show on Sonarr, which is an internal sequential ID, and the query displayed on the log is using this value on the field 'tvdbId' which is the ID on tvdb, I don't think this is the key it should be using to match the show on the table_show table.

I'm sorry I didn't have the time to fork and look for a solution, I hope this information helps to fix this issue.

Bazarr Version 0.9.6
Sonarr Version 2.0.0.5344
Operating System Linux-5.10.17-v7l+-armv7l-with-debian-10.10
Python Version 3.7.3

Thanks for the amazing work

**Comment by morpheus65535** [comment]
Thanks for reporting! I fixed this query an another one I found. You'll be able to test the result in the upcoming 0.9.7-beta.1 and report back. Thanks again!

**Comment by morpheus65535** [comment]
No news good news!

**Comment by TRaSH-** [comment]
He should upgrade his outdated Sonarr,
V2 is EOL
