### ISSUE TITLE
Bazarr can't sync with Sonarr

### ISSUE THREAD

**Issue by knocc** [morpheus65535/bazarr#1486]
Bazarr can't find any series in sonarr and every time I try to sync it raises an exception, as you can you see in the image below.

![image](https://user-images.githubusercontent.com/9316873/127167620-e20b5d6d-517f-45a3-855c-1b30268d16a4.png)

I managed to sync bazarr with radarr without any problems.
To help you, the stack traceback is:
```
Traceback (most recent call last):

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 6884, in get

    return clone.execute(database)[0]

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 4275, in __getitem__

    return self.row_cache[item]

IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "c:\\bazarr\\bazarr\\get_episodes.py", line 88, in sync_episodes

    episodes_to_add.append(episodeParser(episode))

  File "c:\\bazarr\\bazarr\\get_episodes.py", line 295, in episodeParser

    audio_language = TableShows.get(TableShows == episode[\'seriesId\']).audio_language

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 6438, in get

    return sq.get()

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 6887, in get

    raise self.model.DoesNotExist(\'%s instance matching query does \'

database.TableShowsDoesNotExist: <Model: TableShows> instance matching query does not exist:

SQL: SELECT "t1"."tvdbId", "t1"."alternateTitles", "t1"."audio_language", "t1"."fanart", "t1"."imdbId", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."seriesType", "t1"."sonarrSeriesId", "t1"."sortTitle", "t1"."tags", "t1"."title", "t1"."year" FROM "table_shows" AS "t1" WHERE ("t1"."tvdbId" = ?) LIMIT ? OFFSET ?

Params: [0, 1, 0]
```

 - Bazarr version: v0.9.6
 - Sonarr version: 2.0.0.5344
 - OS: Windows 10

**Comment by morpheus65535** [comment]
Already fixed in 0.9.7-beta: https://github.com/morpheus65535/bazarr/commit/d5b898064d7188d5bc47bcb3a73405a38133d5d6
