### ISSUE TITLE
Cannot Search for Subtitles on Fresh Install and Restored Config

### ISSUE THREAD

**Issue by cannedpeanut** [morpheus65535/bazarr#1489]
Description:
The most recent update to Bazaar broke my installation. I needed to do a fresh install. I cleared my install directory and the only thing I saved was my config folder from my last install.  I was able to get it running again by following the steps in the wiki, but when I go to search for subs, nothing happens. When investigating the logs, I get this traceback:

```
Traceback (most recent call last):

  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper

    resp = resource(*args, **kwargs)

  File "/opt/bazarr/bazarr/../libs/flask/views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request

    resp = meth(*args, **kwargs)

  File "/opt/bazarr/bazarr/api.py", line 73, in wrapper

    return actual_method(*args, **kwargs)

  File "/opt/bazarr/bazarr/api.py", line 1208, in get

    \'movie\')

  File "/opt/bazarr/bazarr/get_subtitle.py", line 304, in manual_search

    language_items = get_profiles_list(profile_id=int(profileId))[\'items\']

TypeError: \'NoneType\' object is not subscriptable
```

Looking at past issues, the closest I could find is that this issue occurred when people were incorrectly mapping directories. I did have a mapped directory, but removed it and am still getting this error. 

**Software (please complete the following information):**
 - Bazarr: 0.9.6
 - Radarr version 3.0.6.1265
 - Sonarr version 3.2.2.5080
 - OS: Linux-5.4.114-1-pve-x86_64-with-Ubuntu-18.04-bionic
 - Python: 3.7.5

**Comment by halali** [comment]
Duplicate #1437
