### ISSUE TITLE
Job "Update Movie list from Radarr" raised an exception

### ISSUE THREAD

**Issue by eni9889** [morpheus65535/bazarr#1497]
**Describe the bug**

My movies stopped syncing and I noticed an error in the logs. I have not changed anything on either radarr or bazarr. Not sure how to reproduce.

```
Traceback (most recent call last):

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 3144, in execute_sql

    cursor.execute(sql, params or ())

sqlite3.IntegrityError: UNIQUE constraint failed: table_movies.path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "c:\\bazarr\\bazarr\\get_movies.py", line 143, in update_movies

    TableMovies.update(updated_movie).where(TableMovies.tmdbId == updated_movie[\'tmdbId\']).execute()

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 1907, in inner

    return method(self, database, *args, **kwargs)

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 1978, in execute

    return self._execute(database)

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 2475, in _execute

    return self.handle_result(database, cursor)

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 2486, in handle_result

    return database.rows_affected(cursor)

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 3236, in rows_affected

    return cursor.rowcount

  File "c:\\bazarr\\bazarr\\../libs\\playhouse\\sqliteq.py", line 94, in rowcount

    self._wait()

  File "c:\\bazarr\\bazarr\\../libs\\playhouse\\sqliteq.py", line 63, in _wait

    raise self._exc

  File "c:\\bazarr\\bazarr\\../libs\\playhouse\\sqliteq.py", line 178, in execute

    cursor = self.database._execute(obj.sql, obj.params, obj.commit)

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 3151, in execute_sql

    self.commit()

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 2917, in __exit__

    reraise(new_type, new_type(exc_value, *exc_args), traceback)

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 190, in reraise

    raise value.with_traceback(tb)

  File "c:\\bazarr\\bazarr\\../libs\\peewee.py", line 3144, in execute_sql

    cursor.execute(sql, params or ())

peewee.IntegrityError: UNIQUE constraint failed: table_movies.path
```

**Software (please complete the following information):**
 - Bazarr: v0.9.6
 - Radarr version 3.2.2.5080
 - OS:  Windows 10

**Comment by morpheus65535** [comment]
Did you reinstall Radarr? Because having to movies with the exact same file path is highly improbable. If you can provide a debug log while running Sync with Radarr task, I could see which movie is problematic.
