### ISSUE TITLE
If log is empty, we get an exception

### ISSUE THREAD

**Issue by morpheus65535** [morpheus65535/bazarr#15]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "Y:\morpheus\Programmation\bazarr\bazarr.py", line 387, in system
    row_count = i
UnboundLocalError: local variable 'i' referenced before assignment

**Comment by morpheus65535** [comment]
Fixed in ba733b791cc084b1da3fb26fbdb55076012e0752.
