### ISSUE TITLE
Cannot search for missing subtitles

### ISSUE THREAD

**Issue by matjaz321** [morpheus65535/bazarr#1507]
**Describe the bug**
Search for missing subtitles does not work correctly. I checked the logs and there is some python exception being thrown.
``` bash
bazarr    | 2021-08-14 19:26:45,104 - peewee                           (7f7b66f0ebf0) :  DEBUG (peewee:3132) - ('SELECT "t1"."path", "t1"."missing_subtitles", "t1"."monitored", "t1"."sonarrEpisodeId", "t1"."scene_name", "t2"."tags", "t2"."seriesType", "t1"."audio_language", "t2"."title", "t1"."season", "t1"."episode", "t1"."title" AS "episodeTitle" FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE ((("t1"."sonarrSeriesId" = ?) AND ("t1"."missing_subtitles" != ?)) AND ("t1"."monitored" = ?))', [5, '[]', 'True'])
bazarr    | --- Logging error ---
bazarr    | Traceback (most recent call last):
bazarr    |   File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
bazarr    |     msg = self.format(record)
bazarr    |   File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
bazarr    |     return fmt.format(record)
bazarr    |   File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
bazarr    |     record.message = record.getMessage()
bazarr    |   File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
bazarr    |     msg = msg % self.args
bazarr    | TypeError: not all arguments converted during string formatting
bazarr    | Call stack:
bazarr    |   File "/usr/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
bazarr    |     return handle(*args_tuple)
bazarr    |   File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 1577, in handle
bazarr    |     handler.handle()
bazarr    |   File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 464, in handle
bazarr    |     result = self.handle_one_request()
bazarr    |   File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 694, in handle_one_request
bazarr    |     self.handle_one_response()
bazarr    |   File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
bazarr    |     self.run_application()
bazarr    |   File "/usr/lib/python3.8/site-packages/geventwebsocket/handler.py", line 87, in run_application
bazarr    |     return super(WebSocketHandler, self).run_application()
bazarr    |   File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 945, in run_application
bazarr    |     self.result = self.application(self.environ, self.start_response)
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 2463, in __call__
bazarr    |     return self.wsgi_app(environ, start_response)
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/flask_socketio/__init__.py", line 45, in __call__
bazarr    |     return super(_SocketIOMiddleware, self).__call__(environ,
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/engineio/middleware.py", line 74, in __call__
bazarr    |     return self.wsgi_app(environ, start_response)
bazarr    |   File "/app/bazarr/bin/bazarr/app.py", line 53, in __call__
bazarr    |     return self.app(environ, start_response)
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 2446, in wsgi_app
bazarr    |     response = self.full_dispatch_request()
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
bazarr    |     rv = self.dispatch_request()
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
bazarr    |     return self.view_functions[rule.endpoint](**req.view_args)
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
bazarr    |     resp = resource(*args, **kwargs)
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 89, in view
bazarr    |     return self.dispatch_request(*args, **kwargs)
bazarr    |   File "/app/bazarr/bin/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
bazarr    |     resp = meth(*args, **kwargs)
bazarr    |   File "/app/bazarr/bin/bazarr/api.py", line 77, in wrapper
bazarr    |     return actual_method(*args, **kwargs)
bazarr    |   File "/app/bazarr/bin/bazarr/api.py", line 744, in patch
bazarr    |     series_download_subtitles(seriesid)
bazarr    |   File "/app/bazarr/bin/bazarr/get_subtitle.py", line 732, in series_download_subtitles
bazarr    |     logging.debug("BAZARR no episode for that sonarrSeriesId can be found in database:", str(no))
bazarr    | Message: 'BAZARR no episode for that sonarrSeriesId can be found in database:'
bazarr    | Arguments: ('5',)
```
**To Reproduce**
1. Use docker https://hub.docker.com/r/linuxserver/bazarr
2. Go to the Series page
3. Click on search icon of missing subtitles on series page

**Expected behavior**
It should search for missing subtitles

**Software (please complete the following information):**
 - Bazarr: 0.9.7
 - Radarr version 3.0.6.1265
 - Sonarr version 3.2.2.5080
 - OS: Linux-5.4.0-81-generic-x86_64-with

**Comment by morpheus65535** [comment]
Thanks for reporting this. I've made a mistake in the debug message.

Your issue is probably that all the episode of this series are ignored because of monitored status/series type/tags. Check your settings.

**Comment by morpheus65535** [comment]
Anything else to fix here?

**Comment by morpheus65535** [comment]
No news, good news.
