### ISSUE TITLE
Bazarr fails to get video information, database query does not exist

### ISSUE THREAD

**Issue by laurensmiers** [morpheus65535/bazarr#1517]
**Describe the bug**
When searching for subtitles (movies, series), bazarr fails to get them due to an error stating that it is unable to get video information for the file.

**To Reproduce**
1. Go to a movie
2. Click on 'Manual' to do a manual search
3. Click on 'Start search'
4. See error in logs

**Expected behavior**
A list of subs it retrieved from the providers.

**Screenshots**
Example debug logs:
```
2021-08-28 10:10:55,793 - root                             (ffffad39a590) :  DEBUG (get_subtitle:297) - BAZARR Manually searching subtitles for this file: /movies/The Unholy (2021)/The.Unholy.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx].mkv
2021-08-28 10:10:55,796 - subzero.video                    (ffffad39a590) :  DEBUG (video:60) - Parsing video: The.Unholy.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx].mkv, hints: {'title': 'The Unholy', 'type': 'movie'}
2021-08-28 10:10:55,797 - subliminal_patch.core            (ffffad39a590) :  INFO (core:508) - Determining basic video properties for 'The.Unholy.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx].mkv' in '/movies/The Unholy (2021)'
2021-08-28 10:10:55,977 - subliminal_patch.core            (ffffad39a590) :  DEBUG (core:534) - GuessIt found: {
    "title": "The Unholy",
    "year": 2021,
    "screen_size": "720p",
    "source": "Web",
    "other": "Rip",
    "size": "800MB",
    "video_codec": "H.264",
    "release_group": "GalaxyRG",
    "container": "mkv",
    "type": "movie"
}
2021-08-28 10:10:56,139 - subliminal_patch.core            (ffffad39a590) :  DEBUG (core:559) - Size is 835783075
2021-08-28 10:10:56,237 - subliminal_patch.core            (ffffad39a590) :  DEBUG (core:587) - Computed hashes {'bsplayer': '8745079e6c9208bd', 'opensubtitles': '8745079e6c9208bd'}
2021-08-28 10:10:56,240 - peewee                           (ffffad39a590) :  DEBUG (peewee:3132) - ('SELECT "t1"."title", "t1"."year", "t1"."alternativeTitles", "t1"."format", "t1"."resolution", "t1"."video_codec", "t1"."audio_codec", "t1"."imdbId" FROM "table_movies" AS "t1" WHERE ("t1"."path" = ?)', ['/media/movies/The Unholy (2021)/The.Unholy.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx].mkv'])
2021-08-28 10:10:56,243 - peewee                           (ffffad39a590) :  DEBUG (peewee:3132) - ('SELECT "t1"."movie_file_id", "t1"."file_size" FROM "table_movies" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ['/media/movies/The Unholy (2021)/The.Unholy.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx].mkv', 1, 0])
2021-08-28 10:10:56,245 - root                             (ffffad39a590) :  ERROR (get_subtitle:83) - BAZARR Error trying to get video information for this file: /movies/The Unholy (2021)/The.Unholy.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx].mkv
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6884, in get
    return clone.execute(database)[0]
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 4275, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 77, in get_video
    refine_from_ffprobe(original_path, video)
  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 1332, in refine_from_ffprobe
    file_id = TableMovies.select(TableMovies.movie_file_id, TableMovies.file_size)\
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6887, in get
    raise self.model.DoesNotExist('%s instance matching query does '
database.TableMoviesDoesNotExist: <Model: TableMovies> instance matching query does not exist:
SQL: SELECT "t1"."movie_file_id", "t1"."file_size" FROM "table_movies" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?
Params: ['/media/movies/The Unholy (2021)/The.Unholy.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx].mkv', 1, 0]
```

**Software (please complete the following information):**
 - Bazarr: v0.9.8-beta.11, also tested with v0.9.7, logs above are with v0.9.8-beta.11
 - Radarr version: 3.2.2.5080
 - Sonarr version 3.0.6.1265
 - OS: Using the linuxserver docker images for all of the above, running on rockhip64/armbian

**Additional info**
I think I changed the path on Sonarr and Radarr for series/movies recently (a few weeks back) but Bazarr is able to retrieve info/updates from both so I would think this isn't an issue?
Also I know that new versions might have DB updates, maybe I forgot a manual update of the DB or something? Tried to find more info but didn't find any.

Thanks for the support and bazarr in general :)

**Comment by laurensmiers** [comment]
While typing the bug report, I realized that it was indeed the path change on Sonarr/Radarr (I misread the path in the debug logs) and I didn't update the Bazarr remote path mappings to the new paths in Sonarr/Radarr.
Sorry for the noise.
