### ISSUE TITLE
Bazarr deployed in Docker is unable to write to /movies and /tv directory for Sonarr/Radarr

### ISSUE THREAD

**Issue by Rhfelwr** [morpheus65535/bazarr#1528]
I get this error in Bazarr that it cannot write to the movies and tv directories. It is deployed as a container in Docker via Portainer. Bazarr sees the files in the Sonarr and Radarr folders but seemingly it cannot write to them. I have set chmod to 777, which did not help.

Here are the last entries from my debug log (and here you can check the rest on pastebin: https://pastebin.com/fHvb4fKN)
```
05/09/2021 13:31:31|DEBUG   |peewee                          |('SELECT "t1"."tvdbId", "t1"."alternateTitles", "t1"."audio_language", "t1"."fanart", "t1"."imdbId", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."seriesType", "t1"."sonarrSeriesId", "t1"."sortTitle", "t1"."tags", "t1"."title", "t1"."year" FROM "table_shows" AS "t1" WHERE ("t1"."sonarrSeriesId" IN (?)) ORDER BY "t1"."sortTitle"', [26])|
05/09/2021 13:31:31|DEBUG   |peewee                          |('SELECT "t1"."tvdbId", "t1"."alternateTitles", "t1"."audio_language", "t1"."fanart", "t1"."imdbId", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."seriesType", "t1"."sonarrSeriesId", "t1"."sortTitle", "t1"."tags", "t1"."title", "t1"."year" FROM "table_shows" AS "t1" WHERE ("t1"."sonarrSeriesId" = ?) LIMIT ? OFFSET ?', [26, 1, 0])|
05/09/2021 13:31:31|DEBUG   |peewee                          |('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE ((("t1"."sonarrSeriesId" = ?) AND ("t1"."missing_subtitles" != ?)) AND ("t1"."monitored" = ?))) AS "_wrapped"', [26, '[]', 'True'])|
05/09/2021 13:31:31|DEBUG   |peewee                          |('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE ("t1"."sonarrSeriesId" = ?)) AS "_wrapped"', [26])|
05/09/2021 13:31:37|DEBUG   |peewee                          |('SELECT "t1"."title", "t1"."path", "t1"."sceneName", "t1"."audio_language" FROM "table_movies" AS "t1" WHERE ("t1"."radarrId" = ?) LIMIT ? OFFSET ?', [1, 1, 0])|
05/09/2021 13:31:37|DEBUG   |peewee                          |('SELECT "t1"."rowid", "t1"."alternativeTitles", "t1"."audio_codec", "t1"."audio_language", "t1"."failedAttempts", "t1"."fanart", "t1"."ffprobe_cache", "t1"."file_size", "t1"."format", "t1"."imdbId", "t1"."missing_subtitles", "t1"."monitored", "t1"."movie_file_id", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."radarrId", "t1"."resolution", "t1"."sceneName", "t1"."sortTitle", "t1"."subtitles", "t1"."tags", "t1"."title", "t1"."tmdbId", "t1"."video_codec", "t1"."year" FROM "table_movies" AS "t1" WHERE ("t1"."radarrId" = ?) LIMIT ? OFFSET ?', [1, 1, 0])|
05/09/2021 13:31:37|DEBUG   |root                            |BAZARR Searching subtitles for this file: /movies/Black Widow (2021)/Black Widow 2021.mkv|
05/09/2021 13:31:37|DEBUG   |subzero.video                   |Parsing video: Black.Widow.2021.2160p.DSNP.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-CM.mkv, hints: {'title': 'Black Widow', 'type': 'movie'}|
05/09/2021 13:31:37|INFO    |subliminal_patch.core           |Determining basic video properties for 'Black.Widow.2021.2160p.DSNP.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-CM.mkv' in '/movies/Black Widow (2021)'|
05/09/2021 13:31:37|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Black Widow",
    "year": 2021,
    "screen_size": "2160p",
    "source": "Web",
    "video_codec": "H.265",
    "color_depth": "10-bit",
    "other": "HDR10",
    "audio_codec": "Dolby Digital Plus",
    "audio_channels": "5.1",
    "release_group": "CM",
    "container": "mkv",
    "type": "movie"
}|
05/09/2021 13:31:37|ERROR   |root                            |BAZARR Error trying to get video information for this file: /movies/Black Widow (2021)/Black Widow 2021.mkv|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 70, in get_video    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,  File "/app/bazarr/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 557, in scan_video    video.size = os.path.getsize(hash_path)  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize    return os.stat(filename).st_sizeFileNotFoundError: [Errno 2] No such file or directory: '/movies/Black Widow (2021)/Black Widow 2021.mkv'|
05/09/2021 13:31:37|DEBUG   |root                            |BAZARR Ended searching Subtitles for file: /movies/Black Widow (2021)/Black Widow 2021.mkv|
05/09/2021 13:31:37|INFO    |socketio.server                 |emitting event "data" to all [/]|
05/09/2021 13:31:40|DEBUG   |peewee                          |('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1") AS "_wrapped"', [])|
05/09/2021 13:31:40|DEBUG   |peewee                          |('SELECT "t1"."rowid", "t1"."alternativeTitles", "t1"."audio_codec", "t1"."audio_language", "t1"."failedAttempts", "t1"."fanart", "t1"."ffprobe_cache", "t1"."file_size", "t1"."format", "t1"."imdbId", "t1"."missing_subtitles", "t1"."monitored", "t1"."movie_file_id", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."radarrId", "t1"."resolution", "t1"."sceneName", "t1"."sortTitle", "t1"."subtitles", "t1"."tags", "t1"."title", "t1"."tmdbId", "t1"."video_codec", "t1"."year" FROM "table_movies" AS "t1" WHERE ("t1"."radarrId" IN (?)) ORDER BY "t1"."sortTitle"', [1])|
05/09/2021 13:31:40|DEBUG   |peewee                          |('SELECT "t1"."rowid", "t1"."alternativeTitles", "t1"."audio_codec", "t1"."audio_language", "t1"."failedAttempts", "t1"."fanart", "t1"."ffprobe_cache", "t1"."file_size", "t1"."format", "t1"."imdbId", "t1"."missing_subtitles", "t1"."monitored", "t1"."movie_file_id", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."radarrId", "t1"."resolution", "t1"."sceneName", "t1"."sortTitle", "t1"."subtitles", "t1"."tags", "t1"."title", "t1"."tmdbId", "t1"."video_codec", "t1"."year" FROM "table_movies" AS "t1" WHERE ("t1"."radarrId" = ?) LIMIT ? OFFSET ?', [1, 1, 0])|
05/09/2021 13:31:57|DEBUG   |peewee.sqliteq                  |received query UPDATE "table_settings_languages" SET "enabled" = ?|
05/09/2021 13:31:57|DEBUG   |peewee                          |('UPDATE "table_settings_languages" SET "enabled" = ?', [0])|
05/09/2021 13:31:57|DEBUG   |peewee.sqliteq                  |received query UPDATE "table_settings_languages" SET "enabled" = ? WHERE ("table_settings_languages"."code2" = ?)|
05/09/2021 13:31:57|DEBUG   |peewee                          |('UPDATE "table_settings_languages" SET "enabled" = ? WHERE ("table_settings_languages"."code2" = ?)', [1, ''])|
05/09/2021 13:31:57|INFO    |socketio.server                 |emitting event "data" to all [/]|
05/09/2021 13:31:57|INFO    |socketio.server                 |emitting event "data" to all [/]|
05/09/2021 13:31:57|DEBUG   |peewee                          |('SELECT "t1"."name", "t1"."enabled", "t1"."url" FROM "table_settings_notifier" AS "t1" ORDER BY "t1"."name"', [])|
05/09/2021 13:31:57|DEBUG   |peewee                          |('SELECT "t1"."name", "t1"."code2", "t1"."enabled" FROM "table_settings_languages" AS "t1" ORDER BY "t1"."name"', [])|
05/09/2021 13:31:57|DEBUG   |peewee                          |('SELECT "t1"."name", "t1"."code2", "t1"."enabled" FROM "table_settings_languages" AS "t1" ORDER BY "t1"."name"', [])|
05/09/2021 13:32:11|DEBUG   |peewee.sqliteq                  |received query UPDATE "table_shows" SET "profileId" = ? WHERE ("table_shows"."sonarrSeriesId" = ?)|
05/09/2021 13:32:11|DEBUG   |peewee                          |('UPDATE "table_shows" SET "profileId" = ? WHERE ("table_shows"."sonarrSeriesId" = ?)', [None, ''])|
05/09/2021 13:32:11|DEBUG   |peewee                          |('SELECT "t1"."sonarrSeriesId", "t2"."sonarrEpisodeId", "t2"."subtitles", "t1"."profileId", "t2"."audio_language" FROM "table_episodes" AS "t2" INNER JOIN "table_shows" AS "t1" ON ("t2"."sonarrSeriesId" = "t1"."sonarrSeriesId") WHERE ("t2"."sonarrSeriesId" = ?)', [''])|
05/09/2021 13:32:11|INFO    |socketio.server                 |emitting event "data" to all [/]|
05/09/2021 13:32:11|DEBUG   |peewee                          |('SELECT "t1"."sonarrEpisodeId" FROM "table_episodes" AS "t1" WHERE ("t1"."sonarrSeriesId" = ?)', [''])|
05/09/2021 13:32:11|INFO    |socketio.server                 |emitting event "data" to all [/]|
05/09/2021 13:32:12|DEBUG   |peewee                          |('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE ((? AND ("t1"."missing_subtitles" != ?)) AND ("t1"."monitored" = ?))) AS "_wrapped"', [True, '[]', 'True'])|
05/09/2021 13:32:12|DEBUG   |peewee                          |('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1" WHERE (? AND ("t1"."missing_subtitles" != ?))) AS "_wrapped"', [True, '[]'])|
05/09/2021 13:32:12|DEBUG   |peewee                          |('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_shows_rootfolder" AS "t1" WHERE ("t1"."accessible" = ?)', [0])|
05/09/2021 13:32:12|DEBUG   |peewee                          |('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = ?)', [0])|
```

**Comment by morpheus65535** [comment]
That's a Docker configuration issue an is not related to Bazarr issue. Although, you can come to Discord for live support. They will be able to help you configure your volume binding/permission accordingly.
