### ISSUE TITLE
Bazarr won't connect to Radarr.

### ISSUE THREAD

**Issue by AbstractUmbra** [morpheus65535/bazarr#1531]
**Describe the bug**
Bazarr cannot connect to Radarr (nightly).
I have inspected the logs and it seems that the endpoint: `GET /api/system/status?apikey=...` is actually a 404.
I believe Radarr may have changed their API endpoint?
Sonarr nightly works just fine however.

**To Reproduce**
1. Go to "Settings > Radarr"
2. Add a known working configuration.
3. Hit "Test".
4. Endless looping and checking the log file will result in:
```py
07/09/2021 00:00:16|ERROR   |app                             |Exception on /bazarr/test_url/http/127.***.***.***:7878/radarr/api/system/status?apikey=********9d [GET]|'Traceback (most recent call last):\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\_compat.py", line 39, in reraise\n    raise value\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "c:\\programdata\\bazarr\\bazarr\\main.py", line 79, in wrap\n    return f(*args, **kwargs)\n  File "c:\\programdata\\bazarr\\bazarr\\main.py", line 482, in test_url\n    return dict(status=False, error=result.raise_for_status())\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\requests\\models.py", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7878/radarr/api/system/status?apikey=<Redacted>'|
07/09/2021 00:00:38|ERROR   |app                             |Exception on /bazarr/test_url/http/127.***.***.***:7878/radarr/api/system/status?apikey=********9d [GET]|'Traceback (most recent call last):\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\_compat.py", line 39, in reraise\n    raise value\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "c:\\programdata\\bazarr\\bazarr\\main.py", line 79, in wrap\n    return f(*args, **kwargs)\n  File "c:\\programdata\\bazarr\\bazarr\\main.py", line 482, in test_url\n    return dict(status=False, error=result.raise_for_status())\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\requests\\models.py", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7878/radarr/api/system/status?apikey=<Redacted>'|
07/09/2021 00:00:42|ERROR   |app                             |Exception on /bazarr/test_url/http/127.***.***.***:7878/radarr/api/system/status?apikey=********9d [GET]|'Traceback (most recent call last):\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\_compat.py", line 39, in reraise\n    raise value\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "c:\\programdata\\bazarr\\bazarr\\main.py", line 79, in wrap\n    return f(*args, **kwargs)\n  File "c:\\programdata\\bazarr\\bazarr\\main.py", line 482, in test_url\n    return dict(status=False, error=result.raise_for_status())\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\requests\\models.py", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7878/radarr/api/system/status?apikey=<Redacted>'|
07/09/2021 00:03:53|ERROR   |apscheduler.executors.default   |Job "Update Movie list from Radarr (trigger: interval[0:05:00], next run at: 2021-09-07 00:08:53 BST)" raised an exception|'Traceback (most recent call last):\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "c:\\programdata\\bazarr\\bazarr\\get_movies.py", line 164, in update_movies\n    tags = [d[\'label\'] for d in tagsDict if d[\'id\'] in movie[\'tags\']]\n  File "c:\\programdata\\bazarr\\bazarr\\get_movies.py", line 164, in <listcomp>\n    tags = [d[\'label\'] for d in tagsDict if d[\'id\'] in movie[\'tags\']]\nTypeError: string indices must be integers'|
```

**Expected behavior**
The Radarr config to Test and save correctly, and for Bazarr to function.

**Screenshots**
N/A but please request any if needed.

**Software (please complete the following information):**
 - Bazarr: 0.9.1
 - Radarr version: 4.0.0.5241 (nightly)
 - Sonarr version: 3.0.6.1333
 - OS: Windows 10.

**Additional context**
N/A

**Comment by morpheus65535** [comment]
Current version is 0.9.8. Uninstall and reinstall using the brand new installer available on our website. You won't loose your settings.
