### ISSUE TITLE
Python-CFFI error

### ISSUE THREAD

**Issue by minimeh** [morpheus65535/bazarr#1532]
**Describe the bug**
I'm seeing irregularly paced yet frequent popups with a python stack trace titled "Python-CFFI error". The stack trace is shown below.

**To Reproduce**
I don't have an explicit repro case as requested.

I had  bazarr running for months if not years and this exception just arbitrarily started with no system or configuration changes except auto updates of bazarr and Windows. 

To try to resolve, I completely removed everything in the bazarr installation folder. I upgraded the Python installation to 3.8.6. I then installed bazarr following the instructions in https://wiki.bazarr.media/Getting-Started/Installation/Windows/windows/ for running from the source files.

I ran bazarr and connected with Firefox. I configured bazarr from scratch. All appeared normal and ran okay.

When I came back to the PC the next day, the popup with the exception stack trace was there. Some hours later, another popped up. 

**Expected behavior**
Obviously, I expect to not have exceptions triggering popup stack traces.

**Screenshots**
The text of the popup is shown below.

**Software (please complete the following information):**
 - Bazarr: version v0.9.8
 - Radarr: version 3.2.2.5080
 - Sonarr: version 3.0.6.1265
 - OS: version Windows 10.0.19042

**Additional context**
I have attached zipped log files. 
[bazarr.log.2021-09-05.zip](https://github.com/morpheus65535/bazarr/files/7119942/bazarr.log.2021-09-05.zip)
[bazarr.log.2021-09-06.zip](https://github.com/morpheus65535/bazarr/files/7119943/bazarr.log.2021-09-06.zip)

This is the text of the error popup:
```
Exception ignored from cffi callback <bound method AbstractCallbacks.python_prepare_callback of <gevent.libuv.loop._Callbacks object at 0x000001D5A11B8BB0>>:
Traceback (most recent call last):
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\_ffi\loop.py", line 302, in python_prepare_callback
    loop._run_callbacks()
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\libuv\loop.py", line 232, in _run_callbacks
    self._prepare_ran_callbacks = self.__run_queued_callbacks()
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\libuv\loop.py", line 502, in __run_queued_callbacks
    val = _callbacks.python_callback(handle, arg)
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\_ffi\loop.py", line 172, in python_callback
    print("WARNING: gevent: Error when handling error",
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [Errno 22] Invalid argument
Exception ignored during handling of the above exception by 'onerror':
Traceback (most recent call last):
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\_ffi\loop.py", line 311, in check_callback_onerror
    loop.handle_error(None, t, v, tb)
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\_ffi\loop.py", line 621, in handle_error
    handle_error(context, type, value, tb)
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\hub.py", line 541, in handle_error
    self.print_exception(context, type, value, tb)
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\hub.py", line 610, in print_exception
    traceback.print_exception(t, v, tb, file=errstream)
  File "C:\Python38\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [Errno 22] Invalid argument
```

**Comment by morpheus65535** [comment]
The only issues I can see in your logs are related to malformed mkv files and Bazarr unable to reach Sonarr. Nothing related to CFFI.

**Comment by minimeh** [comment]
In both bazarr.log.2021-09-05 and bazarr.log.2021-09-06, the 5 "Requiem.S01E0x.mkv" files turn out to be mp4 files and have incorrect file extensions. File "Britannia.S03E06.mkv" hangs up mkvalidator so that mkv seems to be munged. In all cases I notice that exceptions occur while handling exceptions. Is that a problem?

Is there something more I can do to facilitate chasing down the CFFI exception (which doesn't appear in the logs)? Would it help to run bazarr from a console window with debugging on? I'll leave the problematic mkv files as they are for now, although I haven't had a recurrence since before I created this ticket.

Oh, and thanks for reformatting the text of the error popup. That's what I was shooting for but my formatting kung fu ain't up to snuff!

**Comment by morpheus65535** [comment]
Just out of curiosity, how are you running Sonarr? Docker?

(BTW: np for the code formatting, it's easier to read that way ;-))

**Comment by morpheus65535** [comment]
Any other instance of ffprobe other than the one inside the Bazarr's bin directory?

**Comment by minimeh** [comment]
> Just out of curiosity, how are you running Sonarr? Docker?

No docker. Running as a Windows service.

**Comment by minimeh** [comment]
> Any other instance of ffprobe other than the one inside the Bazarr's bin directory?

Yes there is. "where ffprobe" returns a "[user folder]\ffmpeg\bin\ffprobe.exe". And in fact, "dir /s ffprobe*.* from within the bazarr returns...nothing. And "dir \s *.exe" returns only unrar.exe.

**Comment by morpheus65535** [comment]
> Yes there is. "where ffprobe" returns "[user folder]\ffmpeg\bin\ffprobe.exe". And in fact, "dir /s ffprobe*.* from within the bazarr folder returns...nothing. And "dir \s *.exe" returns only unrar.exe.

What version of ffprobe it is? Can you try to rename it to let Bazarr download it's own version?

**Comment by minimeh** [comment]
> What version of ffprobe it is? Can you try to rename it to let Bazarr download it's own version?

> ffprobe version N-93302-g147ef1d947 Copyright (c) 2007-2019 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20190212
> configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
> libavutil      56. 26.100 / 56. 26.100
> libavcodec     58. 47.103 / 58. 47.103
> libavformat    58. 26.101 / 58. 26.101
> libavdevice    58.  6.101 / 58.  6.101
> libavfilter     7. 48.100 /  7. 48.100
> libswscale      5.  4.100 /  5.  4.100
> libswresample   3.  4.100 /  3.  4.100
> libpostproc    55.  4.100 / 55.  4.100

I renamed the folder and then restarted bazaar. While I was at it, I updated my version of ffprobe but it will still be invisible to bazarr. As of the moment, unrar.exe is still the only *.exe in bazarr's folder but I expect that will change the next time ffprobe is needed.

**Comment by morpheus65535** [comment]
Yes the version of ffprobe you're using is a nightly build and, unfortunately, the Python module we sue to interface with it only support final versions.

The 2approved" version will get downloaded next time a call is made to run ffprobe. You should see it appear in bin directory.

**Comment by minimeh** [comment]
I got another exception stack trace. It's the same as the previous ones except for the first line has a different object address:
`_Callbacks object at 0x000002427ADC6AC0>>`

Bazarr's own ffprobe.exe is in C:\bazarr\bin\Windows\i386\ffmpeg. No other instances of ffprobe are visible to bazarr.

In the attached log files, the same misnamed (Requiem.S01[E02-E06.mkv]) and malformed (Britannia.S03E06.mkv) videos are triggering errors. 

In only the bazarr.log.2021-09-08 do I find:
`08/09/2021 13:13:26|ERROR   |engineio.server                 |Invalid session thcA2olrbZzKPfqOAAGt (further occurrences of this error will be logged with level INFO)|
`
and I do not see further occurrences of this error logged with level INFO.

Sorry, but I'm not sure if the stack trace popup occurred on 9/8 or 9/9, but I _think_ it was 9/9. And there is currently the one popup.
```
---------------------------
Python-CFFI error
---------------------------
Exception ignored from cffi callback <bound method AbstractCallbacks.python_prepare_callback of <gevent.libuv.loop._Callbacks object at 0x000002427ADC6AC0>>:
Traceback (most recent call last):
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\_ffi\loop.py", line 302, in python_prepare_callback
    loop._run_callbacks()
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\libuv\loop.py", line 232, in _run_callbacks
    self._prepare_ran_callbacks = self.__run_queued_callbacks()
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\libuv\loop.py", line 502, in __run_queued_callbacks
    val = _callbacks.python_callback(handle, arg)
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\_ffi\loop.py", line 172, in python_callback
    print("WARNING: gevent: Error when handling error",
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [Errno 22] Invalid argument
Exception ignored during handling of the above exception by 'onerror':
Traceback (most recent call last):
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\_ffi\loop.py", line 311, in check_callback_onerror
    loop.handle_error(None, t, v, tb)
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\_ffi\loop.py", line 621, in handle_error
    handle_error(context, type, value, tb)
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\hub.py", line 541, in handle_error
    self.print_exception(context, type, value, tb)
  File "C:\Users\pdellera\AppData\Roaming\Python\Python38\site-packages\gevent\hub.py", line 610, in print_exception
    traceback.print_exception(t, v, tb, file=errstream)
  File "C:\Python38\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [Errno 22] Invalid argument

---------------------------
OK   
---------------------------

```
[bazarr.log.2021-09-07.zip](https://github.com/morpheus65535/bazarr/files/7140183/bazarr.log.2021-09-07.zip)
[bazarr.log.2021-09-08.zip](https://github.com/morpheus65535/bazarr/files/7140177/bazarr.log.2021-09-08.zip)

**Comment by morpheus65535** [comment]
I'm kind of driving blind here... using `pip list`, can you confirm what version of gevent you have installed?

**Comment by minimeh** [comment]
Understood, I don't envy you here. :-)
```
pip list
Package          Version
---------------- ------------
cffi             1.14.6
gevent           21.1.2
gevent-websocket 0.10.1
greenlet         1.1.0
lxml             4.6.3
numpy            1.21.2
pip              21.2.4
pycparser        2.20
setuptools       49.2.1
webrtcvad-wheels 2.0.10.post2
zope.event       4.5.0
zope.interface   5.4.0
```

**Comment by morpheus65535** [comment]
Any specific reason why you have cffi installed? I don't have it:
```
Package          Version
---------------- ------------
gevent           21.1.2
gevent-websocket 0.10.1
greenlet         1.1.0
lxml             4.6.3
numpy            1.21.2
pip              21.2.1
setuptools       57.4.0
webrtcvad-wheels 2.0.10.post2
wheel            0.36.2
zope.event       4.5.0
zope.interface   5.4.0
```

**Comment by minimeh** [comment]
> Any specific reason why you have cffi installed? I don't have it:

Well, that's an interesting turn of events. If _you_ don't have it, why is bazarr using it?

I don't explicitly have a known reason for it to be there. I do run and sometimes remove python stuff (including my own), but I have no memory of cffi.

On another note, I just had another stack trace popup. Same as before. I grabbed a look at the running bazarr log. It actually contains an error with a stack trace caused by a timeout error with sonarr.
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/7143499/bazarr.zip)

**Comment by minimeh** [comment]
Just looked up cffi. Sounds like something I would play with. If bazarr doesn't use it, I'll just eliminate the package and see if anything else breaks.

**Comment by morpheus65535** [comment]
Bazarr doesn't use CFFI. It use gevent that, on Windows, seems to require CFFI. As I'm on MacOS and Linux, I don't have this requirement.

You can try to uninstall it but I would guess that Bazarr won't start due to an ImportError.

**Comment by morpheus65535** [comment]
@vitiko98 any chance you see something that I've miss?

**Comment by minimeh** [comment]
> Bazarr doesn't use CFFI. It use gevent that, on Windows, seems to require CFFI. As I'm on MacOS and Linux, I don't have this requirement.
> 
> You can try to uninstall it but I would guess that Bazarr won't start due to an ImportError.

Yeah, I did uninstall it. Got errors and cffi package was left in tatters. So I once again wiped the python38 installation (after stopping everything I am aware of that is a python app). That was incomplete, accessed denied in the lib folder. Reinstalled python38, did pip list, and lo, cffi was still there in tatters. Uninstalled python38, sought the sem-hidden ghost library, and wiped it out. Now going to reboot and see if I can then remove the remnants of python38/lib to which access was denied. And hopefully achieve a clean installation of python38.

**Comment by minimeh** [comment]
I did a complete reinstall of python38. The full pip list:
```
Package    Version
---------- -------
pip        20.2.1
setuptools 49.2.1

```
Then I went into the bazarr folder and did `pip install -r requirements.txt`. Following that, pip list is more fulsome:
```
pip list
Package          Version
---------------- ------------
cffi             1.14.6
gevent           21.8.0
gevent-websocket 0.10.1
greenlet         1.1.1
lxml             4.6.3
numpy            1.21.2
pip              21.2.4
pycparser        2.20
setuptools       49.2.1
webrtcvad-wheels 2.0.10.post2
zope.event       4.5.0
zope.interface   5.4.0
```
So confirmed, bazarr does use cffi. Bazarr is now up and running with a truly clean python38 installation. Fingers crossed.

**Comment by minimeh** [comment]
I can uncross my fingers now. Same error triggered another stack trace popup.

So when I went to check the log file, I found only bazarr.log. All of the previous log files, _and_ the zips of them that I had created to upload here, were gone. Is that normal? Note that I had not wiped the bazarr folder while reinstalling python38. Maybe `pip install -r requirements.txt` causes wiping the log folder?

Anyway. the running bazarr.log is short and so here it is:
```
11/09/2021 01:20:42|ERROR   |engineio.server                 |Invalid session Gp66pJp_QBgtvJuZAAAw (further occurrences of this error will be logged with level INFO)|
11/09/2021 01:34:02|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
11/09/2021 01:58:22|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
11/09/2021 04:00:35|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
11/09/2021 04:34:02|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
11/09/2021 04:58:22|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
11/09/2021 05:00:05|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
11/09/2021 07:34:02|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
11/09/2021 07:58:22|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
11/09/2021 10:34:02|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
11/09/2021 10:40:06|ERROR   |apscheduler.executors.default   |Job "Update Bazarr (trigger: interval[6:00:00], next run at: 2021-09-11 16:39:34 PDT)" raised an exception|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "c:\\bazarr\\bazarr\\check_update.py", line 86, in check_if_new_update\n    download_release(url=release[\'download_link\'])\n  File "c:\\bazarr\\bazarr\\check_update.py", line 117, in download_release\n    apply_update()\n  File "c:\\bazarr\\bazarr\\check_update.py", line 166, in apply_update\n    os.remove(bazarr_zip)\nFileNotFoundError: [WinError 3] The system cannot find the path specified: \'C:\\\\bazarr\\\\data\\\\update\\\\bazarr.zip\''|
11/09/2021 10:58:22|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
11/09/2021 13:34:02|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
11/09/2021 13:58:22|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
11/09/2021 14:33:10|INFO    |root                            |BAZARR Running cache maintenance|
11/09/2021 16:34:02|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
11/09/2021 16:39:34|ERROR   |apscheduler.executors.default   |Job "Update Bazarr (trigger: interval[6:00:00], next run at: 2021-09-11 22:39:34 PDT)" raised an exception|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "c:\\bazarr\\bazarr\\check_update.py", line 60, in check_if_new_update\n    check_releases()\n  File "c:\\bazarr\\bazarr\\check_update.py", line 45, in check_releases\n    with open(os.path.join(args.config_dir, \'config\', \'releases.txt\'), \'w\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'C:\\\\bazarr\\\\data\\\\config\\\\releases.txt\''|
```
For full disclosure, here is the text of the current popup:
```
---------------------------
Python-CFFI error
---------------------------
Exception ignored from cffi callback <bound method AbstractCallbacks.python_prepare_callback of <gevent.libuv.loop._Callbacks object at 0x000001B05E3F9130>>:
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\gevent\_ffi\loop.py", line 302, in python_prepare_callback
    loop._run_callbacks()
  File "C:\Python38\lib\site-packages\gevent\libuv\loop.py", line 227, in _run_callbacks
    self._prepare_ran_callbacks = self.__run_queued_callbacks()
  File "C:\Python38\lib\site-packages\gevent\libuv\loop.py", line 497, in __run_queued_callbacks
    val = _callbacks.python_callback(handle, arg)
  File "C:\Python38\lib\site-packages\gevent\_ffi\loop.py", line 172, in python_callback
    print("WARNING: gevent: Error when handling error",
  File "c:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [Errno 22] Invalid argument
Exception ignored during handling of the above exception by 'onerror':
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\gevent\_ffi\loop.py", line 311, in check_callback_onerror
    loop.handle_error(None, t, v, tb)
  File "C:\Python38\lib\site-packages\gevent\_ffi\loop.py", line 623, in handle_error
    handle_error(context, type, value, tb)
  File "C:\Python38\lib\site-packages\gevent\hub.py", line 541, in handle_error
    self.print_exception(context, type, value, tb)
  File "C:\Python38\lib\site-packages\gevent\hub.py", line 610, in print_exception
    traceback.print_exception(t, v, tb, file=errstream)
  File "C:\Python38\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
  File "c:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\bazarr\bazarr\../libs\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [Errno 22] Invalid argument

---------------------------
OK   
---------------------------

```

**Comment by minimeh** [comment]
More to report: I noticed that bazarr wasn't apparently functioning--no page updates, no activity, no signs of life. When I clicked on Series, the page just went blank, not busy loading but just blank. A page refresh also displays  a blank page.

I killed the pythonw instances running bazarr.py and main.py. I then executed `pythonw bazarr.py`. Bazarr came up with the main page but it was completely missing any configuration--no series, no movies, no history, no settings, etc.

I opened config.ini and of course it was just an uninitialized config file, brand new. Fortunately,  I had saved the working configuration to C:\bazarr\config-bak.ini .because I saw this happen before and wanted to not have to reconfigure everything again. And unbelievably, that too is gone. Also, of course as reported above, all of the log files and the zips created to upload them here are gone.

I see in the attached log this error attempting to update bazarr (eols unrolled):
```
11/09/2021 10:40:06|ERROR   |apscheduler.executors.default   |Job "Update Bazarr (trigger: interval[6:00:00], next run at: 2021-09-11 16:39:34 PDT)" raised an exception|'Traceback (most recent call last):
  File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\\bazarr\\bazarr\\check_update.py", line 86, in check_if_new_update
    download_release(url=release[\'download_link\'])
  File "c:\\bazarr\\bazarr\\check_update.py", line 117, in download_release
    apply_update()
  File "c:\\bazarr\\bazarr\\check_update.py", line 166, in apply_update
    os.remove(bazarr_zip)
FileNotFoundError: [WinError 3] The system cannot find the path specified: \'C:\\\\bazarr\\\\data\\\\update\\\\bazarr.zip\''|

```
I also note that the timestamps for the files "VERSION" and "requirements.txt" as well as the files in c::\bazarr\bazarr reflect this  same time frame:
```
 Directory of C:\bazarr

09/11/2021  10:40 AM    <DIR>          .
09/11/2021  10:40 AM    <DIR>          ..
09/05/2021  04:09 AM    <DIR>          bazarr
09/05/2021  04:10 AM    <DIR>          bin
09/12/2021  02:59 AM    <DIR>          data
08/31/2021  09:53 AM    <DIR>          frontend
09/05/2021  04:09 AM    <DIR>          libs
08/31/2021  09:53 AM             3,128 bazarr.py
09/11/2021  10:39 AM                97 requirements.txt
09/11/2021  10:39 AM                 7 VERSION
               3 File(s)          3,232 bytes
               7 Dir(s)  3,331,175,051,264 bytes free

 Directory of c:\bazarr\bazarr

09/05/2021  04:09 AM    <DIR>          .
09/05/2021  04:09 AM    <DIR>          ..
09/12/2021  03:00 AM    <DIR>          __pycache__
09/11/2021  10:39 AM                15 __init__.py
09/11/2021  10:39 AM             2,901 analytics.py
09/11/2021  10:39 AM            89,301 api.py
09/11/2021  10:39 AM             1,747 app.py
09/11/2021  10:39 AM             5,244 binaries.json
09/11/2021  10:39 AM            11,056 check_update.py
09/11/2021  10:39 AM            18,816 config.py
09/11/2021  10:39 AM             5,286 custom_lang.py
09/11/2021  10:39 AM            17,227 database.py
09/11/2021  10:39 AM             4,921 embedded_subs_reader.py
09/11/2021  10:39 AM               841 event_handler.py
09/11/2021  10:39 AM             3,994 filesystem.py
09/11/2021  10:39 AM             1,551 get_args.py
09/11/2021  10:39 AM            18,560 get_episodes.py
09/11/2021  10:39 AM             3,339 get_languages.py
09/11/2021  10:39 AM            24,008 get_movies.py
09/11/2021  10:39 AM            13,767 get_providers.py
09/11/2021  10:39 AM             8,396 get_rootfolder.py
09/11/2021  10:39 AM            14,148 get_series.py
09/11/2021  10:39 AM            85,702 get_subtitle.py
09/11/2021  10:39 AM             7,066 helper.py
09/11/2021  10:39 AM             7,832 init.py
09/11/2021  10:39 AM               617 libs.py
09/11/2021  10:39 AM            31,128 list_subtitles.py
09/11/2021  10:39 AM             5,287 logger.py
09/11/2021  10:39 AM             6,722 main.py
09/11/2021  10:39 AM             3,694 notifier.py
09/11/2021  10:39 AM            13,110 scheduler.py
09/11/2021  10:39 AM             7,797 score.py
09/11/2021  10:39 AM             2,677 server.py
09/11/2021  10:39 AM             7,587 signalr_client.py
09/11/2021  10:39 AM             3,797 subsyncer.py
09/11/2021  10:39 AM            20,649 utils.py
              33 File(s)        448,783 bytes
               3 Dir(s)  3,331,172,630,528 bytes free

```
Finally, the VERSION text in c:\bazarr is "v0.9.9" while the VERSION text in the zip file I installed with is "v0.9.8".

I can't believe that updating bazarr, even if an error occurs, could result in the resetting of all configuration and deletion of all files such as logs and config backups, yet that is what clearly happened.

[bazarr.log.2021-09-11.zip](https://github.com/morpheus65535/bazarr/files/7149494/bazarr.log.2021-09-11.zip)

**Comment by halali** [comment]
Oh, now i see. You run bazarr with pythonw.exe instead python.exe.

**Comment by minimeh** [comment]
In normal circumstances, of course. While working this issue, I have also run it with python.exe from the command line so as to see the stdout/stderr  output.  The stack trace popup about CFFI error has occurred under both circumstances.

**Comment by morpheus65535** [comment]
Ok, I've been running 0.9.9 installed through the Windows Installer with embedded Python version without any issues for the last 3 days. As I can reproduce the issue you're having, I would suggest to remove everything (Bazarr, Python, etc.) then use the Windows Installer available on www.bazarr.media.

Other than that, I guess you'll have to try it on another Windows installation. You're having extremely strange issues that I can't explain myself. In the last 4 days, 95% of the Windows users have upgraded without any issues to 0.9.9. I can't see why yours can work as expected.

**Comment by minimeh** [comment]
> Ok, I've been running 0.9.9 installed through the Windows Installer with embedded Python version without any issues for the last 3 days. **_As I can reproduce the issue you're having_**, I would suggest to remove everything (Bazarr, Python, etc.) then use the Windows Installer available on [www.bazarr.media](http://www.bazarr.media).
> 
You reproduced the issue but still want me to nuke my installation yet again and reinstall using the Windows installer? Is it official, then, that running from the source is no longer supported?
> Other than that, I guess you'll have to try it on another Windows installation. You're having extremely strange issues that I can't explain myself. In the last 4 days, 95% of the Windows users have upgraded without any issues to 0.9.9. I can't see why yours can work as expected.

Sure, I'll buy a new PC with Windows and see if that doesn't do the job. 

Everything I've reported here has been accurate and true. I've tried to give you whatever supporting evidence asked for or available. If you can't figure it out, just say so without implying that it must be me. I can live with that. I'm just reporting undeniable bugs in your software running on my system and trying as best I can to help you track them down.

Obviously for the majority of users (although I do question your 95% figure. That's a guess, not a fact.), thee are problems on this system. I should think that would be worth pursuing from your perspective.

If there is anything more I can do for you to help you resolve your bugs please let me know. Thank you.

**Comment by morpheus65535** [comment]
@minimeh dude, sorry I've made a type and you should have seen here that I can't reproduce the issue. Of course running from source is still supported and I've recommended to use the Windows Installer so you could see if the issue is present. My only objective is that your instance works so no need to get aggressive here.

To be totally honest, I don't understand what's causing your issue but of course not being able to reproduce it isn't helping. I've never said that what you provide wasn't accurate, it's just that the way CFFI is logging doesn't help me pin point the source of the issue.

BTW, no need to buy a new PC. You can achieve the same result by having a virtual machine on your actual PC. That's how I'm able to test multiple operating system.

P.S.: 95% is an actual fact based on the anonymous stats that we are collecting and are made public here: https://wiki.bazarr.media/bazarr-stats/

**Comment by minimeh** [comment]
> ...so no need to get aggressive here.

???
> BTW, no need to buy a new PC. You can achieve the same result by having a virtual machine on your actual PC. That's how I'm able to test multiple operating system.

If the core problem is hardware related, this buys nothing, does it? And meanwhile introducing new variables while not addressing the bug in bazarr as reported.

> P.S.: 95% is an actual fact based on the anonymous stats that we are collecting and are made public here: https://wiki.bazarr.media/bazarr-stats/

The anonymous stats collection is an option that not all users enable. So, still a guess at best I mean, it could be greater than 95% if all users were accounted for. I'm not convinced that 5% failure rate is a great metric anyway.

No aggression intended, just calling it as I see it.

**Comment by morpheus65535** [comment]
Dude, from what I see in the log, I can't fix your issue. No harm intended.

**Comment by minimeh** [comment]
Thanks for looking into it. The offer stands if there's anything I can do to help you track the bug down.
