### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by merc1031** [morpheus65535/bazarr#1543]
**Describe the bug**
Attempt to sync .ass file throws exception 

**To Reproduce**
Go to TV show
Go to episode with an .ass external sub file
select sync
Check off the .ass file and press the sync button, nothing seems to happen
Check the log.

**Screenshots**
![image](https://user-images.githubusercontent.com/311356/133174707-618765a0-4a7b-492c-8074-823894e856a9.png)
![image](https://user-images.githubusercontent.com/311356/133174829-41be3f19-085d-4ac4-9fb2-a0e3d83ecf88.png)

**Software (please complete the following information):**
Bazarr "linuxserver/bazarr:v0.9.9-ls127"
Sonarr  "linuxserver/sonarr:3.0.6.1265-ls118"
Docker version 1.13.0, build 49bf474
Ubuntu 12.04.4 LTS

```
bazarr:
  container_name: "bazarr"
  image: "linuxserver/bazarr:v0.9.9-ls127"
  ports:
   - "6767:6767"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /media/yggdrasil/files/config/.bazarr:/config
   - /media/yggdrasil/TV/:/tv
   - /media/yggdrasil/TV2/:/tv2
   - /media/yggdrasil/TV3/:/tv3
   - /media/yggdrasil/Movies/:/movies
  environment:
   - TZ=America/Los_Angeles
   - PGID=1000
   - PUID=1000
  restart: unless-stopped
```
**Additional context**
```
2021-09-13 17:13:27,553 - ffsubsync.ffsubsync              (7f237b954370) :  INFO (ffsubsync:153) - writing output to /tv/Bleach/Season.12/Bleach.-.S12E01.-.A213.-.The.Soul.Burial.Detective,.Karakuraizer.is.Born.HDTV-720p.x264 AAC[JA].BTN.synced.srt
2021-09-13 17:13:27,563 - ffsubsync.ffsubsync              (7f237b954370) :  ERROR (ffsubsync:161) - __init__() got an unexpected keyword argument 'text'
2021-09-13 17:13:27,563 - root                             (7f237b954370) :  ERROR (subsyncer:58) - BAZARR an exception occurs during the synchronization process for this subtitles: /tv/Bleach/Season.12/Bleach.-.S12E01.-.A213.-.The.Soul.Burial.Detective,.Karakuraizer.is.Born.HDTV-720p.x264 AAC[JA].BTN.ass
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/subsyncer.py", line 56, in sync
    result = run(self.args)
  File "/app/bazarr/bin/bazarr/../libs/ffsubsync/ffsubsync.py", line 338, in run
    sync_was_successful = try_sync(args, reference_pipe, result)
  File "/app/bazarr/bin/bazarr/../libs/ffsubsync/ffsubsync.py", line 167, in try_sync
    raise exc
  File "/app/bazarr/bin/bazarr/../libs/ffsubsync/ffsubsync.py", line 154, in try_sync
    out_subs.write_file(srtout)
  File "/app/bazarr/bin/bazarr/../libs/ffsubsync/generic_subtitles.py", line 148, in write_file
    to_write = srt.compose(subs)
  File "/app/bazarr/bin/bazarr/../libs/srt.py", line 446, in compose
    return "".join(subtitle.to_srt(strict=strict, eol=eol) for subtitle in subtitles)
  File "/app/bazarr/bin/bazarr/../libs/srt.py", line 446, in <genexpr>
    return "".join(subtitle.to_srt(strict=strict, eol=eol) for subtitle in subtitles)
  File "/app/bazarr/bin/bazarr/../libs/srt.py", line 275, in sort_and_reindex
    subtitle = Subtitle(**vars(subtitle))
TypeError: __init__() got an unexpected keyword argument 'text'
```

**Comment by morpheus65535** [comment]
Bazarr is only able to sync srt, not ass.

**Comment by merc1031** [comment]
Ah ok. Thanks (was just a weird error), rather than saying so.
Thanks again

**Comment by morpheus65535** [comment]
Yes I agree we should inform the users. Maybe add a better description of "how to reproduce" would help?

**Comment by merc1031** [comment]
I added a little more description. Thanks for the quick replies

**Comment by morpheus65535** [comment]
@LASER-Yi can we disable the sync menu item if there's subtitles with extension other than .srt selected in tools modal?

**Comment by LASER-Yi** [comment]
> @LASER-Yi can we disable the sync menu item if there's subtitles with extension other than .srt selected in tools modal?

Of course

**Comment by morpheus65535** [comment]
@LASER-Yi Thanks for your help!

@merc1031 This issue wont happen again once @LASER-Yi made the suggested change.

**Comment by merc1031** [comment]
Thanks all!
