### ISSUE TITLE
Bazarr unable to import existing subtitles

### ISSUE THREAD

**Issue by fabiorzfreitas** [morpheus65535/bazarr#1551]
**Describe the bug**
After selecting subtitle files to upload via Upload button, Bazarr never processes the files. Log says `Exception on /api/subtitles/info [GET]`

Additionally, log ends with `TypeError: Object of type Country is not JSON serializable`

**Expected behavior**
Bazarr post-processing the files uploaded

**Log**
<details>
    <summary>Traceback from Log section</summary>

```
Traceback (most recent call last):

  File "c:\\program files\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "c:\\program files\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "c:\\program files\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 458, in wrapper

    resp = resource(*args, **kwargs)

  File "c:\\program files\\bazarr\\bazarr\\../libs\\flask\\views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "c:\\program files\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 573, in dispatch_request

    resp = meth(*args, **kwargs)

  File "c:\\program files\\bazarr\\bazarr\\api.py", line 77, in wrapper

    return actual_method(*args, **kwargs)

  File "c:\\program files\\bazarr\\bazarr\\api.py", line 2028, in get

    return jsonify(data=results)

  File "c:\\program files\\bazarr\\bazarr\\../libs\\flask\\json\\__init__.py", line 370, in jsonify

    dumps(data, indent=indent, separators=separators) + "\

",

  File "c:\\program files\\bazarr\\bazarr\\../libs\\flask\\json\\__init__.py", line 211, in dumps

    rv = _json.dumps(obj, **kwargs)

  File "C:\\Program Files\\Bazarr\\WinPython\\python-3.8.0\\lib\\json\\__init__.py", line 234, in dumps

    return cls(

  File "C:\\Program Files\\Bazarr\\WinPython\\python-3.8.0\\lib\\json\\encoder.py", line 201, in encode

    chunks = list(chunks)

  File "C:\\Program Files\\Bazarr\\WinPython\\python-3.8.0\\lib\\json\\encoder.py", line 431, in _iterencode

    yield from _iterencode_dict(o, _current_indent_level)

  File "C:\\Program Files\\Bazarr\\WinPython\\python-3.8.0\\lib\\json\\encoder.py", line 405, in _iterencode_dict

    yield from chunks

  File "C:\\Program Files\\Bazarr\\WinPython\\python-3.8.0\\lib\\json\\encoder.py", line 325, in _iterencode_list

    yield from chunks

  File "C:\\Program Files\\Bazarr\\WinPython\\python-3.8.0\\lib\\json\\encoder.py", line 405, in _iterencode_dict

    yield from chunks

  File "C:\\Program Files\\Bazarr\\WinPython\\python-3.8.0\\lib\\json\\encoder.py", line 438, in _iterencode

    o = _default(o)

  File "c:\\program files\\bazarr\\bazarr\\../libs\\flask\\json\\__init__.py", line 100, in default

    return _json.JSONEncoder.default(self, o)

  File "C:\\Program Files\\Bazarr\\WinPython\\python-3.8.0\\lib\\json\\encoder.py", line 179, in default

    raise TypeError(f\'Object of type {o.__class__.__name__} \'

TypeError: Object of type Country is not JSON serializable
```
</details>

**Software**
- Bazarr Version: 0.9.9
- Sonarr Version: 3.0.6.1266
- Radarr Version: 3.2.2.5080
- Operating System: Windows-10-10.0.19041-SP0
- Python Version: 3.8.0

**Additional context**
Might be the same issue from #1182

**Comment by morpheus65535** [comment]
@LASER-Yi can you take a look at this one please? I'm not familiar with the modifications you've made to the upload process.

**Comment by LASER-Yi** [comment]
> @LASER-Yi can you take a look at this one please? I'm not familiar with the modifications you've made to the upload process.

Of course :)

**Comment by LASER-Yi** [comment]
Can you give me the file name you want to upload to bazarr? Just file name should be enough

**Comment by fabiorzfreitas** [comment]
Sure: `The.Office.US.S02E01.The.Dundies.WEBRip.x264-FGT.srt`

**Comment by LASER-Yi** [comment]
Should be fixed in the next upcoming beta version
