### ISSUE TITLE
When [English] is at the start of the filename when importing bazarr gets stuck

### ISSUE THREAD

**Issue by Dnkhatri** [morpheus65535/bazarr#1553]
When [English] is at the start of the filename when importing bazarr gets stuck. This is the stack trace error. Filename example

[English] Sweet Sweet episode 7 - 1186751v [DownSub.com].srt

```
Traceback (most recent call last):

  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper

    resp = resource(*args, **kwargs)

  File "/opt/bazarr/bazarr/../libs/flask/views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request

    resp = meth(*args, **kwargs)

  File "/opt/bazarr/bazarr/api.py", line 77, in wrapper

    return actual_method(*args, **kwargs)

  File "/opt/bazarr/bazarr/api.py", line 2028, in get

    return jsonify(data=results)

  File "/opt/bazarr/bazarr/../libs/flask/json/__init__.py", line 370, in jsonify

    dumps(data, indent=indent, separators=separators) + "\

",

  File "/opt/bazarr/bazarr/../libs/flask/json/__init__.py", line 211, in dumps

    rv = _json.dumps(obj, **kwargs)

  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 385, in dumps

    return cls(

  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 298, in encode

    chunks = list(chunks)

  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 696, in _iterencode

    for chunk in _iterencode_dict(o, _current_indent_level):

  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 652, in _iterencode_dict

    for chunk in chunks:

  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 531, in _iterencode_list

    for chunk in chunks:

  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 652, in _iterencode_dict

    for chunk in chunks:

  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 716, in _iterencode

    o = _default(o)

  File "/opt/bazarr/bazarr/../libs/flask/json/__init__.py", line 100, in default

    return _json.JSONEncoder.default(self, o)

  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 272, in default

    raise TypeError(\'Object of type %s is not JSON serializable\' %

TypeError: Object of type Language is not JSON serializable
```

**Comment by morpheus65535** [comment]
Duplicate #1551
