### ISSUE TITLE
Provider Titrari HTTPError

### ISSUE THREAD

**Issue by bogdan-mihalcea** [morpheus65535/bazarr#1564]
**Describe the bug**
Don't really know when the issue started. but seems to not work at the moment. I believe they changed the name for their advanced search page, which I think now it is "cautarepreaavansata". Also, just changing the url seems to not find any subtitles, it may need more modifications to the url structure to work. From a quick glance on their website, a typical url looks like this: "https://www.titrari.ro/index.php?page=cautarepreaavansata&z8=1&z5=0870154&subtitrare=Jungle+Cruise+%282012%29" which actually uses IMDBid as a filter. Might be talking nonsense but worth talking a look.

**Software (please complete the following information):**

Bazarr Version: 0.9.9
Sonarr Version: 3.0.6.1265
Operating System: Linux-5.11.0-37-generic-x86_64-with

**Additional context**

30/09/2021 03:34:14|INFO    |root                            |Throttling titrari for 10 minutes, until 21/09/30 03:44, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: https://www.titrari.ro/?page=cautarenedevansata&z8=1&z7=chapter+seventy+seven+climax'|
30/09/2021 03:57:35|DEBUG   |urllib3.connectionpool          |https://www.titrari.ro:443 "GET /?page=cautarenedevansata&z8=1&z7=chapter+seventy+seven+climax HTTP/1.1" 200 None|
30/09/2021 03:57:35|DEBUG   |subliminal_patch.providers.titrari|[#### Provider: titrari.ro] Sorting by download count...|
3

**Comment by bogdan-mihalcea** [comment]
Hi, just updated to the beta and while the url scheme is working now, the search function won't work. Have a look: https://www.titrari.ro/?page=cautarepreaavansata&z8=1&z7=chapter+ninety+four+next+to+normal , I think they switched their advanced search to be based on the IMDBid. For example, riverdale would be https://www.titrari.ro/index.php?page=cautarepreaavansata&z8=-1&z5=5420376 from what I can see. Sorry for opening the issue again.

**Comment by Znuff** [comment]
I've patched [`titrari.py`](https://github.com/morpheus65535/bazarr/blob/development/libs/subliminal_patch/providers/titrari.py) locally and I'm still encountering issues somehow. I've also documented the parameters to best of my abilities and made sure to include all the parameters that are made by a legit user:

```python
    # titrari.ro seems to require all parameters now
    #  z2 = comment (empty)
    #  z3 = fps (-1: any, 0: N/A, 1: 23.97 FPS etc.)
    #  z4 = CD count (-1: any)
    #  z5 = imdb_id (empty or integer)
    #  z6 = sort order (0: unsorted, 1: by date, 2: by name)
    #  z7 = title (empty or string)
    #  z8 = language (-1: all, 1: ron, 2: eng)
    #  z9 = genre (All: all, Action: action etc.)
    # z11 = type (0: any, 1: movie, 2: series)
    def getQueryParams(self, imdb_id, title):
        queryParams = {
            'page': self.query_advanced_search,
            'z7': '',
            'z2': '',
            'z5': '',
            'z3': '-1',
            'z4': '-1',
            'z8': '-1',
            'z9': 'All',
            'z11': '0',
            'z6': '0'
        }
        if imdb_id is not None:
            queryParams["z5"] = imdb_id
        elif title is not None:
            queryParams["z7"] = title

        return queryParams
```

This will seem to work:

```
09/10/2021 03:32:25|INFO    |subliminal_patch.core           |Listing subtitles with provider 'titrari' and languages {<Language [ro]>}|
09/10/2021 03:32:25|INFO    |subliminal_patch.core           |Initializing provider titrari|
09/10/2021 03:32:25|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.titrari.ro:443|
09/10/2021 03:32:26|DEBUG   |urllib3.connectionpool          |https://www.titrari.ro:443 "GET /?page=cautarepreaavansata&z7=&z2=&z5=11284502&z3=-1&z4=-1&z8=-1&z9=All&z11=0&z6=0 HTTP/1.1" 200 None|
09/10/2021 03:32:26|DEBUG   |subliminal_patch.providers.titrari|[#### Provider: titrari.ro] Sorting by download count...|
```

Then not even a minute later, it fails spectacularly with a `404`:

```
09/10/2021 03:32:42|INFO    |subliminal_patch.core           |Listing subtitles with provider 'titrari' and languages {<Language [en]>}|
09/10/2021 03:32:42|INFO    |subliminal_patch.core           |Initializing provider titrari|
09/10/2021 03:32:42|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.titrari.ro:443|
09/10/2021 03:32:43|DEBUG   |urllib3.connectionpool          |https://www.titrari.ro:443 "GET /?page=cautarepreaavansata&z7=&z2=&z5=12982370&z3=-1&z4=-1&z8=-1&z9=All&z11=0&z6=0 HTTP/1.1" 404 None|
09/10/2021 03:32:43|ERROR   |subliminal_patch.core           |Unexpected error in provider 'titrari': Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch
/providers/titrari.py", line 226, in list_subtitles    self.query(languages, title, imdb_id, video)]  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titrari.py", line 118, in query    search_response.raise_for_status()  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 943, in raise_for_status    raise HTTPError(http_error_msg, res
ponse=self)requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.titrari.ro/?page=cautarepreaavansata&z7=&z2=&z5=12982370&z3=-1&z4=-1&z8=-1&z9=All&z11=0&z6=0|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider    results = self[provider].list_subtitles
(video, provider_languages)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titrari.py", line 226, in list_subtitles    self.query(languages, title, imdb_id, video)]  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titrari.py", line 118, in query    search_response.raise_for_status()  File "/app/bazarr/bin/bazarr/../libs/request
s/models.py", line 943, in raise_for_status    raise HTTPError(http_error_msg, response=self)requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.titrari.ro/?page=cautarepreaavansata&z7=&z2=&z5=12982370&z3=-1&z4=-1&z8=-1&z9=All&z11=0&z6=0|
09/10/2021 03:32:43|INFO    |root                            |Throttling titrari for 10 minutes, until 21/10/09 03:42, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: https://www.titrari.ro/?page=cautarepreaavansata&z7=&z2=&z5=12982370&z3=-1&z4=-1&z8=-1&z9=All&z11=0&z6=0'|
```

I legit don't understand why it would get a 404, as I can't replicate it either via `curl` or via browser. All URLs work fine and the status is `200`.

**Comment by Znuff** [comment]
Should be fixed by #1573
