### ISSUE TITLE
Proxy ignored addresses list is ignored

### ISSUE THREAD

**Issue by woopla** [morpheus65535/bazarr#1566]
**Describe the bug**
Hosts in the exclude list for the proxy are still contacted through the proxy.

**To Reproduce**
1. Add either a FQDN or wildcard host  in the Proxy section and click on save
2. Check that the config file is updated as expected
3. Go to the Radarr or Sonarr config section, enter the proper information (hostname and port)
4. Click on test
5. Bazarr is trying to connect through the proxy as shown by the error message and the proxy logs

**Expected behavior**
Bazarr connects to the host directly

**Software (please complete the following information):**
 - Bazarr: v0.9.9 through the LSIO Docker image v0.9.9-ls129
 - Radarr version: LSIO Docker image 3.2.2.5080-ls11
 - Sonarr version: LSIO Docker image 3.0.6.1342-ls124
 - OS: Debian 10 (Proxmox VE)

**Comment by morpheus65535** [comment]
No logs, no screenshot, nothing... how can I help?

**Comment by woopla** [comment]
Hey @morpheus65535, sorry there's not a lot more I can give you. Here's what the log says:
```
2021-10-01 14:32:50,535 - urllib3.connectionpool           (7f6493fba480) :  DEBUG (connectionpool:814) - Starting new HTTPS connection (1): movies.orb.<redacted>.net:443
```

I had to use the browser's dev tools to be able to copy the contents of the error bar that shows up when clicking _test_. Here goes:
`ProxyError(MaxRetryError("HTTPSConnectionPool(host='movies.orb.<redacted>.net', port=443): Max retries exceeded with url: /api/v3/system/status?apikey=<redacted> (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Privoxy Error')))"))`

Here are the relevant parts of `config.ini`:
```
[proxy]
type = http
url = docker.orb.<redacted>.net
port = 8118
username =
password =
exclude = ['localhost', '127.0.0.1', '*.orb.<redacted>.net']
```

Here's confirmation that Bazarr is trying to connect through the proxy - these are the Privoxy logs:
```
2021-10-01 14:44:03.443 7f1b83545b20 Info: Can not resolve movies.orb.<redacted>.net: Name does not resolve,
2021-10-01 14:44:03.737 7f1b83568b20 Info: Can not resolve tvseries.orb.<redacted>.net: Name does not resolve
```

I'm sure the setup otherwise works, since Radarr and Sonarr are using the same proxy with similar exclusions for `*.orb.<redacted>.net`

**Comment by morpheus65535** [comment]
Just to be sure, I understand that the test button for both Sonarr and Radarr doesn't works but if you save settings and force the sync with Sonarr/Radarr in System-->Tasks, does it works?

**Comment by woopla** [comment]
No it still won't work. Here's the stacktrace from the logs:
```python
Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 597, in urlopen

    self._prepare_proxy(conn)

  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 807, in _prepare_proxy

    conn.connect()

  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 324, in connect

    self._tunnel()

  File "/usr/lib/python3.8/http/client.py", line 901, in _tunnel

    raise OSError("Tunnel connection failed: %d %s" % (code,

OSError: Tunnel connection failed: 500 Internal Privoxy Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 640, in urlopen

    retries = retries.increment(method, url, error=e, _pool=self,

  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 399, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'tvseries.orb.<redacted>.net\', port=443): Max retries exceeded with url: /api/v3/series/?apikey=(removed) (Caused by ProxyError(\'Cannot connect to proxy.\', OSError(\'Tunnel connection failed: 500 Internal Privoxy Error\')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/get_series.py", line 329, in get_series_from_sonarr_api

    r = requests.get(url_sonarr_api_series, timeout=60, verify=False, headers=headers)

  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 76, in get

    return request(\'get\', url, params=params, **kwargs)

  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 61, in request

    return session.request(method=method, url=url, **kwargs)

  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 510, in send

    raise ProxyError(e, request=request)

requests.exceptions.ProxyError: HTTPSConnectionPool(host=\'tvseries.orb.<redacted>.net\', port=443): Max retries exceeded with url: /api/v3/series/?apikey=(removed) (Caused by ProxyError(\'Cannot connect to proxy.\', OSError(\'Tunnel connection failed: 500 Internal Privoxy Error\')))
```

Actually, if you can point me to the Bazarr source file that deals with proxy handling I can take a look at it.

**Comment by morpheus65535** [comment]
You can try to contact Sonarr/Radarr directly without going through a reverse proxy (any this could cause so many issue with websocket...).

Here's the code that deals with proxy environment variables: https://github.com/morpheus65535/bazarr/blob/ac2052f43d7e53a3bf073849e006c780a344bdbd/bazarr/config.py#L585-L595
