### ISSUE TITLE
new install in windows 10 localhost:6767 not working

### ISSUE THREAD

**Issue by turki123456789** [morpheus65535/bazarr#1568]
**Describe the bug**
Bazarr is running in windows service but i cannot open localhost:6767 (this page cannot be reach) 
it was working befoer
i am using caddy reverse proxy for sonarr and radarr

**To Reproduce**
1. install bazarr.exe
2. open the bazarr shortcut
3. this page cannot be reach

**Software (please complete the following information):**
 - Bazarr: [v0.9.9]
 - Radarr version [3.2.2.5080]
 - Sonarr version [3.0.6.1342]
 - OS: [ Windows 10.0.19043 Build 19043]

log 
```
03/10/2021 22:28:46|ERROR   |root                            |BAZARR unable to download unrar.exe to C:\Bazarr\bin\Windows\i386\unrar|

'Traceback (most recent call last):
  File "c:\\bazarr\\bazarr\\../libs\\urllib3\\connectionpool.py", line 600, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "c:\\bazarr\\bazarr\\../libs\\urllib3\\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "c:\\bazarr\\bazarr\\../libs\\urllib3\\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "c:\\bazarr\\bazarr\\../libs\\urllib3\\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "c:\\bazarr\\bazarr\\../libs\\urllib3\\util\\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Roaming\\Python\\Python38\\site-packages\\gevent\\_ssl3.py", line 114, in wrap_socket
    return self.sslsocket_class(
  File "C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Roaming\\Python\\Python38\\site-packages\\gevent\\_ssl3.py", line 312, in __init__
    raise x
  File "C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Roaming\\Python\\Python38\\site-packages\\gevent\\_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Roaming\\Python\\Python38\\site-packages\\gevent\\_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()\nssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):
  File "c:\\bazarr\\bazarr\\../libs\\requests\\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\\bazarr\\bazarr\\../libs\\urllib3\\connectionpool.py", line 640, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "c:\\bazarr\\bazarr\\../libs\\urllib3\\util\\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'github.com\', port=443): Max retries exceeded with url: /morpheus65535/bazarr-binaries/raw/master/bin/Windows/i386/unrar/UnRAR.exe (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)\')))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):
  File "c:\\bazarr\\bazarr\\utils.py", line 186, in get_binary
    r = requests.get(binary[\'url\'])
  File "c:\\bazarr\\bazarr\\../libs\\requests\\api.py", line 76, in get
    return request(\'get\', url, params=params, **kwargs)
  File "c:\\bazarr\\bazarr\\../libs\\requests\\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\\bazarr\\bazarr\\../libs\\requests\\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\\bazarr\\bazarr\\../libs\\requests\\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\\bazarr\\bazarr\\../libs\\requests\\adapters.py", line 514, in send
    raise SSLError(e, request=request)\nrequests.exceptions.SSLError: HTTPSConnectionPool(host=\'github.com\', port=443): Max retries exceeded with url: /morpheus65535/bazarr-binaries/raw/master/bin/Windows/i386/unrar/UnRAR.exe (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)\')))'|
```

**Comment by morpheus65535** [comment]
You're probably using something like PiHole that is messing with github SSL certificate along the way. It's totally unrelated to Bazarr:

`requests.exceptions.SSLError: HTTPSConnectionPool(host=\'github.com\', port=443): Max retries exceeded with url: /morpheus65535/bazarr-binaries/raw/master/bin/Windows/i386/unrar/UnRAR.exe (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain`
