### ISSUE TITLE
Error when running after install

### ISSUE THREAD

**Issue by RimfireFoShizzle** [morpheus65535/bazarr#157]
I installed bazarr following the instructions in the wiki.
However, when I try to run it, I get the following error:

```
D:\Program Files\Bazarr\bazarr>python bazarr.py
Traceback (most recent call last):
  File "bazarr.py", line 6, in <module>
    from get_argv import config_dir, no_update
  File "D:\Program Files\Bazarr\bazarr\get_argv.py", line 11
    print 'bazarr.py -h --no-update --config <config_directory>'
                                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int 'bazarr.py -h --no-update --config <config_directory>')?
```

Any idea what's causing this?

**Comment by halali** [comment]
Bazarr not support python 3.x
Use python 2.7.15
