### ISSUE TITLE
Fresh install: Error 500 when trying to access bazarr webapp at http://myip:6767

### ISSUE THREAD

**Issue by LechuckThePirate** [morpheus65535/bazarr#1583]
**Describe the bug**
I get this error after a fresh install of Bazarr trying to access for the first time at http://myraspberryip:6767

**To Reproduce**
From console:
```
cd /opt
sudo apt-get install python3 idle3
sudo apt-get install git python3-pip python3-distutils
sudo apt-get install libxml2-dev libxslt1-dev python3-libxml2 python3-lxml unrar-free ffmpeg libatlas-base-dev
sudo git clone https://github.com/morpheus65535/bazarr.git /opt/bazarr
cd /opt/bazarr/
python3 -m pip install -r requirements.txt
sudo chown -R pi:pi /opt/bazarr/
python3 bazarr.py
```

No errors are thrown thoughout all the process...
The output of bazarr is the following:

```
Bazarr starting...
2021-10-16 14:11:19,653 - root                             (b65e9210) :  INFO (driver:121) - Generating grammar tables from /usr/lib/python3.7/lib2to3/Grammar.txt
2021-10-16 14:11:19,723 - root                             (b65e9210) :  INFO (driver:121) - Generating grammar tables from /usr/lib/python3.7/lib2to3/PatternGrammar.txt
2021-10-16 14:11:21,250 - root                             (b65e9210) :  INFO (server:39) - BAZARR is started and waiting for request on http://0.0.0.0:6767

```

I open the browser in my computer, and I try to navigate to http://192.168.1.100:6767 and I get the error

_Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application._

in the console I see this 2 lines appear:

```
2021-10-16 14:11:55,009 - app                              (aeeb26f0) :  ERROR (app:1891) - Exception on / [GET]
2021-10-16 14:11:55,153 - app                              (aeeb26f0) :  ERROR (app:1891) - Exception on /favicon.ico [GET]

```

And this is the content of my /opt/bazarr/data/log/bazarr.log
```
16/10/2021 14:11:19|INFO    |root                            |Generating grammar tables from /usr/lib/python3.7/lib2to3/Grammar.txt|
16/10/2021 14:11:19|INFO    |root                            |Generating grammar tables from /usr/lib/python3.7/lib2to3/PatternGrammar.txt|
16/10/2021 14:11:21|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
16/10/2021 14:11:55|ERROR   |app                             |Exception on / [GET]|'Traceback (most recent call last):\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/opt/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise\n    raise value\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "bazarr/main.py", line 119, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 138, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 869, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 830, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 804, in _load_template\n    template = self.loader.load(self, name, globals)\n  File "/opt/bazarr/bazarr/../libs/jinja2/loaders.py", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 60, in get_source\n    return self._get_source_fast(environment, template)\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 89, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|

```

**Software (please complete the following information):**
 - Bazarr: Latest master from github
 - Radarr version: 0.2.0.1120
 - Sonarr version: 3.0.6.1265
 - OS: Raspbian GNU/Linux 10 (buster)

Attached the log file
[bazarr.log](https://github.com/morpheus65535/bazarr/files/7357532/bazarr.log)

**Comment by seekr** [comment]
@morpheus65535 following the guide tell us to download a bazarr.zip that does not include the requirements.txt. The repo does. maybe the guide needs updating?

**Comment by morpheus65535** [comment]
@seekr I don't know what guide you are refering to but the one I linked in my previous post have a link to download latest bazarr.zip release asset that include this:
![image](https://user-images.githubusercontent.com/5130500/150248455-8a8df5c9-546b-484b-ae0d-57130375da21.png)
There's nothing missing there to run Bazarr successfully.

**Comment by kidstretch** [comment]
> @seekr I don't know what guide you are refering to but the one I linked in my previous post have a link to download latest bazarr.zip release asset that include this: ![image](https://user-images.githubusercontent.com/5130500/150248455-8a8df5c9-546b-484b-ae0d-57130375da21.png) There's nothing missing there to run Bazarr successfully.

Hello, i tried many times to install bazarr, even with bazar.py, no luck.
Is there any guide to successfully install bazarr on a reaspberry pi 4?
I'm fairly new to this, so any guided steps would be great!

**Comment by morpheus65535** [comment]
> Is there any guide to successfully install bazarr on a reaspberry pi 4?

https://wiki.bazarr.media/
