### ISSUE TITLE
OpenSubtitles.com doesn't work in cases of missing titles

### ISSUE THREAD

**Issue by GuyKh** [morpheus65535/bazarr#1602]
**Describe the bug**

**To Reproduce**
1. Define OpenSubtitles(.com) provider with your credentials
2. Search manually for subtitles for non-existing subs
3. Check logs

**Expected behavior**
All works great and search works

**Logs**
```
AttributeError. Exception info: "'NoneType' object has no attribute 'lower'"
```

**Software (please complete the following information):**
 - Bazarr: 1.0.0
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1342
 - OS: Docker under Ubuntu 20.10 -- Linux-5.13.0-20-generic-x86_64-with

**Additional context**
```
2021-11-03 13:30:02,024 - subliminal_patch.core            (7fe1b50679d0) :  INFO (core:166) - Listing subtitles with provider 'opensubtitlescom' and languages {<Language [he]>}
2021-11-03 13:30:02,025 - subliminal_patch.core            (7fe1b50679d0) :  INFO (core:103) - Initializing provider opensubtitlescom
2021-11-03 13:30:02,027 - root                             (7fe1b50679d0) :  DEBUG (opensubtitlescom:249) - Searching using this hash: 224eb401dfd0f9ca15
2021-11-03 13:30:02,028 - dogpile.lock                     (7fe1b50679d0) :  DEBUG (lock:89) - NeedRegenerationException
2021-11-03 13:30:02,028 - dogpile.lock                     (7fe1b50679d0) :  DEBUG (lock:131) - no value, waiting for create lock
2021-11-03 13:30:02,029 - dogpile.lock                     (7fe1b50679d0) :  DEBUG (lock:135) - value creation lock <dogpile.cache.region.CacheRegion._LockWrapper object at 0x7fe1b43cdc40> acquired
2021-11-03 13:30:02,030 - dogpile.lock                     (7fe1b50679d0) :  DEBUG (lock:174) - Calling creation function for not-yet-present value
2021-11-03 13:30:02,031 - root                             (7fe1b50679d0) :  DEBUG (opensubtitlescom:202) - Searching using this IMDB id: 12851524
2021-11-03 13:30:02,039 - urllib3.connectionpool           (7fe1b50679d0) :  DEBUG (connectionpool:814) - Starting new HTTPS connection (1): api.opensubtitles.com:443
2021-11-03 13:30:02,348 - urllib3.connectionpool           (7fe1b50679d0) :  DEBUG (connectionpool:394) - https://api.opensubtitles.com:443 "GET /api/v1/features?imdb_id=12851524 HTTP/1.1" 200 1911
2021-11-03 13:30:02,349 - subliminal_patch.providers.opensubtitlescom (7fe1b50679d0) :  DEBUG (opensubtitlescom:243) - No match found for Only Murders in the Building
2021-11-03 13:30:02,350 - dogpile.lock                     (7fe1b50679d0) :  DEBUG (lock:183) - Released creation lock
2021-11-03 13:30:02,350 - subliminal_patch.core            (7fe1b50679d0) :  ERROR (core:199) - Unexpected error in provider 'opensubtitlescom': Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 349, in list_subtitles
    return self.query(languages, video)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 258, in query
    title_id = self.search_titles(title)
  File "</app/bazarr/bin/bazarr/../libs/decorator.py:decorator-gen-15>", line 2, in search_titles
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 1271, in get_or_create_for_user_func
    return self.get_or_create(key, user_func, timeout,
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 874, in get_or_create
    with Lock(
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 93, in _enter
    generated = self._enter_create(value, createdtime)
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 179, in _enter_create
    return self.creator()
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 839, in gen_value
    created_value = creator(*creator_args[0], **creator_args[1])
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 233, in search_titles
    if fix_tv_naming(title).lower() == result['attributes']['title'].lower() and \
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 349, in list_subtitles
    return self.query(languages, video)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 258, in query
    title_id = self.search_titles(title)
  File "</app/bazarr/bin/bazarr/../libs/decorator.py:decorator-gen-15>", line 2, in search_titles
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 1271, in get_or_create_for_user_func
    return self.get_or_create(key, user_func, timeout,
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 874, in get_or_create
    with Lock(
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 93, in _enter
    generated = self._enter_create(value, createdtime)
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 179, in _enter_create
    return self.creator()
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 839, in gen_value
    created_value = creator(*creator_args[0], **creator_args[1])
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 233, in search_titles
    if fix_tv_naming(title).lower() == result['attributes']['title'].lower() and \
AttributeError: 'NoneType' object has no attribute 'lower'
2021-11-03 13:30:02,351 - root                             (7fe1b50679d0) :  INFO (get_providers:227) - Throttling opensubtitlescom for 10 minutes, until 21/11/03 13:40, because of: AttributeError. Exception info: "'NoneType' object has no attribute 'lower'"
2021-11-03 13:30:02,352 - socketio.server                  (7fe1b50679d0) :  INFO (server:291) - emitting event "data" to all [/]
2021-11-03 13:30:02,353 - subliminal_patch.core            (7fe1b50679d0) :  INFO (core:232) - Discarding provider opensubtitlescom
2021-11-03 13:30:02,353 - subliminal_patch.core            (7fe1b50679d0) :  INFO (core:166) - Listing subtitles with provider 'opensubtitles' and languages {<Language [he]>, <Language [he]>}
```

**Comment by morpheus65535** [comment]
We already use an API key for os.com and it's defined here:
https://github.com/morpheus65535/bazarr/blob/master/bazarr/get_providers.py#L142-L146

**Comment by GuyKh** [comment]
I guess it's an OS.com issue, but this call (replicated from the Provider):
```
curl --location --request POST 'https://api.opensubtitles.com/api/v1/login' \
--header 'Api-Key: s38zmzVlW7IlYruWi7mHwDYl2SfMQoC1' \
--header 'Content-Type: application/json' \
--data-raw '{ "username": "myUserName", "password": "bigBlackPass" }'
```

the result I'm getting back is:
```
{
    "message": "Missing username and password",
    "status": 401
}
```

**Comment by morpheus65535** [comment]
I have bring tht issue back to their Slack channel. Waiting on them to fix it.

**Comment by GuyKh** [comment]
Thanks!

**Comment by morpheus65535** [comment]
This should work:
```
curl --request POST \
  --url https://api.opensubtitles.com/api/v1/login \
  --header 'Api-Key: s38zmzVlW7IlYruWi7mHwDYl2SfMQoC1' \
  --header 'Content-Type: application/json' \
  --data '{
	"username": "user",
	"password": "password"
}'
```

**Comment by GuyKh** [comment]
It still doesn't -- throws this error (verified the correct user/pass against the login to the site).

```
{
    "message": "Error, invalid username/password",
    "status": 401
}
```

**Comment by morpheus65535** [comment]
It could be some strange characters in your password maybe... it works fine for me:
```
{
  "user": {
    "allowed_downloads": 20,
    "level": "Sub leecher",
    "user_id": 186673,
    "ext_installed": false,
    "vip": false
  },
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1S2tyWGl0NXh2c0kyNThOYWNLSEdscXQyUGlMMGVlQSIsImV4cCI6MTYzNSk2MzE1MX0.4Kzwv-jwuo7kch4fGOcTyC-w9-MOcVt06FSFXPCUPvs",
  "status": 200
}
```

You can try with a simpler password.

**Comment by GuyKh** [comment]
Yes, I changed the password and low and behold, it works.
I guess that something in the import or anything in the process caused it.

Thanks for your help

**Comment by GuyKh** [comment]
After updating the password -- i'm getting now:
```
2021-11-03 13:30:02,350 - subliminal_patch.core            (7fe1b50679d0) :  ERROR (core:199) - Unexpected error in provider 'opensubtitlescom': Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 349, in list_subtitles
    return self.query(languages, video)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 258, in query
    title_id = self.search_titles(title)
  File "</app/bazarr/bin/bazarr/../libs/decorator.py:decorator-gen-15>", line 2, in search_titles
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 1271, in get_or_create_for_user_func
    return self.get_or_create(key, user_func, timeout,
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 874, in get_or_create
    with Lock(
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 93, in _enter
    generated = self._enter_create(value, createdtime)
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 179, in _enter_create
    return self.creator()
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 839, in gen_value
    created_value = creator(*creator_args[0], **creator_args[1])
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 233, in search_titles
    if fix_tv_naming(title).lower() == result['attributes']['title'].lower() and \
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 349, in list_subtitles
    return self.query(languages, video)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 258, in query
    title_id = self.search_titles(title)
  File "</app/bazarr/bin/bazarr/../libs/decorator.py:decorator-gen-15>", line 2, in search_titles
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 1271, in get_or_create_for_user_func
    return self.get_or_create(key, user_func, timeout,
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 874, in get_or_create
    with Lock(
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 93, in _enter
    generated = self._enter_create(value, createdtime)
  File "/app/bazarr/bin/bazarr/../libs/dogpile/lock.py", line 179, in _enter_create
    return self.creator()
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 839, in gen_value
    created_value = creator(*creator_args[0], **creator_args[1])
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 233, in search_titles
    if fix_tv_naming(title).lower() == result['attributes']['title'].lower() and \
AttributeError: 'NoneType' object has no attribute 'lower'
```


This looks like an actual issues.
Note that the result is not found when doing this manually

**Comment by morpheus65535** [comment]
Can you provide a longer part of your debug where I can see the call made to os.com API and try to reproduce it?

**Comment by morpheus65535** [comment]
They are having major issues right now. I'm waiting for feedback from them. Their API is quite unstable for now.

**Comment by GuyKh** [comment]
Updated the main ticket

**Comment by morpheus65535** [comment]
Should be better in upcoming beta. Can you test and confirm please?

**Comment by GuyKh** [comment]
Looks great in beta.11

```
2021-11-05 10:29:58,302 - subliminal_patch.core            (7f1476a75b38) :  INFO (core:166) - Listing subtitles with provider 'opensubtitlescom' and languages {<Language [he]>}
2021-11-05 10:29:58,303 - subliminal_patch.core            (7f1476a75b38) :  INFO (core:103) - Initializing provider opensubtitlescom
2021-11-05 10:29:58,304 - root                             (7f1476a75b38) :  DEBUG (opensubtitlescom:248) - Searching using this hash: <built-in function hash>
2021-11-05 10:29:58,305 - root                             (7f1476a75b38) :  DEBUG (opensubtitlescom:280) - Searching for this languages: ['he']
2021-11-05 10:29:58,315 - urllib3.connectionpool           (7f1476a75b38) :  DEBUG (connectionpool:814) - Starting new HTTPS connection (1): api.opensubtitles.com:443
2021-11-05 10:29:58,568 - urllib3.connectionpool           (7f1476a75b38) :  DEBUG (connectionpool:394) - https://api.opensubtitles.com:443 "GET /api/v1/subtitles?episode_number=1&foreign_parts_only=exclude&languages=he&moviehash=214eb4dfd0f9ca15&imdb_id=12851524&season_number=1&query=Only.Murders.in.the.Building.S01E01.True.Crime.2160p.HULU.WEB-DL.DDP5.1.DV.HEVC-FLUX.mkv HTTP/1.1" 301 0
2021-11-05 10:29:58,658 - urllib3.connectionpool           (7f1476a75b38) :  DEBUG (connectionpool:394) - https://api.opensubtitles.com:443 "GET /api/v1/subtitles?episode_number=1&foreign_parts_only=exclude&imdb_id=12851524&languages=he&moviehash=214eb4dfd0f9ca15&query=only.murders.in.the.building.s01e01.true.crime.2160p.hulu.web-dl.ddp5.1.dv.hevc-flux.mkv&season_number=1 HTTP/1.1" 200 52
2021-11-05 10:29:58,662 - root                             (7f1476a75b38) :  DEBUG (opensubtitlescom:317) - Query returned 0 subtitles
```

**Comment by morpheus65535** [comment]
Thanks for the confirmation!
