### ISSUE TITLE
Exception while serving /bazarr/api/socket.io/	

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1613]
**Describe the bug**
The following message appears in the logs: "Exception while serving /bazarr/api/socket.io/"

**Screenshots**
<img width="767" alt="Screen Shot 2021-11-20 at 14 42 03" src="https://user-images.githubusercontent.com/19681420/142728534-d955da0f-e2c3-4031-aa8c-edbcdcf26728.png">

**Software (please complete the following information):**
Bazarr Version 1.0.1
Sonarr Version 3.0.6.1342
Radarr Version 3.2.2.5080
Operating System Linux-4.19.0-0.bpo.17-amd64-x86_64-with
Python Version 3.9.5
Bazarr Directory /app/bazarr/bin
Bazarr Config Directory /config

**Additional context**

**Comment by morpheus65535** [comment]
This one can be ignored. It's just a disconnected socket io connection issue. I'll try ro mute it.

**Comment by anonyme123** [comment]
Ok thanks for the reply! :)

**Comment by anonyme123** [comment]
This error seems to be appearing _more_ following v1.0.2 release.

```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/waitress/channel.py", line 397, in service
    task.service()
  File "/app/bazarr/bin/bazarr/../libs/waitress/task.py", line 168, in service
    self.execute()
  File "/app/bazarr/bin/bazarr/../libs/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/app/bazarr/bin/bazarr/../libs/flask_socketio/__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/app/bazarr/bin/bazarr/../libs/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/app/bazarr/bin/bazarr/../libs/socketio/server.py", line 571, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/app/bazarr/bin/bazarr/../libs/engineio/server.py", line 429, in handle_request
    socket = self._get_socket(sid)
  File "/app/bazarr/bin/bazarr/../libs/engineio/server.py", line 638, in _get_socket
    raise KeyError(\'Session is disconnected\')
KeyError: \'Session is disconnected\
```

<img width="1440" alt="Screen Shot 2022-01-03 at 19 21 53" src="https://user-images.githubusercontent.com/19681420/147965483-0f5dd180-8608-46e2-815c-65b359068630.png">

**Comment by morpheus65535** [comment]
Nothing have changed. It's either your server or your client that is to slow to respond to ping within a minute.

**Comment by anonyme123** [comment]
Both server and client are quite fast and have reliable internet connectivity.

**Comment by morpheus65535** [comment]
This guy is the socket.io guru: https://github.com/miguelgrinberg/Flask-SocketIO/issues/814#issuecomment-429669073

Maybe you have a reverse proxy between your client and server?
