### ISSUE TITLE
BAZARR Error trying to get video information for this file: 

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1617]
**Describe the bug**
BAZARR Error trying to get video information for this file: /home/***/media/Movies/One Flew Over the Cuckoo's Nest (1975)/One Flew Over the Cuckoo's Nest (1975).mp4

**Screenshots**
<img width="1250" alt="Screen Shot 2021-11-21 at 15 08 01" src="https://user-images.githubusercontent.com/19681420/142765263-c8341ea5-e3bc-4f1a-9243-7c7a9bcd9b68.png">

**Software (please complete the following information):**
Bazarr Version 1.0.1
Sonarr Version 3.0.6.1342
Radarr Version 3.2.2.5080
Operating System Linux-4.19.0-0.bpo.17-amd64-x86_64-with
Python Version 3.9.5
Bazarr Directory /app/bazarr/bin
Bazarr Config Directory /config

**Additional context**
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 258, in describe
    result = self._describe_tracks(video_path, general_track, video_tracks, audio_tracks, subtitle_tracks, context)
  File "/app/bazarr/bin/bazarr/../libs/knowit/provider.py", line 55, in _describe_tracks
    t = self._validate_track(track_type, self._describe_track(track, track_type, context))
  File "/app/bazarr/bin/bazarr/../libs/knowit/provider.py", line 93, in _describe_track
    value = prop.extract_value(track, context)
  File "/app/bazarr/bin/bazarr/../libs/knowit/property.py", line 49, in extract_value
    result = self.handle(value, context)
  File "/app/bazarr/bin/bazarr/../libs/knowit/properties/video/ratio.py", line 29, in handle
    result = round(float(width) / float(height), 3)
ZeroDivisionError: float division by zero
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 77, in get_video
    refine_from_ffprobe(original_path, video)
  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 1354, in refine_from_ffprobe
    data = parse_video_metadata(file=path, file_size=file_id[\'file_size\'],
  File "/app/bazarr/bin/bazarr/embedded_subs_reader.py", line 111, in parse_video_metadata
    data["ffprobe"] = api.know(file)
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 70, in know
    raise KnowitException(debug_info(context=context, exc_info=True))
knowit.api.KnowitException: +-------------------------------------------------------+

**Comment by morpheus65535** [comment]
This is probably related to an issue with the mp4 file. If not, you should follow this issue for the knowit module: https://github.com/ratoaq2/knowit/issues/23

**Comment by anonyme123** [comment]
Thanks, followed.
