### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: index.html

### ISSUE THREAD

**Issue by radub2** [morpheus65535/bazarr#1630]
Hi,
I have a fresh installation on a raspberry pi and whenever I'm doing `sudo python3.8 bazarr.py --dev --debug` I get:
```
2021-12-05 23:33:22,894 - peewee                           (7f7f2fe1c0) :  DEBUG (peewee:3132) - ('SELECT "t1"."configured", "t1"."updated" FROM "system" AS "t1" LIMIT ? OFFSET ?', [1, 0])
2021-12-05 23:33:22,905 - waitress                         (7f7f2fe1c0) :  ERROR (channel:404) - Exception while serving /
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/waitress/channel.py", line 397, in service
    task.service()
  File "/opt/bazarr/bazarr/../libs/waitress/task.py", line 168, in service
    self.execute()
  File "/opt/bazarr/bazarr/../libs/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/bazarr/bazarr/../libs/flask_socketio/__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/opt/bazarr/bazarr/../libs/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/bazarr/bazarr/app.py", line 53, in __call__
    return self.app(environ, start_response)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bazarr/main.py", line 112, in catch_all
    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/bazarr/bazarr/../libs/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2021-12-05 23:33:23,315 - peewee                           (7f7eafd1c0) :  DEBUG (peewee:3132) - ('SELECT "t1"."configured", "t1"."updated" FROM "system" AS "t1" LIMIT ? OFFSET ?', [1, 0])
2021-12-05 23:33:23,323 - waitress                         (7f7eafd1c0) :  ERROR (channel:404) - Exception while serving /favicon.ico
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/waitress/channel.py", line 397, in service
    task.service()
  File "/opt/bazarr/bazarr/../libs/waitress/task.py", line 168, in service
    self.execute()
  File "/opt/bazarr/bazarr/../libs/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/bazarr/bazarr/../libs/flask_socketio/__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/opt/bazarr/bazarr/../libs/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/bazarr/bazarr/app.py", line 53, in __call__
    return self.app(environ, start_response)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bazarr/bazarr/../libs/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bazarr/main.py", line 112, in catch_all
    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/bazarr/bazarr/../libs/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
```

I did a find on the index.html and it seems it is in the right place 
```
pi@raspberrypi:/opt/bazarr $ find . -name index.html
./frontend/public/index.html
pi@raspberrypi:/opt/bazarr $ ls -la ./frontend/public/index.html
-rw-r--r-- 1 pi pi 924 Dec  5 20:49 ./frontend/public/index.html
```
Does anybody have a hint on how to fix it?

**Comment by morpheus65535** [comment]
Looks like you didn't follow wiki and used git or tarball to install. Make sure you follow the instructions from the wiki: https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/#raspbian-and-maybe-other-arm-based-distro

**Comment by radub2** [comment]
I redid it following the steps in the wiki and it worked. Thank you!
