### ISSUE TITLE
Exception on /api/badges [GET]

### ISSUE THREAD

**Issue by poneli** [morpheus65535/bazarr#1631]
I see this on dev branch.

Exception on /api/badges [GET]
Traceback (most recent call last):

  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 467, in wrapper

    resp = resource(*args, **kwargs)

  File "/opt/bazarr/bazarr/../libs/flask/views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 582, in dispatch_request

    resp = meth(*args, **kwargs)

  File "/opt/bazarr/bazarr/api/utils.py", line 30, in wrapper

    return actual_method(*args, **kwargs)

  File "/opt/bazarr/bazarr/api/badges/badges.py", line 37, in get

    throttled_providers = len(eval(str(get_throttled_providers())))

  File "<string>", line 1, in <module>

NameError: name \'datetime\' is not defined

System info:
Bazarr Version
1.0.2-beta.4
Operating System
Linux-5.15.5-200.fc35.x86_64-x86_64-with-glibc2.34
Python Version
3.10.0

**Comment by morpheus65535** [comment]
Should be fixed in next beta. Thanks for reporting!

**Comment by morpheus65535** [comment]
No news, good news.
