### ISSUE TITLE
ParseResponseError in provider Titulky.com

### ISSUE THREAD

**Issue by rchovan** [morpheus65535/bazarr#1643]
**Describe the bug**
Provider titulkky.com does not work. It show error " ParseResponseError. Exception info: 'Could not find table. Did the HTML source change?'"

**To Reproduce**
1. Add privders Titulky.com
2. Search for subtitles with this provider
3. See error in logs

**Debug logs**
```
17/12/2021 20:46:10|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
17/12/2021 20:46:10|DEBUG   |urllib3.connectionpool          |https://premium.titulky.com:443 "GET / HTTP/1.1" 200 7026|
17/12/2021 20:46:10|DEBUG   |urllib3.connectionpool          |Resetting dropped connection: premium.titulky.com|
17/12/2021 20:46:10|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (2): premium.titulky.com:443|
17/12/2021 20:46:10|DEBUG   |urllib3.connectionpool          |https://premium.titulky.com:443 "POST / HTTP/1.1" 302 0|
17/12/2021 20:46:10|INFO    |subliminal_patch.providers.titulky|Titulky.com: Finding subtitles by IMDB ID, Season and Episode (1)|
17/12/2021 20:46:10|DEBUG   |subliminal_patch.providers.titulky|Titulky.com: Searching only for approved subtitles|
17/12/2021 20:46:10|DEBUG   |subliminal_patch.providers.titulky|Titulky.com: Fetching url: https://premium.titulky.com/?Serial=S&Sezona=1&Epizoda=1&IMDB=2261227&Jazyk=SK&ASchvalene=1&action=search&fsf=1|
17/12/2021 20:46:10|DEBUG   |urllib3.connectionpool          |Resetting dropped connection: premium.titulky.com|
17/12/2021 20:46:10|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (3): premium.titulky.com:443|
17/12/2021 20:46:11|DEBUG   |urllib3.connectionpool          |https://premium.titulky.com:443 "GET /?Serial=S&Sezona=1&Epizoda=1&IMDB=2261227&Jazyk=SK&ASchvalene=1&action=search&fsf=1 HTTP/1.1" 200 2047|
17/12/2021 20:46:11|DEBUG   |subliminal_patch.providers.titulky|Titulky.com: Could not find table|
17/12/2021 20:46:11|ERROR   |subliminal_patch.core           |Unexpected error in provider 'titulky': Traceback (most recent call last):  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 171, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bin/bazarr/../libs/subliminal_patch/providers/titulky.py", line 778, in list_subtitles    partial_subs = self.query(language,  File "/app/bin/bazarr/../libs/subliminal_patch/providers/titulky.py", line 612, in query    raise ParseResponseError(subliminal_patch.exceptions.ParseResponseError: Could not find table. Did the HTML source change?|Traceback (most recent call last):  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 171, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bin/bazarr/../libs/subliminal_patch/providers/titulky.py", line 778, in list_subtitles    partial_subs = self.query(language,  File "/app/bin/bazarr/../libs/subliminal_patch/providers/titulky.py", line 612, in query    raise ParseResponseError(subliminal_patch.exceptions.ParseResponseError: Could not find table. Did the HTML source change?|
17/12/2021 20:46:11|INFO    |root                            |Throttling titulky for 6 hours, until 21/12/18 02:46, because of: ParseResponseError. Exception info: 'Could not find table. Did the HTML source change?'|

```

**Expected behavior**
Probably download subtitle or show info, that they does not exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/6713920/146604864-617e7f7d-ebc3-4ffb-be97-6a5b5caac937.png)

**Software (please complete the following information):**
Docker installation:
Bazarr Version: 1.0.1
Sonarr Version: 3.0.6.1342
Radarr Version: 3.2.2.5080
Operating System: Linux-5.15.0-2-amd64-x86_64-with
Python Version: 3.9.7
Bazarr Directory: /app/bin
Bazarr Config Directory: /config

**Comment by morpheus65535** [comment]
@sambartik could you look into this one? Seems to be following your refactor of this provider.

**Comment by sambartik** [comment]
I can't seem to reproduce the issue. Can you access the [fetched URL](https://premium.titulky.com/?Serial=S&Sezona=1&Epizoda=1&IMDB=2261227&Jazyk=SK&ASchvalene=1&action=search&fsf=1) while logged in? Can you manage to download subtitles via titulky provider for different tv series / movie?

**Comment by rchovan** [comment]
My bad, I didn't notice that it is only for VIP members. Maybe add function to check and verify  for valid VIP account. 
thanks.

**Comment by morpheus65535** [comment]
![image](https://user-images.githubusercontent.com/5130500/146677387-7534c239-798c-4177-a68b-8bb4f286a71e.png)
 It's quite obvious already. I guess @sambartik could take a look to see if it's possible to detect user VIP status but there's no rush on this.
