### ISSUE TITLE
Path does not exist error

### ISSUE THREAD

**Issue by hulleyrob** [morpheus65535/bazarr#1645]
**Describe the bug**
Traceback (most recent call last):
  File "/usr/local/share/bazarr/bazarr/get_subtitle.py", line 70, in get_video
    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
  File "/usr/local/share/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video
    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
  File "/usr/local/share/bazarr/bazarr/../libs/subliminal_patch/core.py", line 501, in scan_video
    raise ValueError(\'Path does not exist\')
ValueError: Path does not exist

BAZARR Error trying to get video information for this file: /home/rob/downloads/radarr/The Plan (2014)/The Plan (2014).mkv

However when I stat this path the movie file definitely exists.

**Software (please complete the following information):**
 - Bazarr: v1.0.1 2021-11-19
 - Radarr version 3.2.2.5080
 - OS: FreeBSD installed via PKG

Not sure how to solve this one?

**Comment by morpheus65535** [comment]
That's not a bug but a support question. Come to Discord support channel for help.
