### ISSUE TITLE
Recent Traceback (unique id for tvdb)

### ISSUE THREAD

**Issue by systemcrash** [morpheus65535/bazarr#1699]
**Describe the bug**
Continuously appeared in the logs at every update period since #1698 I think. 

```py
Update Series list from Sonarr (trigger: interval[0:15:00], next run at: 2022-01-29 00:18:47 UTC)" raised an exception|'Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: UNIQUE constraint failed: table_shows.tvdbId

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/bazarr/bin/bazarr/get_series.py", line 110, in update_series
    TableShows.update(updated_series).where(TableShows.sonarrSeriesId ==
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 1978, in execute
    return self._execute(database)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 2475, in _execute
    return self.handle_result(database, cursor)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 2486, in handle_result
    return database.rows_affected(cursor)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3236, in rows_affected
    return cursor.rowcount
  File "/app/bazarr/bin/bazarr/../libs/playhouse/sqliteq.py", line 94, in rowcount
    self._wait()
  File "/app/bazarr/bin/bazarr/../libs/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
  File "/app/bazarr/bin/bazarr/../libs/playhouse/sqliteq.py", line 178, in execute
    cursor = self.database._execute(obj.sql, obj.params, obj.commit)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: UNIQUE constraint failed: table_shows.tvdbId'
```

**Software (please complete the following information):**

Bazarr Version
1.0.0
Sonarr Version
3.0.6.1394
Radarr Version
3.2.2.5080
Operating System
Linux-4.4.180+-x86_64-with
Python Version
3.9.5
Bazarr Directory
/app/bazarr/bin
Bazarr Config Directory
/config

**Comment by morpheus65535** [comment]
This means that Bazarr is trying to add a tv show with a tvdb_id already used. This typically happens when Sonarr or Radarr get reinstalled (ie: new configuration). Normally you can't have two tv show in Sonarr with the same tvdb_id.

**Comment by systemcrash** [comment]
OK - understood the explanation, but that might not prevent this traceback. Was more concerned about code quality.

**Comment by morpheus65535** [comment]
Of course this could be in a try...except block and wouldn't prevent sync to continue. I'll look into this.

**Comment by morpheus65535** [comment]
BTW you should update to latest version of Bazarr.

**Comment by morpheus65535** [comment]
Should be better now.
