### ISSUE TITLE
Addic7ed, LegendasTV and TVSubtitles error under Docker

### ISSUE THREAD

**Issue by morpheus65535** [morpheus65535/bazarr#17]
'Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/subliminal/core.py", line 118, in list_subtitles_provider
return self[provider].list_subtitles(video, provider_languages)
File "/usr/lib/python2.7/site-packages/subliminal/providers/tvsubtitles.py", line 197, in list_subtitles
return [s for s in self.query(video.series, video.season, video.episode, video.year) if s.language in languages]
File "/usr/lib/python2.7/site-packages/subliminal/providers/tvsubtitles.py", line 163, in query
show_id = self.search_show_id(series, year)
File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1231, in decorate
should_cache_fn)
File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 833, in get_or_create
async_creator) as value:
File "/usr/lib/python2.7/site-packages/dogpile/lock.py", line 154, in __enter__
return self._enter()
File "/usr/lib/python2.7/site-packages/dogpile/lock.py", line 87, in _enter
value = value_fn()
File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 788, in get_value
value = self.backend.get(key)
File "/usr/lib/python2.7/site-packages/dogpile/cache/backends/file.py", line 220, in get
with self._dbm_file(False) as dbm:
File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
return self.gen.next()
File "/usr/lib/python2.7/site-packages/dogpile/cache/backends/file.py", line 215, in _dbm_file
"w" if write else "r")
File "/usr/lib/python2.7/anydbm.py", line 84, in open
mod = __import__(result)
File "/usr/lib/python2.7/dbhash.py", line 7, in 
import bsddb
File "/usr/lib/python2.7/bsddb/__init__.py", line 67, in 
import _bsddb
ImportError: No module named _bsddb'

**Comment by morpheus65535** [comment]
Rolled back to Debian Buster instead of Alpine 3.6. It's now working until we get it fixed with Alipne.

**Comment by morpheus65535** [comment]
Workaround used in 472980e3b34f105fb03983c61d6d713fb8ffd8be and switched back to Alpine in 1591529ff62fee1be93210a46a64efca7611d4c2
