### ISSUE TITLE
Stuck at scanning subtitles from disk...

### ISSUE THREAD

**Issue by StateConscious** [morpheus65535/bazarr#1708]
Job "Update all Movie Subtitles from disk (trigger: cron[hour='5'], next run at: 2022-02-05 05:00:00 EST)" raised an exception

Traceback (most recent call last):  File "c:\bazarr\bazarr\../libs\apscheduler\executors\base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "c:\bazarr\bazarr\get_movies.py", line 23, in update_all_movies    movies_full_scan_subtitles()  File "c:\bazarr\bazarr\list_subtitles.py", line 484, in movies_full_scan_subtitles    store_subtitles_movie(movie['path'], path_mappings.path_replace_movie(movie['path']),  File "c:\bazarr\bazarr\list_subtitles.py", line 201, in store_subtitles_movie    logging.debug(f'{language.alpha3} is an unsupported language code.')AttributeError: 'NoneType' object has no attribute 'alpha3

**Comment by morpheus65535** [comment]
Please fill out the complete issue template.
