### ISSUE TITLE
Job "Update all Movie Subtitles from disk raised an exception

### ISSUE THREAD

**Issue by StateConscious** [morpheus65535/bazarr#1709]
**Describe the bug**
Job "Update all Movie Subtitles from disk" keeps getting stuck after a few dozen movies.

**To Reproduce**
1. Click refresh on "Update all Movie Subtitles from disk" task.
2. See error in the log.

**Expected behavior**
Scan goes through from start to finish.

Bazarr Version 1.0.3-beta.24
Radarr Version 4.0.4.5922
Operating System
Windows-10-10.0.19042-SP0
Python Version 3.10.0
Bazarr Directory c:\bazarr
Bazarr Config Directory C:\ProgramData\Bazarr

**Additional context**
Job "Update all Movie Subtitles from disk (trigger: cron[hour='5'], next run at: 2022-02-05 05:00:00 EST)" raised an exception

Traceback (most recent call last):  File "c:\bazarr\bazarr\../libs\apscheduler\executors\base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "c:\bazarr\bazarr\get_movies.py", line 23, in update_all_movies    movies_full_scan_subtitles()  File "c:\bazarr\bazarr\list_subtitles.py", line 484, in movies_full_scan_subtitles    store_subtitles_movie(movie['path'], path_mappings.path_replace_movie(movie['path']),  File "c:\bazarr\bazarr\list_subtitles.py", line 201, in store_subtitles_movie    logging.debug(f'{language.alpha3} is an unsupported language code.')AttributeError: 'NoneType' object has no attribute 'alpha3

**Comment by TomWillenPXL** [comment]
Would like to chime in and say I've also had this issue. My error gives me a different stack trace though. One regarding parsing the audio format.

**Comment by morpheus65535** [comment]
> Would like to chime in and say I've also had this issue. My error gives me a different stack trace though. One regarding parsing the audio format.

It's unrelated, open your own issue with stack if it's not already fixed in development branch. I'm pretty sure I fexed it already.

**Comment by morpheus65535** [comment]
@StateConscious should be fixed in upcoming 1.0.3-beta.27. Can you test and report please?

**Comment by StateConscious** [comment]
It's working now. Thanks man!
