### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fce2288da30>: Failed to establish a new connection: [Errno -3] Try again'))

### ISSUE THREAD

**Issue by riccardocalligaro** [morpheus65535/bazarr#1712]
**Describe the bug**
Bazarr stops working and gives ERR_CONNECTION_REFUSED. Below there is the stacktrace, it seems that it doesen't connect to `api.cognitive.microsofttranslator.com`.

Internet connection on the machine is working fine. This is the 2nd time that happened, last time I got it working back by deleting the config files and re-setting everything up. 

Stacktrace
```
bazarr          | Bazarr starting...
bazarr          | Bazarr exited.
bazarr          | Traceback (most recent call last):
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 159, in _new_conn
bazarr          |     conn = connection.create_connection(
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 366, in patched_create_connection
bazarr          |     return _orig_create_connection((host, port), *args, **kwargs)
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 57, in create_connection
bazarr          |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
bazarr          |   File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
bazarr          |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
bazarr          | socket.gaierror: [Errno -3] Try again
bazarr          | 
bazarr          | During handling of the above exception, another exception occurred:
bazarr          | 
bazarr          | Traceback (most recent call last):
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 600, in urlopen
bazarr          |     httplib_response = self._make_request(conn, method, url,
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 344, in _make_request
bazarr          |     self._validate_conn(conn)
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 843, in _validate_conn
bazarr          |     conn.connect()
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 316, in connect
bazarr          |     conn = self._new_conn()
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 168, in _new_conn
bazarr          |     raise NewConnectionError(
bazarr          | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fce2288da30>: Failed to establish a new connection: [Errno -3] Try again
bazarr          | 
bazarr          | During handling of the above exception, another exception occurred:
bazarr          | 
bazarr          | Traceback (most recent call last):
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 439, in send
bazarr          |     resp = conn.urlopen(
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 640, in urlopen
bazarr          |     retries = retries.increment(method, url, error=e, _pool=self,
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 399, in increment
bazarr          |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
bazarr          | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fce2288da30>: Failed to establish a new connection: [Errno -3] Try again'))
bazarr          | 
bazarr          | During handling of the above exception, another exception occurred:
bazarr          | 
bazarr          | Traceback (most recent call last):
bazarr          |   File "/app/bazarr/bin/bazarr/main.py", line 20, in <module>
bazarr          |     from init import *
bazarr          |   File "/app/bazarr/bin/bazarr/init.py", line 196, in <module>
bazarr          |     init_binaries()
bazarr          |   File "/app/bazarr/bin/bazarr/init.py", line 174, in init_binaries
bazarr          |     from utils import get_binary
bazarr          |   File "/app/bazarr/bin/bazarr/utils.py", line 27, in <module>
bazarr          |     from deep_translator import GoogleTranslator
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/deep_translator/__init__.py", line 4, in <module>
bazarr          |     from .google_trans import GoogleTranslator
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/deep_translator/google_trans.py", line 5, in <module>
bazarr          |     from .constants import BASE_URLS, GOOGLE_LANGUAGES_TO_CODES
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/deep_translator/constants.py", line 193, in <module>
bazarr          |     microsoft_languages_response = requests.get(microsoft_languages_api_url)
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 76, in get
bazarr          |     return request('get', url, params=params, **kwargs)
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 61, in request
bazarr          |     return session.request(method=method, url=url, **kwargs)
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 542, in request
bazarr          |     resp = self.send(prep, **send_kwargs)
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 655, in send
bazarr          |     r = adapter.send(request, **kwargs)
bazarr          |   File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 516, in send
bazarr          |     raise ConnectionError(e, request=request)
bazarr          | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fce2288da30>: Failed to establish a new connection: [Errno -3] Try again'))
```

Ping 
```
riccardo@riccardo-server:~/server/compose/media-server$ ping api.cognitive.microsofttranslator.com
PING dev-c.microsofttranslator.search.prod.ms.akadns.net (20.49.96.128) 56(84) bytes of data.
^C
--- dev-c.microsofttranslator.search.prod.ms.akadns.net ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9201ms

riccardo@riccardo-server:~/server/compose/media-server$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=114 time=39.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=114 time=28.5 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 28.459/33.808/39.157/5.349 ms
```

**To Reproduce**
No clear steps to reproduce the bug, it happens randomly. I didn't change any configuration.

**Software**
 - Bazarr: latest (linuxserver/bazarr)
 - Radarr version 3.2.2.5080
 - OS:  Ubuntu Server 21.10 x86_64

**Comment by morpheus65535** [comment]
Are you using a proxy?

**Comment by morpheus65535** [comment]
No news, good news.

**Comment by MightyMrMuesli** [comment]
Sorry for reopening, but can confirm on Arch Linux with the [bazarr package from the AUR](https://aur.archlinux.org/packages/bazarr), bazarr release 1.0.3.

Tested with and without proxy, behavior is the same: Instant service crash on start with error trace from above. Manually opening [https://api.cognitive.microsofttranslator.com/languages?api-version=3.0&scope=translation](https://api.cognitive.microsofttranslator.com/languages?api-version=3.0&scope=translation) from browser works, also behind proxy. So it doesn't seem to be a network related issue.

    $ python -V
    Python 3.10.2

**Comment by morpheus65535** [comment]
> Sorry for reopening, but can confirm on Arch Linux with the [bazarr package from the AUR](https://aur.archlinux.org/packages/bazarr), bazarr release 1.0.3.
> 
> Tested with and without proxy, behavior is the same: Instant service crash on start with error trace from above. Manually opening https://api.cognitive.microsofttranslator.com/languages?api-version=3.0&scope=translation from browser works, also behind proxy. So it doesn't seem to be a network related issue.
> 
> ```
> $ python -V
> Python 3.10.2
> ```

It's fixed in v1.0.4-beta.5

**Comment by MightyMrMuesli** [comment]
Can confirm, the service starts without crash. But now I get a new error when I try to open the site:

    ERROR (app:1457) - Exception on / [GET]
    ERROR (app:1457) - Exception on /favicon.ico [GET]

In browser this presents as return code 500. Tested with v1.0.4-beta.5, v1.0.4-beta.11 and v1.0.4-beta.12

Should I open a new issue for this or am I missing something obvious?

**Comment by morpheus65535** [comment]
> Can confirm, the service starts without crash. But now I get a new error when I try to open the site:
> 
> ```
> ERROR (app:1457) - Exception on / [GET]
> ERROR (app:1457) - Exception on /favicon.ico [GET]
> ```
> 
> In browser this presents as return code 500. Tested with v1.0.4-beta.5, v1.0.4-beta.11 and v1.0.4-beta.12
> 
> Should I open a new issue for this or am I missing something obvious?

Yes please we'll start a new one with your debug log.
