### ISSUE TITLE
BAZARR Error (An internal error has occured in guessit.===================== Guessit Exception Report

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1714]
Basarr: v1.0.3-beta.27
Sonarr: 3.0.6.1457
Radarr: 4.0.4.5922
unRAID: 6.9.2

When searching for subtitles for "Reacher S01E07 Reacher Said Nothing" a guessit error occure 

[bazarr.log](https://github.com/morpheus65535/bazarr/files/8013473/bazarr.log)
[debug.log](https://github.com/morpheus65535/bazarr/files/8013593/debug.log)

![image](https://user-images.githubusercontent.com/45288008/152774019-7fcbd00b-7f5b-4553-b3ae-a79ade9e4525.png)

**Comment by morpheus65535** [comment]
```python3
Traceback (most recent call last):\n  File "/app/bin/bazarr/../libs/guessit/api.py", line 209, in guessit\n    matches = self.rebulk.matches(string, options)\n  File "/app/bin/bazarr/../libs/rebulk/rebulk.py", line 115, in matches\n    self._execute_rules(matches, context)\n  File "/app/bin/bazarr/../libs/rebulk/rebulk.py", line 146, in _execute_rules\n    rules.execute_all_rules(matches, context)\n  File "/app/bin/bazarr/../libs/rebulk/rules.py", line 312, in execute_all_rules\n    when_response = execute_rule(rule, matches, context)\n  File "/app/bin/bazarr/../libs/rebulk/rules.py", line 337, in execute_rule\n    rule.then(matches, when_response, context)\n  File "/app/bin/bazarr/../libs/guessit/rules/properties/episode_title.py", line 119, in then\n    matches.remove(title)\n  File "/usr/lib/python3.9/_collections_abc.py", line 1108, in remove\n    del self[self.index(value)]\n  File "/app/bin/bazarr/../libs/rebulk/match.py", line 554, in __delitem__\n    self._remove_match(match)\n  File "/app/bin/bazarr/../libs/rebulk/match.py", line 129, in _remove_match\n    _BaseMatches._base_remove(self._tag_dict[tag], match)\nValueError: list.remove(x): x not in list\n--------------------------------------------------------------------\nPlease report at https://github.com/guessit-io/guessit/issues.\n====================================================================
```

Please report at https://github.com/guessit-io/guessit/issues.
