### ISSUE TITLE
ValueError: Timezone offset does not match system offset: -18000 != 0. Please, check your config files.

### ISSUE THREAD

**Issue by dbgithub101** [morpheus65535/bazarr#1725]
Trying to start Bazaar on Windows 11 using the latest installer found here https://github.com/bazarr/bazarr.github.io/releases/latest/download/bazarr.zip

I navigated to C:\Bazarr and using cmd, I typed "python bazaar.py" to start Bazarr.

This is what I am getting:
Bazarr starting...
Traceback (most recent call last):
  File "c:\bazarr\bazarr\main.py", line 34, in <module>
    from signalr_client import sonarr_signalr_client, radarr_signalr_client
  File "c:\bazarr\bazarr\signalr_client.py", line 17, in <module>
    from scheduler import scheduler
  File "c:\bazarr\bazarr\scheduler.py", line 259, in <module>
    scheduler = Scheduler()
  File "c:\bazarr\bazarr\scheduler.py", line 33, in __init__
    self.aps_scheduler = BackgroundScheduler()
  File "c:\bazarr\bazarr\../libs\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "c:\bazarr\bazarr\../libs\apscheduler\schedulers\base.py", line 131, in configure
    self._configure(config)
  File "c:\bazarr\bazarr\../libs\apscheduler\schedulers\background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "c:\bazarr\bazarr\../libs\apscheduler\schedulers\base.py", line 702, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "c:\bazarr\bazarr\../libs\tzlocal\win32.py", line 95, in get_localzone
    utils.assert_tz_offset(_cache_tz)
  File "c:\bazarr\bazarr\../libs\tzlocal\utils.py", line 46, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: -18000 != 0. Please, check your config files.

I tried to find similar issues in the community and found a few but they were not exactly the same issue so I was having trouble following the recommended steps.

**Software (please complete the following information):**
 - Bazarr: 1.0.2
 - Radarr version 4.0.4.5922
 - Sonarr version 3.0.6.1342
 - OS: Windows 11

**Additional context**

**Comment by morpheus65535** [comment]
If you have set your timezone properly in Windows, you can try to download the latest pre-release bazarr.zip asset to your `%programdata%\Bazarr\update` directory. Edit config\config.ini to change branch to `development`, save and try to restart Bazarr. We updated this dependencies recently.

**Comment by dbgithub101** [comment]
I believe I did as you recommended and when I tried to start it again I got the following error:

Bazarr starting...
Traceback (most recent call last):
  File "c:\bazarr\bazarr\main.py", line 20, in <module>
    from init import *  # noqa E402
  File "c:\bazarr\bazarr\init.py", line 205, in <module>
    init_binaries()
  File "c:\bazarr\bazarr\init.py", line 186, in init_binaries
    from utils import get_binary
  File "c:\bazarr\bazarr\utils.py", line 22, in <module>
    from list_subtitles import store_subtitles, store_subtitles_movie
  File "c:\bazarr\bazarr\list_subtitles.py", line 18, in <module>
    from embedded_subs_reader import embedded_subs_reader
  File "c:\bazarr\bazarr\embedded_subs_reader.py", line 6, in <module>
    from knowit import api
  File "c:\bazarr\bazarr\../libs\knowit\__init__.py", line 19, in <module>
    from knowit.api import KnowitException, know
  File "c:\bazarr\bazarr\../libs\knowit\api.py", line 7, in <module>
    from knowit.provider import Provider
  File "c:\bazarr\bazarr\../libs\knowit\provider.py", line 8, in <module>
    from knowit.properties import Quantity
  File "c:\bazarr\bazarr\../libs\knowit\properties\__init__.py", line 18, in <module>
    from knowit.properties.video import (
ImportError: cannot import name 'VideoDimensions' from 'knowit.properties.video' (c:\bazarr\bazarr\../libs\knowit\properties\video\__init__.py)

**Comment by morpheus65535** [comment]
I should release 1.0.3 to master within a week. You should wait for it and upgrade normally. We'll see after that if you still have an issue.

TBH, I've never tested the installer under Windows 11 but I don't see why it shouldn't work.

**Comment by morpheus65535** [comment]
1.0.3 is released. Can you test it?

**Comment by morpheus65535** [comment]
No news, good news.

**Comment by dbgithub101** [comment]
Hi Morpheus65535,

I am sorry for not getting back sooner. I had some family stuff going on. I
just tried to install version 1.0.3 and I got this
[image: image.png]

Are you able to advise?

**Comment by morpheus65535** [comment]
Could be related to this: https://github.com/regebro/tzlocal/issues/73

Maybe a wrong time zone definition or TZ environment variable.

**Comment by dbgithub101** [comment]
After some further trial and error, I think this fixed it for me. I opened win32.py in Notepad++ located here - C:\Bazarr\libs\tzlocal.

I commented out the following lines,
121 if not utils._tz_name_from_env():
125 utils.assert_tz_offset(_cache_tz)

Once I saved that and tried to relaunch bazaar.py, it's running now.

**Comment by morpheus65535** [comment]
Of course you've disabled the validation but it's going to be overwritten on next update. You didn't fix the issue with your timezone and you'll keep having problems.
