### ISSUE TITLE
Radarr not updating movie list 

### ISSUE THREAD

**Issue by tonypanduru** [morpheus65535/bazarr#1739]
Hello,
Fresh install of Bazarr on manjaro-arm RasPi4 I get movie sync stuck at first movie
![Screenshot from 2022-02-25 14-54-34](https://user-images.githubusercontent.com/36454932/155718631-0a546437-4521-4730-b121-07cfa8b86bf6.png)
 :
"Job "Update Movie list from Radarr (trigger: interval[1:00:00], next run at: 2022-02-25 15:43:56 EET)" raised an exception"

Stack traceback
Traceback (most recent call last):

  File "/usr/lib/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/usr/lib/bazarr/bazarr/get_movies.py", line 86, in update_movies

    movies_to_add.append(movieParser(movie, action=\'insert\',

  File "/usr/lib/bazarr/bazarr/get_movies.py", line 433, in movieParser

    audioCodec = RadarrFormatAudioCodec(audioFormat, audioCodecID, audioProfile,

  File "/usr/lib/bazarr/bazarr/get_movies.py", line 292, in RadarrFormatAudioCodec

    if audioFormat.strip() == "mp3": return "MP3"

AttributeError: \'NoneType\' object has no attribute \'strip\

**Comment by morpheus65535** [comment]
Fixed in 1.0.3-beta.1.
