### ISSUE TITLE
Bazarr v1.0.3 - 500 Error - TemplateNotFound: index.html

### ISSUE THREAD

**Issue by slimjim91** [morpheus65535/bazarr#1743]
**Describe the bug**
Noticed bazarr was down again. Updated to latest build, ran in to the error from #1742 . Deleted the bazarr folder (except data), and unzipped v1.0.3 back in to the same folder. Now receiving the following error:

```
28/02/2022 14:12:31|ERROR   |app                             |Exception on /bazarr/ [GET]|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  [Previous line repeated 7 more times]\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File "c:\\bazarr\\bazarr\\main.py", line 112, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 997, in get_template\n    return self._load_template(name, globals)\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\loaders.py", line 125, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 59, in get_source\n    return self._get_source_fast(environment, template)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 95, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
28/02/2022 14:12:31|ERROR   |app                             |Exception on /bazarr/ [GET]|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  [Previous line repeated 7 more times]\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File "c:\\bazarr\\bazarr\\main.py", line 112, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 997, in get_template\n    return self._load_template(name, globals)\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\loaders.py", line 125, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 59, in get_source\n    return self._get_source_fast(environment, template)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 95, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
28/02/2022 14:12:34|ERROR   |app                             |Exception on /bazarr/ [GET]|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  [Previous line repeated 7 more times]\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File "c:\\bazarr\\bazarr\\main.py", line 112, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 997, in get_template\n    return self._load_template(name, globals)\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\loaders.py", line 125, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 59, in get_source\n    return self._get_source_fast(environment, template)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 95, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
28/02/2022 14:12:34|ERROR   |app                             |Exception on /bazarr/ [GET]|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  [Previous line repeated 7 more times]\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File "c:\\bazarr\\bazarr\\main.py", line 112, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 997, in get_template\n    return self._load_template(name, globals)\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File "c:\\bazarr\\bazarr\\../libs\\jinja2\\loaders.py", line 125, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 59, in get_source\n    return self._get_source_fast(environment, template)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\templating.py", line 95, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
28/02/2022 14:13:27|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
```

On the Web GUI I see Internal Server Error - The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I can see that index.html exists at "C:\bazarr\frontend\public\index.html"

**Software (please complete the following information):**
 - Bazarr: v1.0.3
 - OS: Windows 10

**Additional context**

**Comment by morpheus65535** [comment]
How did you install?

**Comment by slimjim91** [comment]
> How did you install?

Deleted everything in the bazarr directory (except for data), and unzipped v1.03 in to the same folder

**Comment by morpheus65535** [comment]
What zip file?

**Comment by slimjim91** [comment]
> What zip file?

O.O
I used  [Source code (zip)](https://github.com/morpheus65535/bazarr/archive/refs/tags/v1.0.3.zip)

But just noticed there was bazarr.zip](https://github.com/morpheus65535/bazarr/releases/download/v1.0.3/bazarr.zip) that I skipped over. I updated using bazarr.zip and everything launched ok. Thanks
