### ISSUE TITLE
Logs UI crashing

### ISSUE THREAD

**Issue by austinwbest** [morpheus65535/bazarr#1752]
**Describe the bug**
Logs UI crashing

**To Reproduce**
1. Click on the Logs link under System

**Expected behavior**
Dont crash

**Screenshots**
https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=Error%3A%20Request%20failed%20with%20status%20code%20500

![image](https://user-images.githubusercontent.com/8321115/156901185-56956764-5974-44d3-b0e8-8a9e318050c9.png)

**Software (please complete the following information):**
 - Bazarr: 1.0.3
 - OS: Windows 10

**Comment by halali** [comment]
Provide debug log.

**Comment by austinwbest** [comment]
```06/03/2022 13:19:20|DEBUG   |SignalRCoreClient               |{"type": 6}|
06/03/2022 13:19:22|ERROR   |app                             |Exception on /api/system/logs [GET]|Traceback (most recent call last):  File "c:\bazarr\bazarr\../libs\flask\app.py", line 1516, in full_dispatch_request    rv = self.dispatch_request()  File "c:\bazarr\bazarr\../libs\flask\app.py", line 1502, in dispatch_request    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)  File "c:\bazarr\bazarr\../libs\flask_restful\__init__.py", line 467, in wrapper    resp = resource(*args, **kwargs)  File "c:\bazarr\bazarr\../libs\flask\views.py", line 84, in view    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)  File "c:\bazarr\bazarr\../libs\flask_restful\__init__.py", line 582, in dispatch_request    resp = meth(*args, **kwargs)  File "c:\bazarr\bazarr\api\utils.py", line 30, in wrapper    return actual_method(*args, **kwargs)  File "c:\bazarr\bazarr\api\system\logs.py", line 19, in get    raw_lines = file.read()MemoryError|
06/03/2022 13:19:23|WARNING |retry.api                       |HTTPSConnectionPool(host='subscene.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
06/03/2022 13:19:26|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x1769ABC8>|```

**Comment by morpheus65535** [comment]
I've made an attempt to at least fix the log rotation issue in upcoming beta.

**Comment by morpheus65535** [comment]
Log roration is now working as expected following the bug intoduced in Python 3.9/10/11.

Unfortunately, I can't have both daily rotation and file size rotation. For now, there's nothing more I can do.
