### ISSUE TITLE
Insufficient data to process request.

### ISSUE THREAD

**Issue by herkalurk** [morpheus65535/bazarr#1766]
**Describe the bug**
 I'm seeing bazarr unable to process an individual tv show file, when it has processed the rest of the series.  Seems to be one specific file and media info isn't showing any issues with the file.  Permissions are the same across whole series.

**To Reproduce**
Unsure, 

**Expected behavior**
Bazarr is able to scan video file as it has scanned all others

**Screenshots**

![image](https://user-images.githubusercontent.com/2532699/158914447-8a1a2c27-efbc-4bc5-bd1e-29898a5584be.png)

**Logs**
#### Python trace
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/get_subtitle/utils.py", line 39, in get_video
    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
  File "/app/bazarr/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video
    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 699, in scan_video
    video = Video.fromguess(path, guessed_result)
  File "/app/bazarr/bin/bazarr/../libs/subliminal/video.py", line 94, in fromguess
    return Episode.fromguess(name, guess)
  File "/app/bazarr/bin/bazarr/../libs/subliminal/video.py", line 171, in fromguess
    raise ValueError(\'Insufficient data to process the guess\')
ValueError: Insufficient data to process the guess
```

#### File Permissions
```
[user@docker S06]# ls -lhn
total 22G
-rw-rw-r--. 1 1000 1000   52K Jan 26 23:43 The.Blacklist.S06E01.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  997M Sep 28 10:15 The.Blacklist.S06E01.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   49K Jan 26 23:43 The.Blacklist.S06E02.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  990M Sep 28 10:16 The.Blacklist.S06E02.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   53K Jan 26 23:44 The.Blacklist.S06E03.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000 1001M Sep 28 10:16 The.Blacklist.S06E03.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   50K Jan 26 23:44 The.Blacklist.S06E04.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  992M Sep 28 10:16 The.Blacklist.S06E04.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   54K Jan 26 23:44 The.Blacklist.S06E05.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000 1000M Sep 28 10:16 The.Blacklist.S06E05.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   50K Jan 26 23:44 The.Blacklist.S06E06.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  997M Sep 28 10:14 The.Blacklist.S06E06.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   54K Jan 26 23:45 The.Blacklist.S06E07.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  994M Sep 28 10:15 The.Blacklist.S06E07.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   47K Jan 26 23:45 The.Blacklist.S06E08.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000 1003M Sep 28 10:16 The.Blacklist.S06E08.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   51K Jan 26 23:45 The.Blacklist.S06E09.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000 1002M Sep 28 10:13 The.Blacklist.S06E09.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   52K Jan 26 23:45 The.Blacklist.S06E10.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  992M Sep 28 10:13 The.Blacklist.S06E10.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   48K Jan 26 23:46 The.Blacklist.S06E11.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  987M Sep 28 10:13 The.Blacklist.S06E11.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000  994M Sep 28 10:13 The.Blacklist.S06E12.HDTV-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   51K Jan 26 23:46 The.Blacklist.S06E13.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000 1001M Sep 28 10:13 The.Blacklist.S06E13.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   44K Jan 26 23:46 The.Blacklist.S06E14.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  999M Sep 28 10:13 The.Blacklist.S06E14.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   52K Jan 26 23:46 The.Blacklist.S06E15.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000 1000M Sep 28 10:14 The.Blacklist.S06E15.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   54K Jan 26 23:47 The.Blacklist.S06E16.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  996M Sep 28 10:13 The.Blacklist.S06E16.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   52K Jan 26 23:47 The.Blacklist.S06E17.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  999M Sep 28 10:10 The.Blacklist.S06E17.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   46K Jan 26 23:47 The.Blacklist.S06E18.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  999M Sep 28 09:59 The.Blacklist.S06E18.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   40K Jan 26 23:47 The.Blacklist.S06E19.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000 1001M Sep 28 10:11 The.Blacklist.S06E19.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   51K Jan 26 23:48 The.Blacklist.S06E20.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  964M Sep 28 09:59 The.Blacklist.S06E20.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   55K Jan 26 23:48 The.Blacklist.S06E21.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000  967M Sep 28 10:13 The.Blacklist.S06E21.Bluray-1080p.h265.AC3.mkv
-rw-rw-r--. 1 1000 1000   46K Jan 26 23:48 The.Blacklist.S06E22.Bluray-1080p.h265.AC3.en.srt
-rw-rw-r--. 1 1000 1000 1000M Sep 28 10:13 The.Blacklist.S06E22.Bluray-1080p.h265.AC3.mkv
```

**Software (please complete the following information):**
 - Bazarr: v1.0.3 
 - Radarr: v4.0.5.5981 
 - Sonarr: v3.0.7.1477 
 - OS: Centos 7 docker host - all containers are form linuxserver via dockerhub

**Additional context**
According to Sonarr the release grabbed was bluray, but for some reason listed as hdtv - the.blacklist.s06e12BluRay.10Bit.1080p.DD5.1.H265-d3g

**Comment by morpheus65535** [comment]
The issue is the missing dot between the episode number and the source in the original filename (scenename). Here's the guessit output from the scenename provided by Sonarr and used during the video analysis by Bazarr:
```
guessit the.blacklist.s06e12BluRay.10Bit.1080p.DD5.1.H265-d3g
For: the.blacklist.s06e12BluRay.10Bit.1080p.DD5.1.H265-d3g
GuessIt found: {
    "title": "the blacklist s06e12BluRay",
    "color_depth": "10-bit",
    "screen_size": "1080p",
    "audio_codec": "Dolby Digital",
    "audio_channels": "5.1",
    "video_codec": "H.265",
    "release_group": "d3g",
    "type": "movie"
}
```
You can rename the episode, rescan in Soanrr and rename again. On the next rescan, Sonarr should reindex the file but without a scenename. Bazarr will then use the filename instead that will work as expected.

**Comment by herkalurk** [comment]
What do you mean by 'rename the episode'?  The actual file that is in my filesystem does have appropriate delimiters.  The release didn't.

 `The.Blacklist.S06E12.HDTV-1080p.h265.AC3.mkv`

**Comment by morpheus65535** [comment]
I mean that do something for Bazarr to forget that you have that file. You can rename it or move it elsewhere while you do a scan in Sonarr.

**Comment by morpheus65535** [comment]
Still an issue?

**Comment by morpheus65535** [comment]
No news, good news!

**Comment by herkalurk** [comment]
Sorry about late reply, I did rename the file from HDTV to BluRay and rescanned from sonarr, this caused bazarr to properly pickup a sub file.
