### ISSUE TITLE
tzlocal() does not support non-zoneinfo timezones like %s

### ISSUE THREAD

**Issue by nerdalertdk** [morpheus65535/bazarr#1779]
**Describe the bug**
After the latest update i am getting this error 

Error when TZ env is set
```
Bazarr starting...                                                                                                                
Traceback (most recent call last):                                                                                                
  File "/app/bazarr/bin/bazarr/main.py", line 34, in <module>                                                                     
    from signalr_client import sonarr_signalr_client, radarr_signalr_client  # noqa E402                                          
  File "/app/bazarr/bin/bazarr/signalr_client.py", line 17, in <module>                                                           
    from scheduler import scheduler                                                                                               
  File "/app/bazarr/bin/bazarr/scheduler.py", line 282, in <module>                                                               
    scheduler = Scheduler()                                                                                                       
  File "/app/bazarr/bin/bazarr/scheduler.py", line 37, in __init__                                                                
    self.aps_scheduler = BackgroundScheduler()                                                                                    
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 87, in __init__                                      
    self.configure(gconfig, **options)                                                                                            
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 131, in configure                                    
    self._configure(config)                                                                                                       
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/background.py", line 29, in _configure                              
    super(BackgroundScheduler, self)._configure(config)                                                                           
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 702, in _configure                                   
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()                                                   
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 203, in get_localzone                                               
    _cache_tz = _get_localzone()                                                                                                  
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 161, in _get_localzone                                              
    tzenv = utils._tz_from_env()                                                                                                  
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/utils.py", line 122, in _tz_from_env                                               
    raise ZoneInfoNotFoundError(                                                                                                  
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the fo
rm of Continent/City'                                                                                                             
Bazarr exited.   
```

Error with no TZ
```

/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py:177:   UserWarning: Can not find any timezone configuration, defaulting to UTC.
--
warnings.warn("Can not find any   timezone configuration, defaulting to UTC.")
Traceback   (most recent call last):
File   "/app/bazarr/bin/bazarr/../libs/apscheduler/util.py", line 166, in   convert_to_datetime
return tz.localize(datetime_,   is_dst=None)
AttributeError:   'datetime.timezone' object has no attribute 'localize'
 
During   handling of the above exception, another exception occurred:
 
Traceback   (most recent call last):
File   "/app/bazarr/bin/bazarr/main.py", line 34, in <module>
from signalr_client import   sonarr_signalr_client, radarr_signalr_client    # noqa E402
File   "/app/bazarr/bin/bazarr/signalr_client.py", line 17, in   <module>
from scheduler import scheduler
File   "/app/bazarr/bin/bazarr/scheduler.py", line 282, in <module>
scheduler = Scheduler()
File   "/app/bazarr/bin/bazarr/scheduler.py", line 56, in __init__
self.update_configurable_tasks()
File   "/app/bazarr/bin/bazarr/scheduler.py", line 68, in   update_configurable_tasks
self.__randomize_interval_task()
File   "/app/bazarr/bin/bazarr/scheduler.py", line 275, in   __randomize_interval_task
self.aps_scheduler.modify_job(job.id,   next_run_time=datetime.now() +   timedelta(seconds=randrange(job.trigger.interval.total_seconds()*0.75,   job.trigger.interval.total_seconds())))
File   "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py",   line 489, in modify_job
job._modify(**changes)
File   "/app/bazarr/bin/bazarr/../libs/apscheduler/job.py", line 225, in   _modify
approved['next_run_time'] =   convert_to_datetime(value, self._scheduler.timezone,
File   "/app/bazarr/bin/bazarr/../libs/apscheduler/util.py", line 168, in   convert_to_datetime
raise TypeError(
TypeError:   Only pytz timezones are supported (need the localize() and normalize()   methods)
Bazarr   exited.
Bazarr   starting...
^[c^[c^[c/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py:177:   UserWarning: Can not find any timezone configuration, defaulting to UTC.
warnings.warn("Can not find any   timezone configuration, defaulting to UTC.")
Traceback   (most recent call last):
File   "/app/bazarr/bin/bazarr/../libs/apscheduler/util.py", line 166, in   convert_to_datetime
return tz.localize(datetime_,   is_dst=None)
AttributeError:   'datetime.timezone' object has no attribute 'localize'
 
During   handling of the above exception, another exception occurred:
 
Traceback   (most recent call last):
File   "/app/bazarr/bin/bazarr/main.py", line 34, in <module>
from signalr_client import   sonarr_signalr_client, radarr_signalr_client    # noqa E402
File   "/app/bazarr/bin/bazarr/signalr_client.py", line 17, in   <module>
from scheduler import scheduler
File   "/app/bazarr/bin/bazarr/scheduler.py", line 282, in <module>
scheduler = Scheduler()
File   "/app/bazarr/bin/bazarr/scheduler.py", line 56, in __init__
self.update_configurable_tasks()
File   "/app/bazarr/bin/bazarr/scheduler.py", line 68, in   update_configurable_tasks
self.__randomize_interval_task()
File   "/app/bazarr/bin/bazarr/scheduler.py", line 275, in   __randomize_interval_task
self.aps_scheduler.modify_job(job.id,   next_run_time=datetime.now() +   timedelta(seconds=randrange(job.trigger.interval.total_seconds()*0.75,   job.trigger.interval.total_seconds())))
File   "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py",   line 489, in modify_job
job._modify(**changes)
File   "/app/bazarr/bin/bazarr/../libs/apscheduler/job.py", line 225, in   _modify
approved['next_run_time'] =   convert_to_datetime(value, self._scheduler.timezone,
File   "/app/bazarr/bin/bazarr/../libs/apscheduler/util.py", line 168, in   convert_to_datetime
raise TypeError(
TypeError:   Only pytz timezones are supported (need the localize() and normalize()   methods)
Bazarr   exited.
Bazarr   starting...
```

**To Reproduce**

Run newest version from linuxserver.io

**Expected behavior**
Container starts

**Software (please complete the following information):**
 - Bazarr: v 1.0.31
 - OS: Docker on Synology

**Additional context**
I've tried with

- No TZ env.
- TZ = 'Europe/Copenhagen'
- TZ= Europe/Copenhagen
- Remove container
- Redownload latest 
- Clean config

**Comment by nerdalertdk** [comment]
Somehow fixed it self. 
ruined half the config

**Comment by morpheus65535** [comment]
I can't test on Synology but it works perfectly fine on x64 ubuntu Docker host:
```
docker run -d \
  --name=bazarr \
  -e TZ=Europe/Copenhagen \
  -p 6767:6767 \
  lscr.io/linuxserver/bazarr
```

```
2022-03-23 16:11:31,446 - root                             (7f3751720b48) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:6767
```

**Comment by clyra** [comment]
I just got the same error and by pure luck found the solution... I'm starting bazarr from docker-compose, and it seems that this works:

````
environment:
      - TZ=America/Sao_Paulo
 ````

while this, does not:

````
environment:
      - TZ="America/Sao_Paulo" 
````

No clue why the no quotes TZ didn't worked for @nerdalertdk. Another funny thing is that radarr, sonarr and  prowlarr didnt complained about the TZ!
