### ISSUE TITLE
bazarr not running 

### ISSUE THREAD

**Issue by Monirzadeh** [morpheus65535/bazarr#1784]
**Describe the bug**

recently i got this error each time i try to run docker container
```
Traceback (most recent call last):
  File "/app/bin/bazarr/main.py", line 37, in <module>
    from server import app, webserver  # noqa E402
  File "/app/bin/bazarr/server.py", line 79, in <module>
    webserver = Server()
  File "/app/bin/bazarr/server.py", line 30, in __init__
    self.server = create_server(app,
  File "/app/bin/bazarr/../libs/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/app/bin/bazarr/../libs/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/app/bin/bazarr/../libs/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/app/bin/bazarr/../libs/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
OSError: [Errno 99] Address not available
```
 - [docker image](https://hub.docker.com/r/linuxserver/bazarr)

**Software (please complete the following information):**
 - Bazarr: 1.0.3
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: debian run on docker

**Comment by morpheus65535** [comment]
Duplicate #774
