### ISSUE TITLE
Clicking "Download Wanted Subtitles" throws an error after a while

### ISSUE THREAD

**Issue by irritatedcone** [morpheus65535/bazarr#179]
When clicking Download Wanted subtitles the page starts loading and errors out after a while with the following error:

Job "Search for wanted subtitles (trigger: interval[3:00:00], next run at: 2018-10-11 00:05:08 CEST)" raised an exception

Traceback (most recent call last):
 File "C:\\Programs\\Bazarr\\bazarr\\libs/apscheduler\\executors\\base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "C:\\Programs\\Bazarr\\bazarr\\get_subtitle.py", line 451, in wanted_search_missing_subtitles
  wanted_download_subtitles(episode[0])
 File "C:\\Programs\\Bazarr\\bazarr\\get_subtitle.py", line 377, in wanted_download_subtitles
  message = download_subtitle(path_replace(episode[0]), str(alpha3_from_alpha2(language)), episode[4], providers_list, providers_auth, episode[5], \series\)
 File "C:\\Programs\\Bazarr\\bazarr\\get_subtitle.py", line 107, in download_subtitle
  downloaded_provider = result[0].provider_name
IndexError: list index out of range

**Comment by morpheus65535** [comment]
What version of Bazarr are you running? Docker or from source?

**Comment by irritatedcone** [comment]
From source, can't give the exact version until later today - cloned it on the 9th of October at around 23:00 CET if that helps.

**Comment by andrewhunt12** [comment]
Hitting this as well, seems to happen both from manual invoke search and from the job.

```
Traceback (most recent call last):
 File "/app/bazarr/libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/get_subtitle.py", line 449, in wanted_search_missing_subtitles
  wanted_download_subtitles(episode[0])
 File "/app/bazarr/get_subtitle.py", line 375, in wanted_download_subtitles
  message = download_subtitle(path_replace(episode[0]), str(alpha3_from_alpha2(language)), episode[4], providers_list, providers_auth, episode[5], \series\)
 File "/app/bazarr/get_subtitle.py", line 105, in download_subtitle
  downloaded_provider = result[0].provider_name
IndexError: list index out of range
```

Running in Docker, version 0.6.6.1

**Comment by morpheus65535** [comment]
Please update to 0.6.6.1 and confirmif you still got the issue. Thanks.

**Comment by andrewhunt12** [comment]
I am already running 0.6.6.1 and having this issue

**Comment by morpheus65535** [comment]
Ok I'll look into it asap.
