### ISSUE TITLE
Connected to Sonarr, but No Series Found

### ISSUE THREAD

**Issue by jeanpaulrh** [morpheus65535/bazarr#1802]
**Describe the bug**
I installed sonarr and try to enable bazarr to work with it (it was previously set up only with radarr).
I enabled sonarr configured address port and api key. Test shows connection and version number, but on the series page I get a No Series Found.

In the logs I found this, which seems like a connection problem, but I can't understand why.

`14/04/2022 07:49:01|ERROR   |root                            |BAZARR Error trying to get series from Sonarr. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 366, in patched_create_connection\n    return _orig_create_connection((host, port), *args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 95, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n  File "/usr/lib/python3.9/http/client.py", line 1253, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output\n    self.send(msg)\n  File "/usr/lib/python3.9/http/client.py", line 948, in send\n    self.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 205, in connect\n    conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f84079a8fd0>: Failed to establish a new connection: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 440, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 785, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=\'***.***.***.***\', port=8989): Max retries exceeded with url: /api/v3/series?apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7f84079a8fd0>: Failed to establish a new connection: [Errno 111] Connection refused\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/get_episodes.py", line 362, in get_series_from_sonarr_api\n    r = requests.get(url_sonarr_api_series, timeout=60, verify=False, headers=headers)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 75, in get\n    return request(\'get\', url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 645, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host=\'***.***.***.***\', port=8989): Max retries exceeded with url: /api/v3/series?apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7f84079a8fd0>: Failed to establish a new connection: [Errno 111] Connection refused\'))'|`

**To Reproduce**
1. Configure Radarr, and test connection success and save config
2. Click Series
3. The message is "No series found"

**Expected behavior**
I have a lot of series but no one is showing up

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.0.3
 - Sonarr 3.0.7.1477
 - OS: Openmediavault 5 - Docker

**Comment by jeanpaulrh** [comment]
Sorry for submitting a false alert. It now works. Don't know what was wrong before though.
