### ISSUE TITLE
Changing/removing cutoff does not save.

### ISSUE THREAD

**Issue by nitschis** [morpheus65535/bazarr#1817]
Changing/removing cutoff does not save.

```

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1502, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

  File "/app/bazarr/bin/bazarr/../libs/flask_restful/__init__.py", line 467, in wrapper

    resp = resource(*args, **kwargs)

  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 84, in view

    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)

  File "/app/bazarr/bin/bazarr/../libs/flask_restful/__init__.py", line 582, in dispatch_request

    resp = meth(*args, **kwargs)

  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper

    return actual_method(*args, **kwargs)

  File "/app/bazarr/bin/bazarr/api/system/settings.py", line 58, in post

    TableLanguagesProfiles.cutoff: item[\'cutoff\'] if item[\'cutoff\'] != \'null\' else None,

KeyError: \'cutoff\

```

**Software (please complete the following information):**
 - Bazarr: v1.0.4-beta.26
 - OS: docker-image

**Comment by nitschis** [comment]
Changing the cutoff works as expected. Just removing it does not work.

**Comment by morpheus65535** [comment]
@LASER-Yi is it possible that when you clear the cutoff, this value isn't sent to backend?

**Comment by LASER-Yi** [comment]
> @LASER-Yi is it possible that when you clear the cutoff, this value isn't sent to backend?

Let me check

**Comment by LASER-Yi** [comment]
Should be fixed in the next upcoming beta version
