### ISSUE TITLE
Search for binaries in PATH

### ISSUE THREAD

**Issue by alexreg** [morpheus65535/bazarr#1825]
A few questions/suggestions here, which impact the creation of a macOS Homebrew formula (package).

* Can we get Bazarr to search the PATH environment variable for the binaries it needs? (Like `ffmpeg`, `ffprobe`, `unrar.) The Homebrew formula needs to set `binaries.json` to an empty array to stop auto-downloads, since this is against the rules of a package manager that builds from source. (Alternatively, an environment variable to disable binary downloads would be nice, but just a bonus really.)
* Is `unrar` absolutely essential for the operation of Bazarr? Currently, if it cannot be found, it prevents Bazarr from starting up. This is correct behaviour if it's required, but not if it's optional, of course.
* A slightly nice solution for unrar-ing archives might be to use [sharpcompress](https://github.com/adamhathcock/sharpcompress), which is written in pure C#, and should do everything the `unrar` CLI does.

Thanks in advance.

**Comment by morpheus65535** [comment]
Hey, 

- Bazarr already try to find binaries preinstalled first: https://github.com/morpheus65535/bazarr/blob/master/bazarr/utils.py#L143-L148
- Unrar is required by some providers. Can tell which one out of memory.
- We use rarFile python module as an interface with unrar. Moving t sharpcompress would means a lot of retrofit for no real benefit.

**Comment by alexreg** [comment]
Thanks for the reply, @morpheus65535. Sorry, I had somehow forgotten that Bazarr is built in Python (unlike Sonarr and Radarr that are built in C#/.NET). Anyway, the rarFile module sounds good! Weird that Bazarr doesn't find `unrar` in the PATH, because it's definitely there. I'll look closer.

**Comment by alexreg** [comment]
Let me know if you want to look into using rarFile, or if I should make a PR. Thanks.

**Comment by morpheus65535** [comment]
We already use the rarFile module but it rely on the unrar executable: https://pypi.org/project/rarfile/

**Comment by alexreg** [comment]
Ah I see.

**Comment by alexreg** [comment]
Looks like I fixed the problem with finding `unrar` now.

Quite independently, I think, I'm getting an error on startup, but I'm not sure if it matters.

```
Bazarr starting...
2022-05-03 15:36:43,493 - root                             (2f64c3000) :  INFO (signalr_client:104) - BAZARR trying to connect to Sonarr SignalR feed...
2022-05-03 15:36:43,494 - root                             (2f74cf000) :  INFO (signalr_client:163) - BAZARR trying to connect to Radarr SignalR feed...
2022-05-03 15:36:43,494 - root                             (100a2c580) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:6767
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/bazarr/1.0.4/libexec/bazarr/signalr_client.py", line 107, in start
    self.connection.start()
  File "/opt/homebrew/Cellar/bazarr/1.0.4/libexec/bazarr/../libs/signalrcore/hub/base_hub_connection.py", line 44, in start
    return self.transport.start()
  File "/opt/homebrew/Cellar/bazarr/1.0.4/libexec/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line 62, in start
    self.negotiate()
  File "/opt/homebrew/Cellar/bazarr/1.0.4/libexec/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line 99, in negotiate
    raise HubError(response.status_code)\
signalrcore.hub.errors.HubError: 502
2022-05-03 15:36:43,542 - root                             (2f64c3000) :  INFO (signalr_client:187) - BAZARR SignalR client for Radarr is connected and waiting for events.
```

**Comment by morpheus65535** [comment]
Sonarr is returning a 502 on the SignalR feed endpoint. You won't get notified of events on Sonarr side and will only be in "pull" mode on a scedule.

**Comment by alexreg** [comment]
That sounds fair enough. I think issue is basically resolved now, thanks.
