### ISSUE TITLE
500 server error on v1.0.5-beta.3 on Ubuntu

### ISSUE THREAD

**Issue by jonheckman** [morpheus65535/bazarr#1829]
**Describe the bug**
When I first launch Bazarr I am getting a 500 server error 

**To Reproduce**
1. Launch service with `python3 bazarr.py`. 
2. Open browser

**Software (please complete the following information):**
 - Bazarr: v1.0.5-beta.3
 - OS: Ubuntu 20.04.4

**Additional context**
This is a new installation, I have not been able to get to the console at all to configure it

Been following the beta versions because of https://github.com/morpheus65535/bazarr/issues/1822
Since this is a new issue I am making a new report

Error in console:
```
torrent@ubuntu:/opt/bazarr$ python3 bazarr.py 
Bazarr starting...
2022-05-05 09:17:19,286 - root                             (7fcb24a96740) :  INFO (server:39) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2022-05-05 09:17:21,022 - app.app                          (7fcb0ffff700) :  ERROR (app:1457) - Exception on / [GET]
```

Log FIle:
```
05/05/2022 09:17:19|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
05/05/2022 09:17:21|ERROR   |app.app                         |Exception on / [GET]|'Traceback (most recent call last):\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 271, in error_router\n    return original_handler(e)\n  [Previous line repeated 7 more times]\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File "bazarr/main.py", line 110, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 997, in get_template\n    return self._load_template(name, globals)\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File "/opt/bazarr/bazarr/../libs/jinja2/loaders.py", line 125, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 59, in get_source\n    return self._get_source_fast(environment, template)\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 95, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
```

**Comment by morpheus65535** [comment]
You don't have the template. Did you use the zip asset file or simply git pulled the repo?

Here's the latest zip asset: https://github.com/morpheus65535/bazarr/releases/download/v1.0.5-beta.3/bazarr.zip

**Comment by jonheckman** [comment]
I just used git since I figured that would be easier. 

Using the zip worked. Sorry about that.

I don't see it in the readme, but if I just need to use git in the future what do I need to run to compile assets (I assume, if this is something like rails)

**Comment by morpheus65535** [comment]
> I don't see it in the readme, but if I just need to use git in the future what do I need to run to compile assets (I assume, if this is something like rails)

`npm run build` from within `frontend` directory.

https://github.com/morpheus65535/bazarr/blob/master/frontend/README.md
