### ISSUE TITLE
Update Movie list from Radarr raised an exception

### ISSUE THREAD

**Issue by altanir84** [morpheus65535/bazarr#1890]
**Describe the bug**
Can't update movie list from Radarr

**To Reproduce**
1. Go to 'tasks'
2. Click on 'Update Movie list from Radarr.'
3.  See error

**Expected behavior**
To update movie list from radarr, removing deleted ones and adding new ones.

**Software (please complete the following information):**
Synology DSM 7.1-42661 
model=DS418

Bazarr Version - From Synocommunity
1.0.4
Sonarr Version
3.0.8.1538
Radarr Version
unknown
Operating System
Linux-4.4.180+-aarch64-with-glibc2.26
Python Version
3.10.4
Bazarr Directory
/volume1/@appstore/bazarr/share/bazarr
Bazarr Config Directory
/volume1/@appdata/bazarr/data
Uptime

**Additional context**

Deleted the cache content but the result is the same.

Log:

Traceback (most recent call last):

  File "/volume1/@appstore/bazarr/share/bazarr/bazarr/../libs/requests/models.py", line 910, in json

    return complexjson.loads(self.text, **kwargs)

  File "/var/packages/python310/target/lib/python3.10/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

  File "/var/packages/python310/target/lib/python3.10/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/var/packages/python310/target/lib/python3.10/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/volume1/@appstore/bazarr/share/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/volume1/@appstore/bazarr/share/bazarr/bazarr/get_movies.py", line 28, in update_movies

    check_radarr_rootfolder()

  File "/volume1/@appstore/bazarr/share/bazarr/bazarr/get_rootfolder.py", line 134, in check_radarr_rootfolder

    get_radarr_rootfolder()

  File "/volume1/@appstore/bazarr/share/bazarr/bazarr/get_rootfolder.py", line 112, in get_radarr_rootfolder

    for folder in rootfolder.json():

  File "/volume1/@appstore/bazarr/share/bazarr/bazarr/../libs/requests/models.py", line 917, in json

    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

**Comment by morpheus65535** [comment]
Try restarting Radarr than Bazarr. It should solve your issue.

**Comment by altanir84** [comment]
Did that, did not work.

Also rebooted the NAS and the update still failed.

**Comment by morpheus65535** [comment]
This error means that Radarr return improper JSON. There's nothing we can do because the return of this call is mandatory. Check that your apikey is good or test with another version of Radarr.

**Comment by altanir84** [comment]
The APIKey changed somehow and the previous one stopped working. It fixed the issue. Thanks!

**Comment by morpheus65535** [comment]
Good to know! Thanks for reporting. I'll try to catch 401 and report it wherever I can think.
