### ISSUE TITLE
No movies from Radarr

### ISSUE THREAD

**Issue by pax0707** [morpheus65535/bazarr#1918]
**Describe the bug**
Movies tab show no movies, it does show a "Error 500
You have disconnected from the server" popup

**To Reproduce**
1 Click on movies tab
2 Show 0 to 0 of 0 entries
3 Popup: Error 500 You have disconnected from the server

**Expected behavior**
Show list of movies from Radarr

**Screenshots**

**Software (please complete the following information):**
Bazarr Version
1.1.0
Sonarr Version
3.0.8.1548
Radarr Version
4.2.0.6438
Operating System
Linux-5.15.32-v8+-aarch64-with-glibc2.31
Python Version
3.9.2

**Additional context**
Exception on /api/movies [GET]

```
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/bazarr/bazarr/../libs/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/opt/bazarr/bazarr/../libs/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/bazarr/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/opt/bazarr/bazarr/api/movies/movies.py", line 33, in get
    postprocessMovie(item)
  File "/opt/bazarr/bazarr/api/utils.py", line 199, in postprocessMovie
    desired_lang_list = get_desired_languages(item[\'profileId\'])
  File "/opt/bazarr/bazarr/app/database.py", line 439, in get_desired_languages
    if profileId == int(profile_id):
ValueError: invalid literal for int() with base 10: \'None\
```

**Comment by pax0707** [comment]
Working in v1.1.1-beta.11.
