### ISSUE TITLE
Docker container continuously restarting

### ISSUE THREAD

**Issue by feerlessleadr** [morpheus65535/bazarr#1920]
**Describe the bug**
I am in the process of migrating all of my services to a new ubuntu machine (running 22.04), and I realized that my bazarr container was not reachable with my most recent backup. I re-spung up bazarr container on my old machine, and realized that it is also not accessible. Here is my current compose file:

```
version: "2.1"
services:
  bazarr:
    image: hotio/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/NewYork
    volumes:
      - ./config:/config
      - /media/v/Movies:/movies #optional
      - /media/v/TV:/tv #optional
      - /media/v/KidsMovies:/kidsmovies #optional
      - /media/v/KidsTV:/kidstv #optional
      - /media/v/ClarkMovies:/clarkmovies #optional
      - /media/v/ClarkTV:/clarktv #optional
      - /media/v/ParentsMovies:/parentsmovies #optional
      - /media/v/ParentsTV:/parentstv #optional
      - /media/gdrive/Movies-emby:/movies-gdrive #optional
      - /media/gdrive/TV-emby:/tv-gdrive #optional
    ports:
      - 6767:6767
    restart: unless-stopped
```
Here is the log when I start the container:

```
kevin@server-linux:~/docker-apps/bazarr$ docker compose up
[+] Running 1/0
 ⠿ Container bazarr  Recreated                                                                                                                                                                          0.1s
Attaching to bazarr
bazarr  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
bazarr  | [s6-init] ensuring user provided files have correct perms...exited 0.
bazarr  | [fix-attrs.d] applying ownership & permissions fixes...
bazarr  | [fix-attrs.d] done.
bazarr  | [cont-init.d] executing container initialization scripts...
bazarr  | [cont-init.d] 00-env-file-init: executing...
bazarr  | [cont-init.d] 00-env-file-init: exited 0.
bazarr  | [cont-init.d] 00-start-container: executing...
bazarr  |
bazarr  | ----------------------------------------------------------------------
bazarr  | ENVIRONMENT
bazarr  | ----------------------------------------------------------------------
bazarr  | PUID=1000
bazarr  | PGID=1000
bazarr  | UMASK=002
bazarr  | TZ=America/NewYork
bazarr  | ----------------------------------------------------------------------
bazarr  |
bazarr  | Executing usermod...
bazarr  | usermod: no changes
bazarr  | Applying permissions to /config
bazarr  | [cont-init.d] 00-start-container: exited 0.
bazarr  | [cont-init.d] done.
bazarr  | [services.d] starting services
bazarr  | [services.d] done.
bazarr  | Traceback (most recent call last):
bazarr  |   File "/app/bin/bazarr/main.py", line 20, in <module>
bazarr  |     from app.config import settings, configure_proxy_func, base_url  # noqa E402
bazarr  |   File "/app/bin/bazarr/app/config.py", line 255, in <module>
bazarr  |     settings.read(os.path.join(args.config_dir, 'config', 'config.ini'))
bazarr  |   File "/usr/lib/python3.10/configparser.py", line 698, in read
bazarr  |     self._read(fp, filename)
bazarr  |   File "/usr/lib/python3.10/configparser.py", line 1117, in _read
bazarr  |     raise e
bazarr  | configparser.ParsingError: Source contains parsing errors: '/config/config/config.ini'
bazarr  |       [line 223]: 'streami'
bazarr  | Bazarr starting...
bazarr  | Bazarr exited.
bazarr  | [cont-finish.d] executing container finish scripts...
bazarr  | [cont-finish.d] done.
bazarr  | [s6-finish] waiting for services.
bazarr  | [s6-finish] sending all processes the TERM signal.
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 1/1
 ⠿ Container bazarr  Stopped                                                                                                                                                                            1.4s
canceled
kevin@server-linux:~/docker-apps/bazarr$ ^C
```

Here is my log with a fresh config folder:

```
kevin@server-linux:~/docker-apps/bazarr$ docker compose up
[+] Running 1/0
 ⠿ Container bazarr  Created                                                                                                                                                                               0.0s
Attaching to bazarr
bazarr  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
bazarr  | [s6-init] ensuring user provided files have correct perms...exited 0.
bazarr  | [fix-attrs.d] applying ownership & permissions fixes...
bazarr  | [fix-attrs.d] done.
bazarr  | [cont-init.d] executing container initialization scripts...
bazarr  | [cont-init.d] 00-env-file-init: executing...
bazarr  | [cont-init.d] 00-env-file-init: exited 0.
bazarr  | [cont-init.d] 00-start-container: executing...
bazarr  |
bazarr  | ----------------------------------------------------------------------
bazarr  | ENVIRONMENT
bazarr  | ----------------------------------------------------------------------
bazarr  | PUID=1000
bazarr  | PGID=1000
bazarr  | UMASK=002
bazarr  | TZ=America/NewYork
bazarr  | ----------------------------------------------------------------------
bazarr  |
bazarr  | Executing usermod...
bazarr  | usermod: no changes
bazarr  | Applying permissions to /config
bazarr  | [cont-init.d] 00-start-container: exited 0.
bazarr  | [cont-init.d] done.
bazarr  | [services.d] starting services
bazarr  | [services.d] done.
bazarr  | Traceback (most recent call last):
bazarr  |   File "/app/bin/bazarr/main.py", line 25, in <module>
bazarr  |     from app.signalr_client import sonarr_signalr_client, radarr_signalr_client  # noqa E402
bazarr  |   File "/app/bin/bazarr/app/signalr_client.py", line 20, in <module>
bazarr  |     from .scheduler import scheduler
bazarr  |   File "/app/bin/bazarr/app/scheduler.py", line 285, in <module>
bazarr  |     scheduler = Scheduler()
bazarr  |   File "/app/bin/bazarr/app/scheduler.py", line 40, in __init__
bazarr  |     self.aps_scheduler = BackgroundScheduler()
bazarr  |   File "/app/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 87, in __init__
bazarr  |     self.configure(gconfig, **options)
bazarr  |   File "/app/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 131, in configure
bazarr  |     self._configure(config)
bazarr  |   File "/app/bin/bazarr/../libs/apscheduler/schedulers/background.py", line 29, in _configure
bazarr  |     super(BackgroundScheduler, self)._configure(config)
bazarr  |   File "/app/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 702, in _configure
bazarr  |     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
bazarr  |   File "/app/bin/bazarr/../libs/tzlocal/unix.py", line 203, in get_localzone
bazarr  |     _cache_tz = _get_localzone()
bazarr  |   File "/app/bin/bazarr/../libs/tzlocal/unix.py", line 161, in _get_localzone
bazarr  |     tzenv = utils._tz_from_env()
bazarr  |   File "/app/bin/bazarr/../libs/tzlocal/utils.py", line 122, in _tz_from_env
bazarr  |     raise ZoneInfoNotFoundError(
bazarr  | tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'
bazarr  | Bazarr starting...
bazarr  | Bazarr exited.
bazarr  | [cont-finish.d] executing container finish scripts...
bazarr  | [cont-finish.d] done.
bazarr  | [s6-finish] waiting for services.
bazarr  | [s6-finish] sending all processes the TERM signal.
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 1/1
 ⠿ Container bazarr  Stopped                                                                                                                                                                               1.1s
canceled
```

**To Reproduce**
1. Create the compose file as above
2. docker compose up
3. See error

**Expected behavior**
bazarr container should start

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1] - Not sure, running with the latest tag in docker
 - Radarr version [e.g. v 0.2.0.0001] - 4.1.0.6175
 - Sonarr version [e.g. v 2.0.0.0001] - 3.0.9.1549
 - OS: [e.g. Windows 10] - Ubuntu 22.04.01

**Additional context**

**Comment by halali** [comment]
delete your config file inside your config directory...

configparser.ParsingError: Source contains parsing errors: '/config/config/config.ini'
bazarr  |       [line 223]: 'streami'

And also correct timezone for new york is

America/New_York

**Comment by feerlessleadr** [comment]
Thanks - that fixed it. Also interesting about the TZ, I use that format for all my other containers and haven't noticed an issue. Thanks for the heads up!

**Comment by SophiaHadash** [comment]
I have the exact same problem and I cannot just delete my config file. Apparently a recent update broke my  config.

**Comment by feerlessleadr** [comment]
I ended up just nuking my data and starting fresh.

**Comment by jaum20** [comment]
> I have the exact same problem and I cannot just delete my config file. Apparently a recent update broke my config. The solution was to remove the trailing newline at the end of the file.

How did you do this? I tried to remove the \n but the error remains

**Comment by SophiaHadash** [comment]
> > I have the exact same problem and I cannot just delete my config file. Apparently a recent update broke my config. The solution was to remove the trailing newline at the end of the file.
> 
> How did you do this? I tried to remove the \n but the error remains

In that case I would start with a fresh config. And if you want your old config back you can gradually populate it with the old data until you find the part with the problem. It's really unfortunate that this keeps happening with bazarr.

**Comment by morpheus65535** [comment]
> It's really unfortunate that this keeps happening with bazarr.

Bazarr 1.4.0 will introduce a mature configuration manager that will prevent config file corruption.

Of course, having your corrupted config.ini to understand where's the issue in the code would be more helpful than just leaving that kind of comment.

**Comment by jaum20** [comment]
> > > I have the exact same problem and I cannot just delete my config file. Apparently a recent update broke my config. The solution was to remove the trailing newline at the end of the file.
> > 
> > 
> > How did you do this? I tried to remove the \n but the error remains
> 
> In that case I would start with a fresh config. And if you want your old config back you can gradually populate it with the old data until you find the part with the problem. It's really unfortunate that this keeps happening with bazarr.

The problem was the [subsync] session. I just copied it from the new default congig.ini and rfelaced in my old config file and it worked fine. I think my file was somehow missing `use_subsync = False` line

**Comment by SophiaHadash** [comment]
> > It's really unfortunate that this keeps happening with bazarr.
> 
> Bazarr 1.4.0 will introduce a mature configuration manager that will prevent config file corruption.
> 
> Of course, having your corrupted config.ini to understand where's the issue in the code would be more helpful than just leaving that kind of comment.

My apologies for the snarky remark. I guess I was upset I had to redo my config again, but that shouldn'tbe directed at the devs. Sorry! Great to hear about the progress though ♥
