### ISSUE TITLE
Subscene: BrotliDecompress failed!

### ISSUE THREAD

**Issue by callym** [morpheus65535/bazarr#1940]
The Subscene provider doesn't work - it throws `BrotliDecompress failed!`

**Software (please complete the following information):**

 - Bazarr Version: 1.1.1
 - Sonarr Version: 3.0.9.1549
 - Radarr Version: 4.1.0.6175
 - Operating System: Linux-5.19.5-arch1-1-x86_64-with-glibc2.36
 - Python Version: 3.10.6

**Additional context**
The debug logs show this:

```
03/09/2022 17:45:39|ERROR   |subliminal_patch.core           |Unexpected error in provider 'subscene': Traceback (most recent call last):  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/core.py", line 308, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/core.py", line 244, in __getitem__    provider.initialize()  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 158, in initialize    self.login()  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 161, in login    r = self.session.get("https://subscene.com/account/login")  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 229, in get    return self.retry_method("get", *args, **kwargs)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 217, in retry_method    return retry_call(getattr(super(RetryingSession, self), method), fargs=args, fkwargs=kwargs, tries=3, delay=5,  File "/usr/lib/bazarr/bazarr/../libs/retry/api.py", line 101, in retry_call    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)  File "/usr/lib/bazarr/bazarr/../libs/retry/api.py", line 33, in __retry_internal    return f()  File "/usr/lib/bazarr/bazarr/../libs/requests/sessions.py", line 542, in get    return self.request('GET', url, **kwargs)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 60, in request    return super(TimeoutSession, self).request(method, url, *args, **kwargs)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 165, in request    ret = self._request(method, url, *args, **kwargs)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 84, in _request    resp._content = brotli.decompress(resp.content)brotli.error: BrotliDecompress failed|Traceback (most recent call last):  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/core.py", line 308, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/core.py", line 244, in __getitem__    provider.initialize()  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 158, in initialize    self.login()  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 161, in login    r = self.session.get("https://subscene.com/account/login")  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 229, in get    return self.retry_method("get", *args, **kwargs)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 217, in retry_method    return retry_call(getattr(super(RetryingSession, self), method), fargs=args, fkwargs=kwargs, tries=3, delay=5,  File "/usr/lib/bazarr/bazarr/../libs/retry/api.py", line 101, in retry_call    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)  File "/usr/lib/bazarr/bazarr/../libs/retry/api.py", line 33, in __retry_internal    return f()  File "/usr/lib/bazarr/bazarr/../libs/requests/sessions.py", line 542, in get    return self.request('GET', url, **kwargs)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 60, in request    return super(TimeoutSession, self).request(method, url, *args, **kwargs)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 165, in request    ret = self._request(method, url, *args, **kwargs)  File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/http.py", line 84, in _request    resp._content = brotli.decompress(resp.content)brotli.error: BrotliDecompress failed|
03/09/2022 17:45:39|INFO    |root                            |Throttling subscene for 10 minutes, until 22/09/03 17:55, because of: error. Exception info: 'BrotliDecompress failed'|
```

**Comment by morpheus65535** [comment]
Subscene is a broken provider and I don't try to fix it anymore. It works for some but they put too much effort to prevent Bazarr connections. You can try to use subf2m instead.

**Comment by callym** [comment]
Thanks! Is it possible to add a warning somewhere saying it's broken so other people know?

**Comment by bphd** [comment]
I got it for soustitreseu titlovi subs4series too

**Comment by bphd** [comment]
Okay I came here having forgot that I've used to have that error. Annnnd, I still got the problem for the 3 others, still no resolution, seems ignored...

**Comment by morpheus65535** [comment]
@bphd this is the kind of stuff that happens when you necro a dead issue with unrelated stuff...

**Comment by bphd** [comment]
It's the same error, it's related in a way. Maybe just the reply you have given would be different

**Comment by morpheus65535** [comment]
@bphd it was closed for 4 months when you added your first comment.

**Comment by bphd** [comment]
Is the issue the same for all providers so we can generalize the BrotliDecompress problem?

**Comment by morpheus65535** [comment]
@bphd no we can't. Open your own issue and provide all the required informations including debug log while reproducing the issue.

**Comment by bphd** [comment]
How to get more precise logs than with `journalctl --unit=bazarr.service`?

**Comment by morpheus65535** [comment]
If you need support, come to Discord. This is a bug reporting system.
