### ISSUE TITLE
KeyError with embeddedsubtitles

### ISSUE THREAD

**Issue by PancakeZik** [morpheus65535/bazarr#1966]
Hi everyone,
I've been successfully using the embeddedsubtitles plugin to extract the sub embedded on my files, but a few of my files are throwing an error. It happens every time I try certain episodes.
It seems to be a problem with the codec, which is strange because these files are using H264, which normally shouldn't be a problem.
Here is what the logs say:

```
06/10/2022 17:41:46|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
06/10/2022 17:41:46|DEBUG   |fese.disposition                |Generic disposition title found: english plain srt|
06/10/2022 17:41:46|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
06/10/2022 17:41:46|DEBUG   |fese.disposition                |Generic disposition title found: english srt|
06/10/2022 17:41:46|ERROR   |subliminal_patch.core           |Unexpected error in provider 'embeddedsubtitles': Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 308, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 179, in list_subtitles    return self.query(  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 121, in query    streams = filter(_check_allowed_codecs, video.get_subtitles())  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 228, in get_subtitles    return super().get_subtitles(*args, **kwargs)  File "/app/bazarr/bin/bazarr/../libs/fese/container.py", line 66, in get_subtitles    subs.append(FFprobeSubtitleStream(stream))  File "/app/bazarr/bin/bazarr/../libs/fese/stream.py", line 23, in __init__    self.codec_name = stream["codec_name"]KeyError: 'codec_name'|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 308, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 179, in list_subtitles    return self.query(  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 121, in query    streams = filter(_check_allowed_codecs, video.get_subtitles())  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 228, in get_subtitles    return super().get_subtitles(*args, **kwargs)  File "/app/bazarr/bin/bazarr/../libs/fese/container.py", line 66, in get_subtitles    subs.append(FFprobeSubtitleStream(stream))  File "/app/bazarr/bin/bazarr/../libs/fese/stream.py", line 23, in __init__    self.codec_name = stream["codec_name"]KeyError: 'codec_name'|
06/10/2022 17:41:46|INFO    |root                            |Throttling embeddedsubtitles for 10 minutes, until 22/10/06 17:51, because of: KeyError. Exception info: 'codec_name'|
```

Any thoughts?
Thank you!

**Comment by morpheus65535** [comment]
@vitiko98 seems to be an issue with fese. You want to add some validation to deal with that edge case?

**Comment by vitiko98** [comment]
Fixed in upcoming beta. Thanks for the report
