### ISSUE TITLE
Cant execute wanted subtitle search

### ISSUE THREAD

**Issue by XenapZ** [morpheus65535/bazarr#199]
**Describe the bug**
Cant execute wanted subtitle search

**To Reproduce**
1. Go to Bazarr
2. Click on Wanted
3. Click on Download Wanted subtitles
4. See error:
Sorry, the requested URL 'http://192.168.1.173:6767/wanted_search_missing_subtitles' caused an error:

Internal Server Error

Exception:

AttributeError("'list' object has no attribute 'lower'",)

Traceback:

Traceback (most recent call last):
  File "/app/bazarr/libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr.py", line 140, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr.py", line 764, in wanted_search_missing_subtitles_list
    wanted_search_missing_subtitles()
  File "/app/bazarr/get_subtitle.py", line 455, in wanted_search_missing_subtitles
    wanted_download_subtitles(episode[0])
  File "/app/bazarr/get_subtitle.py", line 381, in wanted_download_subtitles
    message = download_subtitle(path_replace(episode[0]), str(alpha3_from_alpha2(language)), episode[4], providers_list, providers_auth, str(episode[5]), 'series')
  File "/app/bazarr/get_subtitle.py", line 66, in download_subtitle
    sorted_subtitles = sorted([(s, compute_score(s, video, hearing_impaired=hi)) for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/app/bazarr/libs/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/app/bazarr/libs/subliminal/providers/opensubtitles.py", line 81, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/app/bazarr/libs/subliminal/subtitle.py", line 244, in guess_matches
    and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'

**Expected behavior**
Download of wanted subtitles.

**Software (please complete the following information):**
 - Bazarr: [v0.6.6.3]
 - Radarr version [0.2.0.1120]
 - Sonarr version [2.0.0.5252]
 - OS: [unRAID 6.6.3]

**Additional context**

**Comment by morpheus65535** [comment]
This is fixed in dev branch that should be merge in less than a week.
