### ISSUE TITLE
Unexpected error in provider 'opensubtitles'

### ISSUE THREAD

**Issue by so1ar** [morpheus65535/bazarr#1997]
**Describe the bug**
Cannot search subtitles useing opensubtitles provider.

**To Reproduce**
1. Enabling debug logging;
2. searching for subtitles;
3. No results from opensubtitles;
4. In the log, I got this error:
 ```
Unexpected error in provider 'opensubtitles': Traceback (most recent call last): File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/core.py", line 311, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 271, in list_subtitles return self.query(video, languages, hash=video.hashes.get('opensubtitles'), size=video.size, File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/__init__.py", line 47, in wrapper return method(self, *args, **kwargs) File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 306, in query response = self.use_token_or_login( File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 220, in use_token_or_login return func() File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 307, in <lambda> lambda: self.retry(lambda: checked(lambda: self.server.SearchSubtitles(self.token, criteria))) File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/mixins.py", line 47, in retry return f() File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 307, in <lambda> lambda: self.retry(lambda: checked(lambda: self.server.SearchSubtitles(self.token, criteria))) File "/usr/lib/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 441, in checked raise ServiceUnavailable("Unknown Error, empty response: %s: %r" % (status_code, response))subliminal.exceptions.ServiceUnavailable: Unknown Error, empty response: None: None
 ```

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.1.2
 - Radarr version 4.2.4.6635
 - Sonarr version 3.0.9.1549
 - OS: Linux-5.15.78-1-MANJARO-ARM-RPI-aarch64-with-glibc2.35

**Additional context**

**Comment by so1ar** [comment]
That's really weird. For many days I cannot find a way to fix this problem. I tried deleting and adding the provider, restarting the service and rebooting the system, nothing worked. But right after I opened this issue, I restarted the service one more time, the problem went gone. I don't know why, but it woks now. :)

**Comment by halali** [comment]
this exception you get when opensubtitles api dont respond... so its overloaded or down... or your host does have issue to connect it... etc
