### ISSUE TITLE
Error when clicking on a serie

### ISSUE THREAD

**Issue by AciDCooL** [morpheus65535/bazarr#2]
Error: 500 Internal Server Error

Sorry, the requested URL 'https://***********/bazarr/episodes/1' caused an error:

Internal Server Error
Exception:

NameError("name 'actual_languages' is not defined",)
Traceback:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python3.5/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/Bazarr/bazarr.py", line 167, in episodes
    return template('episodes', no=no, details=series_details, seasons=seasons_list, url_sonarr_short=url_sonarr_short, base_url=base_url)
  File "/usr/lib/python3.5/site-packages/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python3.5/site-packages/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/lib/python3.5/site-packages/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/opt/Bazarr/views/episodes.tpl", line 160, in <module>
    %if actual_languages is not None:
NameError: name 'actual_languages' is not defined

Oh and can't run it under python 2.7.. only way is using python3

**Comment by morpheus65535** [comment]
I've not tested it under python 3.x. I'm using python 2.7 in development.

On the "Series" tab, do an "update all episodes" and wait until it finish. It's probably going to take some time as it open every mkv file to list internal subtitles track.

**Comment by AciDCooL** [comment]
I'll reinstall using the docker image and get back to that.

**Comment by AciDCooL** [comment]
Error: 500 Internal Server Error

Sorry, the requested URL 'http://*******:6767/episodes/1' caused an error:

Internal Server Error
Exception:

NameError("name 'actual_languages' is not defined",)
Traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/bazarr/bazarr.py", line 167, in episodes
    return template('episodes', no=no, details=series_details, seasons=seasons_list, url_sonarr_short=url_sonarr_short, base_url=base_url)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/bazarr/views/episodes.tpl", line 160, in <module>
    %if actual_languages is not None:
NameError: name 'actual_languages' is not defined

**Comment by morpheus65535** [comment]
Have you used path substitution? That's the kind of thing that happen when you got it set wrong. You want to share some screenshots so I can see what'S going wrong?

**Comment by morpheus65535** [comment]
I've putted together some instructions for the first run:

https://github.com/morpheus65535/bazarr/blob/master/README.md#first-run-important-to-read

Give it a try and give me your comment.

Thanks!

**Comment by AciDCooL** [comment]
Ah that makes sense since I'm running the docker container now. However everything is on the host of the docker instance, ill try and local mount dir's and report back

**Comment by morpheus65535** [comment]
I agree with you, I need to add more error management in the code.

It’s an early beta and I need more time to get it to be robust.

Thanks for your time!

**Comment by AciDCooL** [comment]
But ui and interaction works nice. Thank you for the hard work so far, really hope this blossoms into something beautiful.

**Comment by morpheus65535** [comment]
Hey @AciDCooL, if you want to give it a try again, you can. I've put more time to make the app more robust. Your feedback would be welcome. Please take the time to follow instructions in the readme file. Starting from scratch should be a good idea. :-)

Thanks!

**Comment by morpheus65535** [comment]
Issue resolved.
