### ISSUE TITLE
When pre-roll & webhook in plex is enabled an  KeyError: \'Guid\` is logged

### ISSUE THREAD

**Issue by Magikarplvl4** [morpheus65535/bazarr#2013]
**Describe the bug**
When a pre-roll video is configured in Plex in combination with a webook to Bazarr, every time a movie will be played there is an error logged in Bazarr

**To Reproduce**
Steps to reproduce the behaviour:
1. configure the webhook feature in plex to do a call to Bazarr
2. Enable Pre-roll video in Plex
3. Play a movie in plex (That will trigger the pre-roll to start)
4. See error in Bazarr

**Expected behavior**
Ignore pre-roll videos to trigger a subtitle search.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v1.1.3
 - Radarr version
 - Sonarr version 
 - OS: [e.g. Windows 10]

**Additional context**

```
Traceback (most recent call last):
  File "/app/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/app/bin/bazarr/api/webhooks/plex.py", line 52, in post
    for item in parsed_json_webhook[\'Metadata\'][\'Guid\']:
KeyError: \'Guid\

```

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?

**Comment by Magikarplvl4** [comment]
works!

**Comment by morpheus65535** [comment]
Thanks for the feedback! :-)
