### ISSUE TITLE
Bazarr not working on MacOS with python3.10 - BAZARR cannot bind to specified TCP port

### ISSUE THREAD

**Issue by kimme1024** [morpheus65535/bazarr#2026]
**Describe the bug**
After updating to MacOS Ventura and Python3.10, bazarr doesn't start anymore.

**To Reproduce**
`python3.10 bazarr.py`

**Expected behavior**
Bazarr should start and be accessible via the WebUI

**Screenshots**
/

**Software (please complete the following information):**
 - Bazarr: latest
 - Radarr version latest
 - Sonarr version latest
 - OS: MacOS 13.1

**Additional context**

```
2022-12-27 16:32:52,171 - root                             (1fbddfa80) :  ERROR (server:58) - BAZARR cannot bind to specified TCP port, trying with default (6767)
Traceback (most recent call last):
  File "/Applications/bazarr/bazarr/main.py", line 41, in <module>
    from app.server import webserver  # noqa E402
  File "/Applications/bazarr/bazarr/app/server.py", line 111, in <module>
    webserver = Server()
  File "/Applications/bazarr/bazarr/app/server.py", line 43, in __init__
    self.configure_server()
  File "/Applications/bazarr/bazarr/app/server.py", line 47, in configure_server
    self.server = create_server(app,
  File "/Applications/bazarr/bazarr/../libs/waitress/server.py", line 57, in create_server
    dispatcher.set_thread_count(adj.threads)
  File "/Applications/bazarr/bazarr/../libs/waitress/task.py", line 99, in set_thread_count
    self.start_new_thread(self.handler_thread, thread_no)
  File "/Applications/bazarr/bazarr/../libs/waitress/task.py", line 63, in start_new_thread
    t.start()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by morpheus65535** [comment]
What tcp port have you configured Bazarr to use?

**Comment by kimme1024** [comment]
Had some time checking it out today. Seems that some daemon I unsuccessfully installed earlier took over. I've shut that down and restarted the process and now it works.

**Comment by morpheus65535** [comment]
It was probably consuming all the available threads configured as maximum in your operating system.
