### ISSUE TITLE
Cannot view Series or Movies Tabs

### ISSUE THREAD

**Issue by ShaylinChetty** [morpheus65535/bazarr#2043]
When clicking the Series or Movie tabs an Error 500 is raised.
![image](https://user-images.githubusercontent.com/8532069/214181117-c3e3a051-c1f5-4675-b5a6-3aa10fd404dd.png)

Issue is present after reinstall. Adblocker and Pihole disabled with no luck. Debug log error provided below.

Bazaar still functions fine, subtitles are retrieved for new content, but neither of these two tabs will work.

```
Traceback (most recent call last):
  File "c:\bazarr\bazarr\../libs\flask_restx\fields.py", line 464, in format
    return int(value)
  ValueError: invalid literal for int() with base 10: 'null'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\bazarr\bazarr\../libs\flask_restx\fields.py", line 202, in output
    data = self.format(value)
  File "c:\bazarr\bazarr\../libs\flask_restx\fields.py", line 466, in format
    raise MarshallingError(ve)flask_restx.fields.Marshalling
  Error: invalid literal for int() with base 10: 'null'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\bazarr\bazarr\../libs\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\bazarr\bazarr\../libs\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\bazarr\bazarr\../libs\flask_restx\api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "c:\bazarr\bazarr\../libs\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "c:\bazarr\bazarr\../libs\flask_restx\resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "c:\bazarr\bazarr\api\utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 264, in wrapper
    return marshal(
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 54, in marshal
    out, has_wildcards = _marshal(data, fields, envelope, skip_none, mask, ordered)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 185, in _marshal
    out = OrderedDict(items) if ordered else dict(items)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 176, in <genexpr>
    else __format_field(k, v)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 170, in __format_field
    value = field.output(key, data, ordered=ordered)
  File "c:\bazarr\bazarr\../libs\flask_restx\fields.py", line 271, in output
    return marshal(value, self.nested, skip_none=self.skip_none, ordered=ordered)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 54, in marshal
    out, has_wildcards = _marshal(data, fields, envelope, skip_none, mask, ordered)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 159, in _marshal
    out = [marshal(d, fields, skip_none=skip_none, ordered=ordered) for d in data]
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 159, in <listcomp>
    out = [marshal(d, fields, skip_none=skip_none, ordered=ordered) for d in data]
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 54, in marshal
    out, has_wildcards = _marshal(data, fields, envelope, skip_none, mask, ordered)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 185, in _marshal
    out = OrderedDict(items) if ordered else dict(items)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 176, in <genexpr>
    else __format_field(k, v)
  File "c:\bazarr\bazarr\../libs\flask_restx\marshalling.py", line 170, in __format_field
    value = field.output(key, data, ordered=ordered)
  File "c:\bazarr\bazarr\../libs\flask_restx\fields.py", line 207, in output
    raise MarshallingError(msg)flask_restx.fields.Marshalling
  Error: Unable to marshal field "profileId" value "null": invalid literal for int() with base 10: 'null'
  ```

![image](https://user-images.githubusercontent.com/8532069/214182934-2907f6b7-eca4-41d2-8948-dff86e311e35.png)

**Comment by morpheus65535** [comment]
I'm not sure how this profile ID got corrupted in databse as there's already failsafe to prevent that but with my latest commit, it shouldn't prevent listing of series or movies. Can you test the upcoming 1.1.5-beta.6 and confirm if it fixes your issue?

**Comment by ShaylinChetty** [comment]
Thanks, resolved in the beta update.
