### ISSUE TITLE
Http 500 error when manually search for subtitle

### ISSUE THREAD

**Issue by kireque** [morpheus65535/bazarr#2056]
**Describe the bug**
When mannually search for subtitle error 500 shows. 

**To Reproduce**
- search manually for new subtitles

**Expected behavior**
no error

**Software (please complete the following information):**
 - Bazarr: v1.1.4
 - Sonarr version 3.0.9.1549
 - OS: Docker (Ubuntu)

**Additional context**
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/api/episodes/episodes_subtitles.py", line 72, in patch
    result = list(generate_subtitles(episodePath, [(language, hi, forced)], audio_language, sceneName,
  File "/app/bazarr/bin/bazarr/subtitles/pool.py", line 77, in decorated
    updated = _update_pool(args[args_spec.index("media_type")], profile_id)
  File "/app/bazarr/bin/bazarr/subtitles/pool.py", line 48, in _update_pool
    _pools[pool_key] = _init_pool(media_type, profile_id)
  File "/app/bazarr/bin/bazarr/subtitles/pool.py", line 21, in _init_pool
    provider_configs=get_providers_auth(),
  File "/app/bazarr/bin/bazarr/app/get_providers.py", line 157, in get_providers_auth
    \'is_vip\': settings.addic7ed.getboolean(\'vip\'),
  File "/app/bazarr/bin/bazarr/../libs/simpleconfigparser/__init__.py", line 72, in getboolean
    return self.parser.getboolean(self.section, name)
  File "/usr/lib/python3.10/configparser.py", line 829, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "/usr/lib/python3.10/configparser.py", line 809, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 804, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.10/configparser.py", line 1167, in _convert_to_boolean
    raise ValueError(\'Not a boolean: %s\' % value)
ValueError: Not a boolean:

**Comment by morpheus65535** [comment]
It seems that your config.ini got corrupted some how. You can edit this single value but it may be the sign of a bigger problem. Did you run out of disk space recently?

```
[addic7ed]
vip = False
```

**Comment by kireque** [comment]
This was indeed the source of issue.
I was unable to decipher the error, so was wondering how you could spot the issue so quick. But now I see that Addic7ed is mentioned in the error, as the boolean is as well...

Btw: Was clean install and saw this issue several hours after the initial installation. No issue regarding free space.
