### ISSUE TITLE
Mr. Robot s02e01 & s02e02 breaks Bazarr

### ISSUE THREAD

**Issue by rodalpho** [morpheus65535/bazarr#206]
I installed Bazarr a couple days ago, and for some reason it never seemed to get through all my files. It just stopped. The refresh job would die with 

`Job "Search for wanted subtitles (trigger: interval[3:00:00], next run at: 2018-10-28 00:26:45 EDT)" raised an exception`

And the traceback

`Traceback (most recent call last):
 File "/opt/Bazarr/libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/opt/Bazarr/get_subtitle.py", line 455, in wanted_search_missing_subtitles
  wanted_download_subtitles(episode[0])
 File "/opt/Bazarr/get_subtitle.py", line 381, in wanted_download_subtitles
  message = download_subtitle(path_replace(episode[0]), str(alpha3_from_alpha2(language)), episode[4], providers_list, providers_auth, str(episode[5]), \series\)
 File "/opt/Bazarr/get_subtitle.py", line 66, in download_subtitle
  sorted_subtitles = sorted([(s, compute_score(s, video, hearing_impaired=hi)) for s in subtitles], key=operator.itemgetter(1), reverse=True)
 File "/opt/Bazarr/libs/subliminal/score.py", line 106, in compute_score
  matches = subtitle.get_matches(video)
 File "/opt/Bazarr/libs/subliminal/providers/podnapisi.py", line 66, in get_matches
  matches `

So I started watching it with debug logging, and noticed it always seemed to die around the Ms. I thought maybe some other task was conflicting with it, because it was taking such a long time, but dropping the confidence all the way to 50 didn't fix it. So I went into the M's, and noticed that whenever I tried to refresh Mr Robot I got a 500 error. 

Exception:
`AttributeError("'list' object has no attribute 'lower'",)`

Traceback:
`Traceback (most recent call last):
  File "/opt/Bazarr/libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/Bazarr/libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/Bazarr/bazarr.py", line 140, in wrapper
    return func(*a, **ka)
  File "/opt/Bazarr/bazarr.py", line 600, in search_missing_subtitles
    series_download_subtitles(no)
  File "/opt/Bazarr/get_subtitle.py", line 323, in series_download_subtitles
    message = download_subtitle(path_replace(episode[0]), str(alpha3_from_alpha2(language)), series_details[0], providers_list, providers_auth, str(episode[3]), 'series')
  File "/opt/Bazarr/get_subtitle.py", line 66, in download_subtitle
    sorted_subtitles = sorted([(s, compute_score(s, video, hearing_impaired=hi)) for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/opt/Bazarr/libs/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/opt/Bazarr/libs/subliminal/providers/podnapisi.py", line 66, in get_matches
    matches |= guess_matches(video, guessit(release, {'type': 'episode'}))
  File "/opt/Bazarr/libs/subliminal/subtitle.py", line 244, in guess_matches
    and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'`

So I manually refreshed every subtitle for Mr. Robot, and found only two episodes caused the problem, s02e01 and s02e02. 

Names:
eps2.0_unm4sk-pt2.tc 
eps2.0_unm4sk-pt1.tc

When I try to manually refresh these two episodes specifically, I get this error:

`DataTables warning: table id=search_result - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

Maybe something in the episode names are a protected word, and the input isn't being validated in Bazarr? That's my guess, anyway.

**Comment by halali** [comment]
Dupe of #196 #199
