### ISSUE TITLE
"Error trying to get video information" for valid files

### ISSUE THREAD

**Issue by rodalpho** [morpheus65535/bazarr#207]
I have a bunch of files with this error. They all play fine in VLC, no errors, seeking works, etc.

Traceback in Bazarr:

`Traceback (most recent call last):
 File "/opt/Bazarr/get_subtitle.py", line 47, in download_subtitle
  video = scan_video(path)
 File "/opt/Bazarr/libs/subliminal/core.py", line 430, in scan_video
  video = Video.fromguess(path, guessit(path))
 File "/opt/Bazarr/libs/subliminal/video.py", line 93, in fromguess
  return Episode.fromguess(name, guess)
 File "/opt/Bazarr/libs/subliminal/video.py", line 170, in fromguess
  raise ValueError(\Insufficient data to process the guess\)
ValueError: Insufficient data to process the guess`

Mediainfo for one of the files:

```
General
Unique ID                                : 176787363559657803273879753350695270677 (0x850001FA63908B7A8CADF50140AAB915)
Complete name                            : /nas/TV/Through the Wormhole/Through the Wormhole - 2010-06-16 - The Riddle of Black Holes Bluray-720p.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 2.19 GiB
Duration                                 : 43 min 48 s
Overall bit rate                         : 7 145 kb/s
Encoded date                             : UTC 2011-04-19 15:35:55
Writing application                      : mkvmerge v4.0.0 ('The Stars were mine') built on Jun  6 2010 16:18:42
Writing library                          : libebml v1.0.0 + libmatroska v1.0.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 43 min 48 s
Bit rate                                 : 6 887 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.312
Stream size                              : 2.07 GiB (94%)
Writing library                          : x264 core 115 r1936 7a9e08d
Encoding settings                        : cabac=1 / ref=5 / deblock=1:0:0 / analyse=0x3:0x133 / me=esa / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=10 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=4 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=6887 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Default                                  : No
Forced                                   : No

Audio
ID                                       : 2
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 43 min 48 s
Bit rate mode                            : Constant
Bit rate                                 : 255 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 79.9 MiB (4%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

````

**Comment by halali** [comment]
it's probably becouse you have poorly named file... there is missing season and episode number, so guessit think is movie not series

**Comment by rodalpho** [comment]
I just did, did not fix the issue.

**Comment by morpheus65535** [comment]
Could you give us the full path for the file you’re having this error?

**Comment by rodalpho** [comment]
Sure:

`/nas/TV/Through the Wormhole/Through the Wormhole - 2010-07-21 - What Are We Really Made of Bluray-720p.mkv`

**Comment by morpheus65535** [comment]
If you have air date instead of season/episode number, there is almost no chance that it be recognized correctly by anything. Sonarr do not rename like this by default, you’ve ask it to do it that way.

**Comment by rodalpho** [comment]
Sure it does, for shows like the Daily Show, for example

`The Daily Show - 2018-10-17 - Julián Castro WEBDL-720p.mkv`

**Comment by morpheus65535** [comment]
You’ve renamed it to SxxExx?

**Comment by rodalpho** [comment]
I just renamed all the files to (for example) 

`Through the Wormhole - 1x02 - The Riddle of Black Holes Bluray-720p.mkv"`

And it looks like it is now working! That was indeed the problem. Thanks for your help!

**Comment by morpheus65535** [comment]
Pleasure!
