### ISSUE TITLE
postgres connection does not recover after broken connection (connection already closed)

### ISSUE THREAD

**Issue by jdeppa** [morpheus65535/bazarr#2075]
**Describe the bug**
Getting exception while syncing from radarr because postgres connection is broken, will not recover until restart

**To Reproduce**
1. After connection is broken, try syncing movie from radarr

**Expected behavior**
If connection to postgres is closed, try to reconnect

**Logs**
```
2023-02-27 10:17:01,157 - root                             (7fa51f5a3b38) :  DEBUG (logger:109) - Bazarr version: 1.1.5-beta.24
2023-02-27 10:17:01,251 - root                             (7fa51f5a3b38) :  DEBUG (logger:110) - Bazarr branch: development
2023-02-27 10:17:01,371 - root                             (7fa51f5a3b38) :  DEBUG (logger:111) - Operating system: Linux-5.15.0-58-generic-x86_64-with
2023-02-27 10:17:01,389 - root                             (7fa51f5a3b38) :  DEBUG (logger:112) - Python version: 3.10.10
2023-02-27 10:17:01,400 - socketio.server                  (7fa51f5a3b38) :  INFO (server:317) - emitting event "data" to all [/]
2023-02-27 10:17:01,401 - engineio.server                  (7fa51f5a3b38) :  INFO (socket:89) - yR5rxb6wOMvRRTwsAAAA: Sending packet MESSAGE data 2["data",{"type":"settings","action":"update","payload":null}]
2023-02-27 10:17:01,683 - peewee                           (7fa51f4a0b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:01,704 - peewee                           (7fa51f4a0b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1" WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:01,759 - engineio.server                  (7fa519efcb38) :  INFO (socket:89) - yR5rxb6wOMvRRTwsAAAA: Sending packet PING data None
2023-02-27 10:17:01,913 - peewee                           (7fa51f4a0b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = %s)', [0])
2023-02-27 10:17:01,919 - peewee                           (7fa51f39db38) :  DEBUG (peewee:3209) - ('SELECT "t1"."name", "t1"."enabled", "t1"."url" FROM "table_settings_notifier" AS "t1" ORDER BY "t1"."name"', [])
2023-02-27 10:17:01,920 - engineio.server                  (7fa51f29ab38) :  INFO (socket:52) - yR5rxb6wOMvRRTwsAAAA: Received packet PONG data 
2023-02-27 10:17:01,941 - peewee                           (7fa51f4a0b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."id", "t1"."timestamp", "t1"."hash", "t1"."text" FROM "table_announcements" AS "t1" WHERE ("t1"."hash" = %s) LIMIT %s OFFSET %s', ['678baaa09c5839568e79499e840cadfdbe8d36d3bf08d820fa12d03bbb46890a', 1, 0])
2023-02-27 10:17:08,315 - apscheduler.scheduler            (7fa521ddcb38) :  DEBUG (base:944) - Looking for jobs to run
2023-02-27 10:17:08,317 - socketio.server                  (7fa521ddcb38) :  INFO (server:317) - emitting event "data" to all [/]
2023-02-27 10:17:08,317 - apscheduler.executors.default    (7fa519fffb38) :  INFO (base:123) - Running job "Update Movie list from Radarr (trigger: interval[0:15:00], next run at: 2023-02-27 10:32:08 CET)" (scheduled at 2023-02-27 10:17:08.298512+01:00)
2023-02-27 10:17:08,325 - engineio.server                  (7fa521ddcb38) :  INFO (socket:89) - yR5rxb6wOMvRRTwsAAAA: Sending packet MESSAGE data 2["data",{"type":"task","action":"update","payload":null}]
2023-02-27 10:17:08,336 - apscheduler.scheduler            (7fa521ddcb38) :  DEBUG (base:1023) - Next wakeup is due at 2023-02-27 10:32:08.298512+01:00 (in 899.981705 seconds)
2023-02-27 10:17:08,336 - urllib3.connectionpool           (7fa519fffb38) :  DEBUG (connectionpool:228) - Starting new HTTP connection (1): radarr:7878
2023-02-27 10:17:08,345 - urllib3.connectionpool           (7fa519fffb38) :  DEBUG (connectionpool:456) - http://radarr:7878 "GET /api/system/status?apikey=radarrapikey HTTP/1.1" 404 0
2023-02-27 10:17:08,347 - urllib3.connectionpool           (7fa519fffb38) :  DEBUG (connectionpool:228) - Starting new HTTP connection (1): radarr:7878
2023-02-27 10:17:08,400 - urllib3.connectionpool           (7fa519fffb38) :  DEBUG (connectionpool:456) - http://radarr:7878 "GET /api/v3/system/status?apikey=radarrapikey HTTP/1.1" 200 None
2023-02-27 10:17:08,403 - root                             (7fa519fffb38) :  DEBUG (info:47) - BAZARR got this Radarr version from its API: 4.4.0.6882
2023-02-27 10:17:08,405 - urllib3.connectionpool           (7fa519fffb38) :  DEBUG (connectionpool:228) - Starting new HTTP connection (1): radarr:7878
2023-02-27 10:17:10,663 - urllib3.connectionpool           (7fa519fffb38) :  DEBUG (connectionpool:456) - http://radarr:7878 "GET /api/v3/rootfolder?apikey=radarrapikey HTTP/1.1" 200 None
2023-02-27 10:17:10,665 - peewee                           (7fa519fffb38) :  DEBUG (peewee:3209) - ('SELECT "t1"."path" FROM "table_movies" AS "t1"', [])
2023-02-27 10:17:10,672 - apscheduler.executors.default    (7fa519fffb38) :  ERROR (base:131) - Job "Update Movie list from Radarr (trigger: interval[0:15:00], next run at: 2023-02-27 10:32:08 CET)" raised an exception
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3219, in execute_sql
    cursor = self.cursor(commit)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3206, in cursor
    return self._state.conn.cursor()
psycopg2.InterfaceError: connection already closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/bazarr/bin/bazarr/radarr/sync/movies.py", line 27, in update_movies
    check_radarr_rootfolder()
  File "/app/bazarr/bin/bazarr/radarr/rootfolder.py", line 59, in check_radarr_rootfolder
    get_radarr_rootfolder()
  File "/app/bazarr/bin/bazarr/radarr/rootfolder.py", line 36, in get_radarr_rootfolder
    radarr_movies_paths = list(TableMovies.select(TableMovies.path).dicts())
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 7038, in __iter__
    self.execute()
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 1946, in inner
    return method(self, database, *args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 2017, in execute
    return self._execute(database)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 2190, in _execute
    cursor = database.execute(self)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3234, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3218, in execute_sql
    with __exception_wrapper__:
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 2994, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3219, in execute_sql
    cursor = self.cursor(commit)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3206, in cursor
    return self._state.conn.cursor()
peewee.InterfaceError: connection already closed
2023-02-27 10:17:10,676 - socketio.server                  (7fa519fffb38) :  INFO (server:317) - emitting event "data" to all [/]
2023-02-27 10:17:10,676 - engineio.server                  (7fa519fffb38) :  INFO (socket:89) - yR5rxb6wOMvRRTwsAAAA: Sending packet MESSAGE data 2["data",{"type":"task","action":"update","payload":null}]
2023-02-27 10:17:11,284 - peewee                           (7fa51ea82b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:11,335 - peewee                           (7fa51ea82b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1" WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:11,350 - peewee                           (7fa51ea82b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = %s)', [0])
2023-02-27 10:17:11,359 - peewee                           (7fa51ea82b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."id", "t1"."timestamp", "t1"."hash", "t1"."text" FROM "table_announcements" AS "t1" WHERE ("t1"."hash" = %s) LIMIT %s OFFSET %s', ['678baaa09c5839568e79499e840cadfdbe8d36d3bf08d820fa12d03bbb46890a', 1, 0])
2023-02-27 10:17:25,732 - peewee                           (7fa51e779b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:25,842 - peewee                           (7fa51e779b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1" WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:25,865 - peewee                           (7fa51e779b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = %s)', [0])
2023-02-27 10:17:25,925 - peewee                           (7fa51e779b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."id", "t1"."timestamp", "t1"."hash", "t1"."text" FROM "table_announcements" AS "t1" WHERE ("t1"."hash" = %s) LIMIT %s OFFSET %s', ['678baaa09c5839568e79499e840cadfdbe8d36d3bf08d820fa12d03bbb46890a', 1, 0])
2023-02-27 10:17:26,958 - engineio.server                  (7fa519efcb38) :  INFO (socket:89) - yR5rxb6wOMvRRTwsAAAA: Sending packet PING data None
2023-02-27 10:17:27,045 - engineio.server                  (7fa51e573b38) :  INFO (socket:52) - yR5rxb6wOMvRRTwsAAAA: Received packet PONG data 
2023-02-27 10:17:32,950 - peewee                           (7fa51e167b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:32,960 - peewee                           (7fa51e167b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1" WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:32,991 - peewee                           (7fa51e167b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = %s)', [0])
2023-02-27 10:17:33,004 - peewee                           (7fa51e167b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."id", "t1"."timestamp", "t1"."hash", "t1"."text" FROM "table_announcements" AS "t1" WHERE ("t1"."hash" = %s) LIMIT %s OFFSET %s', ['678baaa09c5839568e79499e840cadfdbe8d36d3bf08d820fa12d03bbb46890a', 1, 0])
2023-02-27 10:17:37,694 - peewee                           (7fa51e064b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:37,864 - peewee                           (7fa51e064b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1" WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:37,925 - peewee                           (7fa51e064b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = %s)', [0])
2023-02-27 10:17:37,928 - peewee                           (7fa51e064b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."id", "t1"."timestamp", "t1"."hash", "t1"."text" FROM "table_announcements" AS "t1" WHERE ("t1"."hash" = %s) LIMIT %s OFFSET %s', ['678baaa09c5839568e79499e840cadfdbe8d36d3bf08d820fa12d03bbb46890a', 1, 0])
2023-02-27 10:17:41,222 - peewee                           (7fa51dc58b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:41,239 - peewee                           (7fa51dc58b38) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1" WHERE (("t1"."missing_subtitles" IS NOT %s) AND ("t1"."missing_subtitles" != %s))) AS "_wrapped"', [None, '[]'])
2023-02-27 10:17:41,265 - peewee                           (7fa51dc58b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = %s)', [0])
2023-02-27 10:17:41,271 - peewee                           (7fa51dc58b38) :  DEBUG (peewee:3209) - ('SELECT "t1"."id", "t1"."timestamp", "t1"."hash", "t1"."text" FROM "table_announcements" AS "t1" WHERE ("t1"."hash" = %s) LIMIT %s OFFSET %s', ['678baaa09c5839568e79499e840cadfdbe8d36d3bf08d820fa12d03bbb46890a', 1, 0])
2023-02-27 10:17:52,083 - engineio.server                  (7fa519efcb38) :  INFO (socket:89) - yR5rxb6wOMvRRTwsAAAA: Sending packet PING data None
2023-02-27 10:17:52,138 - engineio.server                  (7fa51db55b38) :  INFO (socket:52) - yR5rxb6wOMvRRTwsAAAA: Received packet PONG data 
```

**Software (please complete the following information):**
 - Bazarr: 1.1.5-beta.24
 - OS: Ubuntu with Docker, linuxserver's image

**Additional context:**
`SELECT * FROM pg_stat_activity` does not show connection from bazarr when this happens

**Comment by halali** [comment]
why you create another issue ?

duplicate from #2071

**Comment by jdeppa** [comment]
Is this the same issue? This is about the postgres connection not recovering, #2071 is about not recovering from error while the connection is still intact.

For this, from postgres side, there is no connection from bazarr at all, while #2071 there is still connection between postgres and bazarr, just that postgres will not accept statements from the still valid connection.

**Comment by jdeppa** [comment]
Different errors too. For this: `peewee.InterfaceError: connection already closed`

For #2071 : `peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block`

**Comment by halali** [comment]
these issues are related... peewee have hard times to maintain connection pool for postgresql
