### ISSUE TITLE
[postgres]: column "year" of relation "table_shows" already exists

### ISSUE THREAD

**Issue by volker-raschek** [morpheus65535/bazarr#2082]
**Describe the bug**

```text
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 22, in <module>
    from init import *  # noqa E402
  File "/app/bazarr/bin/bazarr/init.py", line 236, in <module>
    migrate_db()
  File "/app/bazarr/bin/bazarr/app/database.py", line 350, in migrate_db
    migrate(migrator.add_column('table_shows', 'year', TextField(null=True)))
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 886, in migrate
    operation.run()
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 158, in _handle_result
    self._handle_result(item)
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 155, in _handle_result
    result.run()
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 153, in _handle_result
    self.execute(result)
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 149, in execute
    self.migrator.database.execute(node)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3234, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/app/bazarr/bin/bazarr/../libs/playhouse/shortcuts.py", line 254, in execute_sql
    raise exc
  File "/app/bazarr/bin/bazarr/../libs/playhouse/shortcuts.py", line 250, in execute_sql
    return super(ReconnectMixin, self).execute_sql(sql, params, commit)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3218, in execute_sql
    with __exception_wrapper__:
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 2994, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3221, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: column "year" of relation "table_shows" already exists
``` 

**To Reproduce**

Setup a new bazarr v1.2.0 instance with postgres backend. 

**Expected behavior**

Database scheme should be correctly initialized.

**Software (please complete the following information):**

 - Bazarr: v1.2.0
 - OS: Arch Linux
 - Kubernetes: 1.26.1

**Additional context**

Deploy bazarr on kubernetes. Mount config, series and tv shows as persistent volume claim into the pod. Create a dedicated database schema/user on postgres. 

```sql
CREATE SCHEMA ${USER};
CREATE USER ${USER} WITH LOGIN PASSWORD '${PASSWORD}';
GRANT ALL ON SCHEMA ${USER} TO ${USER}; 
ALTER USER ${USER} SET search_path=${USER};
```

Reference the created database scheme/user in my `config.ini`

```ini
[postgresql]
enabled = True
host = postgres.example.com
port = 5432
database = postgres
username = bazarr
password = "sensitive"
```

**Comment by halali** [comment]
can you provide full debug log of bazarr startup with postgresql enabled ?

**Comment by volker-raschek** [comment]
Sure

```text
[custom-init] No custom files found, skipping...
2023-03-03 20:46:10,327 - root                             (7f954ce19b48) :  DEBUG (logger:109) - Bazarr version: 1.2.0
2023-03-03 20:46:10,328 - root                             (7f954ce19b48) :  DEBUG (logger:110) - Bazarr branch: master
2023-03-03 20:46:10,334 - root                             (7f954ce19b48) :  DEBUG (logger:111) - Operating system: Linux-5.15.94-1-lts-x86_64-with
2023-03-03 20:46:10,334 - root                             (7f954ce19b48) :  DEBUG (logger:112) - Python version: 3.10.10
2023-03-03 20:46:12,897 - app.database                     (7f954ce19b48) :  DEBUG (database:36) - Connecting to PostgreSQL database: postgres.example.com:5432/postgres
2023-03-03 20:46:12,915 - root                             (7f954ce19b48) :  DEBUG (binaries:47) - BAZARR returning this binary: /usr/bin/ffprobe
2023-03-03 20:46:12,917 - root                             (7f954ce19b48) :  DEBUG (binaries:47) - BAZARR returning this binary: /usr/bin/ffmpeg
2023-03-03 20:46:12,923 - urllib3.connectionpool           (7f954ce19b48) :  DEBUG (connectionpool:1003) - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2023-03-03 20:46:13,194 - urllib3.connectionpool           (7f954ce19b48) :  DEBUG (connectionpool:456) - https://raw.githubusercontent.com:443 "GET /morpheus65535/bazarr-binaries/master/announcements.json HTTP/1.1" 200 226
2023-03-03 20:46:13,201 - root                             (7f954ce19b48) :  DEBUG (init:183) - BAZARR Created announcements file
2023-03-03 20:46:13,205 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = %s ORDER BY tablename', ('public',))
2023-03-03 20:46:13,226 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "system" ("configured" TEXT, "updated" TEXT)', [])
2023-03-03 20:46:13,230 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_announcements" ("id" SERIAL NOT NULL PRIMARY KEY, "timestamp" TIMESTAMP NOT NULL, "hash" TEXT, "text" TEXT)', [])
2023-03-03 20:46:13,233 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE UNIQUE INDEX IF NOT EXISTS "tableannouncements_hash" ON "table_announcements" ("hash")', [])
2023-03-03 20:46:13,240 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_blacklist" ("language" TEXT, "provider" TEXT, "sonarr_episode_id" INTEGER, "sonarr_series_id" INTEGER, "subs_id" TEXT, "timestamp" TIMESTAMP)', [])
2023-03-03 20:46:13,244 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_blacklist_movie" ("language" TEXT, "provider" TEXT, "radarr_id" INTEGER, "subs_id" TEXT, "timestamp" TIMESTAMP)', [])
2023-03-03 20:46:13,249 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_custom_score_profiles" ("id" SERIAL NOT NULL PRIMARY KEY, "name" TEXT, "media" TEXT, "score" INTEGER)', [])
2023-03-03 20:46:13,253 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_custom_score_profile_conditions" ("id" SERIAL NOT NULL PRIMARY KEY, "profile_id" INTEGER NOT NULL, "type" TEXT, "value" TEXT, "required" BOOLEAN NOT NULL, "negate" BOOLEAN NOT NULL, FOREIGN KEY ("profile_id") REFERENCES "table_custom_score_profiles" ("id"))', [])
2023-03-03 20:46:13,259 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE INDEX IF NOT EXISTS "tablecustomscoreprofileconditions_profile_id" ON "table_custom_score_profile_conditions" ("profile_id")', [])
2023-03-03 20:46:13,265 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_episodes" ("rowid" SERIAL NOT NULL PRIMARY KEY, "audio_codec" TEXT, "audio_language" TEXT, "episode" INTEGER NOT NULL, "episode_file_id" INTEGER, "failedAttempts" TEXT, "ffprobe_cache" BYTEA, "file_size" BIGINT, "format" TEXT, "missing_subtitles" TEXT, "monitored" TEXT, "path" TEXT NOT NULL, "resolution" TEXT, "sceneName" TEXT, "season" INTEGER NOT NULL, "sonarrEpisodeId" INTEGER NOT NULL, "sonarrSeriesId" INTEGER NOT NULL, "subtitles" TEXT, "title" TEXT NOT NULL, "video_codec" TEXT)', [])
2023-03-03 20:46:13,268 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE UNIQUE INDEX IF NOT EXISTS "tableepisodes_sonarrEpisodeId" ON "table_episodes" ("sonarrEpisodeId")', [])
2023-03-03 20:46:13,272 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_history" ("id" SERIAL NOT NULL PRIMARY KEY, "action" INTEGER NOT NULL, "description" TEXT NOT NULL, "language" TEXT, "provider" TEXT, "score" INTEGER, "sonarrEpisodeId" INTEGER NOT NULL, "sonarrSeriesId" INTEGER NOT NULL, "subs_id" TEXT, "subtitles_path" TEXT, "timestamp" TIMESTAMP NOT NULL, "video_path" TEXT)', [])
2023-03-03 20:46:13,276 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_history_movie" ("id" SERIAL NOT NULL PRIMARY KEY, "action" INTEGER NOT NULL, "description" TEXT NOT NULL, "language" TEXT, "provider" TEXT, "radarrId" INTEGER NOT NULL, "score" INTEGER, "subs_id" TEXT, "subtitles_path" TEXT, "timestamp" TIMESTAMP NOT NULL, "video_path" TEXT)', [])
2023-03-03 20:46:13,279 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_languages_profiles" ("profileId" SERIAL NOT NULL PRIMARY KEY, "cutoff" INTEGER, "originalFormat" BOOLEAN, "items" TEXT NOT NULL, "name" TEXT NOT NULL, "mustContain" TEXT, "mustNotContain" TEXT)', [])
2023-03-03 20:46:13,284 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_movies" ("rowid" SERIAL NOT NULL PRIMARY KEY, "alternativeTitles" TEXT, "audio_codec" TEXT, "audio_language" TEXT, "failedAttempts" TEXT, "fanart" TEXT, "ffprobe_cache" BYTEA, "file_size" BIGINT, "format" TEXT, "imdbId" TEXT, "missing_subtitles" TEXT, "monitored" TEXT, "movie_file_id" INTEGER, "overview" TEXT, "path" TEXT NOT NULL, "poster" TEXT, "profileId" INTEGER, "radarrId" INTEGER NOT NULL, "resolution" TEXT, "sceneName" TEXT, "sortTitle" TEXT, "subtitles" TEXT, "tags" TEXT, "title" TEXT NOT NULL, "tmdbId" TEXT NOT NULL, "video_codec" TEXT, "year" TEXT)', [])
2023-03-03 20:46:13,288 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE UNIQUE INDEX IF NOT EXISTS "tablemovies_path" ON "table_movies" ("path")', [])
2023-03-03 20:46:13,291 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE UNIQUE INDEX IF NOT EXISTS "tablemovies_radarrId" ON "table_movies" ("radarrId")', [])
2023-03-03 20:46:13,293 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE UNIQUE INDEX IF NOT EXISTS "tablemovies_tmdbId" ON "table_movies" ("tmdbId")', [])
2023-03-03 20:46:13,297 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_movies_rootfolder" ("accessible" INTEGER, "error" TEXT, "id" INTEGER, "path" TEXT)', [])
2023-03-03 20:46:13,299 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_settings_languages" ("code3" TEXT NOT NULL PRIMARY KEY, "code2" TEXT, "code3b" TEXT, "enabled" INTEGER, "name" TEXT NOT NULL)', [])
2023-03-03 20:46:13,302 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_settings_notifier" ("name" TEXT PRIMARY KEY, "enabled" INTEGER, "url" TEXT)', [])
2023-03-03 20:46:13,305 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_shows" ("tvdbId" SERIAL NOT NULL PRIMARY KEY, "alternativeTitles" TEXT, "audio_language" TEXT, "fanart" TEXT, "imdbId" TEXT, "monitored" TEXT, "overview" TEXT, "path" TEXT NOT NULL, "poster" TEXT, "profileId" INTEGER, "seriesType" TEXT, "sonarrSeriesId" INTEGER NOT NULL, "sortTitle" TEXT, "tags" TEXT, "title" TEXT NOT NULL, "year" TEXT)', [])
2023-03-03 20:46:13,312 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE UNIQUE INDEX IF NOT EXISTS "tableshows_path" ON "table_shows" ("path")', [])
2023-03-03 20:46:13,316 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE UNIQUE INDEX IF NOT EXISTS "tableshows_sonarrSeriesId" ON "table_shows" ("sonarrSeriesId")', [])
2023-03-03 20:46:13,318 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('CREATE TABLE IF NOT EXISTS "table_shows_rootfolder" ("accessible" INTEGER, "error" TEXT, "id" INTEGER, "path" TEXT)', [])
2023-03-03 20:46:13,321 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('SELECT COUNT(1) FROM (SELECT 1 FROM "system" AS "t1") AS "_wrapped"', [])
2023-03-03 20:46:13,326 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT column_name, is_nullable, data_type, column_default\n            FROM information_schema.columns\n            WHERE table_name = %s AND table_schema = %s\n            ORDER BY ordinal_position', ('table_shows', 'public'))
2023-03-03 20:46:13,343 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT kc.column_name\n            FROM information_schema.table_constraints AS tc\n            INNER JOIN information_schema.key_column_usage AS kc ON (\n                tc.table_name = kc.table_name AND\n                tc.table_schema = kc.table_schema AND\n                tc.constraint_name = kc.constraint_name)\n            WHERE\n                tc.constraint_type = %s AND\n                tc.table_name = %s AND\n                tc.table_schema = %s', ('PRIMARY KEY', 'table_shows', 'public'))
2023-03-03 20:46:13,353 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT column_name, is_nullable, data_type, column_default\n            FROM information_schema.columns\n            WHERE table_name = %s AND table_schema = %s\n            ORDER BY ordinal_position', ('table_episodes', 'public'))
2023-03-03 20:46:13,362 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT kc.column_name\n            FROM information_schema.table_constraints AS tc\n            INNER JOIN information_schema.key_column_usage AS kc ON (\n                tc.table_name = kc.table_name AND\n                tc.table_schema = kc.table_schema AND\n                tc.constraint_name = kc.constraint_name)\n            WHERE\n                tc.constraint_type = %s AND\n                tc.table_name = %s AND\n                tc.table_schema = %s', ('PRIMARY KEY', 'table_episodes', 'public'))
2023-03-03 20:46:13,369 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT column_name, is_nullable, data_type, column_default\n            FROM information_schema.columns\n            WHERE table_name = %s AND table_schema = %s\n            ORDER BY ordinal_position', ('table_movies', 'public'))
2023-03-03 20:46:13,378 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT kc.column_name\n            FROM information_schema.table_constraints AS tc\n            INNER JOIN information_schema.key_column_usage AS kc ON (\n                tc.table_name = kc.table_name AND\n                tc.table_schema = kc.table_schema AND\n                tc.constraint_name = kc.constraint_name)\n            WHERE\n                tc.constraint_type = %s AND\n                tc.table_name = %s AND\n                tc.table_schema = %s', ('PRIMARY KEY', 'table_movies', 'public'))
2023-03-03 20:46:13,385 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT column_name, is_nullable, data_type, column_default\n            FROM information_schema.columns\n            WHERE table_name = %s AND table_schema = %s\n            ORDER BY ordinal_position', ('table_history', 'public'))
2023-03-03 20:46:13,394 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT kc.column_name\n            FROM information_schema.table_constraints AS tc\n            INNER JOIN information_schema.key_column_usage AS kc ON (\n                tc.table_name = kc.table_name AND\n                tc.table_schema = kc.table_schema AND\n                tc.constraint_name = kc.constraint_name)\n            WHERE\n                tc.constraint_type = %s AND\n                tc.table_name = %s AND\n                tc.table_schema = %s', ('PRIMARY KEY', 'table_history', 'public'))
2023-03-03 20:46:13,400 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT column_name, is_nullable, data_type, column_default\n            FROM information_schema.columns\n            WHERE table_name = %s AND table_schema = %s\n            ORDER BY ordinal_position', ('table_history_movie', 'public'))
2023-03-03 20:46:13,410 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT kc.column_name\n            FROM information_schema.table_constraints AS tc\n            INNER JOIN information_schema.key_column_usage AS kc ON (\n                tc.table_name = kc.table_name AND\n                tc.table_schema = kc.table_schema AND\n                tc.constraint_name = kc.constraint_name)\n            WHERE\n                tc.constraint_type = %s AND\n                tc.table_name = %s AND\n                tc.table_schema = %s', ('PRIMARY KEY', 'table_history_movie', 'public'))
2023-03-03 20:46:13,416 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT column_name, is_nullable, data_type, column_default\n            FROM information_schema.columns\n            WHERE table_name = %s AND table_schema = %s\n            ORDER BY ordinal_position', ('table_languages_profiles', 'public'))
2023-03-03 20:46:13,426 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('\n            SELECT kc.column_name\n            FROM information_schema.table_constraints AS tc\n            INNER JOIN information_schema.key_column_usage AS kc ON (\n                tc.table_name = kc.table_name AND\n                tc.table_schema = kc.table_schema AND\n                tc.constraint_name = kc.constraint_name)\n            WHERE\n                tc.constraint_type = %s AND\n                tc.table_name = %s AND\n                tc.table_schema = %s', ('PRIMARY KEY', 'table_languages_profiles', 'public'))
2023-03-03 20:46:13,433 - peewee                           (7f954ce19b48) :  DEBUG (peewee:3209) - ('ALTER TABLE "table_shows" ADD COLUMN "year" TEXT', [])
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3221, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.DuplicateColumn: column "year" of relation "table_shows" already exists


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 22, in <module>
    from init import *  # noqa E402
  File "/app/bazarr/bin/bazarr/init.py", line 236, in <module>
    migrate_db()
  File "/app/bazarr/bin/bazarr/app/database.py", line 350, in migrate_db
    migrate(migrator.add_column('table_shows', 'year', TextField(null=True)))
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 886, in migrate
    operation.run()
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 158, in _handle_result
    self._handle_result(item)
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 155, in _handle_result
    result.run()
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 153, in _handle_result
    self.execute(result)
  File "/app/bazarr/bin/bazarr/../libs/playhouse/migrate.py", line 149, in execute
    self.migrator.database.execute(node)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3234, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/app/bazarr/bin/bazarr/../libs/playhouse/shortcuts.py", line 254, in execute_sql
    raise exc
  File "/app/bazarr/bin/bazarr/../libs/playhouse/shortcuts.py", line 250, in execute_sql
    return super(ReconnectMixin, self).execute_sql(sql, params, commit)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3218, in execute_sql
    with __exception_wrapper__:
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 2994, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 3221, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: column "year" of relation "table_shows" already exists
```

**Comment by halali** [comment]
im not able to reproduce this,

but it should be connected with this
ALTER USER ${USER} SET search_path=${USER};
you are set default schema as your username.

never test it with different schema than public

**Comment by volker-raschek** [comment]
Ahaa okay, that is of course a pity. For me all applications like gitea, drone, homeassistant, nextcloud ect get their own schema on the same database. So there is no need to manage and backup a separate database for each application. 

Can we turn the defect into a feature request for the next version? Surely not only me, but also many others would be happy about this feature.

**Comment by halali** [comment]
Best practise is use one db per application.

It will be time consuming to implement schema support with almost no benefit.
You can open FR for this...
