### ISSUE TITLE
Bazaar does not want to run... 

### ISSUE THREAD

**Issue by AiOGajo** [morpheus65535/bazarr#2089]
I am trying to run Bazaar in Ubuntu Server, but when I do:

`python3 bazarr.py`

This happens:

```
Bazarr starting...
Traceback (most recent call last):
  File "/home/USER/bazarr-master/bazarr/main.py", line 22, in <module>
    from init import *  # noqa E402
  File "/home/USER/bazarr-master/bazarr/init.py", line 13, in <module>
    from subliminal_patch.extensions import provider_registry
  File "/home/USER/bazarr-master/bazarr/../libs/subliminal_patch/__init__.py", line 8, in <module>
    from .providers import Provider
  File "/home/USER/bazarr-master/bazarr/../libs/subliminal_patch/providers/__init__.py", line 12, in <module>
    from subliminal_patch.extensions import provider_registry
  File "/home/USER/bazarr-master/bazarr/../libs/subliminal_patch/extensions.py", line 61, in <module>
    subliminal.refiner_manager.register('sz_omdb = subliminal_patch.refiners.omdb:refine')
  File "/home/USER/bazarr-master/bazarr/../libs/subliminal/extensions.py", line 65, in register
    ext = self._load_one_plugin(ep, False, (), {}, False)
  File "/home/USER/bazarr-master/bazarr/../libs/stevedore/extension.py", line 261, in _load_one_plugin
    plugin = ep.resolve()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2474, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/USER/bazarr-master/bazarr/../libs/subliminal_patch/refiners/omdb.py", line 9, in <module>
    from subliminal_patch.http import TimeoutSession
  File "/home/USER/bazarr-master/bazarr/../libs/subliminal_patch/http.py", line 24, in <module>
    from subliminal_patch.pitcher import pitchers
  File "/home/USER/bazarr-master/bazarr/../libs/subliminal_patch/pitcher.py", line 10, in <module>
    from python_anticaptcha import AnticaptchaClient, NoCaptchaTaskProxylessTask, NoCaptchaTask, AnticaptchaException
  File "/home/USER/bazarr-master/bazarr/../libs/python_anticaptcha/__init__.py", line 26, in <module>
    __version__ = get_distribution(__name__).version
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 514, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 386, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    env = Environment(self.entries)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2685, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.1build1' (package: distro-info)
Bazarr exited.
```

I am doing something wrong? 
Thanks

**Comment by halali** [comment]
Downgrade your python3-distro-info ubuntu package.

**Comment by AiOGajo** [comment]
I installed python3.8 alongside. python3.10

Then, installed python3.8-discutils

Then changed the service to:

ExecStart=/usr/bin/python3.8 /home/USER/Bazarr/bazarr.py

and done. 

It's working again. 

thanks for the help
