### ISSUE TITLE
Error when manual searching: Error 500 - You have disconnected from the server

### ISSUE THREAD

**Issue by Krolitian** [morpheus65535/bazarr#2102]
**Describe the bug**
An error pops up when attempting to manually search a show's subtitles. Movies are working as intended.

**To Reproduce**
Do a manual search of a TV show episode. Receive error.

**Expected behavior**
No error and subtitles to successfully search.

**Software (please complete the following information):**
 - Bazarr: v1.2.0
 - Sonarr v3.0.10.1567
 - OS: Unraid v6.11.5

**Additional context**
The error shown in logs is as follows:

Exception on /api/providers/episodes [GET]

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/api/providers/providers_episodes.py", line 69, in get
    data = manual_search(episodePath, profileId, providers_list, sceneName, title, \'series\')
  File "/app/bazarr/bin/bazarr/subtitles/pool.py", line 85, in decorated
    return f(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/subtitles/manual.py", line 86, in manual_search
    logging.debug(f"BAZARR Skipping {s}, because it doesn\'t match our series/episode")
TypeError: __str__ returned non-string (type bytes)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Please test and confirm.

**Comment by Krolitian** [comment]
Can confirm that beta no longer has the error, thanks.
