### ISSUE TITLE
500 Disconnected from server when clicking on Series

### ISSUE THREAD

**Issue by jeremysherriff** [morpheus65535/bazarr#2114]
**Describe the bug**
Every time I attempt to enter the Series part of the GUI, I receive a 500 disconnected message and no TV series are shown.
Log shows:
```
Exception on /bazarr/api/series [GET]|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/fields.py", line 464, in format\n    return int(value)\nValueError: invalid literal for int() with base 10: \'None\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/fields.py", line 202, in output\n    data = self.format(value)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/fields.py", line 466, in format\n    raise MarshallingError(ve)\nflask_restx.fields.MarshallingError: invalid literal for int() with base 10: \'None\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper\n    resp = resource(*args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view\n    return current_app.ensure_sync(self.dispatch_request)(**kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request\n    resp = meth(*args, **kwargs)\n  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper\n    return actual_method(*args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 264, in wrapper\n    return marshal(\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 54, in marshal\n    out, has_wildcards = _marshal(data, fields, envelope, skip_none, mask, ordered)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 185, in _marshal\n    out = OrderedDict(items) if ordered else dict(items)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 176, in <genexpr>\n    else __format_field(k, v)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 170, in __format_field\n    value = field.output(key, data, ordered=ordered)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/fields.py", line 271, in output\n    return marshal(value, self.nested, skip_none=self.skip_none, ordered=ordered)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 54, in marshal\n    out, has_wildcards = _marshal(data, fields, envelope, skip_none, mask, ordered)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 159, in _marshal\n    out = [marshal(d, fields, skip_none=skip_none, ordered=ordered) for d in data]\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 159, in <listcomp>\n    out = [marshal(d, fields, skip_none=skip_none, ordered=ordered) for d in data]\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 54, in marshal\n    out, has_wildcards = _marshal(data, fields, envelope, skip_none, mask, ordered)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 185, in _marshal\n    out = OrderedDict(items) if ordered else dict(items)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 176, in <genexpr>\n    else __format_field(k, v)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 170, in __format_field\n    value = field.output(key, data, ordered=ordered)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/fields.py", line 207, in output\n    raise MarshallingError(msg)\nflask_restx.fields.MarshallingError: Unable to marshal field "profileId" value "None": invalid literal for int() with base 10: \'None\''|
```

**To Reproduce**
1. Go to Bazarr web UI
2. Click on Series
3. See error

**Expected behavior**
A list of the Series available in Sonarr should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1082213/230703299-4e7ac2d3-49ff-4bd2-bae4-629ed3f1cc3a.png)

**Software (please complete the following information):**
Running in LSIO Docker container:
- Bazarr Version    1.2.0
- Package Version    v1.2.0-ls191 by linuxserver.io
- Sonarr Version    3.0.10.1567
- Radarr Version    4.3.2.6857
- Operating System    Linux-5.15.0-69-generic-x86_64-with
- Python Version     3.10.10

**Additional context**
When I restart the container, I see Bazarr correctly enumerate the series in Sonarr, and the Sonarr connection test is successful.  I suspect the series info is not being populated in the Bazarr database correctly.

I don't think this is related, but for completeness:  At some time in the last few months all my Bazarr settings were lost, presumably from a DB corruption.  I don't keep a close eye so this may have been up to a year ago.  I attempted to restore from backup (31-day retention) and was not able to get a working system, so I set up all connections again today.

**Comment by jeremysherriff** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/11182545/bazarr.log)

**Comment by morpheus65535** [comment]
Can you provide your bazarr.db in private on Discord please? Something seems to be corrupted in your series table and I would like to understand what.

**Comment by jeremysherriff** [comment]
Done. 
Diagnosed as "Corrupted value as languages profile for shows."
Received back a modified backup file to restore, issue resolved.
