### ISSUE TITLE
Error 500 When Manual Searching Episode

### ISSUE THREAD

**Issue by xen0m0rph2020** [morpheus65535/bazarr#2119]
**Describe the bug**
When you do a manual search on a episode i get error 500
The log is as below

`Traceback (most recent call last):
  File "/app/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/app/bin/bazarr/../libs/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/app/bin/bazarr/api/providers/providers_episodes.py", line 69, in get
    data = manual_search(episodePath, profileId, providers_list, sceneName, title, \'series\')
  File "/app/bin/bazarr/subtitles/pool.py", line 85, in decorated
    return f(*args, **kwargs)
  File "/app/bin/bazarr/subtitles/manual.py", line 86, in manual_search
    logging.debug(f"BAZARR Skipping {s}, because it doesn\'t match our series/episode")
TypeError: __str__ returned non-string (type bytes)`

**To Reproduce**
Search for a episode using manual search

**Expected behavior**
You should get results of search

**Software (please complete the following information):**
 - Bazarr: 1.2.0
 - OS: Linux Container

**Additional context**

**Comment by morpheus65535** [comment]
Fixed in beta.

**Comment by xen0m0rph2020** [comment]
thanks
