### ISSUE TITLE
Error 500 You have disconnected from the server

### ISSUE THREAD

**Issue by maximunited** [morpheus65535/bazarr#2122]
**Describe the bug**
Unable to manually search for subtitles for a specific episode for a TV show

**To Reproduce**
1. Go to 'TV shows'
2. Click on 'Manual search' for a specific episode
3. See error:
Error 500
You have disconnected from the server

**Expected behavior**
Manual search should work

**Error from log**
```
Exception on /api/providers/episodes [GET]|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
resp = resource(*args, **kwargs)  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
return current_app.ensure_sync(self.dispatch_request)(**kwargs)  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
resp = meth(*args, **kwargs)  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
return actual_method(*args, **kwargs)  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 244, in wrapper
resp = f(*args, **kwargs)  File "/app/bazarr/bin/bazarr/api/providers/providers_episodes.py", line 69, in get
data = manual_search(episodePath, profileId, providers_list, sceneName, title, 'series')  File "/app/bazarr/bin/bazarr/subtitles/pool.py", line 85, in decorated
return f(*args, **kwargs)  File "/app/bazarr/bin/bazarr/subtitles/manual.py", line 86, in manual_search
logging.debug(f"BAZARR Skipping {s}, because it doesn't match our series/episode")TypeError: __str__ returned non-string (type bytes)
```

**Software (please complete the following information):**
Bazarr Version
1.2.0
Package Version
v1.2.0-ls193 by linuxserver.io
Sonarr Version
3.0.10.1567
Radarr Version
4.4.4.7068
Operating System
Linux-5.4.0-146-generic-x86_64-with
Python Version
3.10.11

**Additional context**

**Comment by halali** [comment]
Multi duplicate... Fixed in development
