### ISSUE TITLE
Know It error + Could it be corrupted error

### ISSUE THREAD

**Issue by KevinBoone90** [morpheus65535/bazarr#2123]
**Describe the bug**
```
2023-04-21 17:48:18,363 - root                             (7f470f6bfb38) :  ERROR (video_analyzer:156) - BAZARR ffprobe cannot analyze this video file /NASext2/TV-Series/American Gods/Season 3/American Gods - S03E08 - The Rapture of Burning Bluray-1080p.mkv. Could it be corrupted? +-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
|                   libmediainfo.so.0                   |
|                         v22.9                         |
|                                                       |
|                   /usr/bin/ffprobe                    |
|                        v5.1.3                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.1                         |
+-------------------------------------------------------+
|                   provider: ffmpeg                    |
|               ffmpeg: /usr/bin/ffprobe                |
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 218, in describe
    data = self.executor.extract_info(video_path)
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 79, in extract_info
    json_dump = self._execute(filename)
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 113, in _execute
    return check_output([self.location, '-v', 'quiet', '-print_format', 'json',
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/NASext2/TV-Series/American Gods/Season 3/American Gods - S03E08 - The Rapture of Burning Bluray-1080p.mkv']' returned non-zero exit status 1.
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.     
```

**Software (please complete the following information):**
 - Bazarr: 1.2.0
 - Radarr version 4.4.4.7068
 - Sonarr version 3.0.9.1555
 - OS: Proxmox / LXC container

Seeing this error in the Bazarr log
`BAZARR ffprobe cannot analyze this video file /NASext2/TV-Series/American Gods/Season 3/American Gods - S03E08 - The Rapture of Burning Bluray-1080p.mkv. Could it be corrupted? +-------------------------------------------------------+`

**Comment by morpheus65535** [comment]
Open the file in VLC, it wont play.

**Comment by KevinBoone90** [comment]
Yes it plays in VLC

**Comment by morpheus65535** [comment]
Is it the only file you get this issue? I suggest you come by Discord for support. This isn't a bug.
