### ISSUE TITLE
(7f79d06a8b38) :  ERROR (app:1741) - Exception on /bazarr/api/movies [PATCH]

### ISSUE THREAD

**Issue by bndzor** [morpheus65535/bazarr#2124]
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/api/movies/movies.py", line 156, in patch
    movies_download_subtitles(radarrid)
  File "/app/bazarr/bin/bazarr/subtitles/mass_download/movies.py", line 40, in movies_download_subtitles
    if ast.literal_eval(movie[\'missing_subtitles\']):
  File "/usr/lib/python3.10/ast.py", line 110, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.10/ast.py", line 109, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.10/ast.py", line 83, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.10/ast.py", line 74, in _convert_num
    _raise_malformed_node(node)
  File "/usr/lib/python3.10/ast.py", line 71, in _raise_malformed_node
    raise ValueError(msg + f\': {node!r}\')
ValueError: malformed node or string: None

**Comment by morpheus65535** [comment]
Malformed database. Run `Update all Movie Subtitles from disk` task and let it finish before messing with every possible button.

**Comment by bndzor** [comment]
It does not seem to resolve the issue. I am not sure if it actually completes the update; https://imgur.com/a/x62mzt6
It gets to 800 something and then the toast goes away, but that could be visual possibly?

**Comment by bndzor** [comment]
Ignore this. I am blind, i had two paths/diferent storages but only mapped one, thus the behaviour. After adding the second the issue was resolved. Thanks for your quick help anyway @morpheus65535
