### ISSUE TITLE
Error starting Bazarr on Raspi 4

### ISSUE THREAD

**Issue by bckspc** [morpheus65535/bazarr#2137]
I had my raspi running Bazarr 1.2.1 fine until recently. I noticed bazarr was not running and tried to run it manually by executing python3 bazarr.py
I got the following error:

Bazarr starting...
Traceback (most recent call last):
  File "bazarr/main.py", line 41, in <module>
    from app.server import webserver  # noqa E402
  File "/opt/bazarr/bazarr/app/server.py", line 12, in <module>
    from api import api_bp
  File "/opt/bazarr/bazarr/api/__init__.py", line 11, in <module>
    from .providers import api_ns_list_providers
  File "/opt/bazarr/bazarr/api/providers/__init__.py", line 4, in <module>
    from .providers_episodes import api_ns_providers_episodes
  File "/opt/bazarr/bazarr/api/providers/providers_episodes.py", line 8, in <module>
    from subtitles.manual import manual_search, manual_download_subtitle
  File "/opt/bazarr/bazarr/subtitles/manual.py", line 91
    continue
    ^
SyntaxError: 'continue' not supported inside 'finally' clause

It hangs there until I CTRL+C but even when "running" the site does not open.

I checked the log files and none is generated.

I though maybe some auto update went wrong so I backed up my current install and downloaded the lastest version (1.2.1) unzipped it to an empty dir and followed all instructions from the wiki again. When I run I get exactly the same error.

I've checked my system and all is up-to-date. I'm running a Raspi 4 with raspbian.

Also tried to reboot the pi, same issue. I event stopped and disabled the systemctl service for bazarr just to make sure nothing was running on start. Same issue. I cannot manually run bazarr.py due to the error stated above. 

I have Sonarr, Radarr and Bazarr running on this raspi for at least a year now without any problems.

Can anyone give me some insight on what might be the problem?

**Comment by morpheus65535** [comment]
Issue with Python 3.7. You can either upgrade Python or switch to dev branch that include a fix for that.

**Comment by madjo1983** [comment]
I upgraded Python to 3.9.9 using https://linuxhint.com/update-python-raspberry-pi.

When running /usr/bin/python3 /opt/bazarr/bazarr.py i get this

```
Bazarr starting...
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/main.py", line 22, in <module>
    from init import *  # noqa E402
  File "/opt/bazarr/bazarr/init.py", line 19, in <module>
    from utilities.backup import restore_from_backup
  File "/opt/bazarr/bazarr/utilities/backup.py", line 5, in <module>
    import sqlite3
  File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
Bazarr exited.
```


When running sudo python3 -m pip install -r /opt/bazarr/requirements.txt
I get

```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 266, in run
    session = self.get_default_session(options)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 74, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 88, in _build_session
    session = PipSession(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 289, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    linux_distribution = distro.linux_distribution()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 98, in main
    return self._main(args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 214, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 143, in handle_pip_version_check
    session = self._build_session(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 88, in _build_session
    session = PipSession(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 289, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    linux_distribution = distro.linux_distribution()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
```

**Comment by morpheus65535** [comment]
The first one is because your build of Python 3.9 doesn't include sqlite3 module that normally standard. No  idea about the second issue but I would start by fixing the first one and see how it goes.

**Comment by madjo1983** [comment]
I have tried plenty things in vain, use last version of python, and there is always something missing...

Here a bunch of commands I tried in addition to the reinstall python:
```
sudo apt install libsqlite3-dev 
sudo apt-get install libbz2-dev
sudo apt-get install libjpeg-dev

sudo pip install pysqlite3
sudo pip3 install bzip2 

sudo pip install --upgrade pip
sudo pip install --upgrade --force-reinstall pillow
sudo pip install --upgrade pip setuptools wheel
sudo pip install --upgrade pip setuptools lxml
```

I'm lost here as installing previous version of bazarr is seems to not me working and neither python...
Is there a specific version of Python I should try ?

**Comment by bckspc** [comment]
I've installed python 3.8 on raspi by building it and everything worked ok (https://trickiknow.com/how-to-install-python-on-raspberry-pi-4-easy-steps/). The raspian sources only have python3.7.

Using the suggested make altinstall will not link python3 command to 3.8 so you can use make install or manually run python3.8 cmd.

I had to manually run python requirements.txt running with python3.8 (also I upgraded pip).

Seems to be working fine and I didn't lost any of the data i had.

@madjo1983 maybe you could try this?

**Comment by madjo1983** [comment]
So I reverted to python 3.7 and installed bazarr v1.2.2-beta.2 and then I was able to resurrect Bazarr processes.
I might try python 3.8, but as this is not the target version for the future, I'm not sure I'll spend time focusing on this.
Many thanks for your help!
