### ISSUE TITLE
Last bazarr version not working...

### ISSUE THREAD

**Issue by foxnetbel** [morpheus65535/bazarr#2143]
After a update, the software not start.

**To Reproduce**
Just run bazarr

**Expected behavior**
Software start without problems

**Screenshots**
root@services /opt/bazarr# python3 ./bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "./bazarr/main.py", line 41, in <module>
    from app.server import webserver  # noqa E402
  File "/opt/bazarr/bazarr/app/server.py", line 12, in <module>
    from api import api_bp
  File "/opt/bazarr/bazarr/api/__init__.py", line 11, in <module>
    from .providers import api_ns_list_providers
  File "/opt/bazarr/bazarr/api/providers/__init__.py", line 4, in <module>
    from .providers_episodes import api_ns_providers_episodes
  File "/opt/bazarr/bazarr/api/providers/providers_episodes.py", line 8, in <module>
    from subtitles.manual import manual_search, manual_download_subtitle
  File "/opt/bazarr/bazarr/subtitles/manual.py", line 91
    continue
    ^
SyntaxError: 'continue' not supported inside 'finally' clause

**Software (please complete the following information):**
 - Bazarr: [e.g. v 1.2.2]
 - OS: Linux services 4.19.0-24-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64 GNU/Linux

**Additional context**

**Comment by morpheus65535** [comment]
You're still in master. Here's the content of line 91 in dev branch: https://github.com/morpheus65535/bazarr/blob/development/bazarr/subtitles/manual.py#L91
