### ISSUE TITLE
BAZARR unable to index external subtitles

### ISSUE THREAD

**Issue by budimanjojo** [morpheus65535/bazarr#2155]
**Describe the bug**
I don't know what is happening here but whatever I downloaded is not being recognized by `bazarr` anymore. It just shows the subtitle is missing although the srt files are there and it keeps downloading the same thing over and over.
I looked at the container log and it shows `ERROR (movies:97) - BAZARR unable to index external subtitles.` so I go to movie with id `97` and deleted all of its subtitles files and it still shows the same error.
Here's the trace log of the error:
```
Traceback (most recent call last):
  File "/app/bazarr/subtitles/indexer/utils.py", line 80, in guess_external_subtitles
    text = text.decode(\'utf-8\')
           ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: \'utf-8\' codec can\'t decode byte 0x92 in position 1317: invalid start byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/subtitles/indexer/movies.py", line 94, in store_subtitles_movie
    subtitles = guess_external_subtitles(full_dest_folder_path, subtitles, "movie",
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/subtitles/indexer/utils.py", line 90, in guess_external_subtitles
    detector = Detector()
               ^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/detector.py", line 67, in __init__
    self._weights = load_weights(encodings)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/resources/__init__.py", line 71, in load_weights
    weights[encoding] = _unpack(WEIGHT_DIRECTORY / f\'{encoding}.gzip\', pattern=\'>e\')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/resources/__init__.py", line 29, in _unpack
    with gzip.open(file, \'rb\') as data:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or \'rb\')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: \'/app/bazarr/../libs/charamel/resources/weights/Encoding.ASCII.gzip\
```

**To Reproduce**
1. Run `Update all Movie Subtitles from disk`
2. See error

**Software (please complete the following information):**
 - Bazarr: 1.2.1
 - Radarr version: 4.4.4.7068
 - OS: running in container with kubernetes

**Comment by budimanjojo** [comment]
I managed to fix this by deleting all of the `.srt` files without language ISO prefix. It was due to me using `Single language` format before and disabling it now. Thanks to `TRaSH` for the help. I close this issue now.
