### ISSUE TITLE
Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by nnleaf** [morpheus65535/bazarr#216]
I'm getting an internal server error, with bazarr not loading. Here are the details. 

Exception:

NameError("name 'current_port' is not defined",)

Traceback:

Traceback (most recent call last):
  File "/opt/bazarr/libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/bazarr/libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/bazarr/bazarr.py", line 140, in wrapper
  File "/opt/bazarr/bazarr.py", line 291, in series
  File "/opt/bazarr/libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/opt/bazarr/libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/opt/bazarr/libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/opt/bazarr/views/series.tpl", line 56, in <module>
    % include('menu.tpl')
  File "/opt/bazarr/libs/bottle.py", line 3386, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/opt/bazarr/libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/opt/bazarr/views/menu.tpl", line 195, in <module>
    if (window.location.port == '{{current_port}}') {
NameError: name 'current_port' is not defined

**Comment by halali** [comment]
Manually restart bazarr
