### ISSUE TITLE
Support for unrar-free is broken

### ISSUE THREAD

**Issue by MichaIng** [morpheus65535/bazarr#2172]
**Describe the bug**
On Debian, when installing `unrar-free` instead of the non-free version, Bazarr fails to start.

**To Reproduce**
1. `apt install unrar-free`
2. You know, install Bazarr, e.g. with a systemd unit
3. `systemctl start bazarr`
4. `journalctl -u bazarr`

**Expected behavior**
Bazarr works with `unrar-nonfree`

**Screenshots**
```
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,228 - root                             (b6fcb640) :  DEBUG (binaries:50) - BAZARR binary not found in path, searching for it...
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,234 - dogpile.cache.region             (b6fcb640) :  DEBUG (region:861) - No value present for key: 'utilities.binaries:get_binaries_from_json|'
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,237 - dogpile.lock                     (b6fcb640) :  DEBUG (lock:90) - NeedRegenerationException
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,240 - dogpile.lock                     (b6fcb640) :  DEBUG (lock:131) - no value, waiting for create lock
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,243 - dogpile.lock                     (b6fcb640) :  DEBUG (lock:135) - value creation lock <dogpile.cache.region.CacheRegion._LockWrapper object at 0xb31f2df0> acquired
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,246 - dogpile.cache.region             (b6fcb640) :  DEBUG (region:861) - No value present for key: 'utilities.binaries:get_binaries_from_json|'
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,250 - dogpile.lock                     (b6fcb640) :  DEBUG (lock:174) - Calling creation function for not-yet-present value
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,256 - dogpile.cache.region             (b6fcb640) :  DEBUG (region:853) - Cache value generated in 0.003 seconds for key(s): 'utilities.binaries:get_binaries_from_json|'
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,260 - dogpile.lock                     (b6fcb640) :  DEBUG (lock:182) - Released creation lock
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,263 - root                             (b6fcb640) :  DEBUG (binaries:72) - BAZARR binary not found in binaries.json
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,267 - root                             (b6fcb640) :  DEBUG (binaries:47) - BAZARR returning this binary: /usr/bin/unrar
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,306 - root                             (b6fcb640) :  ERROR (init:226) - BAZARR requires a rar archive extraction utilities (unrar, unar) and it can't be found.
Jun 13 23:46:40 Amizero Bazarr[3718]: Traceback (most recent call last):
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/init.py", line 215, in init_binaries
Jun 13 23:46:40 Amizero Bazarr[3718]:     exe = get_binary("unar")
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/utilities/binaries.py", line 73, in get_binary
Jun 13 23:46:40 Amizero Bazarr[3718]:     raise BinaryNotFound
Jun 13 23:46:40 Amizero Bazarr[3718]: utilities.binaries.BinaryNotFound
Jun 13 23:46:40 Amizero Bazarr[3718]: During handling of the above exception, another exception occurred:
Jun 13 23:46:40 Amizero Bazarr[3718]: Traceback (most recent call last):
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/init.py", line 224, in init_binaries
Jun 13 23:46:40 Amizero Bazarr[3718]:     rarfile.tool_setup(unrar=True, unar=False, bsdtar=False, force=True)
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/../libs/rarfile.py", line 3331, in tool_setup
Jun 13 23:46:40 Amizero Bazarr[3718]:     raise RarCannotExec("Cannot find working tool")
Jun 13 23:46:40 Amizero Bazarr[3718]: rarfile.RarCannotExec: Cannot find working tool
Jun 13 23:46:40 Amizero Bazarr[3718]: Traceback (most recent call last):
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/init.py", line 215, in init_binaries
Jun 13 23:46:40 Amizero Bazarr[3718]:     exe = get_binary("unar")
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/utilities/binaries.py", line 73, in get_binary
Jun 13 23:46:40 Amizero Bazarr[3718]:     raise BinaryNotFound
Jun 13 23:46:40 Amizero Bazarr[3718]: utilities.binaries.BinaryNotFound
Jun 13 23:46:40 Amizero Bazarr[3718]: During handling of the above exception, another exception occurred:
Jun 13 23:46:40 Amizero Bazarr[3718]: Traceback (most recent call last):
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/init.py", line 224, in init_binaries
Jun 13 23:46:40 Amizero Bazarr[3718]:     rarfile.tool_setup(unrar=True, unar=False, bsdtar=False, force=True)
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/../libs/rarfile.py", line 3331, in tool_setup
Jun 13 23:46:40 Amizero Bazarr[3718]:     raise RarCannotExec("Cannot find working tool")
Jun 13 23:46:40 Amizero Bazarr[3718]: rarfile.RarCannotExec: Cannot find working tool
Jun 13 23:46:40 Amizero Bazarr[3718]: During handling of the above exception, another exception occurred:
Jun 13 23:46:40 Amizero Bazarr[3718]: Traceback (most recent call last):
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/main.py", line 22, in <module>
Jun 13 23:46:40 Amizero Bazarr[3718]:     from init import *  # noqa E402
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/init.py", line 240, in <module>
Jun 13 23:46:40 Amizero Bazarr[3718]:     init_binaries()
Jun 13 23:46:40 Amizero Bazarr[3718]:   File "/opt/bazarr/bazarr/init.py", line 227, in init_binaries
Jun 13 23:46:40 Amizero Bazarr[3718]:     raise BinaryNotFound
Jun 13 23:46:40 Amizero Bazarr[3718]: utilities.binaries.BinaryNotFound
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,367 - peewee.sqliteq                   (b6fcb640) :  DEBUG (sqliteq:274) - environment stop requested.
Jun 13 23:46:40 Amizero Bazarr[3718]: 2023-06-13 23:46:40,375 - peewee.sqliteq                   (b31c0440) :  INFO (sqliteq:138) - writer received shutdown request, exiting.
Jun 13 23:46:42 Amizero Bazarr[3717]: Bazarr starting...
Jun 13 23:46:42 Amizero Bazarr[3717]: Bazarr exited.
Jun 13 23:46:43 Amizero systemd[1]: bazarr.service: Succeeded.
```
It would btw make sense if Bazarr exited with an error code, so one knows that it failed and was not shutdown on purpose.

**Software (please complete the following information):**
 - Bazarr: `v1.2.1`
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: `Debian 11+12` tested on ARMv6 RPi (where no `unrar-nonfree` is available) and `x86_64`.

**Additional context**
Bazarr does not only check for the existence of the executable (this succeeds), but tests it with command-line arguments which are not understood by `unrar-free`: https://github.com/morpheus65535/bazarr/blob/0c3c5a0/libs/rarfile.py#L3272-L3273
```console
root@Amizero:~# unrar-free -?
Usage: unrar-free [OPTION...] ARCHIVE [FILE...] [DESTINATION]
Extract files from rar archives.

  -x, --extract              Extract files from archive (default)
  -t, --list                 List files in archive
  -f, --force                Overwrite files when extracting
      --extract-newer        Only extract newer files from the archive
      --extract-no-paths     Don't create directories while extracting
  -p, --password             Decrypt archive using a password
  -?, --help                 Give this help list
      --usage                Give a short usage message
  -V, --version              Print program version

Report bugs to <benasselstine@canada.com>.
```
I first thought it may be expected and `unrar-free` (sadly) simply not intended to be supported, but then I found some issues where this worked in the past: https://github.com/search?q=repo%3Amorpheus65535%2Fbazarr+unrar-free&type=issues
So probably it is possible to re-add support for the free tool.

**Comment by morpheus65535** [comment]
To my knowledge, it never worked with `unrar-free` binary. Bazarr use either `unrar` or `unar` but not `unrar-free` (or if it ever worked, it was unintended). This part of code or rarfile haven't been updated in more than a year so I would be surprise you had it working recently. I don't see anything broken here but I can understand you would appreciate it to be supported. We're open to PR if you wish so.

**Comment by MichaIng** [comment]
In October 2021 it seems to have worked: #1583
And in January 2020 you suggested installing it as solution: https://github.com/morpheus65535/bazarr/issues/735#issuecomment-571397856

However, indeed old already, and `unar` seems to be an alternative for ARMv6 and RISC-V, which both on Debian/Raspbian do not have the `unrar` package.

But I will see if I can easily add `unrar-free` support. It actually has certain compatibility with the non-free variant:
https://manpages.debian.org/unrar-free#NON-FREE_UNRAR_COMPATIBLE_OPTIONS

But Bazarr uses the `-inul` flag to "disable all messages" which is not understood by `unrar-free`. Usually, if an unarchiver is piping the data stream to STDOUT, progress/informational output is not done to the STDOUT, reasonably. So I think it would not cause any issues to remove that flag, but it must be tested, of course. A benefit could be that Bazarr has a chance to incorporate the tool's output into its error log. It took me a while to understand why the test fails, which would have been much easier with "invalid argument '-inul'".

**Comment by morpheus65535** [comment]
Bazarr now rely on rarfile module that doesn't seems to support unrar-free. https://rarfile.readthedocs.io/

**Comment by MichaIng** [comment]
Ah I see, and I guess you are not keen to use any different `rarfile.py` than upstream one, right?

**Comment by morpheus65535** [comment]
I prefer to use unmodified module of course.

**Comment by MichaIng** [comment]
Makes sense. I just opened an issue upstream, as it would be generally great to support FLOSS software alternatives: https://github.com/markokr/rarfile/issues/94
