### ISSUE TITLE
BAZARR unable to index external subtitles.

### ISSUE THREAD

**Issue by kromsam** [morpheus65535/bazarr#2185]
**Describe the bug**
When I try to _Update all Movie Subtitles from disk_ or _Update all Episode Subtitles from disk_ I get an error in the logs. There are two errors with the same name.

BAZARR unable to index external subtitles.
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/subtitles/indexer/movies.py", line 94, in store_subtitles_movie
    subtitles = guess_external_subtitles(full_dest_folder_path, subtitles, "movie",
  File "/app/bazarr/bin/bazarr/subtitles/indexer/utils.py", line 86, in guess_external_subtitles
    text = text.decode(encoding)
TypeError: decode() argument \'encoding\' must be str, not None
```

BAZARR unable to index external subtitles.
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/subtitles/indexer/movies.py", line 94, in store_subtitles_movie
    subtitles = guess_external_subtitles(full_dest_folder_path, subtitles, "movie",
  File "/app/bazarr/bin/bazarr/subtitles/indexer/utils.py", line 86, in guess_external_subtitles
    text = text.decode(encoding)
  File "/usr/lib/python3.10/encodings/cp1251.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: \'charmap\' codec can\'t decode byte 0x98 in position 13285: character maps to <undefined>
```

**Software (please complete the following information):**
 - Bazarr: v1.2.2-ls200 by linuxserver.io
 - Radarr version 4.5.2.7388
 - Sonarr version 3.0.10.1567
 - OS: Linux-6.1.0-0.deb11.6-amd64-x86_64-with

**Additional context**
I have looked at some other similar issues in this repo and try to incorporate the offered solutions. From this one https://github.com/morpheus65535/bazarr/issues/421 I got the idea to add the Locale in the environment files. From this one https://github.com/morpheus65535/bazarr/issues/509 I got the idea to run

`python -c "import sys; print(sys.getdefaultencoding())"`

inside the container. The result was:
`
utf-8`

This is my docker set-up:

```
# Bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: always
    network_mode: "service:vpn"
    depends_on:
      - vpn
    healthcheck:
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LANG="en_US.UTF-8" \
      - LANGUAGE="en_US:en" \
      - LC_ALL="en_US.UTF-8"
    volumes:
      - ${APPDATA}/Bazarr:/config
      - ${FILMS}:/movies
      - ${SERIES}:/tv

# Bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: always
    network_mode: "service:vpn"
    depends_on:
      - vpn
    healthcheck:
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LANG="en_US.UTF-8" \
      - LANGUAGE="en_US:en" \
      - LC_ALL="en_US.UTF-8"
    volumes:
      - ${APPDATA}/Bazarr:/config
      - ${FILMS}:/movies
      - ${SERIES}:/tv

# Bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: always
    network_mode: "service:vpn"
    depends_on:
      - vpn
    healthcheck:
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LANG="en_US.UTF-8" \
      - LANGUAGE="en_US:en" \
      - LC_ALL="en_US.UTF-8"
    volumes:
      - ${APPDATA}/Bazarr:/config
      - ${FILMS}:/movies
      - ${SERIES}:/tv
```

**Comment by kromsam** [comment]
I fixed the problem. The solution was to enable debug-logging so that I could see which files caused the problems and I deleted those files.
