### ISSUE TITLE
Whisper errors on the latest version

### ISSUE THREAD

**Issue by ayancey** [morpheus65535/bazarr#2205]
```
File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 455, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/whisperai.py", line 291, in download_subtitle
    params={\'task\': subtitle.task, \'language\': whisper_get_language_reverse(subtitle.audio_language), \'output\': \'srt\', \'encode\': \'false\'},
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/whisperai.py", line 162, in whisper_get_language_reverse
    raise ValueError
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/movies/movies_subtitles.py", line 73, in patch
    result = list(generate_subtitles(moviePath, [(language, hi, forced)], audio_language,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/subtitles/download.py", line 69, in generate_subtitles
    downloaded_subtitles = download_best_subtitles(videos={video},
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core_persistent.py", line 72, in download_best_subtitles
    subtitles = pool_instance.download_best_subtitles(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 596, in download_best_subtitles
    if self.download_subtitle(subtitle):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 475, in download_subtitle
    self.throttle_callback(subtitle.provider_name, e)
  File "/app/bazarr/bin/bazarr/app/get_providers.py", line 334, in provider_throttle
    if cls_name == \'ValueError\' and exception.args[0].startswith(\'unsupported pickle protocol\'):
                                    ~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

**Comment by ayancey** [comment]
Unable to reproduce. Reporter of this issue hasn't responded to messages.
