### ISSUE TITLE
Can't see history of movies and series

### ISSUE THREAD

**Issue by xloooolx** [morpheus65535/bazarr#2210]
**Describe the bug**
I GET AN ERROR when I click history episodes or movies in the main menu.
Error 500
You have disconnected from the server

**Software (please complete the following information):**
 - Bazarr: 1.2.5-beta.6
 - Radarr version 4.7.4.7732
 - Sonarr version 4.0.0.582
 - OS: Linux-5.15.0-72-generic-x86_64-with

**Additional context**
Exception on /api/episodes/history [GET]
`Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/episodes/history.py", line 99, in get
    upgradable_episodes_not_perfect.c.id.label(\'upgradable\'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'list\' object has no attribute \'c\`

Exception on /api/movies/history [GET]
`Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/movies/history.py", line 94, in get
    upgradable_movies_not_perfect.c.id.label(\'upgradable\'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'list\' object has no attribute \'c\`

**Comment by morpheus65535** [comment]
Did you disable `Upgrade Previously Downloaded Subtitles` in Settings-->Subtitles? That's a bug but I just want to understand how to reproduce it properly.

**Comment by xloooolx** [comment]
When the feature is disabled, there may be some issues, but once I enable it, everything works like a charm. The only problem arises when I disable the "Upgrade Previously Downloaded Subtitles" option.

**Comment by crispybegs** [comment]
i'm having exactly this same error (but running in docker)
I already have 'Upgrade Previously Downloaded Subtitles' enabled, but it's still happening. Any ideas?
