### ISSUE TITLE
Translate to different language results into error 500

### ISSUE THREAD

**Issue by hunter-nl** [morpheus65535/bazarr#2214]
**Describe the bug**
When I extract an English embedded subtitle and want to translate this into for example Dutch language. Then I get with the latest version an error 500.
Series subtitle is translating just fine.

**To Reproduce**
1. Go to Movie
2. Click on Manual
3. Click on the embedded subtitle to extract it to a subtitle file.
4. Close Manual Search window
5. Go to the new external subtitle
6. Click on '...'
7. Click in menu on Translate
8. Choose language
9. Get in right bottom corner the error 500 popup.

**Expected behavior**
Translated movie subtitle to being available after the translation process.

**Software (please complete the following information):**
 - Bazarr: v1.2.5-beta.8 (upgraded from v1.2.4)
 - Radarr version 4.6.4.7568
 - Sonarr version 3.0.10.1567
 - OS: Rocky Linux 8.8

**Additional context**
Log of the Translate action:
``` Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/../libs/sqlalchemy/engine/_py_row.py", line 117, in _get_by_key_impl_mapping
    rec = self._keymap[key]
KeyError: \'sonarrSeriesId\'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/../libs/sqlalchemy/engine/_py_row.py", line 134, in __getattr__
    return self._get_by_key_impl_mapping(name)
  File "/opt/Bazarr/bazarr/../libs/sqlalchemy/engine/_py_row.py", line 119, in _get_by_key_impl_mapping
    rec = self._parent._key_fallback(key, ke)
  File "/opt/Bazarr/bazarr/../libs/sqlalchemy/engine/result.py", line 135, in _key_fallback
    raise KeyError(key) from err
KeyError: \'sonarrSeriesId\'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/Bazarr/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/Bazarr/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/Bazarr/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/opt/Bazarr/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/Bazarr/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/opt/Bazarr/bazarr/api/subtitles/subtitles.py", line 95, in patch
    sonarr_series_id=metadata.sonarrSeriesId,
  File "/opt/Bazarr/bazarr/../libs/sqlalchemy/engine/_py_row.py", line 136, in __getattr__
    raise AttributeError(e.args[0]) from e
AttributeError: sonarrSeriesId ```

**Comment by morpheus65535** [comment]
Will be fixed in upcoming beta. Thanks for reporting!
