### ISSUE TITLE
Downloading the same subtitles over and over.

### ISSUE THREAD

**Issue by TKinslayer** [morpheus65535/bazarr#2237]
**Describe the bug**
Bazarr has been downloading the same subtitles over and over for days. And it doesn't download any other subtitles I asked for (3200 episodes and 100s of film)

**Expected behavior**
To download the subtiles for a given show once and not get stuck on always the same handful of episodes.

**Screenshots**
<img width="627" alt="Capture d’écran 2023-08-29 à 19 47 33" src="https://github.com/morpheus65535/bazarr/assets/23481097/2d47f8ee-5dc1-4227-b8a5-d2d8cb572fb7">

**Software (please complete the following information):**
 - Bazarr: v1.2.4 (but it has been having the same behavior for the last 4 weeks)
 - Radarr version : v4.7.5.7809
 - Sonarr version : v3.0.10.1567
 - OS: Oracle 9

**Additional context**
The logs don't show any kind of loops in downloading subtitles. Unfortunately, it usually says, for the vast majority of all 3000+ episodes and 100+ of films that the files are corrupted. It does make me wonder (because that's the 99% of my library) it the two problems are the same bug. 

2023-08-29T17:42:48.429813457Z 2023-08-29 19:42:48,429 - root                             (7f0408a42b38) :  ERROR (video_analyzer:164) - BAZARR ffprobe cannot analyze this video file /tv/Wynonna Earp/Season 4/Wynonna.Earp.S04E12.1080p.WEB.H264-CAKES[TGx]/wynonna.earp.s04e12.1080p.web.h264-cakes.mkv. Could it be corrupted? +-------------------------------------------------------+
2023-08-29T17:42:48.429850301Z |                     KnowIt 0.5.2                      |
2023-08-29T17:42:48.429853902Z +-------------------------------------------------------+
2023-08-29T17:42:48.429856920Z |                      pymediainfo                      |
2023-08-29T17:42:48.429859320Z |                                                       |
2023-08-29T17:42:48.429861993Z |                   libmediainfo.so.0                   |
2023-08-29T17:42:48.429864331Z |                         v23.7                         |
2023-08-29T17:42:48.429866606Z |                                                       |
2023-08-29T17:42:48.429868877Z |                   /usr/bin/ffprobe                    |
2023-08-29T17:42:48.429871125Z |                         v6.0                          |
2023-08-29T17:42:48.429873342Z |                                                       |
2023-08-29T17:42:48.429875581Z |                                                       |
2023-08-29T17:42:48.429877820Z |                        enzyme                         |
2023-08-29T17:42:48.429880083Z |                         0.4.1                         |
2023-08-29T17:42:48.429882350Z +-------------------------------------------------------+
2023-08-29T17:42:48.429884603Z |                   provider: ffmpeg                    |
2023-08-29T17:42:48.430004105Z |               ffmpeg: /usr/bin/ffprobe                |
2023-08-29T17:42:48.430006692Z |                   profile: default                    |
2023-08-29T17:42:48.430008987Z +-------------------------------------------------------+
2023-08-29T17:42:48.430011287Z Traceback (most recent call last):
2023-08-29T17:42:48.430013622Z   File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 59, in know
2023-08-29T17:42:48.430016168Z     result = provider.describe(video_path, context)
2023-08-29T17:42:48.430018529Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T17:42:48.430020817Z   File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 222, in describe
2023-08-29T17:42:48.430023227Z     data = self.executor.extract_info(video_path)
2023-08-29T17:42:48.430025483Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T17:42:48.430027749Z   File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 80, in extract_info
2023-08-29T17:42:48.430030152Z     json_dump = self._execute(filename)
2023-08-29T17:42:48.430032418Z                 ^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T17:42:48.430035506Z   File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 114, in _execute
2023-08-29T17:42:48.430037993Z     return check_output([self.location, '-v', 'quiet', '-print_format', 'json',
2023-08-29T17:42:48.430040395Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T17:42:48.430042693Z   File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
2023-08-29T17:42:48.430046714Z     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
2023-08-29T17:42:48.430049135Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-29T17:42:48.430051448Z   File "/usr/lib/python3.11/subprocess.py", line 571, in run
2023-08-29T17:42:48.430053790Z     raise CalledProcessError(retcode, process.args,
2023-08-29T17:42:48.430056272Z subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/tv/Wynonna Earp/Season 4/Wynonna.Earp.S04E12.1080p.WEB.H264-CAKES[TGx]/wynonna.earp.s04e12.1080p.web.h264-cakes.mkv']' returned non-zero exit status 1.

**Comment by morpheus65535** [comment]
What is the output of:
`ls -l /tv/Wynonna Earp/Season 4/Wynonna.Earp.S04E12.1080p.WEB.H264-CAKES[TGx]/wynonna.earp.s04e12.1080p.web.h264-cakes.mkv`

Is the file playable in VLC?

**Comment by TKinslayer** [comment]
Hi, 

    Yeah, the file is playable in VLC. 

    As for the result of the comment you suggested, the result is as follow : 

-rwxrwxrwx 1 nobody users 1971453274 Aug 31  2022 Wynonna.Earp.S04E12.1080p.WEB.H264-CAKES[TGx]/wynonna.earp.s04e12.1080p.web.h264-cakes.mkv*

**Comment by morpheus65535** [comment]
What is the output of:
`/usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -sexagesimal "/tv/Wynonna Earp/Season 4/Wynonna.Earp.S04E12.1080p.WEB.H264-CAKES[TGx]/wynonna.earp.s04e12.1080p.web.h264-cakes.mkv"`

**Comment by abiacco** [comment]
Not to hijack your issue, but I have a similar problem with a handful of episodes, where it just keeps downloading the same sub over and over, every time the "Upgrade Previously Downloaded Subtitles" schedule runs
I don't have the ffprobe problems and it's always on opensubtitlescom. I have to blacklist the sub to get it to stop.

**Comment by morpheus65535** [comment]
@abiacco please come see us on Discord for support or at least open your own issue by filling the required information and providing log if possible.

**Comment by morpheus65535** [comment]
No news, good news!
