### ISSUE TITLE
Postgres Error Against Fresh Database

### ISSUE THREAD

**Issue by owine** [morpheus65535/bazarr#2249]
**Describe the bug**
Bazarr throws a SQL error when provisioning a fresh Postgres database. This is a regression from `:release-1.2.3` which provisions the database without error.

**To Reproduce**
1. Create blank Postgres DB
2. Run bazarr `:latest` against new DB
3. Observe error

**Expected behavior**
Database should provision without issue and start Bazarr normally. This is the behavior observed on `:release-1.2.3`

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.2.5
 - Radarr version n/a
 - Sonarr version n/a
 - OS: Ubuntu 20.04 via Docker

**Additional context**
```
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop constraint table_shows_pkey on table table_shows because other objects depend on it
DETAIL:  constraint table_episodes_sonarrSeriesId_fkey on table table_episodes depends on index table_shows_pkey
constraint table_blacklist_sonarr_series_id_fkey on table table_blacklist depends on index table_shows_pkey
constraint table_history_sonarrSeriesId_fkey on table table_history depends on index table_shows_pkey
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: ALTER TABLE table_shows DROP CONSTRAINT IF EXISTS table_shows_pkey;]
```

**Comment by damiensgit** [comment]
I also observed this issue. I created a new postgres:14 docker container with a single database and pointed the bazarr instance to this. The log I got was as follows:

```
2023/09/19 18:34:14	stdout	[SQL: ALTER TABLE table_shows DROP CONSTRAINT IF EXISTS table_shows_pkey;]
2023/09/19 18:34:14	stdout	
2023/09/19 18:34:14	stdout	HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2023/09/19 18:34:14	stdout	constraint table_history_sonarrSeriesId_fkey on table table_history depends on index table_shows_pkey
2023/09/19 18:34:14	stdout	constraint table_blacklist_sonarr_series_id_fkey on table table_blacklist depends on index table_shows_pkey
2023/09/19 18:34:14	stdout	DETAIL:  constraint table_episodes_sonarrSeriesId_fkey on table table_episodes depends on index table_shows_pkey
2023/09/19 18:34:14	stdout	sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop constraint table_shows_pkey on table table_shows because other objects depend on it
2023/09/19 18:34:14	stdout	    cursor.execute(statement, parameters)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
2023/09/19 18:34:14	stdout	    self.dialect.do_execute(
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
2023/09/19 18:34:14	stdout	    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
2023/09/19 18:34:14	stdout	    self._handle_dbapi_exception(
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
2023/09/19 18:34:14	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/09/19 18:34:14	stdout	    return self._exec_single_context(
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1842, in _execute_context
2023/09/19 18:34:14	stdout	          ^^^^^^^^^^^^^^^^^^^^^^
2023/09/19 18:34:14	stdout	    ret = self._execute_context(
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
2023/09/19 18:34:14	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/09/19 18:34:14	stdout	    return connection._execute_clauseelement(
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
2023/09/19 18:34:14	stdout	           ^^^^^
2023/09/19 18:34:14	stdout	    return meth(
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1414, in execute
2023/09/19 18:34:14	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/09/19 18:34:14	stdout	    return conn.execute(  # type: ignore[call-overload]
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/ddl/impl.py", line 193, in _exec
2023/09/19 18:34:14	stdout	    self._exec(sql, execution_options)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/ddl/impl.py", line 202, in execute
2023/09/19 18:34:14	stdout	    operations.migration_context.impl.execute(
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/toimpl.py", line 207, in execute_sql
2023/09/19 18:34:14	stdout	           ^^^^^^^^^^^^^^^^^^^
2023/09/19 18:34:14	stdout	    return fn(self, operation)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/base.py", line 401, in invoke
2023/09/19 18:34:14	stdout	           ^^^^^^^^^^^^^^^^^^^^^
2023/09/19 18:34:14	stdout	    return operations.invoke(op)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/ops.py", line 2411, in execute
2023/09/19 18:34:14	stdout	  File "<string>", line 3, in execute
2023/09/19 18:34:14	stdout	    batch_op.execute('ALTER TABLE table_shows DROP CONSTRAINT IF EXISTS table_shows_pkey;')
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/migrations/versions/dc09994b7e65_.py", line 75, in upgrade
2023/09/19 18:34:14	stdout	    step.migration_fn(**kw)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/runtime/migration.py", line 622, in run_migrations
2023/09/19 18:34:14	stdout	    self.get_context().run_migrations(**kw)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/runtime/environment.py", line 868, in run_migrations
2023/09/19 18:34:14	stdout	  File "<string>", line 8, in run_migrations
2023/09/19 18:34:14	stdout	    context.run_migrations()
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/migrations/env.py", line 98, in run_migrations_online
2023/09/19 18:34:14	stdout	    run_migrations_online()
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/migrations/env.py", line 104, in <module>
2023/09/19 18:34:14	stdout	  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023/09/19 18:34:14	stdout	  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2023/09/19 18:34:14	stdout	    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/09/19 18:34:14	stdout	    spec.loader.exec_module(module)  # type: ignore
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/util/pyfiles.py", line 110, in load_module_py
2023/09/19 18:34:14	stdout	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/09/19 18:34:14	stdout	    module = load_module_py(module_id, path)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/util/pyfiles.py", line 94, in load_python_file
2023/09/19 18:34:14	stdout	    util.load_python_file(self.dir, "env.py")
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/script/base.py", line 576, in run_env
2023/09/19 18:34:14	stdout	    script.run_env()
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/alembic/command.py", line 378, in upgrade
2023/09/19 18:34:14	stdout	    command.upgrade(config, revision, sql=sql, tag=tag)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/flask_migrate/__init__.py", line 200, in upgrade
2023/09/19 18:34:14	stdout	    f(*args, **kwargs)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/flask_migrate/__init__.py", line 111, in wrapped
2023/09/19 18:34:14	stdout	    flask_migrate.upgrade(directory=migrations_directory)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/app/database.py", line 312, in migrate_db
2023/09/19 18:34:14	stdout	    migrate_db(app)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/main.py", line 58, in <module>
2023/09/19 18:34:14	stdout	Traceback (most recent call last):
2023/09/19 18:34:14	stdout	
2023/09/19 18:34:14	stdout	The above exception was the direct cause of the following exception:
2023/09/19 18:34:14	stdout	
2023/09/19 18:34:14	stdout	
2023/09/19 18:34:14	stdout	HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2023/09/19 18:34:14	stdout	constraint table_history_sonarrSeriesId_fkey on table table_history depends on index table_shows_pkey
2023/09/19 18:34:14	stdout	constraint table_blacklist_sonarr_series_id_fkey on table table_blacklist depends on index table_shows_pkey
2023/09/19 18:34:14	stdout	DETAIL:  constraint table_episodes_sonarrSeriesId_fkey on table table_episodes depends on index table_shows_pkey
2023/09/19 18:34:14	stdout	psycopg2.errors.DependentObjectsStillExist: cannot drop constraint table_shows_pkey on table table_shows because other objects depend on it
2023/09/19 18:34:14	stdout	    cursor.execute(statement, parameters)
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
2023/09/19 18:34:14	stdout	    self.dialect.do_execute(
2023/09/19 18:34:14	stdout	  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
2023/09/19 18:34:14	stdout	Traceback (most recent call last):
2023/09/19 18:33:55	stdout	Bazarr starting...
```

**Comment by halali** [comment]
Can you update your bazarr to recent 1.3.0 and try again?

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?
