### ISSUE TITLE
Can't recognize embedded subtitles, ffprobe invalid argument error

### ISSUE THREAD

**Issue by georgemisto** [morpheus65535/bazarr#2251]
**Describe the bug**
When scanning movies it doesn't recognize the embedded subtitles. It only happens at some movies.
```
2023-09-21 00:23:28,255 - root                             (7fc3adb23b38) :  DEBUG (movies:25) - BAZARR started subtitles indexing for this file: /Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv
2023-09-21 00:23:28,273 - root                             (7fc3adb23b38) :  DEBUG (movies:29) - BAZARR is trying to index embedded subtitles.
2023-09-21 00:23:28,277 - root                             (7fc3adb23b38) :  DEBUG (binaries:47) - BAZARR returning this binary: /usr/bin/ffprobe
2023-09-21 00:23:28,791 - root                             (7fc3adb23b38) :  ERROR (video_analyzer:164) - BAZARR ffprobe cannot analyze this video file /Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv. Could it be corrupted? +-------------------------------------------------------+
|                     KnowIt 0.5.2                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
|                   libmediainfo.so.0                   |
|                         v23.7                         |
|                                                       |
|                   /usr/bin/ffprobe                    |
|                         v6.0                          |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.1                         |
+-------------------------------------------------------+
|                   provider: ffmpeg                    |
|               ffmpeg: /usr/bin/ffprobe                |
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 222, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 80, in extract_info
    json_dump = self._execute(filename)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/knowit/providers/ffmpeg.py", line 114, in _execute
    return check_output([self.location, '-v', 'quiet', '-print_format', 'json',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv']' returned non-zero exit status 1.

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2023-09-21 00:23:28,799 - subliminal_patch.core            (7fc3adb23b38) :  DEBUG (core:988) - external subs: scanning path /Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv
2023-09-21 00:23:28,806 - subliminal_patch.core            (7fc3adb23b38) :  DEBUG (core:967) - Found subtitles {}
2023-09-21 00:23:28,806 - subliminal_patch.core            (7fc3adb23b38) :  DEBUG (core:993) - external subs: found {}
2023-09-21 00:23:28,813 - root                             (7fc3adb23b38) :  DEBUG (movies:142) - BAZARR storing those languages to DB: []
2023-09-21 00:23:28,819 - socketio.server                  (7fc3adb23b38) :  INFO (server:317) - emitting event "data" to all [/]
2023-09-21 00:23:28,819 - engineio.server                  (7fc3adb23b38) :  INFO (socket:89) - TtNBpgVwZ6wFWT1KAAAC: Sending packet MESSAGE data 2["data",{"type":"movie","action":"update","payload":605}]
2023-09-21 00:23:28,822 - socketio.server                  (7fc3adb23b38) :  INFO (server:317) - emitting event "data" to all [/]
2023-09-21 00:23:28,822 - engineio.server                  (7fc3adb23b38) :  INFO (socket:89) - TtNBpgVwZ6wFWT1KAAAC: Sending packet MESSAGE data 2["data",{"type":"movie-wanted","action":"update","payload":605}]
2023-09-21 00:23:28,823 - socketio.server                  (7fc3adb23b38) :  INFO (server:317) - emitting event "data" to all [/]
2023-09-21 00:23:28,824 - engineio.server                  (7fc3adb23b38) :  INFO (socket:89) - TtNBpgVwZ6wFWT1KAAAC: Sending packet MESSAGE data 2["data",{"type":"badges","action":"update","payload":null}]
2023-09-21 00:23:28,825 - root                             (7fc3adb23b38) :  DEBUG (movies:149) - BAZARR ended subtitles indexing for this file: /Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv
2023-09-21 00:23:37,158 - socketio.server                  (7fc3aceb7b38) :  INFO (server:317) - emitting event "data" to all [/]
2023-09-21 00:23:37,159 - engineio.server                  (7fc3aceb7b38) :  INFO (socket:89) - TtNBpgVwZ6wFWT1KAAAC: Sending packet MESSAGE data 2["data",{"type":"progress","action":"update","payload":{"id":"movie_search_progress_605","header":"Searching missing subtitles...","name":"Jurassic World: Fallen Kingdom","value":0,"count":1}}]
2023-09-21 00:23:37,161 - root                             (7fc3aceb7b38) :  DEBUG (pool:79) - BAZARR updating pools: {}
2023-09-21 00:23:37,162 - root                             (7fc3aceb7b38) :  DEBUG (pool:44) - BAZARR updating pool: movie_
2023-09-21 00:23:37,163 - root                             (7fc3aceb7b38) :  DEBUG (pool:48) - BAZARR pool not initialized: movie_. Initializing
2023-09-21 00:23:37,168 - subliminal_patch.core            (7fc3aceb7b38) :  DEBUG (core:108) - No provider config updates
2023-09-21 00:23:37,169 - subliminal_patch.core            (7fc3aceb7b38) :  INFO (core:680) - Using 3 threads for 3 providers ({'subf2m', 'embeddedsubtitles', 'opensubtitlescom'})
2023-09-21 00:23:37,173 - subliminal_patch.core            (7fc3aceb7b38) :  DEBUG (core:246) - Discarded providers: set() | New providers: {'subf2m', 'embeddedsubtitles', 'opensubtitlescom'}
2023-09-21 00:23:37,173 - subliminal_patch.core            (7fc3aceb7b38) :  DEBUG (core:248) - Updated discarded providers: set()
2023-09-21 00:23:37,174 - subliminal_patch.core            (7fc3aceb7b38) :  DEBUG (core:252) - Removed providers: set()
2023-09-21 00:23:37,174 - subliminal_patch.core            (7fc3aceb7b38) :  DEBUG (core:108) - No provider config updates
2023-09-21 00:23:37,175 - root                             (7fc3aceb7b38) :  DEBUG (pool:92) - BAZARR pools update elapsed time: 12.8ms
2023-09-21 00:23:37,177 - root                             (7fc3aceb7b38) :  DEBUG (download:32) - BAZARR Searching subtitles for this file: /Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv
2023-09-21 00:23:37,178 - subliminal_patch.core            (7fc3aceb7b38) :  DEBUG (core:108) - No provider config updates
2023-09-21 00:23:37,178 - subzero.video                    (7fc3aceb7b38) :  DEBUG (video:60) - Parsing video: Jurassic.World.Fallen.Kingdom.2018.1080p.BluRay.DTS.x264.HuN-No1.mkv, hints: {'title': 'Jurassic World: Fallen Kingdom', 'type': 'movie'}
2023-09-21 00:23:37,179 - subliminal_patch.core            (7fc3aceb7b38) :  INFO (core:812) - Determining basic video properties for 'Jurassic.World.Fallen.Kingdom.2018.1080p.BluRay.DTS.x264.HuN-No1.mkv' in '/Data/Movies/Jurassic World Fallen Kingdom (2018)'
2023-09-21 00:23:37,529 - subliminal_patch.core            (7fc3aceb7b38) :  DEBUG (core:820) - GuessIt found: {
    "title": "Jurassic World Fallen Kingdom",
    "year": 2018,
    "screen_size": "1080p",
    "source": "Blu-ray",
    "audio_codec": "DTS",
    "video_codec": "H.264",
    "language": "Hungarian",
    "release_group": "No1",
    "container": "mkv",
    "type": "movie"
}
2023-09-21 00:23:37,531 - subliminal_patch.core            (7fc3aceb7b38) :  DEBUG (core:836) - Size is 18872715761
2023-09-21 00:23:37,533 - root                             (7fc3aceb7b38) :  ERROR (utils:55) - BAZARR Error ([Errno 22] Invalid argument: '/Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv') trying to get video information for this file: /Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 41, in get_video
    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video
    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 846, in scan_video
    video.hashes['opensubtitlescom'] = osub_hash = osub_hash or hash_opensubtitles(hash_path)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/subliminal/utils.py", line 20, in hash_opensubtitles
    with open(video_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '/Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv'
2023-09-21 00:23:37,538 - root                             (7fc3aceb7b38) :  DEBUG (download:123) - BAZARR Ended searching Subtitles for file: /Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv

```

**To Reproduce**
1. Unknown, only happens at certain movies. Deep analyze enabled or disabled, the error is the same.

**Expected behavior**
Recognize embedded subtitles.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.3.0 and 1.3.1
 - Radarr version: 4.7.5.7809
 - OS: Linux Debian 5.10.0-23-amd64

**Additional context**

**Comment by morpheus65535** [comment]
Never tested with ffprobe 6. Can you confirm if it works with a previous version?

**Comment by morpheus65535** [comment]
What is the output from this command:
`/usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -sexagesimal "/Data/Movies/Jurassic World Fallen Kingdom (2018)/Jurassic.World.Fallen.Kingdom.(2018).Bluray-1080p.mkv"`

**Comment by georgemisto** [comment]
I tried it with ffprobe 5.1.3 and now I movied it to LinuxServer's alpine docker container. Their [v1.3.0-ls215](https://github.com/linuxserver/docker-bazarr/releases/tag/v1.3.0-ls215) version contains the ffprobe 6, so I downgraded to 5.1.3 but the same error persist on both debian and docker.
The output is empty:
```
{

}
```
The video file works, VLC can play it and it shows two audio channels and four embedded subtitles

**Comment by morpheus65535** [comment]
Thanks for testing with previous version of ffprobe.

If ffprobe can't parse the file properly, there's not much I can do. Looks like an improper file encoding or a bug in ffprobe itself. I'll leave it to you to open an issue with ffprobe if you want to.
