### ISSUE TITLE
UNIQUE constraint failed: _alembic_tmp_table_shows_rootfolder.id

### ISSUE THREAD

**Issue by echen92** [morpheus65535/bazarr#2253]
**Describe the bug**
Bazarr is failing to start
```
/usr/lib/python3.11/contextlib.py:144: SAWarning: Table '_alembic_tmp_table_shows' specifies columns 'tvdbId' as primary_key=True, not matching locally specified columns 'sonarrSeriesId'; setting the current primary key columns to 'sonarrSeriesId'. This warning may become an exception in a future release
  next(self.gen)
/usr/lib/python3.11/contextlib.py:144: SAWarning: Table '_alembic_tmp_table_shows' specifies columns 'tvdbId', 'sonarrSeriesId' as primary_key=True, not matching locally specified columns 'sonarrSeriesId'; setting the current primary key columns to 'sonarrSeriesId'. This warning may become an exception in a future release
  next(self.gen)
/usr/lib/python3.11/contextlib.py:144: SAWarning: Table '_alembic_tmp_table_episodes' specifies columns 'rowid' as primary_key=True, not matching locally specified columns 'sonarrEpisodeId'; setting the current primary key columns to 'sonarrEpisodeId'. This warning may become an exception in a future release
  next(self.gen)
/usr/lib/python3.11/contextlib.py:144: SAWarning: Table '_alembic_tmp_table_episodes' specifies columns 'rowid', 'sonarrEpisodeId' as primary_key=True, not matching locally specified columns 'sonarrEpisodeId'; setting the current primary key columns to 'sonarrEpisodeId'. This warning may become an exception in a future release
  next(self.gen)
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: _alembic_tmp_table_shows_rootfolder.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 58, in <module>
    migrate_db(app)
  File "/app/bazarr/bin/bazarr/app/database.py", line 312, in migrate_db
    flask_migrate.upgrade(directory=migrations_directory)
  File "/app/bazarr/bin/bazarr/../libs/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/app/bazarr/bin/bazarr/../libs/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/app/bazarr/bin/bazarr/../libs/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/app/bazarr/bin/bazarr/../libs/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/bazarr/bin/migrations/env.py", line 104, in <module>
    run_migrations_online()
  File "/app/bazarr/bin/migrations/env.py", line 98, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/app/bazarr/bin/bazarr/../libs/alembic/runtime/environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/app/bazarr/bin/bazarr/../libs/alembic/runtime/migration.py", line 622, in run_migrations
    step.migration_fn(**kw)
  File "/app/bazarr/bin/migrations/versions/dc09994b7e65_.py", line 180, in upgrade
    with op.batch_alter_table('table_shows_rootfolder') as batch_op:
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/base.py", line 383, in batch_alter_table
    impl.flush()
  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/batch.py", line 161, in flush
    batch_impl._create(self.impl)
  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/batch.py", line 451, in _create
    op_impl._exec(
  File "/app/bazarr/bin/bazarr/../libs/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: _alembic_tmp_table_shows_rootfolder.id
[SQL: INSERT INTO _alembic_tmp_table_shows_rootfolder (accessible, error, id, path) SELECT table_shows_rootfolder.accessible, table_shows_rootfolder.error, table_shows_rootfolder.id, table_shows_rootfolder.path 
FROM table_shows_rootfolder]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**To Reproduce**
1. Start bazarr docker container
2. Error appears in docker logs of container

**Expected behavior**
Bazarr to startup with no errors

**Screenshots**
N/A.

**Software (please complete the following information):**
 - Bazarr: 1.3.1-beta.3
 - Radarr: 4.7.5.7809
 - Sonarr: 3.0.10.1567
 - OS: docker linuxserver/*arr

**Additional context**
N/A

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
