### ISSUE TITLE
Client is disconnected with HTTP 500

### ISSUE THREAD

**Issue by scetu** [morpheus65535/bazarr#2262]
**Describe the bug**
"Search All" funtion does not work, it starts to search, but after a while, client gets disconnected from server with HTTP error 500. 
There is error message with HTTP 500, and also Bazzar seems to continue with search, but it is stuck.

From logs
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/series/series.py", line 218, in patch
    wanted_search_missing_subtitles_series()
  File "/app/bazarr/bin/bazarr/subtitles/wanted/series.py", line 119, in wanted_search_missing_subtitles_series
    wanted_download_subtitles(episode.sonarrEpisodeId)
  File "/app/bazarr/bin/bazarr/subtitles/wanted/series.py", line 82, in wanted_download_subtitles
    _wanted_episode(episode)
  File "/app/bazarr/bin/bazarr/subtitles/wanted/series.py", line 57, in _wanted_episode
    history_log(1, episode.sonarrSeriesId, episode.sonarrEpisodeId, result)
  File "/app/bazarr/bin/bazarr/sonarr/history.py", line 10, in history_log
    description = result.message
                  ^^^^^^^^^^^^^^
AttributeError: \'tuple\' object has no attribute \'message\
```
![image](https://github.com/morpheus65535/bazarr/assets/30218362/668aaf52-e0d9-4c05-bad3-9bb21659d659)

It seems that it is related with recent commit https://github.com/morpheus65535/bazarr/commit/1f187d89ca80e3734bf0831e2f7940bb01235695
And also issue https://github.com/morpheus65535/bazarr/issues/2072 has been updated by another user.

**To Reproduce**
1. Go to Wanted Episodes
2. Click on Search All
3. Wait for the error

**Expected behavior**
Bazzar should search for all subtitles.

**Software (please complete the following information):**
 - Bazarr: 1.3.1-beta.7
 - Radarr version 4.7.5.7809
 - Sonarr version 3.0.10.1567
 - OS: [e.g. Windows 10]

**Additional context**
Commit https://github.com/morpheus65535/bazarr/commit/1f187d89ca80e3734bf0831e2f7940bb01235695
Issue https://github.com/morpheus65535/bazarr/issues/2072

**Comment by morpheus65535** [comment]
Duplicate #2261
