### ISSUE TITLE
SQL error while trying to sync with Radarr/Sonarr

### ISSUE THREAD

**Issue by joaofernandes** [morpheus65535/bazarr#2294]
**Describe the bug**
While trying to sync with Radarr/Sonarr the tasks through an SQL error 

Task log : **Job "Sync with Radarr (trigger: interval[1:00:00], next run at: 2023-11-10 22:00:22 -01)" raised an exception**

Stacktrace
`Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "RETURNING": syntax error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/bazarr/bazarr/radarr/sync/movies.py", line 112, in update_movies
    removed_movies = database.execute(delete(TableMovies)
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/scoping.py", line 724, in execute
    return self._proxied.execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/bulk_persistence.py", line 1838, in orm_execute_statement
    return super().orm_execute_statement(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/context.py", line 253, in orm_execute_statement
    result = conn.execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "RETURNING": syntax error
[SQL: DELETE FROM table_movies WHERE table_movies."tmdbId" IN (?) RETURNING "radarrId"]
[parameters: (\'542196\',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) `

**Expected behavior**
Full sync

**Screenshots**

**Software (please complete the following information):**
Bazarr Version 1.3.1
Sonarr Version 3.0.10.1567
Radarr Version 4.6.4.7568
Operating System Linux-5.15.74-1-pve-x86_64-with-glibc2.31
Python Version 3.9.2
Bazarr Directory /opt/bazarr
Bazarr Config Directory /opt/bazarr/data

**Comment by morpheus65535** [comment]
Duplicate #2281 and #2291.
