### ISSUE TITLE
DynaBox object has no attributes "getbollean"

### ISSUE THREAD

**Issue by joaofernandes** [morpheus65535/bazarr#2296]
**Describe the bug**
Considering that this https://github.com/morpheus65535/bazarr/issues/2294 was considered duplicated and fixed, I've downloaded the latest beta 1.3.2. beta 11
Following install procedure from https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/ once launching bazarr.py I get the following error 

`root@bazarr2:/opt/bazarr# python3 bazarr.py 
Bazarr starting...
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/main.py", line 37, in <module>
    check_if_new_update()
  File "/opt/bazarr/bazarr/app/check_update.py", line 110, in check_if_new_update
    download_release(url=release['download_link'])
  File "/opt/bazarr/bazarr/app/check_update.py", line 136, in download_release
    apply_update()
  File "/opt/bazarr/bazarr/app/check_update.py", line 191, in apply_update
    from .server import webserver
  File "/opt/bazarr/bazarr/app/server.py", line 12, in <module>
    from api import api_bp
  File "/opt/bazarr/bazarr/api/__init__.py", line 6, in <module>
    from .badges import api_ns_list_badges
  File "/opt/bazarr/bazarr/api/badges/__init__.py", line 3, in <module>
    from .badges import api_ns_badges
  File "/opt/bazarr/bazarr/api/badges/badges.py", line 11, in <module>
    from app.signalr_client import sonarr_signalr_client, radarr_signalr_client
  File "/opt/bazarr/bazarr/app/signalr_client.py", line 17, in <module>
    from sonarr.sync.episodes import sync_episodes, sync_one_episode
  File "/opt/bazarr/bazarr/sonarr/sync/episodes.py", line 11, in <module>
    from subtitles.indexer.series import store_subtitles, series_full_scan_subtitles
  File "/opt/bazarr/bazarr/subtitles/__init__.py", line 3, in <module>
    from . import mass_download  # noqa: W0611
  File "/opt/bazarr/bazarr/subtitles/mass_download/__init__.py", line 3, in <module>
    from .movies import movies_download_subtitles  # noqa: W0611
  File "/opt/bazarr/bazarr/subtitles/mass_download/movies.py", line 12, in <module>
    from subtitles.indexer.movies import store_subtitles_movie
  File "/opt/bazarr/bazarr/subtitles/indexer/movies.py", line 267, in <module>
    def movies_full_scan_subtitles(use_cache=settings.radarr.getboolean('use_ffprobe_cache')):
  File "/opt/bazarr/bazarr/../libs/dynaconf/utils/boxing.py", line 18, in evaluate
  File "/opt/bazarr/bazarr/../libs/dynaconf/utils/boxing.py", line 41, in __getattr__
  File "/opt/bazarr/bazarr/../libs/dynaconf/vendor/box/box.py", line 356, in __getattr__
dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has no attribute 'getboolean'"
Bazarr exited.`

**To Reproduce**
1. start a new server instance
2. Follow https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/ and use latest beta
3. run bazarr.py

**Expected behavior**
proper startup

**Comment by morpheus65535** [comment]
I'm not sure what you've downloaded because I've downloaded the beta.11 asset ([bazarr.zip](https://github.com/morpheus65535/bazarr/releases/download/v1.3.2-beta.11/bazarr.zip)) and the line 267 of `bazarr/subtitles/indexer/movies.py` doesn't match what you have. 

You can simply keep your previous install and switch to development branch in Settings-->General then force a update of Bazarr in System-->Tasks. There's no need to do such complicated re-installation.

**Comment by morpheus65535** [comment]
BTW, if you need support, come to Discord as there is no issue here. You probably simply installed beta asset without chaging the desired branch in Settings.

**Comment by joaofernandes** [comment]
Indeed, I've installed from the assets link within a release and I've assumed those betas were a full release and didn't rely on a specific branch.
