### ISSUE TITLE
Error while installing requirements

### ISSUE THREAD

**Issue by Julien-D** [morpheus65535/bazarr#23]
Hi

I am trying to install Bazarr but I have the following error while trying to install the dependencies:
```
pi@PiNAS:~/bazarr $ sudo pip install -r requirements.txt
Collecting apscheduler (from -r requirements.txt (line 1))
  Downloading APScheduler-3.5.0-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 1.3MB/s
Collecting babelfish (from -r requirements.txt (line 2))
  Downloading babelfish-0.5.5.tar.gz (90kB)
    100% |████████████████████████████████| 92kB 1.5MB/s
Collecting bottle (from -r requirements.txt (line 3))
  Downloading bottle-0.12.13.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 1.4MB/s
Collecting bottle-fdsend (from -r requirements.txt (line 4))
  Downloading bottle-fdsend-0.1.1.zip
Collecting dogpile.cache (from -r requirements.txt (line 5))
  Downloading https://www.piwheels.hostedpi.com/simple/dogpile-cache/dogpile.cac                                                                                                                                                             he-0.6.4-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 1.0MB/s
Collecting enzyme (from -r requirements.txt (line 6))
  Downloading enzyme-0.4.1.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 745kB/s
Collecting Pillow (from -r requirements.txt (line 7))
  Downloading Pillow-4.3.0.tar.gz (13.9MB)
    100% |████████████████████████████████| 13.9MB 12kB/s
Collecting py-pretty (from -r requirements.txt (line 8))
  Downloading py-pretty-1.zip
Collecting pycountry (from -r requirements.txt (line 9))
  Downloading pycountry-17.9.23.tar.gz (9.2MB)
    100% |████████████████████████████████| 9.2MB 19kB/s
Collecting pygit2 (from -r requirements.txt (line 10))
  Downloading pygit2-0.26.3.tar.gz (462kB)
    100% |████████████████████████████████| 471kB 472kB/s
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lsYqdK/pygit2/setup.py", line 202, in <module>
        **extra_args)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 317, in _                                                                                                                                                             _init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 372, in f                                                                                                                                                             etch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 84                                                                                                                                                             6, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 11                                                                                                                                                             18, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 11                                                                                                                                                             30, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 440, in f                                                                                                                                                             etch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py"                                                                                                                                                             , line 699, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py"                                                                                                                                                             , line 725, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py"                                                                                                                                                             , line 906, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py"                                                                                                                                                             , line 1145, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py"                                                                                                                                                             , line 1133, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'ar                                                                                                                                                             m-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ls                                                                                                                                                             YqdK/pygit2/
```
Could you please help me?

**Comment by morpheus65535** [comment]
Can you give me more details?

**Comment by Julien-D** [comment]
Feel free to tell me if you need me to lauch any command that could help you obtain more details.
My system:
```
julien@PiNAS:/media $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
julien@PiNAS:/media $ python -V
Python 2.7.13
```
What I did to install Bazarr:
`sudo apt-get install git-core
sudo apt install python-pip
su pi
cd ~
git clone https://github.com/morpheus65535/bazarr.git
cd bazarr
pip install -r requirements.txt
`
Everyting goes well until I launch the last command and I obtain the error displayed on the first message (I tried with sudo but obtained the exact same errors)

Julien

**Comment by morpheus65535** [comment]
Sorry, my bad. The instructions need some more work. From the dockerfile:

    apt-get install -y build-essential python-dev python-pip python-setuptools libjpeg-dev zlib1g-dev git libgit2-dev libffi-dev

libgit2-dev MUST be version 0.26. If you cannot get it from APT repositories, you're going to need to build it from source. :-/

**Comment by Julien-D** [comment]
Thank you Morpheus
I had to compile cmake and libgit2 but it finally worked
Thank you for your help on this topic

**Comment by morpheus65535** [comment]
It’s a pleasure! :-)
