### ISSUE TITLE
Job "Sync with Sonarr (trigger: ...)" raised an exception

### ISSUE THREAD

**Issue by j007bond007** [morpheus65535/bazarr#2301]
Series are not getting subtitles. I looked in the logs and found exceptions when Bazarr tries to sync with Sonarr. 

sqlite3.OperationalError: near "RETURNING": syntax error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/bazarr/bazarr/sonarr/sync/series.py", line 100, in update_series
    sync_episodes(series_id=show[\'id\'], send_event=send_event)
  File "/opt/bazarr/bazarr/sonarr/sync/episodes.py", line 116, in sync_episodes
    added_episodes = database.execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/scoping.py", line 724, in execute
    return self._proxied.execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/orm/bulk_persistence.py", line 1225, in orm_execute_statement
    result = conn.execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "RETURNING": syntax error
[SQL: INSERT INTO table_episodes (audio_codec, audio_language, episode, episode_file_id, file_size, format, monitored, path, resolution, "sceneName", season, "sonarrEpisodeId", "sonarrSeriesId", title, video_codec) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING "sonarrEpisodeId", path, "sonarrSeriesId"]
[parameters: (\'DTS\', "[\'English\']", 1, 1, 5866010649, \'HDTV\', \'False\', \'/media/media-nas/Shows/11.22.63/Season 1/11.22.63 - S01E01 - The Rabbit Hole.mkv\', \'1080p\', None, 1, 2, 1, \'The Rabbit Hole\', \'h264\', \'DTS\', "[\'English\']", 2, 2, 4691232320, \'HDTV\', \'False\', \'/media/media-nas/Shows/11.22.63/Season 1/11.22.63 - S01E02 - The Kill Floor.mkv\', \'1080p\', None, 1, 3, 1, \'The Kill Floor\', \'h264\', \'DTS\', "[\'English\']", 3, 3, 3519390796, \'HDTV\', \'False\', \'/media/media-nas/Shows/11.22.63/Season 1/11.22.63 - S01E03 - Other Voices, Other Rooms.mkv\', \'1080p\', None, 1, 4, 1, \'Other Voices, Other Rooms\', \'h264\', \'DTS\', "[\'English\']", 4, 4, 4690436369 ... 20 parameters truncated ... 1, 6, 1, \'The Truth\', \'h264\', \'DTS\', "[\'English\']", 6, 6, 3516836667, \'HDTV\', \'False\', \'/media/media-nas/Shows/11.22.63/Season 1/11.22.63 - S01E06 - Happy Birthday, Lee Harvey Oswald.mkv\', \'1080p\', None, 1, 7, 1, \'Happy Birthday, Lee Harvey Oswald\', \'h264\', \'DTS\', "[\'English\']", 7, 7, 4692440322, \'HDTV\', \'False\', \'/media/media-nas/Shows/11.22.63/Season 1/11.22.63 - S01E07 - Soldier Boy.mkv\', \'1080p\', None, 1, 8, 1, \'Soldier Boy\', \'h264\', \'DTS\', "[\'English\']", 8, 8, 4691459934, \'HDTV\', \'False\', \'/media/media-nas/Shows/11.22.63/Season 1/11.22.63 - S01E08 - The Day in Question.mkv\', \'1080p\', None, 1, 9, 1, \'The Day in Question\', \'h264\')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Expected behavior**
I would expect there to be no exceptions and for my subtitles to download for series.

**Software (please complete the following information):**
 - Bazarr: v 1.3.1
 - Radarr version v 4.6.4.7568
 - Sonarr version 3.0.10.1567
 - OS: Debian (Linux-5.15.74-1-pve-x86_64-with-glibc2.31)
 - Python: 3.9.2

**Additional context**
Movies with Radarr appear to sync and it downloads subtitles for most entries, this is only happening with Sonarr.

**Comment by morpheus65535** [comment]
6th duplicate from #2281 and still counting ;)
