### ISSUE TITLE
Radarr and Sonarr raised an exception

### ISSUE THREAD

**Issue by greatvc** [morpheus65535/bazarr#2303]
Hi,

I haven't change anything to my installation maybe an update to the bazarr but over the past weeks it does not download any subtitles and always raise an exception

`Job "Sync with Radarr (trigger: interval[0:15:00], next run at: 2023-11-23 10:16:58 EET)" raised an exception	23/11/2023 10:01:58	
Job "Sync with Sonarr (trigger: interval[0:15:00], next run at: 2023-11-23 10:15:23 EET)" raised an exception`

The logs from these exceptions:

```
Traceback (most recent call last):
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "RETURNING": syntax error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Applications/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Applications/bazarr/bazarr/sonarr/sync/series.py", line 100, in update_series
    sync_episodes(series_id=show[\'id\'], send_event=send_event)
  File "/Applications/bazarr/bazarr/sonarr/sync/episodes.py", line 116, in sync_episodes
    added_episodes = database.execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/scoping.py", line 724, in execute
    return self._proxied.execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/bulk_persistence.py", line 1225, in orm_execute_statement
    result = conn.execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "RETURNING": syntax error
[SQL: INSERT INTO table_episodes (audio_codec, audio_language, episode, episode_file_id, file_size, format, monitored, path, resolution, "sceneName", season, "sonarrEpisodeId", "sonarrSeriesId", title, video_codec) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING "sonarrEpisodeId", path, "sonarrSeriesId"]
[parameters: (\'EAC3\', "[\'English\']", 1, 8536, 1535579983, \'WEBDL\', \'True\', \'/Users//Documents/TV Shows/Fargo/Season 5/Fargo 5x01.mkv\', \'720p\', \'Fargo.S05E01.720p.AMZN.WEB-DL.DDP5.1.H.264-FLUX\', 5, 15091, 47, \'The Tragedy of the Commons\', \'h264\', \'EAC3\', "[\'English\']", 2, 8537, 1306404793, \'WEBDL\', \'True\', \'/Users//Documents/TV Shows/Fargo/Season 5/Fargo 5x02.mkv\', \'720p\', \'Fargo.S05E02.720p.AMZN.WEB-DL.DDP5.1.H.264-FLUX\', 5, 15092, 47, \'Trials and Tribulations\', \'h264\')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

```
Traceback (most recent call last):
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "RETURNING": syntax error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Applications/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Applications/bazarr/bazarr/radarr/sync/movies.py", line 112, in update_movies
    removed_movies = database.execute(delete(TableMovies)
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/scoping.py", line 724, in execute
    return self._proxied.execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/bulk_persistence.py", line 1838, in orm_execute_statement
    return super().orm_execute_statement(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/orm/context.py", line 253, in orm_execute_statement
    result = conn.execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Applications/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "RETURNING": syntax error
[SQL: DELETE FROM table_movies WHERE table_movies."tmdbId" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING "radarrId"]
[parameters: (\'869641\', \'705996\', \'884605\', \'363088\', \'447365\', \'912908\', \'570670\', \'447332\', \'395834\', \'520763\')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

These are all the same i think every 15 minutes of the interval.

![image](https://github.com/morpheus65535/bazarr/assets/13116317/a76d37f4-a06b-488a-ab56-2cdee9aaa8ca)

Looking forward for you help.

Regards, 
Vassilis

**Comment by halali** [comment]
7th duplicate from #2281
