### ISSUE TITLE
Log says: Exception on /api/series [PATCH]

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#2356]
Bazarr: 1.4.1-beta.14
Sonarr: 4.0.0.825
Radarr: 5.2.6.8376
OS: unRAID 6.12.6

When I click the "Search" button I get errors in the log:
(bazarr debug-log attached in the bottom)

![Monarch-Search](https://github.com/morpheus65535/bazarr/assets/45288008/623fe228-1d3e-4169-aede-402385715cf8)

- - - - - - - - - - - - - -

> Traceback (most recent call last):
  File "/app/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/api/series/series.py", line 212, in patch
    series_download_subtitles(seriesid)
  File "/app/bin/bazarr/subtitles/mass_download/series.py", line 84, in series_download_subtitles
    for result in generate_subtitles(path_mappings.path_replace(episode.path),
  File "/app/bin/bazarr/subtitles/download.py", line 105, in generate_subtitles
    processed_subtitle = process_subtitle(subtitle=subtitle, media_type=media_type,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/subtitles/processing.py", line 89, in process_subtitle
    sync_subtitles(video_path=path, srt_path=downloaded_path,
  File "/app/bin/bazarr/subtitles/sync.py", line 20, in sync_subtitles
    if media_type == \'series\':
       ^^^^^^^^^^
NameError: name \'media_type\' is not defined

- - - - - - - - - - - - - -

[bazarr.log](https://github.com/morpheus65535/bazarr/files/13919433/bazarr.log)

**Comment by morpheus65535** [comment]
Thanks for reporting. I've introduced a merge issue that should be fixed in upcoming beta.
