### ISSUE TITLE
Searching for any subtitles results in "500 you have disconnected from the server"

### ISSUE THREAD

**Issue by driesmp** [morpheus65535/bazarr#2361]
**Describe the bug**
When searching for any subtitle manually, it errors out on "500 you have disconnected from the server"

**To Reproduce**
Search for any subtitle

**Expected behavior**
I expect subtitles to be found

**Screenshots**

**Software (please complete the following information):**
 - Bazarr Version 1.4.1-beta.14
Package Version 1.4.0 by michiel@vanbaak.eu
Sonarr Version 4.0.0.748
Radarr Version 5.2.6.8376
Operating System FreeBSD-14.0-STABLE-amd64-64bit-ELF
Python Version 3.9.18

**Additional context**
stack trace
```
Traceback (most recent call last):
  File "/usr/local/share/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/share/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/share/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/share/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/local/share/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/share/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/usr/local/share/bazarr/bin/bazarr/api/movies/movies.py", line 185, in patch
    wanted_search_missing_subtitles_movies()
  File "/usr/local/share/bazarr/bin/bazarr/subtitles/wanted/movies.py", line 107, in wanted_search_missing_subtitles_movies
    wanted_download_subtitles_movie(movie.radarrId)
  File "/usr/local/share/bazarr/bin/bazarr/subtitles/wanted/movies.py", line 80, in wanted_download_subtitles_movie
    _wanted_movie(movie)
  File "/usr/local/share/bazarr/bin/bazarr/subtitles/wanted/movies.py", line 47, in _wanted_movie
    for result in generate_subtitles(path_mappings.path_replace_movie(movie.path),
  File "/usr/local/share/bazarr/bin/bazarr/subtitles/download.py", line 105, in generate_subtitles
    processed_subtitle = process_subtitle(subtitle=subtitle, media_type=media_type,
  File "/usr/local/share/bazarr/bin/bazarr/subtitles/processing.py", line 107, in process_subtitle
    command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language, downloaded_language_code2,
  File "/usr/local/share/bazarr/bin/bazarr/subtitles/sync.py", line 20, in sync_subtitles
    if media_type == \'series\':
NameError: name \'media_type\' is not defined
```

**Comment by morpheus65535** [comment]
Already fixed in beta.15.
