### ISSUE TITLE
Homebrew formula broken: Internal Server Error

### ISSUE THREAD

**Issue by alexreg** [morpheus65535/bazarr#2392]
**Describe the bug**
When I try to open the Bazarr admin page in the browser, I get an 'Internal Server Error'. The Bazarr log shows the following issue, which concerns templating.

```
2024-02-14 01:51:55|ERROR   |app.app                         |Exception on / [GET]|'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask/app.py", line 2525, in wsgi_app\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask/app.py", line 1822, in full_dispatch_request\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask_restx/api.py", line 675, in error_router\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask_cors/extension.py", line 165, in wrapped_function\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask/app.py", line 1796, in dispatch_request\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/app/ui.py", line 97, in catch_all\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask/templating.py", line 146, in render_template\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/jinja2/environment.py", line 1081, in get_or_select_template\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/jinja2/environment.py", line 1010, in get_template\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/jinja2/environment.py", line 969, in _load_template\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/jinja2/loaders.py", line 126, in load\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask/templating.py", line 62, in get_source\n  File "/opt/homebrew/Cellar/bazarr/1.4.0/libexec/bazarr/../libs/flask/templating.py", line 98, in _get_source_fast\njinja2.exceptions.TemplateNotFound: index.html'|
```

**To Reproduce**
1. Install the macOS Homebrew formula `bazarr`.
2. Run `sudo brew services start bazarr` to start bazarr as a service.

**Expected behavior**
The Bazarr admin page should load in the web browser. There should not be a templating error. It seems that something major changed in a release of Bazarr (concerning templating), as the Homebrew formula was working for a long time.

**Software (please complete the following information):**
 - Bazarr: 1.4.1
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: macOS 14.2.1

**Comment by morpheus65535** [comment]
We do not maintain Homebrew formula, you'll have to check with them.

**Comment by alexreg** [comment]
Yes, I maintain it haha. But the real question is: have you changed the way in which templating works? Because it suddenly broke without any change on my end.

**Comment by JaiZed** [comment]
Why does your exception trace refer to Bazarr 1.4.0 when you say you are running 1.4.1?

**Comment by morpheus65535** [comment]
Nope, no change here but you probably didn't include the frontend/build directory that come with releases.

**Comment by alexreg** [comment]
@morpheus65535 Okay, I'll check into that. Thanks for the tip.

**Comment by morpheus65535** [comment]
You can get to our Discord server to debug this if you need more help! :-)
