### ISSUE TITLE
Subdivx broken again, however nothing seems to have changed on their side

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2424]
it's been about a week that Subdivx is not giving any results, checking the log it yields:
JSONDecodeError. Exception info: "'Expecting value: line 1 column 1 (char 0)' ~ subdivx.py@200"

Did some experiments, and really don't understand what's happening - if I run (on the same server but not inside the docker) a simple test script that I created (just posts a request and decodes the json), it runs ok. Subdivx does not seem to have changed anything on the way it handles the requests and results.
The POST operation returns 200, so no error there. For some reason Bazarr is breaking while decoding the result.

The full debug log of the issue is as follows:

2024-03-06 18:00:40|DEBUG   |urllib3.connectionpool          |https://www.subdivx.com:443 "POST /inc/ajax.php HTTP/1.1" 200 None|
2024-03-06 18:00:40|ERROR   |subliminal_patch.core           |Unexpected error in provider 'subdivx': Traceback (most recent call last):  File "/app/bin/bazarr/../libs/requests/models.py", line 971, in json    return complexjson.loads(self.text, **kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads    return _default_decoder.decode(s)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 366, in list_subtitles_provider    results = self[provider].list_subtitles(video, to_request)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bin/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 225, in list_subtitles    return self.query(video, languages)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bin/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 139, in query    subtitles += self._handle_search(f"{title} S{video.season:02}E{video.episode:02}", video)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bin/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 200, in _handle_search    data = response.json()           ^^^^^^^^^^^^^^^  File "/app/bin/bazarr/../libs/requests/models.py", line 975, in json    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)|Traceback (most recent call last):  File "/app/bin/bazarr/../libs/requests/models.py", line 971, in json    return complexjson.loads(self.text, **kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads    return _default_decoder.decode(s)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 366, in list_subtitles_provider    results = self[provider].list_subtitles(video, to_request)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bin/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 225, in list_subtitles    return self.query(video, languages)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bin/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 139, in query    subtitles += self._handle_search(f"{title} S{video.season:02}E{video.episode:02}", video)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bin/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 200, in _handle_search    data = response.json()           ^^^^^^^^^^^^^^^  File "/app/bin/bazarr/../libs/requests/models.py", line 975, in json    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)|
2024-03-06 18:00:40|INFO    |root                            |Throttling subdivx for 10 minutes, until 24/03/06 18:10, because of: JSONDecodeError. Exception info: "'Expecting value: line 1 column 1 (char 0)' ~ subdivx.py@200"|

**Comment by morpheus65535** [comment]
Duplicate #2406
