### ISSUE TITLE
Error: 500 Internal Server Error on System

### ISSUE THREAD

**Issue by dimitrov-adrian** [morpheus65535/bazarr#244]
**Describe the bug**
Got error

```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://bazarr.local/system' caused an error:

Internal Server Error
Exception:
AttributeError("'str' object has no attribute 'json'",)
Traceback:
Traceback (most recent call last):
  File "/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/bazarr/bazarr/main.py", line 119, in wrapper
    return func(*a, **ka)
  File "/bazarr/bazarr/main.py", line 1465, in system
    sonarr_version=sonarr_version.json()['version'], radarr_version=radarr_version.json()['version'],
AttributeError: 'str' object has no attribute 'json'
```

**To Reproduce**
1. Go to 'System'

**Software (please complete the following information):**
 - Bazarr: 0.6.9
 - Sonarr version 2.0.0.5252
 - OS: Docker

Restarting the container doesn't helps. All other endpoints seems to works fine.

**Comment by morpheus65535** [comment]
@halali shouldn’t that one been fixed already?

**Comment by morpheus65535** [comment]
I've fixed it. Should be good in 0.6.9.1 that will be released later this week.
