### ISSUE TITLE
sqlalchemy.exc.IntegrityError

### ISSUE THREAD

**Issue by tallevi1000** [morpheus65535/bazarr#2540]
i had a previous version 1.2.0 which worked fine.
after installing the app v1.4.3 using docker (used same "docker run" to create the container as the one i used before to create the 1.2.0), the app wont start.
the container is running but the app wont start.

Error message:
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: table_history.id
[SQL: INSERT INTO table_history (id, action, description, language, provider, score, "sonarrEpisodeId", "sonarrSeriesId", subs_id, subtitles_path, timestamp, video_path, matched, not_matched) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]

Full error stack:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1929, in _exec_single_context
    self.dialect.do_executemany(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 921, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: table_history.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 51, in <module>
    migrate_db(app)
  File "/app/bazarr/bin/bazarr/app/database.py", line 324, in migrate_db
    flask_migrate.upgrade(directory=migrations_directory)
  File "/app/bazarr/bin/bazarr/../libs/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/app/bazarr/bin/bazarr/../libs/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/app/bazarr/bin/bazarr/../libs/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/app/bazarr/bin/bazarr/../libs/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/bazarr/bin/migrations/env.py", line 119, in <module>
    run_migrations_online()
  File "/app/bazarr/bin/migrations/env.py", line 106, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/app/bazarr/bin/bazarr/../libs/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/app/bazarr/bin/bazarr/../libs/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/app/bazarr/bin/migrations/versions/195144da1f7e_.py", line 63, in upgrade
    op.bulk_insert(TableHistory.__table__, rows=table_history_data)
  File "<string>", line 8, in bulk_insert
  File "<string>", line 3, in bulk_insert
  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/ops.py", line 2431, in bulk_insert
    operations.invoke(op)
  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/base.py", line 445, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/alembic/operations/toimpl.py", line 215, in bulk_insert
    operations.impl.bulk_insert(  # type: ignore[union-attr]
  File "/app/bazarr/bin/bazarr/../libs/alembic/ddl/impl.py", line 438, in bulk_insert
    self._exec(
  File "/app/bazarr/bin/bazarr/../libs/alembic/ddl/impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
           ^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1929, in _exec_single_context
    self.dialect.do_executemany(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 921, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: table_history.id
[SQL: INSERT INTO table_history (id, action, description, language, provider, score, "sonarrEpisodeId", "sonarrSeriesId", subs_id, subtitles_path, timestamp, video_path, matched, not_matched) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]

**To Reproduce**
1. start with version 1.2.0 installed and running
2. delete previous container
3. delete previous docker image
4. execute docker run
docker run -d \
  --name=bazarr-1.4.3 \
  -e PUID=1003 \
  -e PGID=100 \
  -e TZ="xxxx" \
  -p 49188:6767 \
  -v "/xxxx/Bazarr":/config \
  -v "/xxxx/Movies":/movies \
  -v "/xxxx/TV":/tv \
  --restart unless-stopped \
  -m 2048m \
  lscr.io/linuxserver/bazarr:latest

6. docker images are pulled. container is running but app wont load...

**Expected behavior**
app loads with no errors

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Radarr version 5.6.0.8846
 - Sonarr version 4.0.5.1710
 - OS: Docker (QNAP docker station)

**Comment by JaiZed** [comment]
1.2.0 is too old to upgrade to 1.4 3.
The database schemas have changed too much.

You would be far better off just to delete your database, set your configuration and then re-index all of your files from Sonarr / Radarr.

**Comment by tallevi1000** [comment]
> 1.2.0 is too old to upgrade to 1.4 3. The database schemas have changed too much.
> 
> You would be far better off just to delete your database, set your configuration and then re-index all of your files from Sonarr / Radarr.


Figured....
i deleted the database files from the container's config folder and recreate the container.
app load fine now.
thanks for the quick reply :)
