### ISSUE TITLE
linuxserver/bazarr wont start OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by vonProteus** [morpheus65535/bazarr#2548]
**Describe the bug**
wont start

**To Reproduce**
i tried to reproduce on other pc and i can't

logs looks like this:
```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 20, in <module>
    from app.check_update import apply_update, check_releases, check_if_new_update  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/check_update.py", line 15, in <module>
    from .config import settings
  File "/app/bazarr/bin/bazarr/app/config.py", line 486, in <module>
    write_config()
  File "/app/bazarr/bin/bazarr/app/config.py", line 436, in write_config
    write(settings_path=config_yaml_file,
  File "/app/bazarr/bin/bazarr/../libs/dynaconf/loaders/yaml_loader.py", line 118, in write
    with open(
OSError: [Errno 28] No space left on device
```

**Expected behavior**
starting bazzar

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - OS:  k3s (kubernates) on debian 11 

**Additional context**
in container when i do `df -h`

```
Filesystem                Size  Used Avail Use% Mounted on
overlay                    60G   42G   16G  74% /
tmpfs                      64M     0   64M   0% /dev
tmpfs                      12G     0   12G   0% /sys/fs/cgroup
nfs_path_to_bazarr         54G   26M   54G   1% /config
nfs_path_to_tvs           ****  ****  ****  80% /tv
nfs_path_to_movies        ****  ****  ****  38% /movies
nfs_path_to_anime         ****  ****  ****  66% /anime
tmpfs                     512M     0  512M   0% /tmp
tmpfs                     512M     0  512M   0% /dev/shm
/dev/vda3                  60G   42G   16G  74% /etc/hosts
tmpfs                     512M   12K  512M   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                      12G     0   12G   0% /proc/acpi
tmpfs                      12G     0   12G   0% /sys/firmware
```
so i don't understand error because i have free space on disk

any suggestion would be greatly appreciated

If this isn't the place for this type of bug, I'm sorry

**Comment by halali** [comment]
This is issue with your kubernetes pvc configuration probably, come to discord and someone will help you... 

I dont see this as bazarr issue.

**Comment by morpheus65535** [comment]
I agree, lets close this one.
