### ISSUE TITLE
Error searching on AvistaZ and CinemaZ subtitles provider 

### ISSUE THREAD

**Issue by mat926** [morpheus65535/bazarr#2552]
**Describe the bug**
```
2024-06-15 18:06:06,150 - root                             (7fbc86f1db38) :  DEBUG (ffprobe:40) - FFprobe found: {'path': '/data/media/movies/Mag-ingat ka sa. Kulam (2008)/Mag-ingat ka sa. Kulam (2008) [imdbid-tt1071223] - [DVD][MP3 2.0][DivX].avi', 'duration': datetime.timedelta(seconds=5663, microseconds=724733), 'size': 894479376, 'bit_rate': 1263450, 'container': 'avi', 'video': [{'id': 0, 'name': 'Video', 'duration': datetime.timedelta(seconds=5663, microseconds=724733), 'width': 720, 'height': 480, 'scan_type': 'Progressive', 'aspect_ratio': Decimal('1.5'), 'pixel_aspect_ratio': Decimal('1.0'), 'resolution': '480p', 'frame_rate': Decimal('29.970'), 'bit_rate': 1123835, 'codec': 'MPEG-4'}], 'audio': [{'id': 1, 'name': 'Audio', 'codec': 'MP3', 'channels_count': 2, 'channels': '2.0', 'bit_rate': 128000, 'sampling_rate': 48000}], 'provider': {'name': 'ffmpeg', 'version': {'/usr/bin/ffprobe': 'v6.0'}}}
2024-06-15 18:06:06,150 - root                             (7fbc86f1db38) :  DEBUG (utils:48) - Running refiner: arr_history
2024-06-15 18:06:06,167 - urllib3.connectionpool           (7fbc86f1db38) :  DEBUG (connectionpool:244) - Starting new HTTP connection (1): 192.168.0.143:7878
2024-06-15 18:06:06,571 - urllib3.connectionpool           (7fbc86f1db38) :  DEBUG (connectionpool:549) - http://192.168.0.143:7878 "GET /api/v3/history?eventType=1&movieIds=67&apikey=0d427009cac24ccf89a9f31283604279 HTTP/1.1" 200 None
2024-06-15 18:06:06,572 - root                             (7fbc86f1db38) :  DEBUG (arr_history:31) - Refining  with Info URL: https://avistaz.to/torrent/29351-mag-ingat-ka-sa-kulam-2008-dvdrip-divx
2024-06-15 18:06:06,573 - root                             (7fbc86f1db38) :  DEBUG (utils:48) - Running refiner: anidb
2024-06-15 18:06:06,573 - root                             (7fbc86f1db38) :  DEBUG (anidb:119) - Video is not an Anime TV series, skipping refinement for 
2024-06-15 18:06:06,573 - root                             (7fbc86f1db38) :  DEBUG (utils:51) - BAZARR is using these video object properties: {'name': '/data/media/movies/Mag-ingat ka sa. Kulam (2008)/Mag-ingat Ka Sa... Kulam (2008) DVDRiP DivX.avi', 'source': 'DVD', 'release_group': None, 'resolution': '0p', 'video_codec': 'DivX', 'audio_codec': 'MP3', 'imdb_id': 'tt1071223', 'hashes': {'opensubtitlescom': 'a7e645028665a5bc'}, 'size': 894479376, 'subtitle_languages': set(), 'original_name': 'Mag-ingat ka sa. Kulam (2008) [imdbid-tt1071223] - [DVD][MP3 2.0][DivX].avi', 'plexapi_metadata': {}, 'hints': {'title': 'Mag-ingat ka sa... Kulam', 'type': 'movie', 'single_value': True}, 'audio_languages': set(), 'external_subtitle_languages': set(), 'streaming_service': None, 'edition': None, 'original_path': '/data/media/movies/Mag-ingat ka sa. Kulam (2008)/Mag-ingat ka sa. Kulam (2008) [imdbid-tt1071223] - [DVD][MP3 2.0][DivX].avi', 'other': 'Rip', 'info_url': 'https://avistaz.to/torrent/29351-mag-ingat-ka-sa-kulam-2008-dvdrip-divx', 'series_anidb_series_id': (None,), 'series_anidb_episode_id': (None,), 'title': 'Mag-ingat ka sa... Kulam', 'year': 2008, 'alternative_titles': [], 'used_scene_name': True, 'radarrId': 67, 'fps': Decimal('29.970')}
2024-06-15 18:06:06,574 - subliminal_patch.core_persistent (7fbc86f1db38) :  INFO (core_persistent:21) - Listing subtitles for 
2024-06-15 18:06:06,574 - subliminal_patch.core            (7fbc81c92b38) :  DEBUG (core:335) - Languages requested: {, }
2024-06-15 18:06:06,575 - subliminal_patch.core            (7fbc81a80b38) :  DEBUG (core:335) - Languages requested: {, }
2024-06-15 18:06:06,575 - subliminal_patch.core            (7fbc81c92b38) :  DEBUG (core:192) - New set: 346 items
2024-06-15 18:06:06,577 - subliminal_patch.core            (7fbc81c92b38) :  DEBUG (core:170) - Nothing to translate found
2024-06-15 18:06:06,577 - subliminal_patch.core            (7fbc81c92b38) :  INFO (core:365) - Listing subtitles with provider 'avistaz' and languages {, }
2024-06-15 18:06:06,578 - subliminal_patch.core            (7fbc81c92b38) :  INFO (core:296) - Initializing provider avistaz
2024-06-15 18:06:06,577 - subliminal_patch.core            (7fbc81a80b38) :  DEBUG (core:192) - New set: 346 items
2024-06-15 18:06:06,575 - subliminal_patch.core            (7fbc8186eb38) :  DEBUG (core:335) - Languages requested: {, }
2024-06-15 18:06:06,578 - subliminal_patch.core            (7fbc81a80b38) :  DEBUG (core:170) - Nothing to translate found
2024-06-15 18:06:06,579 - subliminal_patch.core            (7fbc8186eb38) :  DEBUG (core:192) - New set: 1688 items
2024-06-15 18:06:06,579 - subliminal_patch.core            (7fbc81a80b38) :  INFO (core:365) - Listing subtitles with provider 'cinemaz' and languages {, }
2024-06-15 18:06:06,580 - subliminal_patch.core            (7fbc8186eb38) :  DEBUG (core:170) - Nothing to translate found
2024-06-15 18:06:06,580 - subliminal_patch.providers.avistaz_network (7fbc81a80b38) :  DEBUG (avistaz_network:296) -  not downloaded from https://cinemaz.to/. Skipped
2024-06-15 18:06:06,581 - subliminal_patch.core            (7fbc8186eb38) :  INFO (core:365) - Listing subtitles with provider 'opensubtitlescom' and languages {, }
2024-06-15 18:06:06,581 - subliminal_patch.providers.opensubtitlescom (7fbc8186eb38) :  DEBUG (opensubtitlescom:295) - Searching using this hash: a7e645028665a5bc
2024-06-15 18:06:06,581 - subliminal_patch.providers.opensubtitlescom (7fbc8186eb38) :  DEBUG (opensubtitlescom:320) - Searching for those languages: en
2024-06-15 18:06:06,610 - urllib3.connectionpool           (7fbc8186eb38) :  DEBUG (connectionpool:549) - https://api.opensubtitles.com:443 "GET /api/v1/subtitles?ai_translated=exclude&imdb_id=1071223&languages=en&moviehash=a7e645028665a5bc HTTP/1.1" 200 66
2024-06-15 18:06:06,610 - subliminal_patch.providers.opensubtitlescom (7fbc8186eb38) :  DEBUG (opensubtitlescom:370) - Query returned 0 subtitles
2024-06-15 18:06:06,689 - urllib3.connectionpool           (7fbc81c92b38) :  DEBUG (connectionpool:1055) - Starting new HTTPS connection (1): avistaz.to:443
2024-06-15 18:06:07,067 - urllib3.connectionpool           (7fbc81c92b38) :  DEBUG (connectionpool:549) - https://avistaz.to:443 "GET /rules HTTP/1.1" 200 None
2024-06-15 18:06:07,069 - subliminal_patch.providers.avistaz_network (7fbc81c92b38) :  DEBUG (avistaz_network:287) - Cookies valid
2024-06-15 18:06:09,296 - urllib3.connectionpool           (7fbc81c92b38) :  DEBUG (connectionpool:549) - https://avistaz.to:443 "GET /torrent/29351-mag-ingat-ka-sa-kulam-2008-dvdrip-divx HTTP/1.1" 200 None
2024-06-15 18:06:09,346 - subliminal_patch.core            (7fbc81c92b38) :  ERROR (core:399) - Unexpected error in provider 'avistaz': Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 368, in list_subtitles_provider
    results = self[provider].list_subtitles(video, to_request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/avistaz_network.py", line 305, in list_subtitles
    release = self._parse_release_table(html)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/avistaz_network.py", line 360, in _parse_release_table
    for tr in release_data_table.find_all('tr', recursive=False):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 368, in list_subtitles_provider
    results = self[provider].list_subtitles(video, to_request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/avistaz_network.py", line 305, in list_subtitles
    release = self._parse_release_table(html)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/avistaz_network.py", line 360, in _parse_release_table
    for tr in release_data_table.find_all('tr', recursive=False):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
2024-06-15 18:06:09,348 - root                             (7fbc81c92b38) :  INFO (get_providers:379) - Throttling avistaz for 10 minutes, until 24/06/15 18:16, because of: AttributeError. Exception info: "''NoneType' object has no attribute 'find_all'' ~ avistaz_network.py@360"
2024-06-15 18:06:09,350 - socketio.server                  (7fbc81c92b38) :  INFO (server:161) - emitting event "data" to all [/]
2024-06-15 18:06:09,351 - engineio.server                  (7fbc81c92b38) :  INFO (socket:76) - lh-bAiYg7z1WR-v_AAAE: Sending packet MESSAGE data 2["data",{"type":"badges","action":"update","payload":null}]
2024-06-15 18:06:09,352 - subliminal_patch.core            (7fbc86f1db38) :  INFO (core:734) - Discarding provider avistaz
2024-06-15 18:06:09,352 - subliminal_patch.core_persistent (7fbc86f1db38) :  INFO (core_persistent:26) - Found 0 subtitle(s)
2024-06-15 18:06:09,354 - root                             (7fbc86f1db38) :  DEBUG (manual:134) - BAZARR 0 Subtitles have been found for this file: /data/media/movies/Mag-ingat ka sa. Kulam (2008)/Mag-ingat ka sa. Kulam (2008) [imdbid-tt1071223] - [DVD][MP3 2.0][DivX].avi
2024-06-15 18:06:09,355 - root                             (7fbc86f1db38) :  DEBUG (manual:135) - BAZARR Ended searching Subtitles for this file: /data/media/movies/Mag-ingat ka sa. Kulam (2008)/Mag-ingat ka sa. Kulam (2008) [imdbid-tt1071223] - [DVD][MP3 2.0][DivX].avi
```

**To Reproduce**
1. Search any subtitles with AvistaZ and CinemaZ

**Expected behavior**
It should find subtitles.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Radarr version 5.6.0.8846
 - Sonarr version 4.0.5.1710
 - OS: Linux

**Additional context**

**Comment by morpheus65535** [comment]
@goroskob could you take a look please?

**Comment by morpheus65535** [comment]
@goroskob any finding?

**Comment by goroskob** [comment]
> @goroskob any finding?

I think I know what's this about. There is a bug, that is known to me, which appears when user has notifications displayed on his account on AvistaZ platform sites. Basically, it breaks the scraping because it introduces an extra element in the HTML layout, where it's not expected. The good thing is that those notifications go away and scraping works again.

I'll try to find the time to fix that bug this week by finding a way to net rely on page's layout so much

**Comment by morpheus65535** [comment]
Thanks @goroskob , I'll wait for your PR!

**Comment by Dnkhatri** [comment]
@goroskob hi any update on the fix for this?

**Comment by goroskob** [comment]
> @goroskob hi any update on the fix for this?

Hey! I submitted a pull request that should fix the issue

**Comment by morpheus65535** [comment]
@goroskob with your PR, the exception is now handled properly but the provider will be throttled for 10 minutes (IIRC). Should you simply debug log the error and return an empty list of subtitles so we simply skip this provider once and reuse it for the next search?

**Comment by goroskob** [comment]
@morpheus65535 sure, if you want it this way. But I don’t think we should. The exception will be thrown if the page layout changed in a way that prevents scraping for subtitles, and I think it makes sense to throttle the provider. This way, if the site is ever updated in an incompatible manner, we’ll learn about it sooner and fix it, because the provider won’t just fail silently.

**Comment by morpheus65535** [comment]
@goroskob oh I was under the impression that it was to fix a temporary issue. I agree then for this PR but I would raise a ProviderError exception instead of a bare Exception.

**Comment by goroskob** [comment]
@morpheus65535 oh i see. The actual fix is the line above the exception handling: I modified the query slightly so that it works with those site notifications present too.

I’ll fix the exception type in a couple of days and will get back to you.

**Comment by goroskob** [comment]
@morpheus65535 I pushed the Exception -> ProviderError fix

**Comment by morpheus65535** [comment]
> @morpheus65535 I pushed the Exception -> ProviderError fix

Thanks, I've merged it and it will be included in upcoming beta!
