### ISSUE TITLE
KeyError with provider `soustitreseu`

### ISSUE THREAD

**Issue by FirelightFlagboy** [morpheus65535/bazarr#2569]
**Describe the bug**
A `KeyError` exception is raised when the provider `soustitreseu` parse some data 

**To Reproduce**
1. Configure the subtitle provider `soustitreseu`
2. Have some wanted subtitles that will use the newly configured provider 
4. Search for missing subtitles
5. See error in logs

**Expected behavior**
I would expect the provider to not raise that exception.

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Radarr version 5.4.6.8723
 - Sonarr version 4.0.5.1801
 - OS: Linux

**Additional context**

From the traceback (see below), the affected line is:

https://github.com/morpheus65535/bazarr/blob/97ea3a81242f604007fcd54c54f4acf17a97fade/custom_libs/subliminal_patch/providers/soustitreseu.py#L280

Where the value `_guess` was set on this line:

https://github.com/morpheus65535/bazarr/blob/97ea3a81242f604007fcd54c54f4acf17a97fade/custom_libs/subliminal_patch/providers/soustitreseu.py#L278

<details>

<summary>Some log</summary>

```
2024-07-07 11:19:49,270 - urllib3.connectionpool           (7fef6f611b38) :  DEBUG (connectionpool:549) - https://www.sous-titres.eu:443 "GET /search.html?q=Hellsing+Ultimate HTTP/1.1" 200 None
2024-07-07 11:19:50,230 - urllib3.connectionpool           (7fef6f611b38) :  DEBUG (connectionpool:549) - https://www.sous-titres.eu:443 "GET /series/hellsing_ultimate.html HTTP/1.1" 200 None
2024-07-07 11:19:50,466 - urllib3.connectionpool           (7fef6f611b38) :  DEBUG (connectionpool:549) - https://www.sous-titres.eu:443 "GET /series/download/bmmiidiwhv6fq4m/Hellsing.Ultimate.S01.DVDRip.Z2-Belge.FR.zip HTTP/1.1" 200 147463
2024-07-07 11:19:50,467 - subliminal_patch.providers.soustitreseu (7fef6f611b38) :  DEBUG (soustitreseu:246) - Sous-Titres.eu: Identified zip archive
2024-07-07 11:19:50,478 - subliminal_patch.core            (7fef6f611b38) :  ERROR (core:399) - Unexpected error in provider 'soustitreseu': Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../custom_libs/subliminal_patch/core.py", line 368, in list_subtitles_provider
    results = self[provider].list_subtitles(video, to_request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../custom_libs/subliminal_patch/providers/soustitreseu.py", line 230, in list_subtitles
    subtitles += [s for s in self.query_series(video, video.series) if s.language in languages]
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../custom_libs/subliminal_patch/providers/soustitreseu.py", line 174, in query_series
    subtitles_from_archive = self._get_subtitle_from_archive(archive, video)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../custom_libs/subliminal_patch/providers/soustitreseu.py", line 280, in _get_subtitle_from_archive
    if video.episode != _guess['episode'] or video.season != _guess['season']:
                        ~~~~~~^^^^^^^^^^^
KeyError: 'episode'
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../custom_libs/subliminal_patch/core.py", line 368, in list_subtitles_provider
    results = self[provider].list_subtitles(video, to_request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../custom_libs/subliminal_patch/providers/soustitreseu.py", line 230, in list_subtitles
    subtitles += [s for s in self.query_series(video, video.series) if s.language in languages]
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../custom_libs/subliminal_patch/providers/soustitreseu.py", line 174, in query_series
    subtitles_from_archive = self._get_subtitle_from_archive(archive, video)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../custom_libs/subliminal_patch/providers/soustitreseu.py", line 280, in _get_subtitle_from_archive
    if video.episode != _guess['episode'] or video.season != _guess['season']:
                        ~~~~~~^^^^^^^^^^^
KeyError: 'episode'
2024-07-07 11:19:50,554 - root                             (7fef6f611b38) :  INFO (get_providers:379) - Throttling soustitreseu for 10 minutes, until 24/07/07 11:29, because of: KeyError. Exception info: "''episode'' ~ soustitreseu.py@280"
```

</details>

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
