### ISSUE TITLE
docker container dev 1.4.4-beta.25 crash on start

### ISSUE THREAD

**Issue by xloooolx** [morpheus65535/bazarr#2592]
**Describe the bug**

**To Reproduce**
after start container crash 

I get this error 

```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
Linuxserver.io version: v1.4.4-beta.25-ls618
Build-date: 2024-07-25T06:33:58+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:165: SyntaxWarning: invalid escape sequence '\.'
  IETF_MATCH = ".+\.([^-.]+)(?:-[A-Za-z]+)?$"
/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:166: SyntaxWarning: invalid escape sequence '\.'
  ENDSWITH_LANGUAGECODE_RE = re.compile("\.([^-.]{2,3})(?:-[A-Za-z]{2,})?$")
/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:170: SyntaxWarning: invalid escape sequence '\.'
  language_match = re.match(".+\.([^\.]+)$" if not ietf
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column table_languages_profiles.tag does not exist
LINE 1: ...tain", table_languages_profiles."originalFormat", table_lang...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 52, in <module>
    upgrade_languages_profile_hi_values()
  File "/app/bazarr/bin/bazarr/app/database.py", line 508, in upgrade_languages_profile_hi_values
    for languages_profile in (database.execute(
                              ^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/scoping.py", line 778, in execute
    return self._proxied.execute(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
           ^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column table_languages_profiles.tag does not exist
LINE 1: ...tain", table_languages_profiles."originalFormat", table_lang...
                                                             ^
[SQL: SELECT table_languages_profiles."profileId", table_languages_profiles.name, table_languages_profiles.cutoff, table_languages_profiles.items, table_languages_profiles."mustContain", table_languages_profiles."mustNotContain", table_languages_profiles."originalFormat", table_languages_profiles.tag 
FROM table_languages_profiles]
(Background on this error at: https://sqlalche.me/e/20/f405)
Connection to localhost (127.0.0.1) 6767 port [tcp/*] succeeded!
[ls.io-init] done.
```

and from PostgreSQL

```
2024-07-25 23:34:48.848 UTC [4264] ERROR:  column table_languages_profiles.tag does not exist at character 268
2024-07-25 23:34:48.848 UTC [4264] STATEMENT:  SELECT table_languages_profiles."profileId", table_languages_profiles.cutoff, table_languages_profiles."originalFormat", table_languages_profiles.items, table_languages_profiles.name, table_languages_profiles."mustContain", table_languages_profiles."mustNotContain", table_languages_profiles.tag 
	FROM table_languages_profiles 
	WHERE table_languages_profiles."profileId" = 1
```

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [1.4.4-beta.25]
 - Radarr version [    5.9.0.8962]
 - Sonarr version [4.0.8.1929]
 - OS: [docker]

**Additional context**

**Comment by bakerboy448** [comment]
PG version?

**Comment by bakerboy448** [comment]
Additional logs from this missing tags column - but different bazarr error - running pg16

https://gist.github.com/bakerboy448/cabc5fcdb1be576d35aecc4f41ec5e6b

@xloooolx - possible postgresql to run to fix to add the column and get moving; worked for me: https://gist.github.com/bakerboy448/f3023d9a9d854ba55db68da1c2606b3d

**Comment by anderson-oki** [comment]
it seems flask migrations are running but none are being applied when i tested with pg14, pg15 and pg16. I'm not sure what is the issue yet.

@xloooolx @bakerboy448 Can you check the table alembic_versions?

**Comment by bakerboy448** [comment]
`452dd0f0b578`

**Comment by xloooolx** [comment]
> PG version?

14




> Additional logs from this missing tags column - but different bazarr error - running pg16
> 
> https://gist.github.com/bakerboy448/cabc5fcdb1be576d35aecc4f41ec5e6b
> 
> @xloooolx - possible postgresql to run to fix to add the column and get moving; worked for me: https://gist.github.com/bakerboy448/f3023d9a9d854ba55db68da1c2606b3d

I added the column, and it works like a charm, thank you.




> it seems flask migrations are running but none are being applied when i tested with pg14, pg15 and pg16. I'm not sure what is the issue yet.
> 
> @xloooolx @bakerboy448 Can you check the table `alembic_versions` and see what is the content?

452dd0f0b578

**Comment by dracossan** [comment]
Hi , same issue:
https://github.com/linuxserver/docker-bazarr/issues/139

I simply delete database for now and restart from scratch for temporary fixe.

**Comment by anderson-oki** [comment]
It will be fixed on the upcoming beta.
