### ISSUE TITLE
Fresh installation crashes on startup v1.4.4-beta.27

### ISSUE THREAD

**Issue by rafaello104** [morpheus65535/bazarr#2597]
**Describe the bug**
When installing bazarr (fresh install) with Python 3.10, using the development branch will crash the program.

**To Reproduce**
1. Install bazarr as mentioned in the docs: https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/
2. Open the web UI
3. Select the beta: Settings > General > development branch
4. Force an update: System > Tasks > Update Bazarr
5. Wait for the update to finish
6. Try to access web UI, check the logs, run the program in the cli, or check system logs in case of systemd service (journalctl -xe, ...)

**Expected behavior**
Software works

**Screenshots**
Pasting code below rather than screenshots

**Software (please complete the following information):**
 - Bazarr: [v1.4.4-beta.27]
 - Radarr version [5.6.0.8846]
 - Sonarr version [4.0.8.1874]
 - OS: [Ubuntu 22.04]
 - Python: [3.10]

**Additional context**
Crash logs:

**If I run it directly in the terminal, it completely hangs and refuses to end the process:**
```
root@indexers:/etc/default# /usr/bin/python3 /opt/bazarr/bazarr.py
Bazarr starting child process with PID 108629...
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: file is not a database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bazarr/bazarr/main.py", line 22, in <module>
    from init import *  # noqa E402
  File "/opt/bazarr/bazarr/init.py", line 219, in <module>
    init_db()
  File "/opt/bazarr/bazarr/app/database.py", line 302, in init_db
    metadata.create_all(engine)
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/schema.py", line 5825, in create_all
    bind._run_ddl_visitor(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 3233, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2439, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/ddl.py", line 897, in visit_metadata
    [t for t in tables if self._can_create_table(t)]
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/ddl.py", line 897, in <listcomp>
    [t for t in tables if self._can_create_table(t)]
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/ddl.py", line 862, in _can_create_table
    return not self.checkfirst or not self.dialect.has_table(
  File "<string>", line 2, in has_table
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/reflection.py", line 88, in cache
    return fn(self, con, *args, **kw)
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/dialects/sqlite/base.py", line 2150, in has_table
    info = self._get_table_pragma(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/dialects/sqlite/base.py", line 2771, in _get_table_pragma
    cursor = connection.exec_driver_sql(statement)
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1769, in exec_driver_sql
    ret = self._execute_context(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is not a database
[SQL: PRAGMA main.table_info("system")]
(Background on this error at: https://sqlalche.me/e/20/4xp6)
^CHandling keyboard interrupt...



^CStop doing that! I heard you the first time!
```
---

**The system service logs right after executing the bazarr-update task through the UI:**
```
Aug 01 07:54:45 indexers bazarr[105277]: 2024-08-01 07:54:45,961 - root                             (7fc27482b000) :  INFO (server:79) - BAZARR is started and waiting for request on http://0.0.0.0:6767
Aug 01 07:55:20 indexers bazarr[105277]: Closing database...
Aug 01 07:55:20 indexers bazarr[105277]: Closing webserver...
Aug 01 07:55:20 indexers bazarr[105277]: 2024-08-01 07:55:20,789 - root                             (7fc1b9fbb640) :  INFO (central:56) - Bazarr is being restarted...
Aug 01 07:55:27 indexers bazarr[105277]: 2024-08-01 07:55:27,034 - app.app                          (7fc1d8ff9640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:32 indexers bazarr[105444]: Traceback (most recent call last):
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
Aug 01 07:55:32 indexers bazarr[105444]:     self.dialect.do_execute(
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
Aug 01 07:55:32 indexers bazarr[105444]:     cursor.execute(statement, parameters)
Aug 01 07:55:32 indexers bazarr[105444]: sqlite3.DatabaseError: file is not a database
Aug 01 07:55:32 indexers bazarr[105444]: The above exception was the direct cause of the following exception:
Aug 01 07:55:32 indexers bazarr[105444]: Traceback (most recent call last):
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/main.py", line 22, in <module>
Aug 01 07:55:32 indexers bazarr[105444]:     from init import *  # noqa E402
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/init.py", line 219, in <module>
Aug 01 07:55:32 indexers bazarr[105444]:     init_db()
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/app/database.py", line 302, in init_db
Aug 01 07:55:32 indexers bazarr[105444]:     metadata.create_all(engine)
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/schema.py", line 5825, in create_all
Aug 01 07:55:32 indexers bazarr[105444]:     bind._run_ddl_visitor(
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 3233, in _run_ddl_visitor
Aug 01 07:55:32 indexers bazarr[105444]:     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2439, in _run_ddl_visitor
Aug 01 07:55:32 indexers bazarr[105444]:     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/visitors.py", line 664, in traverse_single
Aug 01 07:55:32 indexers bazarr[105444]:     return meth(obj, **kw)
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/ddl.py", line 897, in visit_metadata
Aug 01 07:55:32 indexers bazarr[105444]:     [t for t in tables if self._can_create_table(t)]
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/ddl.py", line 897, in <listcomp>
Aug 01 07:55:32 indexers bazarr[105444]:     [t for t in tables if self._can_create_table(t)]
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/ddl.py", line 862, in _can_create_table
Aug 01 07:55:32 indexers bazarr[105444]:     return not self.checkfirst or not self.dialect.has_table(
Aug 01 07:55:32 indexers bazarr[105444]:   File "<string>", line 2, in has_table
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/reflection.py", line 88, in cache
Aug 01 07:55:32 indexers bazarr[105444]:     return fn(self, con, *args, **kw)
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/dialects/sqlite/base.py", line 2150, in has_table
Aug 01 07:55:32 indexers bazarr[105444]:     info = self._get_table_pragma(
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/dialects/sqlite/base.py", line 2771, in _get_table_pragma
Aug 01 07:55:32 indexers bazarr[105444]:     cursor = connection.exec_driver_sql(statement)
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1769, in exec_driver_sql
Aug 01 07:55:32 indexers bazarr[105444]:     ret = self._execute_context(
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1839, in _execute_context
Aug 01 07:55:32 indexers bazarr[105444]:     return self._exec_single_context(
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
Aug 01 07:55:32 indexers bazarr[105444]:     self._handle_dbapi_exception(
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
Aug 01 07:55:32 indexers bazarr[105444]:     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
Aug 01 07:55:32 indexers bazarr[105444]:     self.dialect.do_execute(
Aug 01 07:55:32 indexers bazarr[105444]:   File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
Aug 01 07:55:32 indexers bazarr[105444]:     cursor.execute(statement, parameters)
Aug 01 07:55:32 indexers bazarr[105444]: sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is not a database
Aug 01 07:55:32 indexers bazarr[105444]: [SQL: PRAGMA main.table_info("system")]
Aug 01 07:55:32 indexers bazarr[105444]: (Background on this error at: https://sqlalche.me/e/20/4xp6)
Aug 01 07:55:33 indexers bazarr[105277]: 2024-08-01 07:55:33,647 - app.app                          (7fc1d6ff5640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:33 indexers bazarr[105277]: 2024-08-01 07:55:33,647 - app.app                          (7fc1d67f4640) :  ERROR (app:828) - Exception on /api/system/settings [GET]
Aug 01 07:55:35 indexers bazarr[105277]: 2024-08-01 07:55:35,336 - app.app                          (7fc1d27ec640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:35 indexers bazarr[105277]: 2024-08-01 07:55:35,336 - app.app                          (7fc1d2fed640) :  ERROR (app:828) - Exception on /api/system/settings [GET]
Aug 01 07:55:36 indexers bazarr[105277]: 2024-08-01 07:55:36,502 - app.app                          (7fc1d07e8640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:36 indexers bazarr[105277]: 2024-08-01 07:55:36,502 - app.app                          (7fc1cf7e6640) :  ERROR (app:828) - Exception on /api/system/settings [GET]
Aug 01 07:55:38 indexers bazarr[105277]: 2024-08-01 07:55:38,720 - app.app                          (7fc1ccfe1640) :  ERROR (app:828) - Exception on /api/system/settings [GET]
Aug 01 07:55:38 indexers bazarr[105277]: 2024-08-01 07:55:38,720 - app.app                          (7fc1cbfdf640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:44 indexers bazarr[105277]: 2024-08-01 07:55:44,564 - app.app                          (7fc1cb7de640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:48 indexers bazarr[105277]: 2024-08-01 07:55:48,758 - app.app                          (7fc1c87d8640) :  ERROR (app:828) - Exception on /api/system/settings [GET]
Aug 01 07:55:48 indexers bazarr[105277]: 2024-08-01 07:55:48,759 - app.app                          (7fc1c7fd7640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:50 indexers bazarr[105277]: 2024-08-01 07:55:50,519 - app.app                          (7fc1c47d0640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:50 indexers bazarr[105277]: 2024-08-01 07:55:50,520 - app.app                          (7fc1c3fcf640) :  ERROR (app:828) - Exception on /api/system/settings [GET]
Aug 01 07:55:51 indexers bazarr[105277]: 2024-08-01 07:55:51,624 - app.app                          (7fc1c1fcb640) :  ERROR (app:828) - Exception on /api/badges [GET]
Aug 01 07:55:51 indexers bazarr[105277]: 2024-08-01 07:55:51,626 - app.app                          (7fc1c0fc9640) :  ERROR (app:828) - Exception on /api/system/settings [GET]
Aug 01 07:55:52 indexers cloudflared[124]: 2024-08-01T07:55:52Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 127.0.0.1:6767: connect: con>
Aug 01 07:56:09 indexers cloudflared[124]: 2024-08-01T07:56:09Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared
Aug 01 07:56:10 indexers bazarr[105277]: 2024-08-01 07:56:10,077 - app.app                          (7fc1e27fc640) :  ERROR (app:828) - Exception on /api/system/settings [GET]
```

**Comment by anderson-oki** [comment]
@rafaello104 GitHub issues are for bug reports. The error you are experiencing is the `sqlite3.DatabaseError: file is not a database`. Most likely the database file is failing to be saved on the bazarr data folder in due to permission or other reasons in due to your system configuration. You can come to Discord for more troubleshooting or assistance.
