### ISSUE TITLE
When the sync task for sonarr runs it is throwing an exception and I end up with no episodes synced.

### ISSUE THREAD

**Issue by juanriccio** [morpheus65535/bazarr#2643]
When the sync task for Sonarr runs, it throws an exception and I end up with no episodes synced.
The same happens with Radarr, but in this report I am only mentioning Sonarr hoping it is a similar problem.
I have zero series and zero movies showing up in Bazarr. They do show up in Sonarr and Radarr respectovely.

**To Reproduce**
I do nothing special, the sync between Bazarr and Sonarr is automated periodically by default

**Expected behavior**
Bazarr tries to download the appropriate subtitles

**Software (please complete the following information):**
 - Bazarr: v1.4.3
 - Sonarr v4.0.9.2244
 - OS: Windows 10. Bazarr running as a service, with path mappings hopefully set up right (network disk on Sonarr side, UNC path on Bazarr side)

**Additional context**
Here's what Bazarr has to say about the exception:
Job "Sync with Radarr (trigger: interval[1:00:00], next run at: 2024-08-29 23:18:24 CEST)" raised an exception	2024-08-29 22:18:24

Traceback (most recent call last):
  File "c:\\bazarr\\bazarr\\../libs\\requests\\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\\Bazarr\\WinPython\\python-3.10.0\\lib\\json\\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\\Bazarr\\WinPython\\python-3.10.0\\lib\\json\\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\\Bazarr\\WinPython\\python-3.10.0\\lib\\json\\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\\bazarr\\bazarr\\radarr\\sync\\movies.py", line 86, in update_movies
    check_radarr_rootfolder()
  File "c:\\bazarr\\bazarr\\radarr\\rootfolder.py", line 64, in check_radarr_rootfolder
    get_radarr_rootfolder()
  File "c:\\bazarr\\bazarr\\radarr\\rootfolder.py", line 33, in get_radarr_rootfolder
    for folder in rootfolder.json():
  File "c:\\bazarr\\bazarr\\../libs\\requests\\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JaiZed** [comment]
Given that Bazarr says you have 0 series, this is not an issue with the Bazarr software, but with your configuration and setup.
If you want assistance, please ask in the Discord support channel.
