### ISSUE TITLE
Cannot connect to PostgreSQL through unix socket

### ISSUE THREAD

**Issue by ostrolucky** [morpheus65535/bazarr#2651]
**Describe the bug**
It seems it's not possible to configure bazarr to use local unix postgresql socket, even though SQLAlchemy supports that

**To Reproduce**
1. Set up local postgresql instance that listens on socket
2. Set up bazarr user on this postgresql who can access bazarr database
3. Configure bazarr's config.yaml like so
```yaml
posgresql:
  database: bazarr
  enabled: true
  host: unix://var/run/posgresql
  password: ''
  port: 5432
  username: ''
```

**Expected behavior**
Bazarr boots up

**Screenshots**
```
sep 07 00:54:32 Haswell systemd[1]: Started bazarr.
sep 07 00:54:39 Haswell bazarr[2792959]: /nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../custom_libs/subzero/language.py:165: SyntaxWarning: invalid escape sequence '\.'
sep 07 00:54:39 Haswell bazarr[2792959]:   IETF_MATCH = ".+\.([^-.]+)(?:-[A-Za-z]+)?$"
sep 07 00:54:39 Haswell bazarr[2792959]: /nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../custom_libs/subzero/language.py:166: SyntaxWarning: invalid escape sequence '\.'
sep 07 00:54:39 Haswell bazarr[2792959]:   ENDSWITH_LANGUAGECODE_RE = re.compile("\.([^-.]{2,3})(?:-[A-Za-z]{2,})?$")
sep 07 00:54:39 Haswell bazarr[2792959]: /nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../custom_libs/subzero/language.py:170: SyntaxWarning: invalid escape sequence '\.'
sep 07 00:54:39 Haswell bazarr[2792959]:   language_match = re.match(".+\.([^\.]+)$" if not ietf
sep 07 00:54:41 Haswell bazarr[2792959]: Traceback (most recent call last):
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 145, in __init__
sep 07 00:54:41 Haswell bazarr[2792959]:     self._dbapi_connection = engine.raw_connection()
sep 07 00:54:41 Haswell bazarr[2792959]:                              ^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 3282, in raw_connection
sep 07 00:54:41 Haswell bazarr[2792959]:     return self.pool.connect()
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 449, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     return _ConnectionFairy._checkout(self)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 1263, in _checkout
sep 07 00:54:41 Haswell bazarr[2792959]:     fairy = _ConnectionRecord.checkout(pool)
sep 07 00:54:41 Haswell bazarr[2792959]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 712, in checkout
sep 07 00:54:41 Haswell bazarr[2792959]:     rec = pool._do_get()
sep 07 00:54:41 Haswell bazarr[2792959]:           ^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/impl.py", line 282, in _do_get
sep 07 00:54:41 Haswell bazarr[2792959]:     return self._create_connection()
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 390, in _create_connection
sep 07 00:54:41 Haswell bazarr[2792959]:     return _ConnectionRecord(self)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 674, in __init__
sep 07 00:54:41 Haswell bazarr[2792959]:     self.__connect()
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 900, in __connect
sep 07 00:54:41 Haswell bazarr[2792959]:     with util.safe_reraise():
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/util/langhelpers.py", line 146, in __exit__
sep 07 00:54:41 Haswell bazarr[2792959]:     raise exc_value.with_traceback(exc_tb)
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 896, in __connect
sep 07 00:54:41 Haswell bazarr[2792959]:     self.dbapi_connection = connection = pool._invoke_creator(self)
sep 07 00:54:41 Haswell bazarr[2792959]:                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/create.py", line 643, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     return dialect.connect(*cargs, **cparams)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 616, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     return self.loaded_dbapi.connect(*cargs, **cparams)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/820d69np275qs2bl43nri4z8kr8mfvnv-python3-3.12.5-env/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]: psycopg2.OperationalError: could not translate host name "unix://var/run/postgresql" to address: Name or service not known
sep 07 00:54:41 Haswell bazarr[2792959]: The above exception was the direct cause of the following exception:
sep 07 00:54:41 Haswell bazarr[2792959]: Traceback (most recent call last):
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/main.py", line 22, in <module>
sep 07 00:54:41 Haswell bazarr[2792959]:     from init import *  # noqa E402
sep 07 00:54:41 Haswell bazarr[2792959]:     ^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/init.py", line 219, in <module>
sep 07 00:54:41 Haswell bazarr[2792959]:     init_db()
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/app/database.py", line 302, in init_db
sep 07 00:54:41 Haswell bazarr[2792959]:     metadata.create_all(engine)
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/sql/schema.py", line 5825, in create_all
sep 07 00:54:41 Haswell bazarr[2792959]:     bind._run_ddl_visitor(
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 3232, in _run_ddl_visitor
sep 07 00:54:41 Haswell bazarr[2792959]:     with self.begin() as conn:
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/pgb120fb7srbh418v4i2a70aq1w9dawd-python3-3.12.5/lib/python3.12/contextlib.py", line 137, in __enter__
sep 07 00:54:41 Haswell bazarr[2792959]:     return next(self.gen)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 3222, in begin
sep 07 00:54:41 Haswell bazarr[2792959]:     with self.connect() as conn:
sep 07 00:54:41 Haswell bazarr[2792959]:          ^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 3258, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     return self._connection_cls(self)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 147, in __init__
sep 07 00:54:41 Haswell bazarr[2792959]:     Connection._handle_dbapi_exception_noconnection(
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2422, in _handle_dbapi_exception_noconnection
sep 07 00:54:41 Haswell bazarr[2792959]:     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 145, in __init__
sep 07 00:54:41 Haswell bazarr[2792959]:     self._dbapi_connection = engine.raw_connection()
sep 07 00:54:41 Haswell bazarr[2792959]:                              ^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 3282, in raw_connection
sep 07 00:54:41 Haswell bazarr[2792959]:     return self.pool.connect()
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 449, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     return _ConnectionFairy._checkout(self)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 1263, in _checkout
sep 07 00:54:41 Haswell bazarr[2792959]:     fairy = _ConnectionRecord.checkout(pool)
sep 07 00:54:41 Haswell bazarr[2792959]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 712, in checkout
sep 07 00:54:41 Haswell bazarr[2792959]:     rec = pool._do_get()
sep 07 00:54:41 Haswell bazarr[2792959]:           ^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/impl.py", line 282, in _do_get
sep 07 00:54:41 Haswell bazarr[2792959]:     return self._create_connection()
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 390, in _create_connection
sep 07 00:54:41 Haswell bazarr[2792959]:     return _ConnectionRecord(self)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 674, in __init__
sep 07 00:54:41 Haswell bazarr[2792959]:     self.__connect()
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 900, in __connect
sep 07 00:54:41 Haswell bazarr[2792959]:     with util.safe_reraise():
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/util/langhelpers.py", line 146, in __exit__
sep 07 00:54:41 Haswell bazarr[2792959]:     raise exc_value.with_traceback(exc_tb)
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/pool/base.py", line 896, in __connect
sep 07 00:54:41 Haswell bazarr[2792959]:     self.dbapi_connection = connection = pool._invoke_creator(self)
sep 07 00:54:41 Haswell bazarr[2792959]:                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/create.py", line 643, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     return dialect.connect(*cargs, **cparams)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/r2bqvn6kry1zvyv4j314qnf1pp8wdpaf-bazarr-1.4.3/share/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 616, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     return self.loaded_dbapi.connect(*cargs, **cparams)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]:   File "/nix/store/820d69np275qs2bl43nri4z8kr8mfvnv-python3-3.12.5-env/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
sep 07 00:54:41 Haswell bazarr[2792959]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sep 07 00:54:41 Haswell bazarr[2792959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 07 00:54:41 Haswell bazarr[2792959]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "unix://var/run/postgresql" to address: Name or service not known
sep 07 00:54:41 Haswell bazarr[2792959]: (Background on this error at: https://sqlalche.me/e/20/e3q8)
sep 07 00:57:57 Haswell systemd[1]: Stopping bazarr...
sep 07 00:57:57 Haswell systemd[1]: bazarr.service: Deactivated successfully.
sep 07 00:57:57 Haswell systemd[1]: Stopped bazarr.
sep 07 00:57:57 Haswell systemd[1]: bazarr.service: Consumed 8.497s CPU time, 150.9M memory peak, 8.5K incoming IP traffic, 
```

**Software (please complete the following information):**
 - Bazarr:  1.4.4-beta.42
 - Radarr version 5.9.1.9070
 - Sonarr version 4.0.9.2244
 - OS: NixOS

**Additional context**
According https://stackoverflow.com/questions/54967660/connect-to-a-database-over-a-unix-socket-using-sqlalchemy, key here is query parameter `host`, which I don't think bazarr allows to configure

**Comment by morpheus65535** [comment]
Bazarr doesn't support unix socket by design. It would require code refactoring to support this edge use case that has never been raised before. You have to use TCP/IP connection. 

You can open a feature request and we'll see how it's upvoted for a potential futur implementation. https://bazarr.featureupvote.com/

**Comment by Allram** [comment]
Unix socket works fine on Bazarr, here is my config:

`postgresql:
  database: bazarr
  enabled: true
  host: /var/run/postgresql
  password: xXXXxxxXXXx
  port: 5432
  username: bazarr`
