### ISSUE TITLE
Series do not update with new seasons

### ISSUE THREAD

**Issue by rzippert** [morpheus65535/bazarr#2666]
**Describe the bug**
A series is updated on sonarr with a new season, but the new episodes are not present in Bazarr, so it doesn't try to download the subtitles.

**To Reproduce**
1. Synchronize from Sonarr
2. Wait a new season from a series
3. Check the episodes list
4. Find no new episodes

**Expected behavior**
As series get new episodes these should also be listed on Bazarr, so that it is aware that subtitles may be missing.

**Screenshots**
![image](https://github.com/user-attachments/assets/68781a5d-2529-4759-b32e-52229fdd292e)
![image](https://github.com/user-attachments/assets/1b976791-3015-4fc4-a742-52dbf5f7eb24)

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Sonarr: 4.0.9.2244
 - OS: Docker (Linux) from linuxserver.io

**Additional context**
I feel like it should solve itself if I'm able to "remove" the series and resync it from Sonarr, but I'm not sure if this is doable. Is there any relevant logs I should attach?

**Comment by morpheus65535** [comment]
What if you force a sync with Sonarr in System-->Tasks? If it doesn't work, can you provide a debug log while retrying the sync?

**Comment by rzippert** [comment]
Sure thing... I actually didn't notice the sync was failing as I couldn't identify any feedback on the interface.

The logs are below:

2024-09-21 18:31:45|INFO    |root                            |BAZARR Log file emptied|
2024-09-21 18:31:49|INFO    |engineio.server                 |P_6PzlHU_sMje3eoAAAC: Sending packet PING data None|
2024-09-21 18:31:49|INFO    |engineio.server                 |P_6PzlHU_sMje3eoAAAC: Received packet PONG data |
2024-09-21 18:31:51|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
2024-09-21 18:31:51|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-09-21 18:31:51|INFO    |engineio.server                 |P_6PzlHU_sMje3eoAAAC: Sending packet MESSAGE data 2["data",{"type":"task","action":"update","payload":null}]|
2024-09-21 18:31:51|INFO    |apscheduler.executors.default   |Running job "Sync with Sonarr (trigger: interval[1:00:00], next run at: 2024-09-21 19:31:51 -03)" (scheduled at 2024-09-21 18:31:51.637097-03:00)|
2024-09-21 18:31:51|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2024-09-21 18:37:21.281744-03:00 (in 329.639737 seconds)|
2024-09-21 18:31:51|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:8989|
2024-09-21 18:31:51|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:8989 "GET /api/v3/rootfolder?apikey=(removed) HTTP/1.1" 401 0|
2024-09-21 18:31:51|ERROR   |apscheduler.executors.default   |Job "Sync with Sonarr (trigger: interval[1:00:00], next run at: 2024-09-21 19:31:51 -03)" raised an exception|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 971, in json    return complexjson.loads(self.text, **kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads    return _default_decoder.decode(s)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bazarr/bin/bazarr/sonarr/sync/series.py", line 43, in update_series    check_sonarr_rootfolder()  File "/app/bazarr/bin/bazarr/sonarr/rootfolder.py", line 64, in check_sonarr_rootfolder    get_sonarr_rootfolder()  File "/app/bazarr/bin/bazarr/sonarr/rootfolder.py", line 33, in get_sonarr_rootfolder    for folder in rootfolder.json():                  ^^^^^^^^^^^^^^^^^  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 975, in json    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)|
2024-09-21 18:31:51|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-09-21 18:31:51|INFO    |engineio.server                 |P_6PzlHU_sMje3eoAAAC: Sending packet MESSAGE data 2["data",{"type":"task","action":"update","payload":null}]|
2024-09-21 18:32:14|INFO    |engineio.server                 |P_6PzlHU_sMje3eoAAAC: Sending packet PING data None|
2024-09-21 18:32:14|INFO    |engineio.server                 |P_6PzlHU_sMje3eoAAAC: Received packet PONG data |

**Comment by rzippert** [comment]
It seems my sonarr API was updated and I didn't notice it. Just fixed this and it is now synchronizing correctly.

I'm wondering now if I missed some notification that this was happening. Should it be on the Status tab?

I appreciate your attention!
