### ISSUE TITLE
Can't upload subtitles

### ISSUE THREAD

**Issue by Ph1L82** [morpheus65535/bazarr#2692]
**Describe the bug**
When trying to upload subtitles it opens the browser files, and allows to select multiple files as always, but uppon clicking OK just returns a blank page. Doesn't upload any subtitles. It happens on all shows and movies. After upgrading to the latest version 1.4.4

**To Reproduce**
1. Go to any tv show or movie
2. Click on upload
3. Select the subtitles to uploadn and click Open
4. Inspecto the empty page.. 
5. See error

the errors:

`13core-Su47KUfs.js:44 Error: [@mantine/core] Duplicate options are not supported. Option with value "ea" was provided more than once
    at Ic (core-Su47KUfs.js:44:144901)
    at Xo (core-Su47KUfs.js:44:146074)
    at Uc (vendors-BAK-HwJ-.js:38:17000)
    at Zm (vendors-BAK-HwJ-.js:40:43963)
    at Ym (vendors-BAK-HwJ-.js:40:39727)
    at W0 (vendors-BAK-HwJ-.js:40:39655)
    at vl (vendors-BAK-HwJ-.js:40:39508)
    at Pu (vendors-BAK-HwJ-.js:40:35875)
    at Ud (vendors-BAK-HwJ-.js:40:36678)
    at Zn (vendors-BAK-HwJ-.js:38:3274)
console.error @ core-Su47KUfs.js:44Understand this error
vendors-BAK-HwJ-.js:38 Uncaught Error: [@mantine/core] Duplicate options are not supported. Option with value "ea" was provided more than once
    at Ic (core-Su47KUfs.js:44:144901)
    at Xo (core-Su47KUfs.js:44:146074)
    at Uc (vendors-BAK-HwJ-.js:38:17000)
    at Zm (vendors-BAK-HwJ-.js:40:43963)
    at Ym (vendors-BAK-HwJ-.js:40:39727)
    at W0 (vendors-BAK-HwJ-.js:40:39655)
    at vl (vendors-BAK-HwJ-.js:40:39508)
    at Pu (vendors-BAK-HwJ-.js:40:35875)
    at Ud (vendors-BAK-HwJ-.js:40:36678)
    at Zn (vendors-BAK-HwJ-.js:38:3274)Understand this error
`
It happens for multiple or single subtitle upload. On every case.

**Expected behavior**
Should show a form to specify language and episode for which the uploaded subtitle is

**Software (please complete the following information):**
 - Bazarr: 1.4.4
 - Radarr version 5.8.3.8933
 - Sonarr version 4.0.8.1874
 - OS: Linux-6.8.12-1-pve-x86_64-with-glibc2.36
 - Python Version 3.11.2

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 1.4.5. Let us know if it's not.
