### ISSUE TITLE
Could not get it running on OSX

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#27]
After following instructions, I get following errors:

```
ERROR:stevedore.extension:Could not load 'legendastv': No module named xmlrpc_client
ERROR:stevedore.extension:Could not load 'shooter': No module named xmlrpc_client
ERROR:stevedore.extension:Could not load 'podnapisi': No module named xmlrpc_client
ERROR:stevedore.extension:Could not load 'tvsubtitles': No module named xmlrpc_client
ERROR:stevedore.extension:Could not load 'opensubtitles': No module named xmlrpc_client
ERROR:stevedore.extension:Could not load 'addic7ed': No module named xmlrpc_client
ERROR:stevedore.extension:Could not load 'subscenter': No module named xmlrpc_client
ERROR:stevedore.extension:Could not load 'thesubdb': No module named xmlrpc_client
Traceback (most recent call last):
  File "bazarr.py", line 34, in <module>
    from get_providers import *
  File "/Users/USER/bazarr/bazarr/get_providers.py", line 3, in <module>
    from subliminal import *
  File "/Library/Python/2.7/site-packages/subliminal/__init__.py", line 16, in <module>
    from .providers import Provider
  File "/Library/Python/2.7/site-packages/subliminal/providers/__init__.py", line 5, in <module>
    from six.moves.xmlrpc_client import SafeTransport
ImportError: No module named xmlrpc_client

```

**Comment by stefandevo** [comment]
Ok, I had to do following:

```
wget https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
tar -zxvf six-1.10.0.tar.gz
cd ./six-1.10.0
sudo python ./setup.py install
```
to get the xmlrpc_client installed.

**Comment by morpheus65535** [comment]
You're probably using the built-in python in Mac OS X which miss standard modules. You could have use this:

    pip install -U six
