### ISSUE TITLE
Receiving an "Error: 500 Internal Server Error"

### ISSUE THREAD

**Issue by angrycuban13** [morpheus65535/bazarr#271]
**Describe the bug**

Internal Server Error
ValueError(u'invalid interpolation syntax in u"`[3aI!?o+&\'RG`L}>b|%" at position 19',)

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Subliminal'
3. Scroll down to 'Subtitle Providers'
4. Fill in the information
4. See error:

"Traceback (most recent call last):
  File "c:\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "c:\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "c:\bazarr\bazarr\main.py", line 141, in wrapper
    return func(*a, **ka)
  File "c:\bazarr\bazarr\main.py", line 1226, in save_settings
    settings.opensubtitles.password = request.forms.get('settings_opensubtitles_password')
  File "c:\bazarr\bazarr\../libs/simpleconfigparser\__init__.py", line 66, in __setattr__
    return self.parser.set(self.section, name, value)
  File "c:\bazarr\bazarr\../libs/simpleconfigparser\__init__.py", line 122, in set
    return configparser.set(self, section, option, value)
  File "c:\bazarr\bazarr\../libs/backports\configparser2\__init__.py", line 1237, in set
    super(ConfigParser, self).set(section, option, value)
  File "c:\bazarr\bazarr\../libs/backports\configparser2\__init__.py", line 916, in set
    value)
  File "c:\bazarr\bazarr\../libs/backports\configparser2\__init__.py", line 392, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in u"`[3aI!?o+&'RG`L}>b|%" at position 19"

**Expected behavior**
I expected to not get an error.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.7.0
 - Radarr version 0.2.0.1217
 - Sonarr version 2.0.0.5298
 - OS: Windows Server 2016

**Additional context**
I'm using NGINX reverse proxy but I can replicate this error using the local address as well.

I've restarted Bazarr using NSSM but no dice.

**Comment by angrycuban13** [comment]
At first, I thought it was because I was copying/pasting the password into the field, but I typed it manually and the same error occurred.

**Comment by halali** [comment]
possible fixed in last commit in development branch

**Comment by angrycuban13** [comment]
It looks like having "%" on the password was creating certain errors.

Changed password and didn't include that special character and we are back in business.
