### ISSUE TITLE
Cannot install - sqlite3.OperationalError: no such column: table_history.upgradedFromId

### ISSUE THREAD

**Issue by donaldallen** [morpheus65535/bazarr#2715]
Installing on Unraid using linuxserver/bazarr.

```
docker run
  -d
  --name='bazarr'
  --net='dallen33'
  --pids-limit 2048
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="bazarr"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:6767]/system/status'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr-logo.png'
  -p '6767:6767/tcp'
  -v '/mnt/user/data/media/movies/':'/movies':'rw'
  -v '/mnt/user/data/media/tv/':'/tv':'rw'
  -v '/mnt/user/appdata/bazarr':'/config':'rw' 'lscr.io/linuxserver/bazarr'
5b412800ca665791227ef0112c50069acf20bb24cbc4dfb1853660071cebd293
```

Cannot launch the UI, logs show:

```
2024-10-11 20:24:02,075 - apscheduler.scheduler            (15063a323b28) :  INFO (base:454) - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-11 20:24:02,077 - apscheduler.scheduler            (15063a323b28) :  INFO (base:454) - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-11 20:24:02,078 - apscheduler.scheduler            (15063a323b28) :  INFO (base:454) - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-11 20:24:02,078 - apscheduler.scheduler            (15063a323b28) :  INFO (base:454) - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-11 20:24:02,079 - apscheduler.scheduler            (15063a323b28) :  INFO (base:454) - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-11 20:24:02,080 - apscheduler.scheduler            (15063a323b28) :  INFO (base:454) - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-11 20:24:02,081 - apscheduler.scheduler            (15063a323b28) :  INFO (base:454) - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-11 20:24:02,081 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Cache Maintenance" to job store "default"
2024-10-11 20:24:02,082 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Check Health" to job store "default"
2024-10-11 20:24:02,082 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Sync with Sonarr" to job store "default"
2024-10-11 20:24:02,082 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Index All Episode Subtitles from Disk" to job store "default"
2024-10-11 20:24:02,082 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Update Release Info" to job store "default"
2024-10-11 20:24:02,082 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Update Announcements File" to job store "default"
2024-10-11 20:24:02,082 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Search for Missing Series Subtitles" to job store "default"
2024-10-11 20:24:02,083 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Upgrade Previously Downloaded Subtitles" to job store "default"
2024-10-11 20:24:02,083 - apscheduler.scheduler            (15063a323b28) :  INFO (base:895) - Added job "Backup Database and Configuration File" to job store "default"
2024-10-11 20:24:02,083 - apscheduler.scheduler            (15063a323b28) :  INFO (base:181) - Scheduler started
2024-10-11 20:24:02,083 - apscheduler.scheduler            (150618a9eb30) :  DEBUG (base:954) - Looking for jobs to run
2024-10-11 20:24:02,083 - apscheduler.scheduler            (150618a9eb30) :  DEBUG (base:1034) - Next wakeup is due at 2024-10-11 21:13:14.080919-07:00 (in 2951.996935 seconds)
2024-10-11 20:24:02,637 - engineio.server                  (15063a323b28) :  INFO (base_server:99) - Server initialized for threading.
2024-10-11 20:24:02,762 - root                             (15063a323b28) :  DEBUG (database:316) - Upgrading database schema
2024-10-11 20:24:02,821 - alembic.runtime.migration        (15063a323b28) :  INFO (migration:216) - Context impl SQLiteImpl.
2024-10-11 20:24:02,822 - alembic.runtime.migration        (15063a323b28) :  INFO (migration:219) - Will assume non-transactional DDL.
2024-10-11 20:24:02,847 - alembic.runtime.migration        (15063a323b28) :  INFO (migration:622) - Running upgrade 95cd4cf40d7a -> 195144da1f7e, empty message
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: table_history.upgradedFromId

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 52, in <module>
    migrate_db(app)
  File "/app/bazarr/bin/bazarr/app/database.py", line 327, in migrate_db
    flask_migrate.upgrade(directory=migrations_directory)
  File "/app/bazarr/bin/bazarr/../libs/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/app/bazarr/bin/bazarr/../libs/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/app/bazarr/bin/bazarr/../libs/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/app/bazarr/bin/bazarr/../libs/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/bazarr/bin/migrations/env.py", line 117, in <module>
    run_migrations_online()
  File "/app/bazarr/bin/migrations/env.py", line 106, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/app/bazarr/bin/bazarr/../libs/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/app/bazarr/bin/bazarr/../libs/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/app/bazarr/bin/migrations/versions/195144da1f7e_.py", line 49, in upgrade
    } for x in bind.execute(select(TableHistory)).all()]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
           ^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: table_history.upgradedFromId
[SQL: SELECT table_history.id, table_history.action, table_history.description, table_history.language, table_history.provider, table_history.score, table_history."sonarrEpisodeId", table_history."sonarrSeriesId", table_history.subs_id, table_history.subtitles_path, table_history.timestamp, table_history.video_path, table_history.matched, table_history.not_matched, table_history."upgradedFromId" 
FROM table_history]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by morpheus65535** [comment]
Stop Bazarr, empty config/db directory from malformed database and start Bazarr. Let it run for a couple of minutes before attempting anything else. If you still have configuration issues, come to our Discord support server.
