### ISSUE TITLE
"OSError: [Errno 97] Address family not supported by protocol" error when IPv6 disabled

### ISSUE THREAD

**Issue by robertg042** [morpheus65535/bazarr#2738]
**Describe the bug**
Web server fails to start when IPv6 is disabled. Versions 1.4.4. and 1.4.5. are affected. Changing `general -> ip` setting in `/config/config.yaml` from `'*'` to `'0.0.0.0'` fixes the issue. Here's related change: https://github.com/morpheus65535/bazarr/commit/4e365c6aa6f7e0786d8ceefdaa91099da59431f1#diff-54d19e4e848a5b9c5be8a33c4d9e57b87e1f35e513ed810f87dc418ef37303a5R78

**To Reproduce**
1. Start docker container
2. Observe that web service is not accessible
3. Check log and find "OSError: [Errno 97] Address family not supported by protocol" error there

**Expected behavior**
Web server starts correctly

**Screenshots**
```
[custom-init] No custom files found, skipping...
/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:165: SyntaxWarning: invalid escape sequence '\.'
  IETF_MATCH = ".+\.([^-.]+)(?:-[A-Za-z]+)?$"
/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:166: SyntaxWarning: invalid escape sequence '\.'
  ENDSWITH_LANGUAGECODE_RE = re.compile("\.([^-.]{2,3})(?:-[A-Za-z]{2,})?$")
/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:170: SyntaxWarning: invalid escape sequence '\.'
  language_match = re.match(".+\.([^\.]+)$" if not ietf
2024-10-27 05:24:09,746 - root                             (7d070d787b28) :  ERROR (server:68) - BAZARR cannot start because of unhandled exception.
Closing database...
Closing webserver...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server
    self.server = create_server(app,
                  ^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
                ^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 236, in __init__
    self.create_socket(self.family, self.socktype)
  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 351, in create_socket
    sock = socket.socket(family, type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 233, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 42, in <module>
    from app.server import webserver, app  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/server.py", line 103, in <module>
    webserver = Server()
                ^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/server.py", line 42, in __init__
    self.configure_server()
  File "/app/bazarr/bin/bazarr/app/server.py", line 69, in configure_server
    self.shutdown()
  File "/app/bazarr/bin/bazarr/app/server.py", line 95, in shutdown
    self.close_all()
  File "/app/bazarr/bin/bazarr/app/server.py", line 92, in close_all
    self.server.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
```

**Software (please complete the following information):**
 - Bazarr: 1.4.4 & 1.4.5
 - Radarr version 5.14.0.9383
 - Sonarr version 4.0.10.2544
 - OS: ubuntu 24.04

**Comment by robertg042** [comment]
I should maybe add that I've disabled IPv6 by adding `ipv6.disable=1` to `GRUB_CMDLINE_LINUX_DEFAULT` in `/etc/default/grub`

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
