### ISSUE TITLE
Chinese subtitle downloading issue for the provider "Assrt"

### ISSUE THREAD

**Issue by xuanguang** [morpheus65535/bazarr#2761]
**Describe the bug**
Lots of Chinese subtitles cannot be downloaded, but they exist in Assrt (_http://assrt.net_).

In my case, for example, the TV show "All Creatures Great & Small (2020)", S05E01, two subtitles can be found from the Assrt website, but none of them can be downloaded.
From the log I can see,
`BAZARR Skipping <AssrtSubtitle: 不知道 [<Language: alpha3=zho>]>, because it doesn't match our series/episode|`
but in fact, they are the right ones.
I tried the API (which was copied from the Bazarr log) from my web browser, and found the response as the figure below.
**It seems the wrong key work is used: the "_videoname_" is not the correct name key, while the "_native_name_" is.**
![image](https://github.com/user-attachments/assets/a1a24725-d425-420d-aab7-d000a7357945)

**Of course not only this TV show in Assrt, but lots of, I found that they have such similar issues.**

**To Reproduce**
1. Add "All Creatures Great & Small (2020)" into "Series"
2. Configure the downloading language as "Chinese".
3. Try to download (automatically or manually) the subtitle of S05E01, as the figure below. You can find that **no subtitle will be downloaded.**
![image](https://github.com/user-attachments/assets/9497ce09-3a4b-4026-91b8-a01d3e3ec21e)
4. But the right subtitles exist on the Assrt website (_http://assrt.net_), as shown below.
![image](https://github.com/user-attachments/assets/5d81e724-25ec-4312-bb3e-f6acaeee4270)

**Expected behavior**
The right subtitles are matched and downloaded correctly.

**Screenshots**
Screenshots are attached above.

**Software (please complete the following information):**
 - Bazarr: [1.4.5]
 - Radarr version [4.4.4.7068]
 - Sonarr version [4.0.10.2544]
 - OS: [Ubuntu 24.04, Linux-6.8.12-1-pve-x86_64-with-glibc2.39]

**Additional context**
From the Bazarr log, I saw the issue should come from the API response keyword, but not sure, please check and help, thanks!

**Comment by xuanguang** [comment]
Maybe there should be some **check logics** here.

I also found that sometimes the key "_videoname_" is configured correctly.
But **in Chinese, the meaning of the word "不知道" in my first example is "unknown**", which is the value of "_videoname_" in the example case. So for such cases, if the "_videoname_"  is "不知道"(which means "unknown"), or other meaningless value, we can try the "_native_name_" again.
Thanks.

**Comment by morpheus65535** [comment]
Sorry for the delay. What are those meaningless values you're referring to? I don't read Chinese so it's hard to tell. If you provide a list, I can try to add a check to try `native_name` if found in `videoname`.

**Comment by xuanguang** [comment]
Hi @morpheus65535, thanks for your replying.
Here, it responds the "videoname" as "不知道", which means "unknown".
So one value of the list should be "**不知道**".
But for other meaningless values, I haven't found any yet. So you can add this first, I will update more if I find in the future.
Thanks.

**Comment by morpheus65535** [comment]
Should be improved in upcoming beta. Let me know if it helps!

**Comment by xuanguang** [comment]
Thanks, @morpheus65535.
It is a pity that I cannot test it locally. When I tried to use the new versions (such as the _v1.5.2-beta.2, v1.5.2-beta.32_, etc.), it always tells me there is an issue, and the web browser always encountered the 500 error:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
And the log tells me that,
```log
2025-04-05 22:49:37|ERROR   |app.app                         |Exception on /wanted/series [GET]|'Traceback (most recent call last):\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1463, in wsgi_app\n    response = self.full_dispatch_request()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 872, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/flask_restx/api.py", line 672, in error_router\n    return original_handler(e)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/flask_cors/extension.py", line 176, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n                                                ^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request\n    rv = self.dispatch_request()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 855, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/app/ui.py", line 111, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 149, in render_template\n    template = app.jinja_env.get_or_select_template(template_name_or_list)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 1081, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 1010, in get_template\n    return self._load_template(name, globals)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/jinja2/environment.py", line 969, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/jinja2/loaders.py", line 125, in load\n    source, filename, uptodate = self.get_source(environment, name)\n                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 65, in get_source\n    return self._get_source_fast(environment, template)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/bazarr/bazarr/../libs/flask/templating.py", line 99, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
```
**I will test it when it can run successfully locally, maybe after the formal version is released.  :)**

**Comment by StevenSYT** [comment]
Hi @morpheus65535,

I’ve been debugging a similar issue with the Assrt provider where subtitles were being found but consistently rejected by Bazarr's matcher. I wanted to share my findings, which build on the discussion here.

The current discussion mentions preferring `native_name` over `videoname`. However, I found cases where `native_name` is actually *less* useful and a more robust strategy might be needed.

**Example (Show: "Dear X"):**
- `videoname`: `"亲爱的X Dear X S01E01 (2025) WEB..."` (Contains the English title)
- `native_name`: `"亲爱的X 친애하는 X (2025)"` (Missing the English title)

In this scenario, Bazarr/Guessit parses `videoname` and incorrectly extracts only the Chinese part (`"亲爱的X"`), which then fails to match against the series title `"Dear X"` in the database. Relying on `native_name` here would also fail as it doesn't contain the English title at all.

**Proposed Logic:**
In my local patch, I implemented a "Series Hint" strategy that has proven effective. Since the provider's `query` method knows the `video.series` name, we can check if that string exists (case-insensitively) in **either** `videoname` or `native_name`. If a match is found, we can then synthesize a "clean" release name (e.g., `Dear X S01E01`) to guarantee a high score from Bazarr's matcher.

This approach makes the provider significantly more resilient to the various mixed-language formats found on Assrt.

I hope these findings are helpful for finalizing the improvements! I could PR my patch if that helps clarify what I did. And I think we should reopen this issue as I don't think it is fixed.

**Comment by morpheus65535** [comment]
@StevenSYT please open a PR to dev branch and I'll review it. Thanks!
