### ISSUE TITLE
Error while searching for subtitles only happening for a few episodes.

### ISSUE THREAD

**Issue by svstoichkov** [morpheus65535/bazarr#2763]
**Describe the bug**
I have over 350 episodes and movies in my movie library. Bazarr fails to search for subtitles for 20 of them.

**To Reproduce**
1. Go to episode
2. Click on the subtitle language
3. Click on search
5. It searches for half a second and immediately shows there are no subtitles found.

**Expected behavior**
Subtitles should be found.

**Software (please complete the following information):**
 - Bazarr: v1.4.5
 - Sonarr version 4.0.10.2544
 - OS: Docker

**Additional context**

I ran `ffprobe -v quiet -print_format json -show_format -show_streams -sexagesimal "media/TV Shows/Dune - Prophecy/Season 1/Dune - Prophecy - S01E01 - The Hidden Hand WEBDL-2160p.mp4"` from within the docker container and it returns only an empty json {}

The same command works fine when I run it on my main Windows PC.

```
2024-11-18 11:28:19|DEBUG   |root                            |Bazarr version: 1.4.5|
2024-11-18 11:28:19|DEBUG   |root                            |Bazarr branch: master|
2024-11-18 11:28:19|DEBUG   |root                            |Operating system: Linux-6.1.0-17-amd64-x86_64-with|
2024-11-18 11:28:19|DEBUG   |root                            |Python version: 3.12.7|
2024-11-18 11:28:19|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-11-18 11:28:19|INFO    |engineio.server                 |Il40-lgIrI0zTQSmAAAE: Sending packet MESSAGE data 2["data",{"type":"settings","action":"update","payload":null}]|
2024-11-18 11:28:22|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): sonarr:8989|
2024-11-18 11:28:22|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): sonarr:8989|
2024-11-18 11:28:22|DEBUG   |urllib3.connectionpool          |http://sonarr:8989 "GET /api/v3/MediaCover/26/poster-500.jpg?apikey=(removed) HTTP/1.1" 200 28803|
2024-11-18 11:28:22|DEBUG   |urllib3.connectionpool          |http://sonarr:8989 "GET /api/v3/MediaCover/26/fanart.jpg?apikey=(removed) HTTP/1.1" 200 283786|
2024-11-18 11:28:24|DEBUG   |root                            |BAZARR updating pools: {'series_': SZAsyncProviderPool [4 providers (4 initialized; 0 discarded)], 'movie_': SZAsyncProviderPool [4 providers (4 initialized; 0 discarded)], 'series_1': SZAsyncProviderPool [4 providers (0 initialized; 0 discarded)], 'movie_1': SZAsyncProviderPool [4 providers (4 initialized; 0 discarded)]}|
2024-11-18 11:28:24|DEBUG   |root                            |BAZARR updating pool: series_1|
2024-11-18 11:28:24|DEBUG   |subliminal_patch.core           |Discarded providers: set() | New providers: {'subssabbz', 'subsunacs', 'opensubtitlescom', 'yavkanet'}|
2024-11-18 11:28:24|DEBUG   |subliminal_patch.core           |Updated discarded providers: set()|
2024-11-18 11:28:24|DEBUG   |subliminal_patch.core           |Removed providers: set()|
2024-11-18 11:28:24|DEBUG   |subliminal_patch.core           |No provider config updates|
2024-11-18 11:28:24|DEBUG   |root                            |BAZARR pools update elapsed time: 30.42ms|
2024-11-18 11:28:24|DEBUG   |root                            |BAZARR Searching subtitles for this file: /media/TV Shows/Dune - Prophecy/Season 1/Dune - Prophecy - S01E01 - The Hidden Hand WEBDL-2160p.mp4|
2024-11-18 11:28:24|DEBUG   |subliminal_patch.core           |No provider config updates|
2024-11-18 11:28:24|DEBUG   |subzero.video                   |Parsing video: Dune Prophecy S01E01 2160p MAX WEB DL DV HDR ENG LATINO DDP5 1 Atmos H265 MP4 BEN THE MEN.mp4, hints: {'title': 'Dune: Prophecy', 'type': 'episode'}|
2024-11-18 11:28:24|INFO    |subliminal_patch.core           |Determining basic video properties for 'Dune Prophecy S01E01 2160p MAX WEB DL DV HDR ENG LATINO DDP5 1 Atmos H265 MP4 BEN THE MEN.mp4' in '/media/TV Shows/Dune - Prophecy/Season 1'|
2024-11-18 11:28:24|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Dune",
    "season": 1,
    "episode_title": "Dune Prophecy",
    "episode": 1,
    "screen_size": "2160p",
    "source": "Web",
    "other": "Dolby Vision",
    "language": "English",
    "audio_codec": "Dolby Digital Plus",
    "audio_channels": "5.1",
    "video_codec": "H.265",
    "container": "mp4",
    "release_group": "BEN THE MEN",
    "mimetype": "video/mp4",
    "type": "episode"
}|
2024-11-18 11:28:24|DEBUG   |subliminal_patch.core           |Size is 10578986853|
2024-11-18 11:28:24|ERROR   |root                            |BAZARR Error ([Errno 22] Invalid argument: '/media/TV Shows/Dune - Prophecy/Season 1/Dune - Prophecy - S01E01 - The Hidden Hand WEBDL-2160p.mp4') trying to get video information for this file: /media/TV Shows/Dune - Prophecy/Season 1/Dune - Prophecy - S01E01 - The Hidden Hand WEBDL-2160p.mp4|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 41, in get_video    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 876, in scan_video    video.hashes['opensubtitlescom'] = osub_hash = osub_hash or hash_opensubtitles(hash_path)                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal/utils.py", line 20, in hash_opensubtitles    with open(video_path, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^^^OSError: [Errno 22] Invalid argument: '/media/TV Shows/Dune - Prophecy/Season 1/Dune - Prophecy - S01E01 - The Hidden Hand WEBDL-2160p.mp4'|
2024-11-18 11:28:24|DEBUG   |root                            |BAZARR Ended searching Subtitles for file: /media/TV Shows/Dune - Prophecy/Season 1/Dune - Prophecy - S01E01 - The Hidden Hand WEBDL-2160p.mp4|
2024-11-18 11:28:24|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-11-18 11:28:24|INFO    |engineio.server                 |Il40-lgIrI0zTQSmAAAE: Sending packet MESSAGE data 2["data",{"type":"episode","action":"update","payload":964}]|
2024-11-18 11:28:24|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-11-18 11:28:24|INFO    |engineio.server                 |Il40-lgIrI0zTQSmAAAE: Sending packet MESSAGE data 2["data",{"type":"message","action":"update","payload":"No BG subtitles found"}]|
```

**Comment by morpheus65535** [comment]
If ffprobe cannot get video properties, there's great chances that the file is corrupted. Bazarr has nothing to do with this. Next time you have a question, get by our Discord support channel. This is a bug reporting board.
