### ISSUE TITLE
Bug: Can't see episode history of a specific anime show (AttributeError)

### ISSUE THREAD

**Issue by boydaihungst** [morpheus65535/bazarr#2768]
**Describe the bug**
I can't see the episode history for a specific anime show, but the rest are unaffected. Please check the debug log below.

**To Reproduce**
1. Go to anime show 'Is It Wrong to Try to Pick Up Girls in a Dungeon?'
2. Click on any episode "history action button"
3. Server throws a 500 internal server error and the history is empty.

**Expected behavior**
The history dialog should be displayed.

**Screenshots**
![image](https://github.com/user-attachments/assets/c0e2cad5-2a1b-4773-962d-0286f5059db9)

**Software (please complete the following information):**
 - Bazarr: 1.4.6-beta.20
 - Radarr version: 5.15.1.9463
 - Sonarr version: 4.0.10.2544
 - OS:  Linux-6.8.0-48-generic-x86_64-with-glibc2.39
 - Python Version: 3.11.9
 
**Additional context**
This is debug log:
```

Nov 21 16:09:19 ubuntu-server bazarr[150026]: 2024-11-21 16:09:19,608 - app.app                          (76191b4006c0) :  ERROR (app:828) - Exception on /api/episodes/history [GET]
Nov 21 16:09:19 ubuntu-server bazarr[150026]: Traceback (most recent call last):
Nov 21 16:09:19 ubuntu-server bazarr[150026]:   File "/opt/bazarr/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request
Nov 21 16:09:19 ubuntu-server bazarr[150026]:     rv = self.dispatch_request()
Nov 21 16:09:19 ubuntu-server bazarr[150026]:          ^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 16:09:19 ubuntu-server bazarr[150026]:   File "/opt/bazarr/bazarr/../libs/flask/app.py", line 855, in dispatch_request
Nov 21 16:09:19 ubuntu-server bazarr[150026]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
Nov 21 16:09:19 ubuntu-server bazarr[150026]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 16:09:19 ubuntu-server bazarr[150026]:   File "/opt/bazarr/bazarr/../libs/flask_restx/api.py", line 402, in wrapper
Nov 21 16:09:19 ubuntu-server bazarr[150026]:     resp = resource(*args, **kwargs)
Nov 21 16:09:19 ubuntu-server bazarr[150026]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 16:09:19 ubuntu-server bazarr[150026]:   File "/opt/bazarr/bazarr/../libs/flask/views.py", line 110, in view
Nov 21 16:09:19 ubuntu-server bazarr[150026]:     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
Nov 21 16:09:19 ubuntu-server bazarr[150026]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 16:09:19 ubuntu-server bazarr[150026]:   File "/opt/bazarr/bazarr/../libs/flask_restx/resource.py", line 41, in dispatch_request
Nov 21 16:09:19 ubuntu-server bazarr[150026]:     resp = meth(*args, **kwargs)
Nov 21 16:09:19 ubuntu-server bazarr[150026]:            ^^^^^^^^^^^^^^^^^^^^^
Nov 21 16:09:19 ubuntu-server bazarr[150026]:   File "/opt/bazarr/bazarr/api/utils.py", line 30, in wrapper
Nov 21 16:09:19 ubuntu-server bazarr[150026]:     return actual_method(*args, **kwargs)
Nov 21 16:09:19 ubuntu-server bazarr[150026]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 16:09:19 ubuntu-server bazarr[150026]:   File "/opt/bazarr/bazarr/api/episodes/history.py", line 141, in get
Nov 21 16:09:19 ubuntu-server bazarr[150026]:     item.update({'original_id': upgradable_episodes_not_perfect.get(item['id'])})
Nov 21 16:09:19 ubuntu-server bazarr[150026]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 16:09:19 ubuntu-server bazarr[150026]: AttributeError: 'Subquery' object has no attribute 'get'

```

**Comment by boydaihungst** [comment]
Oh. Now there are more shows and movies got this issue.

**Comment by boydaihungst** [comment]
History page is now empty.
![image](https://github.com/user-attachments/assets/6867fd3a-93d6-4b81-9694-e7bb71e9f38a)

**Comment by morpheus65535** [comment]
The update to beta-20 didn't work properly. You should stop Bazarr, delete the instalation directory content and unzip the beta-20 zipped release. Be sure to preserve your data directory.

**Comment by boydaihungst** [comment]
The issue persists even after reinstalling Bazarr and its pip requirements. I tested using the local IP, so reverse proxy isn't the cause.

**Comment by morpheus65535** [comment]
It can't be the same error. There's no more subquery returned in beta-20. Please provide the new exception.

**Comment by boydaihungst** [comment]
It's the same error. @@ Should I also remove python virtual env folder?

**Comment by boydaihungst** [comment]
Also, I disabled subtitles upgrade.:

```
Nov 21 17:07:41 ubuntu-server bazarr[548561]: 2024-11-21 17:07:41,398 - root                             (720cd0c006c0) :  DEBUG (upgrade:271) - Subtitles upgrade is disabled so we wont go further.
Nov 21 17:07:41 ubuntu-server bazarr[548561]: 2024-11-21 17:07:41,476 - app.app                          (720cd0c006c0) :  ERROR (app:828) - Exception on /api/episodes/history [GET]
Nov 21 17:07:41 ubuntu-server bazarr[548561]: Traceback (most recent call last):
Nov 21 17:07:41 ubuntu-server bazarr[548561]:   File "/opt/bazarr/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request
Nov 21 17:07:41 ubuntu-server bazarr[548561]:     rv = self.dispatch_request()
Nov 21 17:07:41 ubuntu-server bazarr[548561]:          ^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 17:07:41 ubuntu-server bazarr[548561]:   File "/opt/bazarr/bazarr/../libs/flask/app.py", line 855, in dispatch_request
Nov 21 17:07:41 ubuntu-server bazarr[548561]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
Nov 21 17:07:41 ubuntu-server bazarr[548561]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 17:07:41 ubuntu-server bazarr[548561]:   File "/opt/bazarr/bazarr/../libs/flask_restx/api.py", line 402, in wrapper
Nov 21 17:07:41 ubuntu-server bazarr[548561]:     resp = resource(*args, **kwargs)
Nov 21 17:07:41 ubuntu-server bazarr[548561]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 17:07:41 ubuntu-server bazarr[548561]:   File "/opt/bazarr/bazarr/../libs/flask/views.py", line 110, in view
Nov 21 17:07:41 ubuntu-server bazarr[548561]:     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
Nov 21 17:07:41 ubuntu-server bazarr[548561]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 17:07:41 ubuntu-server bazarr[548561]:   File "/opt/bazarr/bazarr/../libs/flask_restx/resource.py", line 41, in dispatch_request
Nov 21 17:07:41 ubuntu-server bazarr[548561]:     resp = meth(*args, **kwargs)
Nov 21 17:07:41 ubuntu-server bazarr[548561]:            ^^^^^^^^^^^^^^^^^^^^^
Nov 21 17:07:41 ubuntu-server bazarr[548561]:   File "/opt/bazarr/bazarr/api/utils.py", line 30, in wrapper
Nov 21 17:07:41 ubuntu-server bazarr[548561]:     return actual_method(*args, **kwargs)
Nov 21 17:07:41 ubuntu-server bazarr[548561]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 17:07:41 ubuntu-server bazarr[548561]:   File "/opt/bazarr/bazarr/api/episodes/history.py", line 141, in get
Nov 21 17:07:41 ubuntu-server bazarr[548561]:     item.update({'original_id': upgradable_episodes_not_perfect.get(item['id'])})
Nov 21 17:07:41 ubuntu-server bazarr[548561]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 21 17:07:41 ubuntu-server bazarr[548561]: AttributeError: 'Subquery' object has no attribute 'get'
```

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Let me know if it's not the case!
