### ISSUE TITLE
Can't add provider OpenSubtitles.com

### ISSUE THREAD

**Issue by EddyVDB24** [morpheus65535/bazarr#2769]
**Describe the bug**
When trying to add to providerOpenSubtitles.com I'm getting the error 500 "You have disconnected from the server" when I click the save button. Other provider I can add.

**To Reproduce**
1. Go to 'Settings', then "Providers'
2. Click on 'the button +'
3. Scroll down to 'OpenSubtitles.com' and fill in the Username and Password.
4. Click twice on the 'Save' button and then I get this error.
![error Bazarr](https://github.com/user-attachments/assets/83a25e7b-cc70-4dda-bb4f-e6251ec73afb)

**Software (please complete the following information):**
 - Bazarr: version 1.4.5
 - Sonarr version 4.0.10.2544
 - OS: Bazarr and Sonarr are running on Docker

**Comment by anderson-oki** [comment]
Provide some logs that are stored in the bazarr folder.

**Comment by EddyVDB24** [comment]
[bazarr.log](https://github.com/user-attachments/files/17879715/bazarr.log)
Here is the logfile you requested.
I've cleaned the directory with logdile before trying to add the provider, for making it easier for you.
Already thanks for the help.

**Comment by morpheus65535** [comment]
Looks like a corrupted cache file. You can empty the `config/cache` directory and restart Bazarr.

```
Exception on /api/system/settings [POST]|Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/api/system/settings.py", line 122, in post
    save_settings(zip(request.form.keys(), request.form.listvalues()))
  File "/app/bazarr/bin/bazarr/app/config.py", line 704, in save_settings
    region.delete('oscom_token')
  File "/app/bazarr/bin/bazarr/../libs/dogpile/cache/region.py", line 1422, in delete
    self.backend.delete(key)
  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/cache_backends/file.py", line 34, in delete
    self._cache.pop(key, None)
  File "<frozen _collections_abc>", line 945, in pop  File "/app/bazarr/bin/bazarr/../libs/fcache/cache.py", line 279, in __getitem__
    return self._read_from_file(filename)
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/fcache/cache.py", line 259, in _read_from_file
    return self._loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/fcache/cache.py", line 219, in _loads
    return value if not self._serialize else pickle.loads(value)
                                             ^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
```

**Comment by EddyVDB24** [comment]
Clearing the cache solved the problem. Many thanks for helping me solve this.
