### ISSUE TITLE
Wrong season selected for Food Wars!

### ISSUE THREAD

**Issue by JaniM** [morpheus65535/bazarr#2795]
**Describe the bug**
When searching for some episodes of the first season of _Food Wars! Shokugeki No Souma_, Bazarr picks entries for the third season.

**To Reproduce**
1. Enable the Anime Tosho provider.
2. Open listing for Food Wars.
3. Run an automatic or manual search on Season 1 Episode 4. (this for me has the file name `/tv/Food Wars! (2015) {tvdb-289909}/Season 01/Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv`)

**Expected behavior**
I expect Bazarr to match the second or third result in the provided picture.

**Screenshots**
![image](https://github.com/user-attachments/assets/9330301c-8fa3-4317-909f-4f0929d03efe)

**Software (please complete the following information):**
 - Bazarr: 1.4.6-beta.32
 - Radarr version: 5.16.3.9541
 - Sonarr version: 4.0.11.2680
 - OS:  Linux

**Comment by morpheus65535** [comment]
We'll need a debug log to understand why it's getting improper results.

**Comment by JaniM** [comment]
I believe this is all the logs caused by the manual search.

```

2024-12-19 01:12:14,856 - root                             (7f74689bfb30) :  INFO (get_providers:196) - Using opensubtitlescom again after 1 minute, (disabled because: TooManyRequests)
2024-12-19 01:12:14,857 - root                             (7f74689bfb30) :  DEBUG (pool:79) - BAZARR updating pools: {'series_2': SZAsyncProviderPool [3 providers (2 initialized; 1 discarded)], 'movie_1': SZAsyncProviderPool [2 providers (1 initialized; 1 discarded)]}
2024-12-19 01:12:14,857 - root                             (7f74689bfb30) :  DEBUG (pool:44) - BAZARR updating pool: series_2
2024-12-19 01:12:14,898 - subliminal_patch.core            (7f74689bfb30) :  DEBUG (core:258) - Discarded providers: {'opensubtitlescom'} | New providers: {'animetosho', 'embeddedsubtitles', 'opensubtitlescom'}
2024-12-19 01:12:14,898 - subliminal_patch.core            (7f74689bfb30) :  DEBUG (core:260) - Updated discarded providers: set()
2024-12-19 01:12:14,898 - subliminal_patch.core            (7f74689bfb30) :  DEBUG (core:264) - Removed providers: set()
2024-12-19 01:12:14,898 - subliminal_patch.core            (7f74689bfb30) :  DEBUG (core:120) - No provider config updates
2024-12-19 01:12:14,899 - root                             (7f74689bfb30) :  DEBUG (pool:103) - BAZARR pools update elapsed time: 41.5ms
2024-12-19 01:12:14,899 - root                             (7f74689bfb30) :  DEBUG (manual:28) - BAZARR Manually searching subtitles for this file: /tv/Food Wars! (2015) {tvdb-289909}/Season 01/Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv
2024-12-19 01:12:14,910 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:65) - Hash value: 119 -> Rest sum: 120
2024-12-19 01:12:14,910 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:65) - Hash value: 359 -> Rest sum: 360
2024-12-19 01:12:14,910 - subliminal_patch.core            (7f74689bfb30) :  DEBUG (core:120) - No provider config updates
2024-12-19 01:12:14,910 - root                             (7f74689bfb30) :  DEBUG (utils:33) - BAZARR guessing video object using video file path: /tv/Food Wars! (2015) {tvdb-289909}/Season 01/Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv
2024-12-19 01:12:14,912 - subzero.video                    (7f74689bfb30) :  DEBUG (video:60) - Parsing video: Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv, hints: {'title': 'Food Wars!', 'type': 'episode'}
2024-12-19 01:12:14,912 - subliminal_patch.core            (7f74689bfb30) :  INFO (core:846) - Determining basic video properties for 'Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv' in '/tv/Food Wars! (2015) {tvdb-289909}/Season 01'
2024-12-19 01:12:15,043 - subliminal_patch.core            (7f74689bfb30) :  DEBUG (core:854) - GuessIt found: {
    "title": "Food Wars!",
    "year": 2015,
    "season": 1,
    "episode": 4,
    "episode_title": "004 - Sacred Mother of Kyokusei",
    "source": "Blu-ray",
2024-12-19 01:12:15,053 - subliminal_patch.core            (7f74689bfb30) :  DEBUG (core:898) - Computed hashes {'opensubtitlescom': '1fba1216edbbca3a'}
2024-12-19 01:12:15,053 - root                             (7f74689bfb30) :  DEBUG (utils:46) - Running refiner: database
2024-12-19 01:12:15,058 - root                             (7f74689bfb30) :  DEBUG (utils:46) - Running refiner: ffprobe
2024-12-19 01:12:15,066 - root                             (7f74689bfb30) :  DEBUG (ffprobe:42) - FFprobe found: {
    "path": "/tv/Food Wars! (2015) {tvdb-289909}/Season 01/Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv",
    "size": 489306728,
    "bit_rate": 2534378,
    "container": "mkv",
        "version": {
            "/usr/bin/ffprobe": "v6.1.1"
2024-12-19 01:12:15,081 - subtitles.refiners.anidb         (7f74689bfb30) :  DEBUG (anidb:223) - AniDB refinement identified Food Wars! as 10901.
2024-12-19 01:12:15,087 - root                             (7f74689bfb30) :  DEBUG (utils:46) - Running refiner: anilist
2024-12-19 01:12:15,088 - root                             (7f74689bfb30) :  DEBUG (utils:49) - BAZARR is using these video object properties: {
    "name": "/tv/Food Wars! (2015) {tvdb-289909}/Season 01/Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv",
    "source": "Blu-ray",
    "release_group": "Prof",
    "resolution": "1080p",
    "video_codec": "H.265",
    "audio_codec": "AAC",
    "imdb_id": null,
    "hashes": {
        "opensubtitlescom": "1fba1216edbbca3a"
    },
    "size": 489306728,
    "subtitle_languages": "set()",
    "original_name": "Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv",
    "plexapi_metadata": {},
    "hints": {
        "title": "Food Wars!",
        "type": "episode",
    "info_url": null,
    "series_anidb_series_id": [
        null
    ],
    "series_anidb_episode_id": [
    "year": 2015,
    "original_series": false,
    "tvdb_id": null,
        "Shokugeki no Soma S3",
        "Shokugeki no Souma - San no Sara",
        "Shokugeki no Souma - Shin no Sara",
        "Shokugeki no Souma S4",
    "sonarrSeriesId": 38,
    "sonarrEpisodeId": 2661,
    "fps": "23.976",
2024-12-19 01:12:15,089 - subliminal_patch.core            (7f745bc68b30) :  DEBUG (core:345) - Languages requested: {<Language: alpha3=eng>, <Language: hi=True;alpha3=eng>}
2024-12-19 01:12:15,089 - subliminal_patch.core            (7f745ba28b30) :  DEBUG (core:345) - Languages requested: {<Language: alpha3=eng>, <Language: hi=True;alpha3=eng>}
2024-12-19 01:12:15,090 - subliminal_patch.core            (7f745bc68b30) :  DEBUG (core:202) - New set: 14 items
2024-12-19 01:12:15,090 - subliminal_patch.core            (7f745b80bb30) :  DEBUG (core:345) - Languages requested: {<Language: alpha3=eng>, <Language: hi=True;alpha3=eng>}
2024-12-19 01:12:15,090 - subliminal_patch.core            (7f745ba28b30) :  DEBUG (core:202) - New set: 744 items
2024-12-19 01:12:15,090 - subliminal_patch.core            (7f745bc68b30) :  DEBUG (core:180) - Nothing to translate found
2024-12-19 01:12:15,091 - subliminal_patch.core            (7f745ba28b30) :  DEBUG (core:180) - Nothing to translate found
2024-12-19 01:12:15,091 - subliminal_patch.core            (7f745bc68b30) :  INFO (core:375) - Listing subtitles with provider 'animetosho' and languages {<Language: alpha3=eng>}
2024-12-19 01:12:15,091 - subliminal_patch.core            (7f745b80bb30) :  DEBUG (core:180) - Nothing to translate found
2024-12-19 01:12:15,092 - subliminal_patch.core            (7f745ba28b30) :  INFO (core:375) - Listing subtitles with provider 'embeddedsubtitles' and languages {<Language: alpha3=eng>, <Language: hi=True;alpha3=eng>}
2024-12-19 01:12:15,093 - subliminal_patch.core            (7f745b80bb30) :  INFO (core:375) - Listing subtitles with provider 'opensubtitlescom' and languages {<Language: alpha3=eng>, <Language: hi=True;alpha3=eng>}
2024-12-19 01:12:15,093 - urllib3.connectionpool           (7f745bc68b30) :  DEBUG (connectionpool:292) - Resetting dropped connection: feed.animetosho.org
2024-12-19 01:12:15,094 - subliminal_patch.core            (7f745b80bb30) :  INFO (core:306) - Initializing provider opensubtitlescom
2024-12-19 01:12:15,103 - subliminal_patch.providers.opensubtitlescom (7f745b80bb30) :  DEBUG (opensubtitlescom:193) - No cached token, we'll try to login again.
2024-12-19 01:12:15,104 - urllib3.connectionpool           (7f745b80bb30) :  DEBUG (connectionpool:1055) - Starting new HTTPS connection (1): api.opensubtitles.com:443
2024-12-19 01:12:15,175 - fese.container                   (7f745ba28b30) :  DEBUG (container:115) - Source doesn't have any subtitle valid streams
2024-12-19 01:12:15,175 - subliminal_patch.providers.embeddedsubtitles (7f745ba28b30) :  DEBUG (embeddedsubtitles:145) - No subtitles found for container: <FFprobeVideoContainer mkv: /tv/Food Wars! (2015) {tvdb-289909}/Season 01/Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv>
2024-12-19 01:12:15,175 - subliminal_patch.providers.embeddedsubtitles (7f745ba28b30) :  DEBUG (embeddedsubtitles:285) - Checking HI fallback for '<Language: alpha3=eng>' language
2024-12-19 01:12:15,175 - subliminal_patch.providers.embeddedsubtitles (7f745ba28b30) :  DEBUG (embeddedsubtitles:285) - Checking HI fallback for '<Language: hi=True;alpha3=eng>' language
2024-12-19 01:12:15,175 - subliminal_patch.providers.embeddedsubtitles (7f745ba28b30) :  DEBUG (embeddedsubtitles:179) - Cache info: CacheInfo(hits=13, misses=6, maxsize=8096, currsize=6)
2024-12-19 01:12:15,249 - urllib3.connectionpool           (7f745bc68b30) :  DEBUG (connectionpool:549) - https://feed.animetosho.org:443 "GET /json?eid=10901&eid=167378 HTTP/1.1" 200 None
2024-12-19 01:12:15,277 - urllib3.connectionpool           (7f745b80bb30) :  DEBUG (connectionpool:549) - https://api.opensubtitles.com:443 "POST /api/v1/login HTTP/1.1" 429 41
2024-12-19 01:12:15,277 - subliminal_patch.providers.opensubtitlescom (7f745b80bb30) :  DEBUG (opensubtitlescom:595) - opensubtitlescom returned a non standard response. Logging request/response for debugging purpose.
2024-12-19 01:12:15,278 - subliminal_patch.providers.opensubtitlescom (7f745b80bb30) :  DEBUG (opensubtitlescom:599) - Request URL: https://api.opensubtitles.com/api/v1/login
2024-12-19 01:12:15,278 - subliminal_patch.providers.opensubtitlescom (7f745b80bb30) :  DEBUG (opensubtitlescom:600) - Request Headers: {'User-Agent': 'Bazarr/1.4.6-beta.32', 'Api-Key': 's38zmzVlW7IlYruWi7mHwDYl2SfMQoC1', 'Content-Type': 'application/json', 'Content-Length': '56'}
2024-12-19 01:12:15,278 - subliminal_patch.providers.opensubtitlescom (7f745b80bb30) :  DEBUG (opensubtitlescom:601) - Request Body: {"username": "seequ", "password": "redacted"}
2024-12-19 01:12:15,278 - subliminal_patch.providers.opensubtitlescom (7f745b80bb30) :  DEBUG (opensubtitlescom:602) - Response Status Code: 429
2024-12-19 01:12:15,278 - subliminal_patch.providers.opensubtitlescom (7f745b80bb30) :  DEBUG (opensubtitlescom:603) - Response Headers: {'Date': 'Thu, 19 Dec 2024 01:12:15 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '41', 'Connection': 'keep-alive', 'X-RateLimit-Remaining-Hour': '0', 'RateLimit-Remaining': '0', 'RateLimit-Reset': '2865', 'Retry-After': '2865', 'X-RateLimit-Limit-Second': '1', 'X-RateLimit-Limit-Hour': '60', 'X-RateLimit-Remaining-Second': '1', 'RateLimit-Limit': '60', 'Access-Control-Allow-Origin': '*', 'X-Kong-Response-Latency': '0', 'cf-cache-status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=NCQnSzLHVb0aKzjJALB6eo8wZ9%2FnyscbfJAhrncryyebbT0fn1SMFuHdiqhdukKJjXy%2BiZ9gGBVAJEOPrtw26gjWU9IAGn4xOWbsibT05iA1t2b647AGvpmX%2BqDUiKBDRg9oG%2FglVh0%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '8f4385f7295392b0-CPH', 'alt-svc': 'h3=":443"; ma=86400', 'server-timing': 'cfL4;desc="?proto=TCP&rtt=21774&min_rtt=21761&rtt_var=8187&sent=5&recv=7&lost=0&retrans=0&sent_bytes=2857&recv_bytes=913&delivery_rate=132437&cwnd=152&unsent_bytes=0&cid=10ba73eefe4a1800&ts=72&x=0"'}
2024-12-19 01:12:15,279 - subliminal_patch.providers.opensubtitlescom (7f745b80bb30) :  DEBUG (opensubtitlescom:604) - Response Body: {"message": "API rate limit exceeded"}
2024-12-19 01:12:15,280 - subliminal_patch.core            (7f745b80bb30) :  ERROR (core:409) - Unexpected error in provider 'opensubtitlescom': Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 378, in list_subtitles_provider
    results = self[provider].list_subtitles(video, to_request)
              ~~~~^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 308, in __getitem__
    provider.initialize()
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/opensubtitlescom.py", line 194, in initialize
    self.login()
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/opensubtitlescom.py", line 214, in login
    r = self.checked(
        ^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/opensubtitlescom.py", line 547, in checked
    raise TooManyRequests()
subliminal_patch.exceptions.TooManyRequests
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 378, in list_subtitles_provider
    results = self[provider].list_subtitles(video, to_request)
              ~~~~^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 308, in __getitem__
2024-12-19 01:12:15,282 - root                             (7f745b80bb30) :  INFO (get_providers:396) - Throttling opensubtitlescom for 1 minute, until 24/12/19 01:13, because of: TooManyRequests. Exception info: "'' ~ opensubtitlescom.py@547"
2024-12-19 01:12:15,284 - socketio.server                  (7f745b80bb30) :  INFO (server:161) - emitting event "data" to all [/]
2024-12-19 01:12:15,285 - engineio.server                  (7f745b80bb30) :  INFO (socket:76) - B0PETAE91P2pTvR0AAAC: Sending packet MESSAGE data 2["data",{"type":"badges","action":"update","payload":null}]
2024-12-19 01:12:15,285 - engineio.server                  (7f745b80bb30) :  INFO (socket:76) - j-mewq70V_wld573AAAE: Sending packet MESSAGE data 2["data",{"type":"badges","action":"update","payload":null}]
2024-12-19 01:12:17,247 - urllib3.connectionpool           (7f745bc68b30) :  DEBUG (connectionpool:549) - https://feed.animetosho.org:443 "GET /json?show=torrent&id=229088 HTTP/1.1" 200 None
2024-12-19 01:12:17,249 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=ita>]>
2024-12-19 01:12:17,250 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=por;country=BR>]>
2024-12-19 01:12:17,250 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=eng>]>
2024-12-19 01:12:17,251 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=eng>]>
2024-12-19 01:12:17,252 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=ara>]>
2024-12-19 01:12:17,252 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=deu>]>
2024-12-19 01:12:17,253 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=spa>]>
2024-12-19 01:12:17,253 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=spa>]>
2024-12-19 01:12:17,254 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=fra>]>
2024-12-19 01:12:19,248 - urllib3.connectionpool           (7f745bc68b30) :  DEBUG (connectionpool:549) - https://feed.animetosho.org:443 "GET /json?show=torrent&id=174739 HTTP/1.1" 200 None
2024-12-19 01:12:19,249 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [AnimeRG] Food Wars Shokugeki no Soma - 4 [720p] [Multi Subbed].mkv [<Language: alpha3=eng>]>
2024-12-19 01:12:19,250 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [AnimeRG] Food Wars Shokugeki no Soma - 4 [720p] [Multi Subbed].mkv [<Language: alpha3=ara>]>
2024-12-19 01:12:19,250 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [AnimeRG] Food Wars Shokugeki no Soma - 4 [720p] [Multi Subbed].mkv [<Language: alpha3=deu>]>
2024-12-19 01:12:19,251 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [AnimeRG] Food Wars Shokugeki no Soma - 4 [720p] [Multi Subbed].mkv [<Language: alpha3=spa>]>
2024-12-19 01:12:19,251 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [AnimeRG] Food Wars Shokugeki no Soma - 4 [720p] [Multi Subbed].mkv [<Language: alpha3=spa>]>
2024-12-19 01:12:21,249 - urllib3.connectionpool           (7f745bc68b30) :  DEBUG (connectionpool:549) - https://feed.animetosho.org:443 "GET /json?show=torrent&id=127489 HTTP/1.1" 200 None
2024-12-19 01:12:23,248 - urllib3.connectionpool           (7f745bc68b30) :  DEBUG (connectionpool:549) - https://feed.animetosho.org:443 "GET /json?show=torrent&id=127435 HTTP/1.1" 200 None
2024-12-19 01:12:25,249 - urllib3.connectionpool           (7f745bc68b30) :  DEBUG (connectionpool:549) - https://feed.animetosho.org:443 "GET /json?show=torrent&id=127436 HTTP/1.1" 200 None
2024-12-19 01:12:27,251 - urllib3.connectionpool           (7f745bc68b30) :  DEBUG (connectionpool:549) - https://feed.animetosho.org:443 "GET /json?show=torrent&id=127412 HTTP/1.1" 200 None
2024-12-19 01:12:27,252 - subliminal_patch.providers.animetosho (7f745bc68b30) :  DEBUG (animetosho:160) - Found subtitle <AnimeToshoSubtitle: [FFF] Shokugeki no Souma - 04 [469F70E1].mkv [<Language: alpha3=eng>]>
2024-12-19 01:12:27,253 - subliminal_patch.core            (7f74689bfb30) :  INFO (core:748) - Discarding provider opensubtitlescom
2024-12-19 01:12:27,253 - subliminal_patch.core_persistent (7f74689bfb30) :  INFO (core_persistent:26) - Found 4 subtitle(s)
2024-12-19 01:12:27,272 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have streaming_service. Returning True
2024-12-19 01:12:27,272 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have edition. Returning True
2024-12-19 01:12:27,272 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have other. Returning True
2024-12-19 01:12:27,272 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:91) - Scores to use for <Episode ['Food Wars!', 2015, 1x4]>: {'hearing_impaired': 1, 'streaming_service': 1, 'video_codec': 2, 'resolution': 2, 'audio_codec': 3, 'source': 7, 'release_group': 14, 'episode': 30, 'season': 30, 'year': 90, 'series': 180, 'hash': 359}
2024-12-19 01:12:27,273 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:171) - Adding title match equivalent
2024-12-19 01:12:27,273 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:180) - Adding tvdb_id match equivalents
2024-12-19 01:12:27,273 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:148) - Matched hearing_impaired
2024-12-19 01:12:27,273 - subliminal_patch.score           (7f74689bfb30) :  INFO (score:154) - <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=eng>]>: Computed score 332 with final matches {'edition', 'other', 'tvdb_id', 'series', 'episode', 'season', 'year', 'streaming_service', 'hearing_impaired', 'title'}
2024-12-19 01:12:27,290 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have streaming_service. Returning True
2024-12-19 01:12:27,290 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have edition. Returning True
2024-12-19 01:12:27,290 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have other. Returning True
2024-12-19 01:12:27,291 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:91) - Scores to use for <Episode ['Food Wars!', 2015, 1x4]>: {'hearing_impaired': 1, 'streaming_service': 1, 'video_codec': 2, 'resolution': 2, 'audio_codec': 3, 'source': 7, 'release_group': 14, 'episode': 30, 'season': 30, 'year': 90, 'series': 180, 'hash': 359}
2024-12-19 01:12:27,291 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:171) - Adding title match equivalent
2024-12-19 01:12:27,291 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:180) - Adding tvdb_id match equivalents
2024-12-19 01:12:27,291 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:148) - Matched hearing_impaired
2024-12-19 01:12:27,291 - subliminal_patch.score           (7f74689bfb30) :  INFO (score:154) - <AnimeToshoSubtitle: [R23] Shokugeki no Soma|Souma (Food Wars!) - San no Sara S3 - 04 [1080p] [x265] [HEVC] [AAC] [10bit] [Multi - Subbed] [<Language: alpha3=eng>]>: Computed score 332 with final matches {'edition', 'other', 'tvdb_id', 'series', 'episode', 'season', 'year', 'streaming_service', 'hearing_impaired', 'title'}
2024-12-19 01:12:27,317 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:457) - resolution matched? False (1080p -> 720p)
2024-12-19 01:12:27,317 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have streaming_service. Returning True
2024-12-19 01:12:27,318 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have edition. Returning True
2024-12-19 01:12:27,318 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have other. Returning True
2024-12-19 01:12:27,318 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:91) - Scores to use for <Episode ['Food Wars!', 2015, 1x4]>: {'hearing_impaired': 1, 'streaming_service': 1, 'video_codec': 2, 'resolution': 2, 'audio_codec': 3, 'source': 7, 'release_group': 14, 'episode': 30, 'season': 30, 'year': 90, 'series': 180, 'hash': 359}
2024-12-19 01:12:27,318 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:171) - Adding title match equivalent
2024-12-19 01:12:27,318 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:180) - Adding tvdb_id match equivalents
2024-12-19 01:12:27,319 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:148) - Matched hearing_impaired
2024-12-19 01:12:27,319 - subliminal_patch.score           (7f74689bfb30) :  INFO (score:154) - <AnimeToshoSubtitle: [AnimeRG] Food Wars Shokugeki no Soma - 4 [720p] [Multi Subbed].mkv [<Language: alpha3=eng>]>: Computed score 332 with final matches {'edition', 'other', 'tvdb_id', 'series', 'season', 'episode', 'year', 'streaming_service', 'hearing_impaired', 'title'}
2024-12-19 01:12:27,342 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have streaming_service. Returning True
2024-12-19 01:12:27,343 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have edition. Returning True
2024-12-19 01:12:27,343 - subliminal_patch.subtitle        (7f74689bfb30) :  DEBUG (subtitle:591) - Both video and guess don't have other. Returning True
2024-12-19 01:12:27,343 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:91) - Scores to use for <Episode ['Food Wars!', 2015, 1x4]>: {'hearing_impaired': 1, 'streaming_service': 1, 'video_codec': 2, 'resolution': 2, 'audio_codec': 3, 'source': 7, 'release_group': 14, 'episode': 30, 'season': 30, 'year': 90, 'series': 180, 'hash': 359}
2024-12-19 01:12:27,344 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:171) - Adding title match equivalent
2024-12-19 01:12:27,344 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:180) - Adding tvdb_id match equivalents
2024-12-19 01:12:27,344 - subliminal_patch.score           (7f74689bfb30) :  DEBUG (score:148) - Matched hearing_impaired
2024-12-19 01:12:27,344 - subliminal_patch.score           (7f74689bfb30) :  INFO (score:154) - <AnimeToshoSubtitle: [FFF] Shokugeki no Souma - 04 [469F70E1].mkv [<Language: alpha3=eng>]>: Computed score 332 with final matches {'edition', 'other', 'tvdb_id', 'series', 'season', 'episode', 'year', 'streaming_service', 'hearing_impaired', 'title'}
2024-12-19 01:12:27,345 - root                             (7f74689bfb30) :  DEBUG (manual:134) - BAZARR 4 Subtitles have been found for this file: /tv/Food Wars! (2015) {tvdb-289909}/Season 01/Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv
2024-12-19 01:12:27,345 - root                             (7f74689bfb30) :  DEBUG (manual:135) - BAZARR Ended searching Subtitles for this file: /tv/Food Wars! (2015) {tvdb-289909}/Season 01/Food Wars! (2015) - S01E04 - 004 - Sacred Mother of Kyokusei [Bluray-1080p][10bit][x265][AAC 2.0][EN+JA]-Prof.mkv
```

**Comment by anderson-oki** [comment]
This seems to be an issue with animetosho itself https://animetosho.org/episode/shokugeki-no-souma-4.167378

Where the Season 3 is wrongly mapped to anidbid `167378`. Open the link i sent and confirm that https://anidb.net/episode/167378 is the season 1 episode 4 on anidb.

**Comment by JaniM** [comment]
I believe you were right and this was an issue on Animetosho's end. Today I see no mention of season 3 in the link you provided and Bazarr gives the correct result.

**Comment by anderson-oki** [comment]
Oh i should have taken a screenshot. Its gone now.

**Comment by JaniM** [comment]
This is strange. Manual search does not show the season 3 result anymore, but automatic search still picked it up.

**Comment by JaniM** [comment]
This is not a cache issue. The issue is that `[AnimeRG] Food Wars Shokugeki no Soma - 4 [720p] [Multi Subbed].mkv` (which is now the first result) on animetosho is actually season 3...

**Comment by anderson-oki** [comment]
> This is not a cache issue. The issue is that `[AnimeRG] Food Wars Shokugeki no Soma - 4 [720p] [Multi Subbed].mkv` (which is now the first result) on animetosho is actually season 3...

I guess they changed the title only?

**Comment by JaniM** [comment]
> I guess they changed the title only?

You can see the current match in the original picture. The blatant season 3 file is gone, but turns out the second match always was season 2. The last match is season 1.

**Comment by anderson-oki** [comment]
Sorry @JaniM I will be closing this issue here and lets try to contact Animetosho admin to have a fix!
