### ISSUE TITLE
Unable to upgrade to 1.5.0 on Docker

### ISSUE THREAD

**Issue by elkinjosetm** [morpheus65535/bazarr#2804]
**Describe the bug**
After upgrading from 1.4.5 to 1.5.0 the container is not longer able to initialize with the following errors in the logs:

```
2024-12-25 11:57:13,267 - root                             (7f9c31648b28) :  ERROR (server:73) - BAZARR cannot start because of unhandled exception.
Closing database...
Closing webserver...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server
    self.server = create_server(app,
                  ^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
                ^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__
    self.bind_server_socket()
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket
    self.bind(sockaddr)
  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind
    return self.socket.bind(addr)
           ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 99] Address not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 43, in <module>
    from app.server import webserver, app  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/server.py", line 108, in <module>
    webserver = Server()
                ^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/server.py", line 42, in __init__
    self.configure_server()
  File "/app/bazarr/bin/bazarr/app/server.py", line 74, in configure_server
    self.shutdown()
  File "/app/bazarr/bin/bazarr/app/server.py", line 100, in shutdown
    self.close_all()
  File "/app/bazarr/bin/bazarr/app/server.py", line 97, in close_all
    self.server.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
```

**To Reproduce**
1. Upgrade 1.4.5 to 1.5.0

**Expected behavior**
Being able to upgrade to 1.5.0

**Software (please complete the following information):**
 - Bazarr: v1.5.0
 - Radarr version v5.16.3.9541
 - Sonarr version v4.0.11.2680
 - OS: Docker container linuxserver/bazarr

**Additional context**
For now I downgraded back to 1.4.5 to keep using the service

**Comment by morpheus65535** [comment]
What IP address did you configure in your config.yaml?

**Comment by elkinjosetm** [comment]
> What IP address did you configure in your config.yaml?

The local ip assigned to the server: 192.158.1.16

**Comment by morpheus65535** [comment]
Python need to be able to hold the IP address. If you're running using Docker, the only valid IP are 127.0.0.1 or the container IP on the docker network. The docker host isn't availble inside the container. If you set it to 0.0.0.0, it will listen on every available address.

**Comment by elkinjosetm** [comment]
Oh! That was it, thank you!

**Comment by steef12111** [comment]
@morpheus65535 Should this IP be set to 0.0.0.0 inside the bazarr config? Or somewhere in the docker-compose.yaml?
Thanks!

**Comment by morpheus65535** [comment]
> @morpheus65535 Should this IP be set to 0.0.0.0 inside the bazarr config? Or somewhere in the docker-compose.yaml?
> 
> Thanks!

In Bazarr config directly. There's no benefit to modify that when using Docker.

**Comment by steef12111** [comment]
Did the job, thanks!
