### ISSUE TITLE
Bazarr docker crashes on start 

### ISSUE THREAD

**Issue by HamdiMaz** [morpheus65535/bazarr#2805]
**Describe the bug**
the docker container of bazaar from linuxserver crashes when started producing this error in the logs :

[migrations] started

[migrations] no migrations found

───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗

      ██║     ██╔════╝██║██╔═══██╗

      ██║     ███████╗██║██║   ██║

      ██║     ╚════██║██║██║   ██║

      ███████╗███████║██║╚██████╔╝

      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io

───────────────────────────────────────

To support the app dev(s) visit:

Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1000

User GID:    1000

───────────────────────────────────────

Linuxserver.io version: v1.5.0-ls284

Build-date: 2024-12-25T22:17:44+00:00

───────────────────────────────────────

    

[custom-init] No custom files found, skipping...

2024-12-26 03:00:32,378 - root                             (7c0bb15a9b28) :  ERROR (server:73) - BAZARR cannot start because of unhandled exception.

Closing database...

Closing webserver...

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server

    self.server = create_server(app,

                  ^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server

    last_serv = TcpWSGIServer(

                ^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__

    self.bind_server_socket()

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket

    self.bind(sockaddr)

  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind

    return self.socket.bind(addr)

           ^^^^^^^^^^^^^^^^^^^^^^

OSError: [Errno 99] Address not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/main.py", line 43, in <module>

    from app.server import webserver, app  # noqa E402

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/app/server.py", line 108, in <module>

    webserver = Server()

                ^^^^^^^^

  File "/app/bazarr/bin/bazarr/app/server.py", line 42, in __init__

    self.configure_server()

  File "/app/bazarr/bin/bazarr/app/server.py", line 74, in configure_server

    self.shutdown()

  File "/app/bazarr/bin/bazarr/app/server.py", line 100, in shutdown

    self.close_all()

  File "/app/bazarr/bin/bazarr/app/server.py", line 97, in close_all

    self.server.close()

    ^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'close'

**Comment by morpheus65535** [comment]
Duplicate #2804
