### ISSUE TITLE
Address not available

### ISSUE THREAD

**Issue by steef12111** [morpheus65535/bazarr#2808]
**Describe the bug**
Bazarr is not accessible in the GUI.
Bazarr is hosted in Docker Compose. In Portainer Bazarr is reported as "Running"

**To Reproduce**
Not sure if related, but I performed a Ubuntu kernel update, from Linux 6.8.0-49-generic x86_64 to Linux 6.8.0-51-generic x86_64. After which I tried to access Bazarr, which resulted in the logs shown below.

**Expected behavior**
The Bazarr GUI to be accessible at the hosts IP address on the corresponding port 6767

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v1.5.0-ls284
 - Radarr version 5.16.3.9541
 - Sonarr version 4.0.11.2680
 - OS: Docker Compose on Linux 6.8.0-51-generic x86_64

**Additional context**
Portainer log
` 
Linuxserver.io version: v1.5.0-ls284

Build-date: 2024-12-25T22:17:44+00:00

───────────────────────────────────────

    

[custom-init] No custom files found, skipping...

2024-12-27 17:34:11,338 - root                             (715b3cae1b28) :  ERROR (server:73) - BAZARR cannot start because of unhandled exception.

Closing database...

Closing webserver...

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server

    self.server = create_server(app,

                  ^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server

    last_serv = TcpWSGIServer(

                ^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__

    self.bind_server_socket()

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket

    self.bind(sockaddr)

  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind

    return self.socket.bind(addr)

           ^^^^^^^^^^^^^^^^^^^^^^

OSError: [Errno 99] Address not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/main.py", line 43, in <module>

    from app.server import webserver, app  # noqa E402

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/app/server.py", line 108, in <module>

    webserver = Server()

                ^^^^^^^^

  File "/app/bazarr/bin/bazarr/app/server.py", line 42, in __init__

    self.configure_server()

  File "/app/bazarr/bin/bazarr/app/server.py", line 74, in configure_server

    self.shutdown()

  File "/app/bazarr/bin/bazarr/app/server.py", line 100, in shutdown

    self.close_all()

  File "/app/bazarr/bin/bazarr/app/server.py", line 97, in close_all

    self.server.close()

    ^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'close'

`

**Comment by morpheus65535** [comment]
Duplicate #2804
