### ISSUE TITLE
Issue with WMV files

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#30]
Just reporting an error I received concerning WMV files. WMV files are of course valid

```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://0.0.0.0:6767/wanted_search_missing_subtitles' caused an error:

Internal Server Error
Exception:

ValueError("u'.WMV' is not a valid video extension",)
Traceback:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr.py", line 276, in wanted_search_missing_subtitles_list
    wanted_search_missing_subtitles()
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 108, in wanted_search_missing_subtitles
    wanted_download_subtitles(episode[0])
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 92, in wanted_download_subtitles
    message = download_subtitle(path_replace(episode[0]), str(pycountry.languages.lookup(language).alpha_3), episode[4], providers_list, providers_auth)
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 19, in download_subtitle
    video = scan_video(path)
  File "/Library/Python/2.7/site-packages/subliminal/core.py", line 374, in scan_video
    raise ValueError('%r is not a valid video extension' % os.path.splitext(path)[1])
ValueError: u'.WMV' is not a valid video extension
```

**Comment by morpheus65535** [comment]
Thanks, I'm going to have to exclude those unsupported file extension. Subliminal, on which Bazarr rely, do not support WMV files.

**Comment by morpheus65535** [comment]
Can you try to rename the file extension to replace uppercase by lowercase?

**Comment by stefandevo** [comment]
No error for lowercase.

**Comment by morpheus65535** [comment]
On which OS are you running it? Subliminal seems to be case sensitive on the extension it support...

**Comment by stefandevo** [comment]
osx

**Comment by morpheus65535** [comment]
I've opened an issue with subliminal. We'll see what came out of it.

**Comment by morpheus65535** [comment]
If you can take a look at the PR for subliminal and report back, I would be able to integrate it in bazarr. Thanks!

**Comment by morpheus65535** [comment]
Bug corrected in subliminal. Should be in the next release of subliminal.
