### ISSUE TITLE
[Bug] Download wanted subtitles problem in latest version

### ISSUE THREAD

**Issue by rickytin** [morpheus65535/bazarr#317]
Bazarr version 0.7.2
Sonarr version 3.0.0.348
Radarr version 0.2.0.1293
Operating system Windows-10-10.0.18312

4 movies that I try to download at the same time with "Download wanted subtitles" and I have this error:

Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:6767/wanted_search_missing_subtitles' caused an error:

Internal Server Error
Exception:
LookupError('No trigger by the name "date" was found',)
Traceback:
Traceback (most recent call last):
  File "c:\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "c:\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "c:\bazarr\bazarr\main.py", line 138, in wrapper
    return func(*a, **ka)
  File "c:\bazarr\bazarr\main.py", line 1069, in wanted_search_missing_subtitles_list
    scheduler.add_job(wanted_search_missing_subtitles)
  File "c:\bazarr\bazarr\../libs/apscheduler\schedulers\base.py", line 416, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "c:\bazarr\bazarr\../libs/apscheduler\schedulers\base.py", line 918, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "c:\bazarr\bazarr\../libs/apscheduler\schedulers\base.py", line 901, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No trigger by the name "date" was found

**Comment by morpheus65535** [comment]
I can reproduce it. I will work on it ASAP but in the mean time it doesn't break the automatic search functionality. You can also trigger it from System-->Tasks and it should work.

**Comment by halali** [comment]
Just pushed fix for this issue, can you please update your bazarr and give feedback if this work? thx

**Comment by rickytin** [comment]
Thanks for the update but I still have the problem:

Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:6767/wanted_search_missing_subtitles' caused an error:

Internal Server Error
Exception:
LookupError('No trigger by the name "date" was found',)
Traceback:
Traceback (most recent call last):
  File "c:\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "c:\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "c:\bazarr\bazarr\main.py", line 138, in wrapper
    return func(*a, **ka)
  File "c:\bazarr\bazarr\main.py", line 1069, in wanted_search_missing_subtitles_list
    scheduler.add_job(wanted_search_missing_subtitles, next_run_time=datetime.now())
  File "c:\bazarr\bazarr\../libs/apscheduler\schedulers\base.py", line 416, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "c:\bazarr\bazarr\../libs/apscheduler\schedulers\base.py", line 918, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "c:\bazarr\bazarr\../libs/apscheduler\schedulers\base.py", line 901, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No trigger by the name "date" was found

**Comment by halali** [comment]
ok another fix...

**Comment by rickytin** [comment]
Yep now it's fix. Thanks

**Comment by halali** [comment]
thx for reporting it and help.
