### ISSUE TITLE
For several weeks I've been getting the following when I search using Bazarr

### ISSUE THREAD

**Issue by jamesking420** [morpheus65535/bazarr#325]
Didn't notice at first, but it seems this has been why I've not been able to download subtitles for 2 weeks or so.

**Describe the bug**
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 660, in wanted_search_missing_subtitles
  wanted_download_subtitles(episode[0])
 File "/app/bazarr/bazarr/get_subtitle.py", line 573, in wanted_download_subtitles
  episode[7], \series\)
 File "/app/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle
  language_hook=None) # fixme
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles
  subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles
  itertools.repeat(languages, len(self.providers))):
 File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator
  yield future.result()
 File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result
  return self.__get_result()
 File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider
  provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider
  if not provider_registry[provider].check(video):
AttributeError: \NoneType\ object has no attribute \check\

**To Reproduce**
Do a subtitle search and check the logs.
**Expected behavior**
Subtitle downloads
**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.7.1
 - Docker container from lunuxserver

**Additional context**
Running on QNAP NAS

**Comment by morpheus65535** [comment]
Go to settings, check for providers and save settings.
