### ISSUE TITLE
Bazarr is not downloading subtitles

### ISSUE THREAD

**Issue by pedrojvaz** [morpheus65535/bazarr#335]
**Describe the bug**
Bazarr is not downloading subtitles

**To Reproduce**
**Message**
`Job "Search for wanted subtitles (trigger: interval[3:00:00], next run at: 2019-03-02 15:33:50 CET)" raised an exception`
**Exception**
```
Traceback (most recent call last):
 File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/opt/bazarr/bazarr/get_subtitle.py", line 660, in wanted_search_missing_subtitles
  wanted_download_subtitles(episode[0])
 File "/opt/bazarr/bazarr/get_subtitle.py", line 573, in wanted_download_subtitles
  episode[7], \series\)
 File "/opt/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle
  language_hook=None) # fixme
 File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles
  subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
 File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles
  itertools.repeat(languages, len(self.providers))):
 File "/opt/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator
  yield future.result()
 File "/opt/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result
  return self.__get_result()
 File "/opt/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider
  provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages)
 File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider
  if not provider_registry[provider].check(video):
AttributeError: \NoneType\ object has no attribute \check\
```

**Software (please complete the following information):**
 - Bazarr: 0.7.1
 - Radarr version 0.2.0.1293 
 - Sonarr version 2.0.0.5301 
 - OS: Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic 
 - Python version: 2.7.15rc1

**Additional context**

**Comment by jouz3** [comment]
I’m getting the same. I think there’s a problem with the **Legendas.TV** provider.

**Comment by morpheus65535** [comment]
Go to Settings, checks providers and save settings.
