### ISSUE TITLE
error when trying to analyze mkv file

### ISSUE THREAD

**Issue by Zixim** [morpheus65535/bazarr#336]
Getting this error, for a single file in my library : 
``
BAZARR error when trying to analyze this mkv file: \\nas\drivepool\video\TV shows\someshow\someseason\the_file_name.mkv
``
```
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\list_subtitles.py", line 38, in store_subtitles
  mkv = enzyme.MKV(f)
 File "c:\\bazarr\\bazarr\\../libs/enzyme\\mkv.py", line 56, in __init__
  raise MalformedMKVError(\Parsing error: %s\ % e)
MalformedMKVError: Parsing error: Cannot read element id
```
I have several files that are very similar (if not identical), which don't cause any kind of issue.
fwiw these are the headers as reported by MediaInfo, with some light redacting 🤐  : 
```
General
Unique ID                   : 84669061028752926736184324282781030832 (0x3FB2AB0209A5878C925E7C177CE459B0)
Complete name               : \\nas\drivepool\video\TV shows\someshow\someseason\the_file_name.mkv
Format                      : Matroska
Format version              : Version 4 / Version 2
File size                   : 216 MiB
Duration                    : 42mn 10s
Overall bit rate            : 716 Kbps
Movie name                  : show_name
Encoded date                : UTC 2018-03-09 10:56:43
Writing application         : mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
Writing library             : libebml v1.3.5 + libmatroska v1.4.8

Video
ID                          : 1
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main@L3.1@Main
Codec ID                    : V_MPEGH/ISO/HEVC
Duration                    : 42mn 10s
Width                       : 1 280 pixels
Height                      : 716 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Default                     : Yes
Forced                      : No
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709

Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : HE-AAC / LC
Codec ID                    : A_AAC
Duration                    : 42mn 10s
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 48.0 KHz / 24.0 KHz
Compression mode            : Lossy
Delay relative to video     : 23ms
Default                     : Yes
Forced                      : No

Text
ID                          : 3
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Default                     : Yes
Forced                      : No
```
Bazarr version 0.7.1
Sonarr version 2.0.0.5301
Radarr version 0.2.0.1293
Operating system Windows-10-10.0.14393
Python version 2.7.15
Bazarr directory c:\windows\system32
Bazarr config directory c:\bazarr\data

**Comment by morpheus65535** [comment]
Could that be related to HEVC file? Enzyme (developed by Diaoul and on which we rely for embedded subtitles) haven't evolve since 2015 and EBML have continue to evolve. Can you try to find the common pattern between those files?

**Comment by Zixim** [comment]
There is just 1 single file that throws the error, so I can't really find a common factor between 1 file 😉 
The other files, which do not throw errors but are encoded in the same way, are also created using HEVC.

I'm thinking I'll just replace or re-encode the file, failin ghtat, I'll live with the error.
If yo like, i have no issue sharing the offending file with you.

**Comment by morpheus65535** [comment]
Ok, I was under the impression that you had many files like this.

I had one like this myself and when I tried to open it in VLC, it didn't worked. I've just downloaded another version of the episode and it fixed my issue.
