### ISSUE TITLE
Insufficient data to process the guess

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#34]
I came across this error when executing Download wanted subtitles:

```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://0.0.0.0:6767/wanted_search_missing_subtitles' caused an error:

Internal Server Error
Exception:

ValueError('Insufficient data to process the guess',)
Traceback:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr.py", line 277, in wanted_search_missing_subtitles_list
    wanted_search_missing_subtitles()
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 108, in wanted_search_missing_subtitles
    wanted_download_subtitles(episode[0])
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 92, in wanted_download_subtitles
    message = download_subtitle(path_replace(episode[0]), str(pycountry.languages.lookup(language).alpha_3), episode[4], providers_list, providers_auth)
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 19, in download_subtitle
    video = scan_video(path)
  File "/Library/Python/2.7/site-packages/subliminal/core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "/Library/Python/2.7/site-packages/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
  File "/Library/Python/2.7/site-packages/subliminal/video.py", line 166, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
```

**Comment by morpheus65535** [comment]
Do you have an idea which file this error report to?

**Comment by stefandevo** [comment]
No. I have more than 500 files without subs and tried this on the wanted screen. Suggestion to add extra logging?

**Comment by morpheus65535** [comment]
Hehe. Not a bad idea... :-)

**Comment by morpheus65535** [comment]
Should help us pinpoint the problematic file. I've merged it to master.

**Comment by stefandevo** [comment]
Pls find the new logs with this message in + included one mkv related to the error. Furthermore the procedure stopped with a new error (included in the logs). Thanks.
https://we.tl/0A8NVhLfhc

**Comment by morpheus65535** [comment]
Guessit, the library used by Subliminal to identify files, recognize "The Night Of" as a movie, not a tv series... strange...

If you move those episodes one level up directly in "The Night Of" directory, it's working perfectly.

Don't know if it worth opening a bug with guessit developer...

**Comment by stefandevo** [comment]
I did some renaming of the files. They had .part1 and .part2 (and so on), changed this to S01E01 and then this error got away.

**Comment by morpheus65535** [comment]
Ok, I’ll keep this one in mind in case someone else got the same problem. 

BTW: thanks for your help debugging Bazarr. :-)

**Comment by stefandevo** [comment]
And thank you for this prog!
