### ISSUE TITLE
TypeError('expected string or buffer',)

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#35]
I get following error:
(maybe you can add some extra logging here?)

```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://0.0.0.0:6767/wanted_search_missing_subtitles' caused an error:

Internal Server Error
Exception:

TypeError('expected string or buffer',)
Traceback:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr.py", line 281, in wanted_search_missing_subtitles_list
    wanted_search_missing_subtitles()
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 113, in wanted_search_missing_subtitles
    wanted_download_subtitles(episode[0])
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 97, in wanted_download_subtitles
    message = download_subtitle(path_replace(episode[0]), str(pycountry.languages.lookup(language).alpha_3), episode[4], providers_list, providers_auth)
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 25, in download_subtitle
    best_subtitles = download_best_subtitles([video], {Language(language)}, providers=providers, hearing_impaired=hi, provider_configs=providers_auth)
  File "/Library/Python/2.7/site-packages/subliminal/core.py", line 647, in download_best_subtitles
    compute_score=compute_score)
  File "/Library/Python/2.7/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/Library/Python/2.7/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/Library/Python/2.7/site-packages/subliminal/providers/opensubtitles.py", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/Library/Python/2.7/site-packages/subliminal/subtitle.py", line 202, in guess_matches
    if video.series and 'title' in guess and sanitize(guess['title']) == sanitize(video.series):
  File "/Library/Python/2.7/site-packages/subliminal/utils.py", line 111, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by morpheus65535** [comment]
I've added better logging in 9328c4f1408ed50803b3913858b7abba801f1c74.

Report back after updating and restarting bazarr.

**Comment by stefandevo** [comment]
After updating the sources I now immediately get:

```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://0.0.0.0:6767/wanted_search_missing_subtitles' caused an error:

Internal Server Error
Exception:

IndexError('list index out of range',)
Traceback:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr.py", line 281, in wanted_search_missing_subtitles_list
    wanted_search_missing_subtitles()
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 115, in wanted_search_missing_subtitles
    wanted_download_subtitles(episode[0])
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 99, in wanted_download_subtitles
    message = download_subtitle(path_replace(episode[0]), str(pycountry.languages.lookup(language).alpha_3), episode[4], providers_list, providers_auth)
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 31, in download_subtitle
    best_subtitle = best_subtitles[video][0]
IndexError: list index out of range
```

**Comment by morpheus65535** [comment]
Should be working now: e8a8c2501a4fd055ea771d358f9f8af1e32ae487

Retry please.

**Comment by stefandevo** [comment]
Thanks.

Issue is:
```
Error trying to best subtitles for this file: /Volumes/plex2/Plex/Series/You Me Her/Season 1/S01E04.mkv
Traceback (most recent call last):
  File "/Users/USER/bazarr/bazarr/get_subtitle.py", line 26, in download_subtitle
    best_subtitles = download_best_subtitles([video], {Language(language)}, providers=providers, hearing_impaired=hi, provider_configs=providers_auth)
  File "/Library/Python/2.7/site-packages/subliminal/core.py", line 647, in download_best_subtitles
    compute_score=compute_score)
  File "/Library/Python/2.7/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/Library/Python/2.7/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/Library/Python/2.7/site-packages/subliminal/providers/opensubtitles.py", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/Library/Python/2.7/site-packages/subliminal/subtitle.py", line 202, in guess_matches
    if video.series and 'title' in guess and sanitize(guess['title']) == sanitize(video.series):
  File "/Library/Python/2.7/site-packages/subliminal/utils.py", line 111, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

File just contained `S01E04.mkv`; once I renamed this to `Series.S01E04.mkv` the error went away.

**Comment by morpheus65535** [comment]
guessit doesn't seems to like renamed episode. It need something to identify the file.

I guess your best bet is to rename those problematic episodes.
