### ISSUE TITLE
Show errors in providers al INFO level

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#354]
I have several subtitle providers configured. For me will be very useful to show in the login window (at INFO level) if some provider is not working. I can see it if I enable the DEBUG mode, but I think this is important, should be visible by default.
Maybe you can add some "Test" button, like in Sonarr and Radarr.

```
Mar 19 20:23:58 XXXX bazarr[396]: 2019-03-19 20:23:58,199 - urllib3.connectionpool           (7f888b91f0) :  DEBUG (connectionpool:393) - http://www.addic7ed.com:80 "POST /dologin.php HTTP/1.1" 301 178
Mar 19 20:23:58 XXXX bazarr[396]: 2019-03-19 20:23:58,205 - subliminal_patch.core            (7f888b91f0) :  ERROR (core:194) - Unexpected error in provider 'addic7ed': Traceback (most recent call last):
Mar 19 20:23:58 XXXX bazarr[396]:   File "/root/scripts/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider
Mar 19 20:23:58 XXXX bazarr[396]:     results = self[provider].list_subtitles(video, provider_languages)
Mar 19 20:23:58 XXXX bazarr[396]:   File "/root/scripts/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__
Mar 19 20:23:58 XXXX bazarr[396]:     provider.initialize()
Mar 19 20:23:58 XXXX bazarr[396]:   File "/root/scripts/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 110, in initialize
Mar 19 20:23:58 XXXX bazarr[396]:     raise AuthenticationError(self.username)
Mar 19 20:23:58 XXXX bazarr[396]: AuthenticationError: XXXX
Mar 19 20:23:58 XXXX bazarr[396]: Traceback (most recent call last):
Mar 19 20:23:58 XXXX bazarr[396]:   File "/root/scripts/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider
Mar 19 20:23:58 XXXX bazarr[396]:     results = self[provider].list_subtitles(video, provider_languages)
Mar 19 20:23:58 XXXX bazarr[396]:   File "/root/scripts/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__
Mar 19 20:23:58 XXXX bazarr[396]:     provider.initialize()
Mar 19 20:23:58 XXXX bazarr[396]:   File "/root/scripts/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 110, in initialize
Mar 19 20:23:58 XXXX bazarr[396]:     raise AuthenticationError(self.username)
Mar 19 20:23:58 XXXX bazarr[396]: AuthenticationError: XXXXX
Mar 19 20:23:58 XXXX bazarr[396]: 2019-03-19 20:23:58,207 - subliminal_patch.core            (7fa8141bd0) :  INFO (core:456) - Discarding provider addic7ed
```

**Comment by halali** [comment]
I dont think this is good idea.

subliminal and subliminal_patch are too much verbose in INFO level... also ERROR level give too much output.
