### ISSUE TITLE
Not showing Movies history anymore

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#368]
**Describe the bug**
When clicking on the tab Movies in History, nothing appears anymore, but there are some errors in the log.

```
Traceback (most recent call last):
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr/main.py", line 136, in wrapper
    return func(*a, **ka)
  File "bazarr/main.py", line 1076, in historymovies
    current_port=settings.general.port, upgradable_movies=upgradable_movies_not_perfect)
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/Users/USER/bazarr/bazarr/views/historymovies.tpl", line 90, in <module>
    % if row[7] in ast.literal_eval(str(row[6])):
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr/main.py", line 136, in wrapper
    return func(*a, **ka)
  File "bazarr/main.py", line 1076, in historymovies
    current_port=settings.general.port, upgradable_movies=upgradable_movies_not_perfect)
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/Users/USER/bazarr/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/Users/USER/bazarr/bazarr/views/historymovies.tpl", line 90, in <module>
    % if row[7] in ast.literal_eval(str(row[6])):
TypeError: argument of type 'NoneType' is not iterable
```

I am on the latest DEV version.0.7.3

**Comment by morpheus65535** [comment]
Can you update your Bazarr from dev branch and confirm if the fix is doing the job?

**Comment by stefandevo** [comment]
Cool! Working again. Thanks!!!!!
