### ISSUE TITLE
Bazarr won't start anymore on my Synology running in virtual python environment

### ISSUE THREAD

**Issue by schumi2004** [morpheus65535/bazarr#369]
**Describe the bug**
When i launch Bazarr using python bazarr.py it throws errors
It was running untill i killed the process for a restart of the Synology nas (DS715 running DSM6.2)

**To Reproduce**
Launch Bazarr using:
python bazarr.py

**Expected behavior**
A running app with minimal errors that can be ignored

**Software (please complete the following information):**
 - Bazarr: Latest master git as of today (27-3)

**Additional context**
root@DS715:/volume1/@appstore/virtualenv/bazarr# python bazarr.py 
Bazarr starting...
Traceback (most recent call last):
  File "bazarr/main.py", line 23, in <module>
    from update_db import *
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/update_db.py", line 7, in <module>
    from scheduler import execute_now
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/scheduler.py", line 3, in <module>
    from get_episodes import sync_episodes, update_all_episodes, update_all_movies
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/get_episodes.py", line 12, in <module>
    from list_subtitles import list_missing_subtitles, store_subtitles, series_full_scan_subtitles, \
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/list_subtitles.py", line 12, in <module>
    import subliminal_patch
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/subliminal_patch/__init__.py", line 7, in <module>
    from .providers import Provider
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/subliminal_patch/providers/__init__.py", line 8, in <module>
    from subliminal_patch.extensions import provider_registry
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/subliminal_patch/extensions.py", line 62, in <module>
    subliminal.refiner_manager.register('drone = subliminal_patch.refiners.drone:refine')
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/subliminal/extensions.py", line 64, in register
    ext = self._load_one_plugin(ep, False, (), {}, False)
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/stevedore/extension.py", line 203, in _load_one_plugin
    plugin = ep.resolve()
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/subliminal_patch/refiners/drone.py", line 11, in <module>
    from subliminal_patch.core import remove_crap_from_fn
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/subliminal_patch/core.py", line 34, in <module>
    from scandir import scandir, scandir_generic as _scandir_generic
  File "/volume1/@appstore/virtualenv/bazarr/bazarr/../libs/scandir.py", line 435, in <module>
    libc = ctypes.CDLL(ctypes.util.find_library('c'), use_errno=True)
  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library c

**Comment by morpheus65535** [comment]
Duplicate from #299.
