### ISSUE TITLE
BAZARR Error trying to get video information for this file

### ISSUE THREAD

**Issue by thierrybla** [morpheus65535/bazarr#374]
**Describe the bug**
No subtitles are being downloaded and I get this error in the log.

Error:

`Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/get_subtitle.py", line 65, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=dont_use_actual_file)
 File "/usr/local/bazarr/bazarr/../libs/subzero/video.py", line 58, in parse_video
  skip_hashing=skip_hashing)
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 522, in scan_video
  video = Video.fromguess(path, guessed_result)
 File "/usr/local/bazarr/bazarr/../libs/subliminal/video.py", line 93, in fromguess
  return Episode.fromguess(name, guess)
 File "/usr/local/bazarr/bazarr/../libs/subliminal/video.py", line 170, in fromguess
  raise ValueError(\Insufficient data to process the guess\)
ValueError: Insufficient data to process the guess`

Ill also upload the complete log.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3026253/bazarr.log)

**Comment by thierrybla** [comment]
Solved this issue by including more info in the file name (such as series name).
