### ISSUE TITLE
GuessitException: An internal error has occured in guessit

### ISSUE THREAD

**Issue by pven** [morpheus65535/bazarr#408]
This just popped up in the logging, it looks like it happened during one of the automatic jobs (I did not trigger it manually). Should I do anything with it, or just ignore it?

```
23/04/2019 09:32:26|ERROR   |root                            |BAZARR Error trying to get video information for this file: /volume1/remote/media/TV/NiceSerie/Season 02/NiceSerie-S02E04.(2019).Corleone.mkv|'Traceback (most recent call last):\n  File "/volume1/@appstore/bazarr/bazarr/get_subtitle.py", line 63, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=dont_use_actual_file)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/subzero/video.py", line 58, in parse_video\n    skip_hashing=skip_hashing)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/subliminal_patch/core.py", line 520, in scan_video\n    guessed_result = guessit(guess_from, options=hints)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/guessit/api.py", line 54, in guessit\n    return default_api.guessit(string, options)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/guessit/api.py", line 132, in guessit\n    raise GuessitException(string, options)\nGuessitException: An internal error has occured in guessit.\n===================== Guessit Exception Report =====================\nversion=2.1.4\nstring=NiceSerie/Season 02/NiceSerie-S02E04.(2019).Corleone.mkv\noptions={\'type\': \'episode\', \'expected_title\': [\'NiceSerie\'], \'single_value\': True, \'title\': \'NiceSerie\'}\n--------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/volume1/@appstore/bazarr/bazarr/../libs/guessit/api.py", line 120, in guessit\n    matches = self.rebulk.matches(string, options)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rebulk.py", line 288, in matches\n    self._execute_rules(matches, context)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rebulk.py", line 319, in _execute_rules\n    rules.execute_all_rules(matches, context)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 318, in execute_all_rules\n    when_response = execute_rule(rule, matches, context)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 343, in execute_rule\n    rule.then(matches, when_response, context)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 122, in then\n    cons.then(matches, next(iterator), context)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 206, in then\n    removed = self.remove.then(matches, when_response, context)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 140, in then\n    matches.remove(match)\n  File "/usr/lib/python2.7/_abcoll.py", line 689, in remove\n    del self[self.index(value)]\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/match.py", line 565, in __delitem__\n    self._remove_match(match)\n  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/match.py", line 133, in _remove_match\n    _BaseMatches._base_remove(self._tag_dict[tag], match)\nValueError: list.remove(x): x not in list\n--------------------------------------------------------------------\nPlease report at https://github.com/guessit-io/guessit/issues.\n===================================================================='|
```

I am using Bazarr Ver. 0.7.3

**Comment by halali** [comment]
This error is becouse you rename your episodes to format guessit is not able to read...

**Comment by pven** [comment]
SABnzbd is renaming them, I don't do it manually. But why is it a problem? It looks like it works for almost all my other files.

**Comment by morpheus65535** [comment]
I've opened an issue on GuessIt Github: https://github.com/guessit-io/guessit/issues/600

**Comment by morpheus65535** [comment]
@pannal as we don't plan to move to GuessIt 3.x, could you please take a look at this issue and see how we can address it in subliminal_patch? Thanks.

**Comment by pannal** [comment]
I can't reproduce this. I'll need the original filename:

```
PYTHONPATH="${PYTHONPATH}:." python guessit/__main__.py "NiceSerie-S02E04.(2019).Corleone.mkv"
For: NiceSerie-S02E04.(2019).Corleone.mkv
GuessIt found: {
    "title": "NiceSerie",
    "season": 2,
    "episode": 4,
    "year": 2019,
    "episode_title": "Corleone",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

**Comment by brunosaragiotto** [comment]
i also have this problem
`Traceback (most recent call last):
 File "C:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 63, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=dont_use_actual_file)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video
  skip_hashing=skip_hashing)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 525, in scan_video
  guessed_result = guessit(guess_from, options=hints)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/guessit\\api.py", line 54, in guessit
  return default_api.guessit(string, options)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/guessit\\api.py", line 132, in guessit
  raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.4
string=Game Of Thrones\\Game of Thrones 2011 Season 5 S05 (1080p Bluray x265 HEVC 10bit AAC 7.1 Tigole)\\Game of Thrones S05E09 The Dance of Dragons (1080p x265 10bit Tigole).mkv
options={\type\: \episode\, \expected_title\: [\Game of Thrones\], \single_value\: True, \title\: \Game of Thrones\}
--------------------------------------------------------------------
Traceback (most recent call last):
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/guessit\\api.py", line 120, in guessit
  matches = self.rebulk.matches(string, options)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\rebulk.py", line 288, in matches
  self._execute_rules(matches, context)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\rebulk.py", line 319, in _execute_rules
  rules.execute_all_rules(matches, context)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\rules.py", line 318, in execute_all_rules
  when_response = execute_rule(rule, matches, context)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\rules.py", line 343, in execute_rule
  rule.then(matches, when_response, context)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\rules.py", line 122, in then
  cons.then(matches, next(iterator), context)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\rules.py", line 206, in then
  removed = self.remove.then(matches, when_response, context)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\rules.py", line 140, in then
  matches.remove(match)
 File "C:\\Python27\\lib\\_abcoll.py", line 689, in remove
  del self[self.index(value)]
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\match.py", line 565, in __delitem__
  self._remove_match(match)
 File "C:\\bazarr\\bazarr\\bazarr\\../libs/rebulk\\match.py", line 133, in _remove_match
  _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
`
Also have problem with anothers series:
GuessitException: An internal error has occured in guessit.
`
===================== Guessit Exception Report =====================
version=2.1.4
string=Parks and Recreation (2009) Season 1-7 S01-S07 (1080p AMZN WEBRip x265 HEVC 10bit AAC 5.1 Silence)\\Season 5\\Parks and Recreation (2009) - S05E19 - Article Two (1080p AMZN WEBRip x265 Silence).mkv
options={\type\: \episode\, \expected_title\: [\Parks and Recreation\], \single_value\: True, \title\: \Parks and Recreation\
`
`===================== Guessit Exception Report =====================
version=2.1.4
string=S\xc3\xa9ries\\Chuck (2007) Season 01-05 S01-05 (1080p BluRay x265 HEVC AAC 5.1 ByteShare) [UTR]\\S05 E04 - Chuck Versus the Business Trip.mkv
options={\type\: \episode\, \expected_title\: [\Chuck\], \single_value\: True, \title\: \Chuck\}
`

**Comment by morpheus65535** [comment]
Is this still an issue?

**Comment by morpheus65535** [comment]
@pven @brunosaragiotto I've update guessit in dev branch. You can test it and report please?

**Comment by pven** [comment]
I try, but it will take some time.
