### ISSUE TITLE
Error when start bazarr

### ISSUE THREAD

**Issue by pantadanillo** [morpheus65535/bazarr#411]
C:\bazarr>python bazarr.py
Bazarr starting...
2019-04-24 08:11:30,591 - root                             (1010) :  INFO (main:2039) - BAZARR is started and waiting for request on http://192.168.0.187:6767/
Traceback (most recent call last):
  File "bazarr\main.py", line 2040, in <module>
    server.serve_forever()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 367, in serve_forever
    self.start()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 305, in start
    self.init_socket()
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 1490, in init_socket
    StreamServer.init_socket(self)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 256, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
socket.error: [Errno 10049] The requested address is not valid in its context: ('192.168.0.187', 6767)

**Comment by morpheus65535** [comment]
Python is unable to bind to this IP. It is probably not the good IP (not available on any network interface).
