### ISSUE TITLE
No Information on History Page for Series or Movies

### ISSUE THREAD

**Issue by kanine** [morpheus65535/bazarr#415]
Both Movies and Series history are not showing any information at the moment.

Running on 0.7.3 Master Branch / Windows / Python 2.7

When clicking on the Series or Movies tab the following error appears in the console:

**Series**
`Traceback (most recent call last):
  File "d:\apps\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "d:\apps\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "d:\apps\bazarr\bazarr\main.py", line 137, in wrapper
    return func(*a, **ka)
  File "d:\apps\bazarr\bazarr\main.py", line 1006, in historyseries
    current_port=settings.general.port, upgradable_episodes=upgradable_episodes_not_perfect)
UnboundLocalError: local variable 'upgradable_episodes_not_perfect' referenced before assignment`

**Movies**
`Traceback (most recent call last):
  File "d:\apps\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "d:\apps\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "d:\apps\bazarr\bazarr\main.py", line 137, in wrapper
    return func(*a, **ka)
  File "d:\apps\bazarr\bazarr\main.py", line 1077, in historymovies
    current_port=settings.general.port, upgradable_movies=upgradable_movies_not_perfect)
UnboundLocalError: local variable 'upgradable_movies_not_perfect' referenced before assignment`

**Comment by morpheus65535** [comment]
You have upgrade subtitles disabled. Can you try dev branch where I've made a fix for that?

**Comment by kanine** [comment]
Thanks, and the development update looks fine to clear the error.
