### ISSUE TITLE
FormatAutodetectionError when doing manual download

### ISSUE THREAD

**Issue by mehdi198080** [morpheus65535/bazarr#433]
Couldn't convert subtitle to .srt format: 

```
Traceback (most recent call last): 
  File "/opt/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 242, in is_valid 
    subs = pysubs2.SSAFile.from_string(text) 
  File "/opt/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 118, in from_string 
    return cls.from_file(fp, format_, fps=fps, **kwargs) 
  File "/opt/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 145, in from_file 
    format_ = autodetect_format(fragment) 
  File "/opt/bazarr/bazarr/../libs/pysubs2/formats.py", line 64, in autodetect_format 
    raise FormatAutodetectionError("No suitable formats")
FormatAutodetectionError: No suitable formats
```

**Comment by morpheus65535** [comment]
Can you provide the link to the subtitle causing this issue?

**Comment by mehdi198080** [comment]
https://subscene.com/subtitles/barry-second-season/farsi_persian/1984291

**Comment by morpheus65535** [comment]
@pannal Why is this exception raised when the file is clearly a valid .srt file?

**Comment by pannal** [comment]
I'll investigate

**Comment by pannal** [comment]
This should be fixed in latest bzr-dev.

**Comment by morpheus65535** [comment]
@mehdi198080 Please test and report.

**Comment by mehdi198080** [comment]
the bug fixed 
thank you very much
