### ISSUE TITLE
Cannot run in docker

### ISSUE THREAD

**Issue by dimitrov-adrian** [morpheus65535/bazarr#49]
I am trying to run in docker, but got an error. Tried both variants, repo from morpheus65535/bazarr and building image. In both cases, the error is the sme.
```

/usr/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/backports': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
Traceback (most recent call last):
  File "/bazarr/bazarr.py", line 30, in <module>
    from update_db import *
  File "/bazarr/update_db.py", line 58, in <module>
    from scheduler import execute_now
  File "/bazarr/scheduler.py", line 3, in <module>
    from get_episodes import *
  File "/bazarr/get_episodes.py", line 7, in <module>
    from list_subtitles import *
  File "/bazarr/list_subtitles.py", line 8, in <module>
    import langdetect
ImportError: No module named langdetect
[cmd] python exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by morpheus65535** [comment]
My bad, I forgot to add latest required module in requirements.txt. I'm building the docker image now and you should be able to pull the new one in 10 minutes. Thanks to bring this to my knowledge! Please report back after testing it.

**Comment by dimitrov-adrian** [comment]
Seems to works, but only if set timezone ( -e TZ=<timezone>) without it, give error
```
/usr/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/backports': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
Traceback (most recent call last):
  File "/bazarr/bazarr.py", line 30, in <module>
    from update_db import *
  File "/bazarr/update_db.py", line 58, in <module>
    from scheduler import execute_now
  File "/bazarr/scheduler.py", line 13, in <module>
    scheduler.add_job(check_and_apply_update, 'interval', hours=6, max_instances=1, coalesce=True, misfire_grace_time=15, id='update_bazarr', name='Update bazarr from source on Github')
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 413, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 907, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 892, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/lib/python2.7/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/lib/python2.7/site-packages/apscheduler/util.py", line 86, in astimezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).
```


Also in both cases give the warning

```
/usr/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/backports': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
```

**Comment by morpheus65535** [comment]
Regarding the TZ that is required, I'm going to look into doing a fallback to UTC if no timezone data is available from OS.

The ImportWarning is only a warning and don't cause any problem. I'm aware of this one and it doesn't seems like something I can resolve. It come from a problematic module that is required by Bazarr. If you know how to get rid of it, I'll be happy to correct it! :-)

Thanks!

**Comment by morpheus65535** [comment]
I've add a validation about timezone data. If nothing is available from OS, scheduler fallback to UTC. I,ve merged it to master and build a new docker image. You can pull it and try it. Report back please.

**Comment by morpheus65535** [comment]
Can you please report if it's working as expected so I can close the issue? Thanks.

**Comment by dimitrov-adrian** [comment]
Yeah, It's working now. I just have problems to deal with Synology container station because would like to run it on my NAS and get some troubles with the permissions to storing the subtitles.

**Comment by morpheus65535** [comment]
Have you taken a look at PGID and PUID environment variable when creating the container?
