### ISSUE TITLE
[Feature request] Support for radarr aphrodite

### ISSUE THREAD

**Issue by h2xtreme** [morpheus65535/bazarr#505]
Radarr aphrodite is the branch with the new UI (similar to Sonarr v3). Right now bazarr isn't able to retrieve the movie list from it.

I know that aphrodite is in early stages so I'm just leaving this here to whenever you have the time to look at this. :)

if it helps the error is:

`06/08/2019 12:28:24|ERROR   |apscheduler.executors.default   |Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2019-08-06 12:33:24 WEST)" raised an exception|'Traceback (most recent call last):\n  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/opt/bazarr/bazarr/get_movies.py", line 27, in update_movies\n    get_profile_list()\n  File "/opt/bazarr/bazarr/get_movies.py", line 222, in get_profile_list\n    profiles_list.append([profile[\'id\'], profile[\'language\'].capitalize()])\nAttributeError: \'dict\' object has no attribute \'capitalize\''|`

**Comment by morpheus65535** [comment]
We already have discussed with Radar devs and the API is subject to many change so we are waiting until it get stable before looking into this.
