### ISSUE TITLE
Addic7ed and Anti Captcha

### ISSUE THREAD

**Issue by faulander** [morpheus65535/bazarr#516]
**Describe the bug**
Login seems to not work, get an error in the logs.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.7.5.1
 - Sonarr version 2.0.0.5322
 - OS: Docker, Linux-4.9.0-8-amd64-x86_64-with

**Additional context**
Logfile Except:
14/08/2019 19:51:25|DEBUG   |root                            |BAZARR is using those video object properties: {'series': u'Lorena', 'original_path': u'/tv/Lorena/Season 1/Lorena.S01E03.An.Irresistible.Impulse.WEBDL-720p.mkv', 'series_imdb_id': None, 'audio_codec': u'EAC3', 'year': 2019, 'size': None, 'title': u'An Irresistible Impulse', 'original_name': u'Lorena.S01E03.An.Irresistible.Impulse.WEBDL-720p.mkv', 'release_group': u'iNSiDiOUS', 'original_series': True, 'plexapi_metadata': {}, 'format': u'WEB-DL', 'season': 1, 'tvdb_id': None, 'imdb_id': None, 'external_subtitle_languages': set([]), 'series_tvdb_id': 357880, 'hashes': {}, 'hints': {'type': 'episode', 'expected_title': [u'Lorena'], 'single_value': True, 'title': u'Lorena'}, 'episode': 3, 'name': u'/tv/Lorena/Season 1/Lorena.S01E03.720p.WEB.H264-iNSiDiOUS[eztv].mkv', 'subtitle_languages': set([]), 'used_scene_name': True, 'alternative_series': [], 'audio_languages': set([]), 'video_codec': u'h264', 'resolution': u'720p'}|
14/08/2019 19:51:25|INFO    |subliminal_patch.core           |Using 1 threads for 1 providers (['addic7ed'])|
14/08/2019 19:51:25|INFO    |subliminal_patch.core           |Downloading best subtitles for <Episode [u'Lorena', 2019, 1x3]>|
14/08/2019 19:51:25|INFO    |subliminal_patch.core           |Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])|
14/08/2019 19:51:25|INFO    |subliminal_patch.core           |Initializing provider addic7ed|
14/08/2019 19:51:25|DEBUG   |subliminal_patch.providers.addic7ed|Addic7ed: using random user agents|
14/08/2019 19:51:25|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Logging in|
14/08/2019 19:51:25|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.addic7ed.com:443|
14/08/2019 19:51:25|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.addic7ed.com|
14/08/2019 19:51:25|DEBUG   |urllib3.connectionpool          |https://www.addic7ed.com:443 "GET /login.php HTTP/1.1" 200 None|
14/08/2019 19:51:25|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Solving captcha. This might take a couple of minutes, but should only happen once every so often|
14/08/2019 19:51:25|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.anti-captcha.com:443|
14/08/2019 19:51:25|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.anti-captcha.com|
14/08/2019 19:51:25|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /createTask HTTP/1.1" 200 None|
14/08/2019 19:51:29|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 19:51:36|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 19:51:39|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 19:51:39|INFO    |subliminal_patch.pitcher        |Addic7ed: Solving took 14s|
14/08/2019 19:51:39|DEBUG   |urllib3.connectionpool          |https://www.addic7ed.com:443 "POST /dologin.php HTTP/1.1" 200 None|
14/08/2019 19:51:39|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Error, trying again. (1/3)|
14/08/2019 19:51:39|DEBUG   |urllib3.connectionpool          |https://www.addic7ed.com:443 "GET /login.php HTTP/1.1" 200 None|
14/08/2019 19:51:39|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Solving captcha. This might take a couple of minutes, but should only happen once every so often|
14/08/2019 19:51:39|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.anti-captcha.com:443|
14/08/2019 19:51:39|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.anti-captcha.com|
14/08/2019 19:51:40|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /createTask HTTP/1.1" 200 None|
14/08/2019 19:51:43|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 19:51:49|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 19:51:52|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 19:51:52|INFO    |subliminal_patch.pitcher        |Addic7ed: Solving took 13s|
14/08/2019 19:51:52|DEBUG   |urllib3.connectionpool          |https://www.addic7ed.com:443 "POST /dologin.php HTTP/1.1" 200 None|
14/08/2019 19:51:52|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed': Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 138, in initialize    raise AuthenticationError(self.username)AuthenticationError: KoopaOne|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 138, in initialize    raise AuthenticationError(self.username)AuthenticationError: KoopaOne|
14/08/2019 19:51:52|INFO    |subliminal_patch.core           |Discarding provider addic7ed|
14/08/2019 19:51:52|INFO    |subliminal_patch.core           |Downloaded 0 subtitle(s)|
14/08/2019 19:51:52|DEBUG   |subliminal.core                 |Terminating initialized providers|

**Comment by morpheus65535** [comment]
Did you set your username and password for Addic7ed in settings?

**Comment by faulander** [comment]
sure, i did. if you check the logs, you can see my username in there.

**Comment by morpheus65535** [comment]
Then you probably have misstyped your password or have a password with strange characters that are not stored correctly or not sent correclty. You can look in config.ini file where it will stored in clear text.

**Comment by faulander** [comment]
re-entered it. it's a very simple password. still doesn't work it seems.

**Comment by morpheus65535** [comment]
It’s working as expected for me. Same anti-captcha provider, same subtitles provider. Look at your config.ini file.

You can come to Discord for live support.

**Comment by faulander** [comment]
Username and Password for Addic7ted are correct.
Just copy & pasted it into addi7ed website, directly from the config.ini

**Comment by faulander** [comment]
still get the same error:

14/08/2019 21:38:14|INFO    |apscheduler.executors.default   |Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-08-14 21:39:13 CEST)" executed successfully|
14/08/2019 21:38:14|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 21:38:22|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 21:38:25|DEBUG   |urllib3.connectionpool          |https://api.anti-captcha.com:443 "POST /getTaskResult HTTP/1.1" 200 None|
14/08/2019 21:38:25|INFO    |subliminal_patch.pitcher        |Addic7ed: Solving took 16s|
14/08/2019 21:38:25|DEBUG   |urllib3.connectionpool          |https://www.addic7ed.com:443 "POST /dologin.php HTTP/1.1" 200 None|
14/08/2019 21:38:25|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed': Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 138, in initialize    raise AuthenticationError(self.username)AuthenticationError: KoopaOne|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 138, in initialize    raise AuthenticationError(self.username)AuthenticationError: KoopaOne|
14/08/2019 21:38:25|INFO    |subliminal_patch.core           |Discarding provider addic7ed|

**Comment by morpheus65535** [comment]
I've created a new account on Addic7ed with a username containing mixed case. I've tested it with Bazarr but I still can't reproduce your issue... I'm kinda lost if I cannot reproduce your issue... :-/
