### ISSUE TITLE
Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by Longshot** [morpheus65535/bazarr#520]
**Describe the bug**
Woke up this morning with an internal server error
**To Reproduce**
1. Going to 'http://192.168.2.155:6767/series' caused an error:

IndexError('tuple index out of range',)

**Software (please complete the following information):**
 - Bazarr: Don't now probably latest version?
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: Ubuntu 18.04 server

**Additional context**
```
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/bazarr/bazarr/main.py", line 139, in wrapper
    return func(*a, **ka)
  File "/opt/bazarr/bazarr/main.py", line 571, in series
    "SELECT table_shows.sonarrSeriesId, COUNT(table_episodes.missing_subtitles) FROM table_shows LEFT JOIN table_episodes ON table_shows.sonarrSeriesId=table_episodes.sonarrSeriesId WHERE table_shows.languages IS NOT 'None'" + monitored_only_query_string + " GROUP BY table_shows.sonarrSeriesId")
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/opt/bazarr/views/series.tpl", line 99, in <module>
    <td>{{row[8]}}</td>
IndexError: tuple index out of range
```

**Comment by morpheus65535** [comment]
Did you try to restart Bazarr? I guess there’s been an update where template were updated but need a restart.

**Comment by Longshot** [comment]
Yes, after restarting bazarr it came back without errors.
I should have tried that before opening an issue.
I will disable automatic update installation for now.

**Comment by morpheus65535** [comment]
You can let it enable but also enable auto restart after update.
