### ISSUE TITLE
AttributeError("'NoneType' object has no attribute 'sort'",)

### ISSUE THREAD

**Issue by pinkstrings** [morpheus65535/bazarr#538]
**Describe the bug**
Internal Server error when attempting to view Movie

**To Reproduce**
Open Movie link.

**Expected behavior**
Movie information page to be displayed.

**Software**
 - Bazarr: 0.8.2
 - OS: Docker (linuxserver/bazarr:development image)
- Python: 2.7.16

**Additional context**
This occurred right after adding a lot of movies -- I believe it's happening because the item was added, and I'm trying to view it before the scan is complete. May cause issues down the line?

```
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 128, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 1065, in movie
    current_port=settings.general.port)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/app/bazarr/views/movie.tpl", line 173, in <module>
    subtitles_files.sort()
AttributeError: 'NoneType' object has no attribute 'sort'
```

**Comment by morpheus65535** [comment]
Shouldn't be an issue anymore in 0.8.2.
