### ISSUE TITLE
Search for wanted subtitles raise None is not a valid language

### ISSUE THREAD

**Issue by r2range** [morpheus65535/bazarr#540]
**Describe the bug**
Delog Log :

Job "Search for wanted subtitles (trigger: interval[3:00:00], next run at: 2019-09-14 15:06:50 CEST)" raised an exception
 ```
Traceback (most recent call last): File "c:\program files (x86)\bazarr\bazarr\../libs/apscheduler\executors\base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) File "c:\program files (x86)\bazarr\bazarr\get_subtitle.py", line 850, in wanted_search_missing_subtitles wanted_download_subtitles(episode[0], i, count_episodes) File "c:\program files (x86)\bazarr\bazarr\get_subtitle.py", line 742, in wanted_download_subtitles series) File "c:\program files (x86)\bazarr\bazarr\get_subtitle.py", line 138, in download_subtitle lang_obj = Language(l) File "c:\program files (x86)\bazarr\bazarr\../libs/subzero\language.py", line 75, in __init__ super(Language, self).__init__(language, country=country, script=script, unknown=unknown) File "c:\program files (x86)\bazarr\bazarr\../libs/babelfish\language.py", line 81, in __init__ raise ValueError(%r is not a valid language % language)ValueError: None is not a valid language
```

**To Reproduce**
Searched for subtitle's 

**Software (please complete the following information):**
 - Bazarr: 0.8.1
 - Radarr version 2.0.0.5338
 - Sonarr version 0.2.0.1358
 - OS: Server 2016 - 1809

**Additional context**

**Comment by morpheus65535** [comment]
What language are your trying to search for?

**Comment by morpheus65535** [comment]
Closing as no answer.
