### ISSUE TITLE
Opensubtitles not working any more.

### ISSUE THREAD

**Issue by svenvg93** [morpheus65535/bazarr#595]
**Describe the bug**
Since a couple of days Bazarr is unable to find subtitles on OpenSubtitles.org. Found the error below in the debug log

**Expected behavior**

**Screenshots**
`Unexpected error in provider 'opensubtitles': Traceback (most recent call last): File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 239, in list_subtitles also_foreign=self.also_foreign) File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 270, in query lambda: self.retry(lambda: checked(lambda: self.server.SearchSubtitles(self.token, criteria))) File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 160, in use_token_or_login self.log_in() File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 147, in log_in lambda: checked( File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/mixins.py", line 46, in retry return f() File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 148, in lambda: self.server.LogIn(self.username, self.password, 'eng', File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 371, in checked raise UnauthorizedUnauthorized`

**Software (please complete the following information):**
 - Bazarr: 0.8.1
 - OS: Centos7 in Docker  (Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with)

**Comment by svenvg93** [comment]
Nevermind, something was wrong with my OS password in the bazarr config
