### ISSUE TITLE
Error trying to get video information for this file

### ISSUE THREAD

**Issue by altendorfme** [morpheus65535/bazarr#606]
**Describe the bug**

06/10/2019 21:38:08|ERROR   |root                            |BAZARR Error trying to get video information for this file: /media/Storage/TV Shows/XYZ.mkv|'Traceback (most recent call last):\n  File "/opt/Bazarr/bazarr/get_subtitle.py", line 70, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/opt/Bazarr/bazarr/get_subtitle.py", line 951, in refine_from_ffprobe\n    data = parser.parseFfprobe(path)\n  File "/opt/Bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 40, in parseFfprobe\n    fdict = self._executeFfprobe(inputFile)\n  File "/opt/Bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 71, in _executeFfprobe\n    outputJson = self._executeParser(self._ffprobe, commandArgs, inputFile)\n  File "/opt/Bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 184, in _executeParser\n    "Error occurred during execution - " + e.output\nIOError: Error occurred during execution - {\n    "error": {\n        "code": -5,\n        "string": "Input/output error"\n    }\n}\n'|

**To Reproduce**
Click to download subttile

**Software (please complete the following information):**
 - Bazarr: 0.8.1
 - OS: Debian Buster 10

**Comment by altendorfme** [comment]
Sorry, it was a permission issue on the external disk.
