### ISSUE TITLE
Unexpected error in provider LegendasTV

### ISSUE THREAD

**Issue by altendorfme** [morpheus65535/bazarr#607]
**Describe the bug**
Debug log file: [bazarr.log](https://github.com/morpheus65535/bazarr/files/3695341/bazarr.log)

**To Reproduce**
Search subtittle

**Software (please complete the following information):**
 - Bazarr: 0.8.1
- OS: Debian Buster 10

**Comment by morpheus65535** [comment]
Please empty log, enable debug logging and reproduce the issue. Add debug log file to this issue.

**Comment by altendorfme** [comment]
```
06/10/2019 23:35:47|DEBUG   |root                            |Bazarr version: 0.8.1|
06/10/2019 23:35:47|DEBUG   |root                            |Bazarr branch: master|
06/10/2019 23:35:47|DEBUG   |root                            |Operating system: Linux-4.19.0-6-amd64-x86_64-with-debian-10.1|
06/10/2019 23:35:47|DEBUG   |root                            |Python version: 2.7.16|
06/10/2019 23:35:48|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/bazarr/|
06/10/2019 23:36:11|INFO    |apscheduler.scheduler           |Added job "manual_wanted_search_missing_subtitles" to job store "default"|
06/10/2019 23:36:11|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
06/10/2019 23:36:11|INFO    |apscheduler.executors.default   |Running job "manual_wanted_search_missing_subtitles (trigger: date[2019-10-06 23:36:11 -03], next run at: 2019-10-06 23:36:11 -03)" (scheduled at 2019-10-06 23:36:11.553039-03:00)|
06/10/2019 23:36:11|INFO    |apscheduler.scheduler           |Removed job manual_wanted_search_missing_subtitles|
06/10/2019 23:36:11|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2019-10-06 23:36:47.570737-03:00 (in 35.996109 seconds)|
06/10/2019 23:36:11|DEBUG   |root                            |BAZARR Searching subtitles for this file: /media/Storage/TV Shows/Modern Family (2009)/Season 11/Modern Family S11E02 WEBDL-720p.mkv|
06/10/2019 23:36:11|DEBUG   |subzero.video                   |Parsing video: Modern Family S11E02 WEBDL-720p.mkv, hints: {'type': 'episode', 'title': u'Modern Family'}|
06/10/2019 23:36:11|INFO    |subliminal_patch.core           |Determining basic video properties for u'Modern Family S11E02 WEBDL-720p.mkv' in u'/media/Storage/TV Shows/Modern Family (2009)/Season 11'|
06/10/2019 23:36:11|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Modern Family",
    "year": 2009,
    "season": 11,
    "episode": 2,
    "format": "WEB-DL",
    "screen_size": "720p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}|
06/10/2019 23:36:11|DEBUG   |subliminal_patch.core           |Size is 832802483|
06/10/2019 23:36:11|DEBUG   |subliminal_patch.core           |Computed hashes {'opensubtitles': '1cbbbd04b5a3968b'}|
06/10/2019 23:36:11|DEBUG   |root                            |BAZARR FFprobe used is /opt/Bazarr/bin/Linux/x86_64/ffprobe/ffprobe|
06/10/2019 23:36:11|DEBUG   |root                            |FFprobe found: {'bit_rate': 5150675, 'chapters': [], 'videos': [{'format': 'null', 'pixel_format': u'yuv420p', 'framerate': 23.976, 'bit_rate': 0, 'codec': u'h264', 'aspect_ratio': u'16:9', 'resolution': (1280, 720)}], 'duration': 1293.504, 'path': u'/media/Storage/TV Shows/Modern Family (2009)/Season 11/Modern Family S11E02 WEBDL-720p.mkv', 'audios': [{'format': 'null', 'channel_layout': 'null', 'channel_count': 6, 'bit_rate': 0, 'codec': u'eac3', 'sample_rate': 48000}], 'subtitles': [], 'size': 832802483}|
06/10/2019 23:36:11|DEBUG   |root                            |BAZARR is using those video object properties: {'series': u'Modern Family', 'original_path': u'/media/Storage/TV Shows/Modern Family (2009)/Season 11/Modern Family S11E02 WEBDL-720p.mkv', 'series_imdb_id': None, 'audio_codec': u'EAC3', 'year': 2009, 'size': 832802483, 'title': u'Snapped', 'original_name': u'Modern Family S11E02 WEBDL-720p.mkv', 'fps': 23.976, 'release_group': None, 'original_series': False, 'plexapi_metadata': {}, 'format': u'WEB-DL', 'season': 11, 'tvdb_id': None, 'imdb_id': None, 'external_subtitle_languages': set([]), 'series_tvdb_id': 95011, 'hashes': {'opensubtitles': '1cbbbd04b5a3968b'}, 'hints': {'type': 'episode', 'expected_title': [u'Modern Family'], 'single_value': True, 'title': u'Modern Family'}, 'episode': 2, 'name': u'/media/Storage/TV Shows/Modern Family (2009)/Season 11/Modern Family S11E02 WEBDL-720p.mkv', 'subtitle_languages': set([]), 'used_scene_name': False, 'alternative_series': [], 'audio_languages': set([]), 'video_codec': u'h264', 'resolution': u'720p'}|
06/10/2019 23:36:11|INFO    |subliminal_patch.core           |Using 2 threads for 2 providers (['legendastv', 'opensubtitles'])|
06/10/2019 23:36:11|INFO    |subliminal_patch.core           |Downloading best subtitles for <Episode [u'Modern Family', 2009, 11x2]>|
06/10/2019 23:36:11|INFO    |subliminal_patch.core           |Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])|
06/10/2019 23:36:11|INFO    |subliminal_patch.core           |Initializing provider legendastv|
06/10/2019 23:36:11|INFO    |subliminal_patch.core           |Listing subtitles with provider 'opensubtitles' and languages set([<Language [pt-BR]>])|
06/10/2019 23:36:11|INFO    |subliminal_patch.core           |Initializing provider opensubtitles|
06/10/2019 23:36:11|DEBUG   |subliminal_patch.providers.opensubtitles|Using timeout: 15|
06/10/2019 23:36:11|DEBUG   |subliminal_patch.providers.opensubtitles|Using HTTPS connection|
06/10/2019 23:36:11|INFO    |subliminal_patch.providers.opensubtitles|Logging in|
06/10/2019 23:36:11|DEBUG   |subliminal_patch.providers.opensubtitles|Trying previous token: 'x0kYkJQjtMXXXXXXXXXXXXXXXXX'|
06/10/2019 23:36:11|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.opensubtitles.org:443|
06/10/2019 23:36:11|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.opensubtitles.org|
06/10/2019 23:36:11|ERROR   |subliminal_patch.core           |Unexpected error in provider 'legendastv': Traceback (most recent call last):  File "/opt/Bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/Bazarr/bazarr/../libs/subliminal_patch/core.py", line 98, in __getitem__    provider = provider_registry[name](**self.provider_configs.get(name, {}))  File "/opt/Bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 74, in __init__    rarfile.custom_check([rarfile.UNRAR_TOOL], True)  File "/opt/Bazarr/bazarr/../libs/rarfile.py", line 2823, in custom_check    p = custom_popen(cmd)  File "/opt/Bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen    creationflags=creationflags)  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__    errread, errwrite)  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child    raise child_exceptionAttributeError: 'NoneType' object has no attribute 'rfind'|Traceback (most recent call last):  File "/opt/Bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/Bazarr/bazarr/../libs/subliminal_patch/core.py", line 98, in __getitem__    provider = provider_registry[name](**self.provider_configs.get(name, {}))  File "/opt/Bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 74, in __init__    rarfile.custom_check([rarfile.UNRAR_TOOL], True)  File "/opt/Bazarr/bazarr/../libs/rarfile.py", line 2823, in custom_check    p = custom_popen(cmd)  File "/opt/Bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen    creationflags=creationflags)  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__    errread, errwrite)  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child    raise child_exceptionAttributeError: 'NoneType' object has no attribute 'rfind'|
06/10/2019 23:36:11|INFO    |subliminal_patch.core           |Discarding provider legendastv|
06/10/2019 23:36:12|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.org:443 "POST /xml-rpc HTTP/1.1" 200 215|
06/10/2019 23:36:12|DEBUG   |subliminal_patch.providers.opensubtitles|Token not valid.|
06/10/2019 23:36:12|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.opensubtitles.org:443|
06/10/2019 23:36:12|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.opensubtitles.org|
06/10/2019 23:36:21|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.org:443 "POST /xml-rpc HTTP/1.1" 200 323|
06/10/2019 23:36:21|DEBUG   |subliminal_patch.providers.opensubtitles|Logged in with token 'E3lF5KcoNFXXXXXXXXXXXXXXXXX'|
06/10/2019 23:36:21|INFO    |subliminal_patch.providers.opensubtitles|Searching subtitles [{'moviebytesize': '832802483', 'sublanguageid': u'pob', 'moviehash': '1cbbbd04b5a3968b'}, {'query': u'Modern Family', 'sublanguageid': u'pob', 'episode': 2, 'season': 11}]|
06/10/2019 23:36:21|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.opensubtitles.org:443|
06/10/2019 23:36:21|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.opensubtitles.org|
06/10/2019 23:36:21|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.org:443 "POST /xml-rpc HTTP/1.1" 200 1316|
06/10/2019 23:36:21|DEBUG   |subliminal_patch.providers.opensubtitles|Found subtitle <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7916048/sid-E3lF5KcoNFYe,xKtY1zA8UiUkS7/modern-family-episode-11-2-pb' [pt-BR:None]> by moviehash|
06/10/2019 23:36:21|DEBUG   |subliminal_patch.providers.opensubtitles|Found subtitle <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7916048/sid-E3lF5KcoNFYe,xKtY1zA8UiUkS7/modern-family-episode-11-2-pb' [pt-BR:None]> by fulltext|
06/10/2019 23:36:22|DEBUG   |subliminal_patch.core           |<OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7916048/sid-E3lF5KcoNFYe,xKtY1zA8UiUkS7/modern-family-episode-11-2-pb' [pt-BR:None]>: Found matches set(['episode', 'title', 'series', 'audio_codec', 'season', 'video_codec', 'hash'])|
06/10/2019 23:36:22|INFO    |subliminal_patch.score          |<OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7916048/sid-E3lF5KcoNFYe,xKtY1zA8UiUkS7/modern-family-episode-11-2-pb' [pt-BR:None]>: Computing score for video <Episode [u'Modern Family', 2009, 11x2]> with {'hearing_impaired': False}|
06/10/2019 23:36:22|DEBUG   |subliminal_patch.score          |<OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7916048/sid-E3lF5KcoNFYe,xKtY1zA8UiUkS7/modern-family-episode-11-2-pb' [pt-BR:None]>: Ignoring hash as other matches are wrong (missing: set(['format'])) and (<Episode [u'Modern Family', 2009, 11x2]>)|
06/10/2019 23:36:22|DEBUG   |subliminal_patch.score          |Adding title match equivalent|
06/10/2019 23:36:22|DEBUG   |subliminal_patch.score          |Matched hearing_impaired|
06/10/2019 23:36:22|INFO    |subliminal_patch.score          |<OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7916048/sid-E3lF5KcoNFYe,xKtY1zA8UiUkS7/modern-family-episode-11-2-pb' [pt-BR:None]>: Computed score 246 with final matches set(['episode', 'title', 'series', 'audio_codec', 'season', 'video_codec', 'hearing_impaired'])|
06/10/2019 23:36:22|INFO    |subliminal_patch.core           |<OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7916048/sid-E3lF5KcoNFYe,xKtY1zA8UiUkS7/modern-family-episode-11-2-pb' [pt-BR:None]>: Score 246 is below min_score (324)|
06/10/2019 23:36:22|INFO    |subliminal_patch.core           |Downloaded 0 subtitle(s)|
06/10/2019 23:36:22|DEBUG   |subliminal.core                 |Terminating initialized providers|
06/10/2019 23:36:22|INFO    |subliminal_patch.core           |Terminating provider opensubtitles|
06/10/2019 23:36:22|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.opensubtitles.org:443|
06/10/2019 23:36:22|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.opensubtitles.org|
```

**Comment by morpheus65535** [comment]
Do you have unrar installed? If it is, can you try do uninstall it and restart Bazarr?

**Comment by altendorfme** [comment]
I use the unrar-free package

**Comment by altendorfme** [comment]
In the log I sent I am not using any unrar

**Comment by altendorfme** [comment]
I added the non-free repositories and installed unrar package, that solved the problem.
It would be better to work with unrar-free, you might want to note this in the documentation.

**Comment by morpheus65535** [comment]
Bazarr already include unrar executable but use the one installed on Linux if it is available. It looks that unrar-free doesn't work the same way a the non-free one. Thanks for reporting!
