### ISSUE TITLE
Upgrade previously downloaded Subtitles raised an exception

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#611]
```
Message
Job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2019-10-08 08:47:59 CEST)" raised an exception

Exception
Traceback (most recent call last):
 File "/XXX/scripts/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/XXX/scripts/bazarr/bazarr/get_subtitle.py", line 1174, in upgrade_subtitles
  count_movie_to_upgrade = len(movies_to_upgrade)
UnboundLocalError: local variable \movies_to_upgrade\ referenced before assignment
```

**Software (please complete the following information):**
 - Bazarr: 0.8.2.1

**Comment by ngosang** [comment]
I can reproduce in Bazarr: 0.8.2.2

**Comment by morpheus65535** [comment]
Could you test dev branch please?

**Comment by ngosang** [comment]
@morpheus65535 tested dev. I can't see the error anymore, but I don't know if this feature is working (I don't have subtitles to upgrade).

```
2019-10-08 23:00:16,474 - apscheduler.executors.default    (7fc205266700) :  INFO (base:123) - Running job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2019-10-09 11:00:16 CEST)" (scheduled at 2019-10-08 23:00:16.444800+02:00)
2019-10-08 23:00:16,481 - apscheduler.executors.default    (7fc205266700) :  INFO (base:144) - Job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2019-10-09 11:00:16 CEST)" executed successfully
```

**Comment by morpheus65535** [comment]
Download a poor score subtitles using manual search and force the execution of upgrade subtitles task.

**Comment by ngosang** [comment]
Tested. It's working in dev.
