### ISSUE TITLE
Unexpected error in provider argenteam

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#612]
I will fix that later.
```
Unexpected error in provider 'argenteam': Traceback (most recent call last): File "XXX/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) File "XXX/bazarr/bazarr/../libs/subliminal_patch/providers/argenteam.py", line 266, in list_subtitles subs = self.query(title, video, titles=titles) File "XXX/bazarr/bazarr/../libs/subliminal_patch/providers/argenteam.py", line 219, in query argenteam_ids = self.search_ids(title, season=season, episode=episode, titles=titles) File "XXX/bazarr/bazarr/../libs/subliminal_patch/providers/argenteam.py", line 182, in search_ids results = r.json() File "XXX/bazarr/bazarr/../libs/requests/models.py", line 897, in json return complexjson.loads(self.text, **kwargs) File "/usr/lib/python2.7/json/__init__.py", line 339, in loads return _default_decoder.decode(s) File "/usr/lib/python2.7/json/decoder.py", line 364, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode raise ValueError("No JSON object could be decoded")ValueError: No JSON object could be decoded
```

**Software (please complete the following information):**
 - Bazarr: 0.8.2.1

**Comment by morpheus65535** [comment]
Probably a failure or a change on their side. We haven't touched it for a while.
