### ISSUE TITLE
Error deleting episodes

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#621]
1. I have an episode with subtitles (downloaded with Bazarr).
2. I delete the subtitle (in Bazarr) => I get the following exception.
3. It's weird that the exception is in the log (with debug disabled) but doesn't appear in the Bazarr Logs tab.
```
Traceback (most recent call last):
  File "XXXbazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "XXXbazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "XXXbazarr/bazarr/main.py", line 134, in wrapper
    return func(*a, **ka)
  File "XXXbazarr/bazarr/main.py", line 2052, in remove_subtitles
    history_log(0, sonarrSeriesId, sonarrEpisodeId, result)
  File "XXXbazarr/bazarr/utils.py", line 32, in history_log
    TableHistory.score: score
  File "XXXbazarr/bazarr/../libs/peewee.py", line 1785, in inner
    return method(self, database, *args, **kwargs)
  File "XXXbazarr/bazarr/../libs/peewee.py", line 1856, in execute
    return self._execute(database)
  File "XXXbazarr/bazarr/../libs/peewee.py", line 2572, in _execute
    return super(Insert, self)._execute(database)
  File "XXXbazarr/bazarr/../libs/peewee.py", line 2321, in _execute
    return self.handle_result(database, cursor)
  File "XXXbazarr/bazarr/../libs/peewee.py", line 2579, in handle_result
    return database.last_insert_id(cursor, self._query_type)
  File "XXXbazarr/bazarr/../libs/peewee.py", line 3035, in last_insert_id
    return cursor.lastrowid
  File "XXXbazarr/bazarr/../libs/playhouse/sqliteq.py", line 88, in lastrowid
    self._wait()
  File "XXXbazarr/bazarr/../libs/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
IntegrityError: UNIQUE constraint failed: table_history.sonarrEpisodeId
```

Database:
![image](https://user-images.githubusercontent.com/10577978/66433624-fdd5a180-ea20-11e9-83d2-d1dfccea75bd.png)

**Software (please complete the following information):**
 - Bazarr: development 0.8.2.2

**Comment by morpheus65535** [comment]
Could you test the fix I've added in dev branch?

**Comment by ngosang** [comment]
Tested. I have to delete the unique constrain in the database to make it work.

![image](https://user-images.githubusercontent.com/10577978/66434933-eba93280-ea23-11e9-9833-824442f1c1fb.png)

**Comment by ngosang** [comment]
Update: If i remove the database, bazarr makes a new one without that problem.

**Comment by morpheus65535** [comment]
Yes but unfortunately I don't know how to remove a unique constraint without drop the table and recreating it...

**Comment by morpheus65535** [comment]
The only solution is to delete db and start from scratch. :-/
