### ISSUE TITLE
Error when trying to analyze this .mkv

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#624]
**Message**
BAZARR error when trying to analyze this .mkv file: /XXX/Stranger Things/Season 03/Stranger.Things.S03E03.1080p.WEBRip.x264-STRiFE.mkv
**Exception**
Traceback (most recent call last):
 File "/root/scripts/bazarr/bazarr/list_subtitles.py", line 38, in store_subtitles
  subtitle_languages = embedded_subs_reader.list_languages(file)
 File "/root/scripts/bazarr/bazarr/embedded_subs_reader.py", line 32, in list_languages
  mkv = enzyme.MKV(f)
 File "/root/scripts/bazarr/bazarr/../libs/enzyme/mkv.py", line 56, in __init__
  raise MalformedMKVError(\Parsing error: %s\ % e)
MalformedMKVError: Parsing error: Less than 1 bytes read (0)

The file is fine. Tested in VLC and Mediainfo.
```
General
Unique ID                                : 262835679106001470869314995626204759792 (0xC5BC4F7BE72D5064A6C7FA6BC6F086F0)
Complete name                            : XXX\Stranger Things\Season 03\Stranger.Things.S03E03.1080p.WEBRip.x264-STRiFE.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 2.48 GiB
Duration                                 : 49 min 43 s
Overall bit rate                         : 7 143 kb/s
Encoded date                             : UTC 2019-07-04 21:26:00
Writing application                      : mkvmerge v35.0.0 ('All The Love In The World') 64-bit
Writing library                          : libebml v1.3.9 + libmatroska v1.5.2
IsTruncated                              : Yes

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 49 min 43 s
Bit rate                                 : 6 361 kb/s
Width                                    : 1 920 pixels
Height                                   : 960 pixels
Display aspect ratio                     : 2.000
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.144
Stream size                              : 2.21 GiB (89%)
Writing library                          : x264 core 157 r2969 d4099dd
Encoding settings                        : cabac=1 / ref=4 / deblock=1:-3:-3 / analyse=0x3:0x133 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=17.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=3:0.80
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 49 min 43 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 228 MiB (9%)
Title                                    : English [Original]
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : English
Language                                 : English
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : Forced
Language                                 : English
Default                                  : No
Forced                                   : Yes
```

**Software (please complete the following information):**
 - Bazarr: 0.8.2.2

**Comment by morpheus65535** [comment]
We almost drop support for Enzyme as it is frequently returning this kind of error. Bazarr should with ffprobe first and we have a couple of executable in bin directory. I'm curious why your installation doesn't use one of them. On what OS/hardware are you running Bazarr?

**Comment by ngosang** [comment]
I'm not using the Docker container. Just git clone in a raspberrypi.

**Comment by morpheus65535** [comment]
I’m going to test on my RPi but ffprobe should be included in bin for RPi.

**Comment by ngosang** [comment]
> I’m going to test on my RPi but ffprobe should be included in bin for RPi.

Only if you have `ffmpeg` installed.

UPDATE: I installed `ffmpeg` and restarted Bazarr. Now it's working fine.
I propose to add a warning in System if ffprobe is not installed. Is easy to install in most platforms.
Sonarr warning example:
![image](https://user-images.githubusercontent.com/10577978/66680668-513e2e80-ec71-11e9-887b-11d2a93c6e72.png)

**Comment by pannal** [comment]
Enzyme hasn't been updated in years. SZ also dropped support for it and uses the Plex Media Server for the metadata. Using ffprobe is definitely the better solution.

**Comment by morpheus65535** [comment]
That should do the trick.
