### ISSUE TITLE
Job "search_missing_subtitles_510" raised an exception in series_download_subtitles: OperationalError: row value misused

### ISSUE THREAD

**Issue by cdemi** [morpheus65535/bazarr#634]
**Describe the bug**
It looks like when I try to bulk update subtitles (for example searching for missing subtitles in series), I get this exception:
```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 592, in series_download_subtitles
  str(alpha3_from_alpha2(language.split(\:\))),
 File "/app/bazarr/bazarr/get_languages.py", line 88, in alpha3_from_alpha2
  TableSettingsLanguages.code2 == lang
 File "/app/bazarr/bazarr/../libs/peewee.py", line 1785, in inner
  return method(self, database, *args, **kwargs)
 File "/app/bazarr/bazarr/../libs/peewee.py", line 2042, in first
  return self.peek(database, n=n)
 File "/app/bazarr/bazarr/../libs/peewee.py", line 1785, in inner
  return method(self, database, *args, **kwargs)
 File "/app/bazarr/bazarr/../libs/peewee.py", line 2033, in peek
  rows = self.execute(database)[:n]
 File "/app/bazarr/bazarr/../libs/peewee.py", line 1785, in inner
  return method(self, database, *args, **kwargs)
 File "/app/bazarr/bazarr/../libs/peewee.py", line 1856, in execute
  return self._execute(database)
 File "/app/bazarr/bazarr/../libs/peewee.py", line 2027, in _execute
  cursor = database.execute(self)
 File "/app/bazarr/bazarr/../libs/peewee.py", line 2962, in execute
  return self.execute_sql(sql, params, commit=commit)
 File "/app/bazarr/bazarr/../libs/playhouse/sqliteq.py", line 248, in execute_sql
  return self._execute(sql, params, commit=commit)
 File "/app/bazarr/bazarr/../libs/peewee.py", line 2956, in execute_sql
  self.commit()
 File "/app/bazarr/bazarr/../libs/peewee.py", line 2732, in __exit__
  reraise(new_type, new_type(*exc_args), traceback)
 File "/app/bazarr/bazarr/../libs/peewee.py", line 2949, in execute_sql
  cursor.execute(sql, params or ())
OperationalError: row value misused
```

**Software:**
 - Bazarr: 0.8.2.4
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: Linux-4.4.0-154-generic-x86_64-with

**Comment by morpheus65535** [comment]
How long have you been using Bazarr? Your DB looks badly initialized... You can try to delete bazarr.db and let Bazarr recreate it.

**Comment by cdemi** [comment]
To be honest, I saw this suggestion in another thread so this is a brand new database created on the current master version. I have upgraded to develop after initializing the database to see if that fixes the issue

I will try to re-initialize the database on the current dev branch and report with updates.
________________________________

**Comment by morpheus65535** [comment]
Send me your DB if you still have the issue.

**Comment by cdemi** [comment]
Just as an FYI I'm not getting this error anymore after re-initializing the database
