### ISSUE TITLE
Job "Upgrade previously downloaded Subtitles" raised an exception

### ISSUE THREAD

**Issue by tommit** [morpheus65535/bazarr#635]
**Description:**
This happens every time the 12-hourly scheduled job "Upgrade previously downloaded Subtitles" is performed. I included a few lines of the debug log before the exception just in case they are relevant:

```
15/10/2019 15:44:06|DEBUG   |subliminal.core                 |Terminating initialized providers|
15/10/2019 15:44:06|INFO    |subliminal_patch.core           |Terminating provider opensubtitles|
15/10/2019 15:44:06|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): api.opensubtitles.org:80|
15/10/2019 15:44:06|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.opensubtitles.org|
15/10/2019 15:44:06|DEBUG   |urllib3.connectionpool          |http://api.opensubtitles.org:80 "POST /xml-rpc HTTP/1.1" 200 171|
15/10/2019 15:44:06|INFO    |subliminal_patch.core           |Terminating provider podnapisi|
15/10/2019 15:44:06|INFO    |subliminal_patch.core           |Terminating provider subscene|
15/10/2019 15:44:06|INFO    |subliminal_patch.providers.subscene|Closing session|
15/10/2019 15:44:06|DEBUG   |root                            |BAZARR No Subtitles were found for this file: C:\Movies\The Movie (3000)\The Movie (3000).mkv|
15/10/2019 15:44:06|DEBUG   |root                            |Not using opensubtitles until 19/10/15 16:01, because of: ServiceUnavailable|
15/10/2019 15:44:06|ERROR   |apscheduler.executors.default   |Job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2019-10-16 03:31:20 EEST)" raised an exception|Traceback (most recent call last):  File "c:\gitclones\bazarr\bazarr\../libs/apscheduler\executors\base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "c:\gitclones\bazarr\bazarr\get_subtitle.py", line 1242, in upgrade_subtitles    if movie['language'] in forced_languages:TypeError: argument of type 'NoneType' is not iterable|
```

**Software:**
 - Bazarr version: 0.8.2.4
 - Radarr version: 0.2.0.1358
 - Sonarr version: 3.0.3.644
 - OS: Windows-10-10.0.17763

**Additional context**
These are some of my (perhaps relevant) current settings, but I used to have the *Series/Movies Default Settings > Forced* set to `Both` for a while:
![Bazarr - Settings - Subtitles - Default Settings](https://user-images.githubusercontent.com/7393895/66836359-dc693e00-ef69-11e9-9662-8fc6952310a6.png)

**Comment by morpheus65535** [comment]
Can you test the fix in dev branch?

**Comment by tommit** [comment]
I believe it fixed it, although I had some issue with updating Bazarr itself. Here's what I did:

1. Changed *Bazarr > Settings > General > Updates - Branch* to `development`
2. Restarted Bazarr (just in case)
3. Manually ran the "Update Bazarr from source on Github" job, which threw this exception:
```
15/10/2019 20:28:57|ERROR   |apscheduler.executors.default   |Job "Update Bazarr from source on Github (trigger: interval[6:00:00], next run at: 2019-10-16 02:28:46 EEST)" raised an exception|'Traceback (most recent call last):\n  File "c:\\gitclones\\bazarr\\bazarr\\../libs/apscheduler\\executors\\base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "c:\\gitclones\\bazarr\\bazarr\\check_update.py", line 50, in check_and_apply_update\n    g.checkout(branch)\n  File "c:\\gitclones\\bazarr\\bazarr\\../libs/git\\cmd.py", line 548, in <lambda>\n    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)\n  File "c:\\gitclones\\bazarr\\bazarr\\../libs/git\\cmd.py", line 1014, in _call_process\n    return self.execute(call, **exec_kwargs)\n  File "c:\\gitclones\\bazarr\\bazarr\\../libs/git\\cmd.py", line 825, in execute\n    raise GitCommandError(command, status, stderr_value, stdout_value)\nGitCommandError: Cmd(\'git\') failed due to: exit code(255)\n  cmdline: git checkout development\n  stderr: \'error: could not lock config file .git/config: File exists\nerror: Unable to write upstream branch configuration\nhint: \nhint: After fixing the error cause you may try to fix up\nhint: the remote tracking information by invoking\nhint: "git branch --set-upstream-to=origin/development".\''|
```
4. Might have restarted Bazarr at this point, don't remember
5. Ran the "Update Bazarr from source on Github" job again, and this time it said this:
```
15/10/2019 20:32:50|INFO    |root                            |BAZARR No new version of Bazarr available.|
15/10/2019 20:32:50|INFO    |apscheduler.executors.default   |Job "Update Bazarr from source on Github (trigger: interval[6:00:00], next run at: 2019-10-16 02:32:49 EEST)" executed successfully|
```
6. Ran the "Upgrade previously downloaded Subtitles" job and although there were some errors with subliminal.providers.tvsubtitles (like *No show id found* and *Episode not found*) the upgrade job finished succesfully with this message:
```
15/10/2019 20:49:47|INFO    |apscheduler.executors.default   |Job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2019-10-16 08:37:23 EEST)" executed successfully|
```

**Comment by morpheus65535** [comment]
Ok, thanks for the feedback!
