### ISSUE TITLE
Issue in autostart Bazarr

### ISSUE THREAD

**Issue by altendorfme** [morpheus65535/bazarr#651]
**Describe the bug**
Every time I restart the Debian 9 server, the service runs normally, but Bazarr does not start correctly.
By running the service bazarr restart command after boot, Bazarr will function normally.

**To Reproduce**
1. Restart server

**Software (please complete the following information):**
 - Bazarr: 0.8.2.4
 - Radarr: 0.2.0.1358
 - Sonarr: 3.0.3.652
 - OS: Debian 9

**Additional context**
Service:
```
[Unit]
Description=Bazarr Daemon
After=syslog.target network.target

[Service]
WorkingDirectory=/opt/Bazarr/
User=xyz
Group=xyz
UMask=0002
Restart=on-failure
RestartSec=5
Type=simple
ExecStart=/usr/bin/python /opt/Bazarr/bazarr.py
KillSignal=SIGINT
TimeoutStopSec=20
SyslogIdentifier=bazarr

[Install]
WantedBy=multi-user.target
```

Terminal after boot:
```
xyz@xyz:/opt/Bazarr/data/log$ sudo journalctl -u bazarr.service
-- Logs begin at Wed 2019-10-30 17:45:05 -03, end at Wed 2019-10-30 17:46:45 -03. --
Oct 30 17:45:06 addicted systemd[1]: Started Bazarr Daemon.

xyz@xyz:/opt/Bazarr/data/log$ sudo service bazarr status
● bazarr.service - Bazarr Daemon
   Loaded: loaded (/etc/systemd/system/bazarr.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-30 17:45:06 -03; 1min 48s ago
 Main PID: 437 (python)
    Tasks: 1 (limit: 4915)
   Memory: 47.8M
   CGroup: /system.slice/bazarr.service
           └─437 /usr/bin/python /opt/Bazarr/bazarr.py

Oct 30 17:45:06 addicted systemd[1]: Started Bazarr Daemon.

xyz@xyz:/opt/Bazarr/data/log$ sudo service bazarr stop
xyz@xyz:/opt/Bazarr/data/log$ sudo journalctl -u bazarr.service
-- Logs begin at Wed 2019-10-30 17:45:05 -03, end at Wed 2019-10-30 17:47:49 -03. --
Oct 30 17:45:06 addicted systemd[1]: Started Bazarr Daemon.
Oct 30 17:47:45 addicted bazarr[437]: Bazarr starting...
Oct 30 17:47:45 addicted bazarr[437]: Traceback (most recent call last):
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/main.py", line 46, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     from get_episodes import *
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/get_episodes.py", line 13, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     from get_subtitle import episode_download_subtitles
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/get_subtitle.py", line 39, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     from analytics import track_event
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/analytics.py", line 16, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     sonarr_version = get_sonarr_version()
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/utils.py", line 108, in get_sonarr_version
Oct 30 17:47:45 addicted bazarr[437]:     logging.DEBUG('BAZARR cannot get Sonarr version')
Oct 30 17:47:45 addicted bazarr[437]: TypeError: 'int' object is not callable
Oct 30 17:47:45 addicted bazarr[437]: Traceback (most recent call last):
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr.py", line 83, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     time.sleep(1)
Oct 30 17:47:45 addicted bazarr[437]: KeyboardInterrupt
Oct 30 17:47:45 addicted systemd[1]: Stopping Bazarr Daemon...
Oct 30 17:47:45 addicted systemd[1]: bazarr.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 17:47:45 addicted systemd[1]: bazarr.service: Failed with result 'exit-code'.
Oct 30 17:47:45 addicted systemd[1]: Stopped Bazarr Daemon.

xyz@xyz:/opt/Bazarr/data/log$ sudo service bazarr start
xyz@xyz:/opt/Bazarr/data/log$ sudo journalctl -u bazarr.service
-- Logs begin at Wed 2019-10-30 17:45:05 -03, end at Wed 2019-10-30 17:48:20 -03. --
Oct 30 17:45:06 addicted systemd[1]: Started Bazarr Daemon.
Oct 30 17:47:45 addicted bazarr[437]: Bazarr starting...
Oct 30 17:47:45 addicted bazarr[437]: Traceback (most recent call last):
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/main.py", line 46, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     from get_episodes import *
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/get_episodes.py", line 13, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     from get_subtitle import episode_download_subtitles
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/get_subtitle.py", line 39, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     from analytics import track_event
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/analytics.py", line 16, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     sonarr_version = get_sonarr_version()
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr/utils.py", line 108, in get_sonarr_version
Oct 30 17:47:45 addicted bazarr[437]:     logging.DEBUG('BAZARR cannot get Sonarr version')
Oct 30 17:47:45 addicted bazarr[437]: TypeError: 'int' object is not callable
Oct 30 17:47:45 addicted bazarr[437]: Traceback (most recent call last):
Oct 30 17:47:45 addicted bazarr[437]:   File "/opt/Bazarr/bazarr.py", line 83, in <module>
Oct 30 17:47:45 addicted bazarr[437]:     time.sleep(1)
Oct 30 17:47:45 addicted bazarr[437]: KeyboardInterrupt
Oct 30 17:47:45 addicted systemd[1]: Stopping Bazarr Daemon...
Oct 30 17:47:45 addicted systemd[1]: bazarr.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 17:47:45 addicted systemd[1]: bazarr.service: Failed with result 'exit-code'.
Oct 30 17:47:45 addicted systemd[1]: Stopped Bazarr Daemon.
Oct 30 17:48:18 addicted systemd[1]: Started Bazarr Daemon.
```

**Comment by morpheus65535** [comment]
Is Sonarr available?
`logging.DEBUG('BAZARR cannot get Sonarr version')`

**Comment by altendorfme** [comment]
Yes, it's available.

```
xyz@xyz:~$ sudo service sonarr status
● sonarr.service - Sonarr Daemon
   Loaded: loaded (/lib/systemd/system/sonarr.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-30 17:45:06 -03; 2h 5min ago
 Main PID: 428 (mono)
    Tasks: 14 (limit: 4915)
   Memory: 233.3M
   CGroup: /system.slice/sonarr.service
           └─428 /usr/bin/mono --debug /usr/lib/sonarr/bin/Sonarr.exe -nobrowser -data=/var/lib/sonarr

Oct 30 18:51:29 addicted mono[428]: [Info] RssSyncService: RSS Sync Completed. Reports found: 150, Reports grabbed: 0
Oct 30 19:06:54 addicted mono[428]: [Info] RssSyncService: Starting RSS Sync
Oct 30 19:06:58 addicted mono[428]: [Info] DownloadDecisionMaker: Processing 150 releases
Oct 30 19:06:59 addicted mono[428]: [Info] RssSyncService: RSS Sync Completed. Reports found: 150, Reports grabbed: 0
Oct 30 19:22:24 addicted mono[428]: [Info] RssSyncService: Starting RSS Sync
Oct 30 19:22:30 addicted mono[428]: [Info] DownloadDecisionMaker: Processing 150 releases
Oct 30 19:22:31 addicted mono[428]: [Info] RssSyncService: RSS Sync Completed. Reports found: 150, Reports grabbed: 0
Oct 30 19:37:55 addicted mono[428]: [Info] RssSyncService: Starting RSS Sync
Oct 30 19:37:59 addicted mono[428]: [Info] DownloadDecisionMaker: Processing 150 releases
Oct 30 19:38:00 addicted mono[428]: [Info] RssSyncService: RSS Sync Completed. Reports found: 150, Reports grabbed: 0
```

Could the issue be related to Sonarr loading after Bazarr?

**Comment by morpheus65535** [comment]
Could be. Is it possible to add a dependencies so it start after Sonarr and Radarr?

**Comment by altendorfme** [comment]
I modified the bazaar systemd to:

```
Type=idle
After=syslog.target network.target radarr.service bazarr.service
```

But it didn't solve either.

**Comment by morpheus65535** [comment]
Shouldn't it be `sonarr.service` as last argument?

**Comment by altendorfme** [comment]
I actually wrote it wrong, but tested again with sonarr.service and it didn't work.

**Comment by morpheus65535** [comment]
Did you try this: https://unix.stackexchange.com/questions/43202/how-can-i-start-a-systemd-service-only-after-mysql-has-started

**Comment by altendorfme** [comment]
I have found a solution now:
`chmod u+x bazarr.py`

- https://stackoverflow.com/questions/907579/making-a-python-script-executable-chmod755

**Comment by pranau97** [comment]
I had the same issue too. I modified the bazarr service file to:
```ini
[Unit]
..
After=syslog.target network.target sonarr.service radarr.service
..

[Service]
..
ExecStartPre=/bin/sleep 30
..
```

It works now.

**Comment by morpheus65535** [comment]
@pranau97 I've added this to the wiki. Thanks!

**Comment by altendorfme** [comment]
> I had the same issue too. I modified the bazarr service file to:
> 
> ```ini
> [Unit]
> ..
> After=syslog.target network.target sonarr.service radarr.service
> ..
> 
> [Service]
> ..
> ExecStartPre=/bin/sleep 30
> ..
> ```
> 
> It works now.

It worked for me too, thank you very much.
