### ISSUE TITLE
manual upload subtitle throws 500 exception

### ISSUE THREAD

**Issue by defcon84** [morpheus65535/bazarr#659]
**Describe the bug**
Exception gets thrown when I try to manually upload a subtitle

**To Reproduce**
1. Upload a subtitle manually
```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://********:6767/manual_upload_subtitle_movie' caused an error:

Internal Server Error
Exception:
ValueError("invalid literal for int() with base 10: 'Aladdin'",)
Traceback:
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 134, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 2344, in perform_manual_upload_subtitle_movie
    history_log_movie(4, radarrId, message, path, language_code, provider, score)
  File "/app/bazarr/bazarr/utils.py", line 48, in history_log_movie
    TableHistoryMovie.score: score
  File "/app/bazarr/bazarr/../libs/peewee.py", line 1785, in inner
    return method(self, database, *args, **kwargs)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 1856, in execute
    return self._execute(database)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 2572, in _execute
    return super(Insert, self)._execute(database)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 2320, in _execute
    cursor = database.execute(self)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 2961, in execute
    sql, params = ctx.sql(query).query()
  File "/app/bazarr/bazarr/../libs/peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 2549, in __sql__
    self._simple_insert(ctx)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 2420, in _simple_insert
    return self._generate_insert((self._insert,), ctx)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 2521, in _generate_insert
    return ctx.sql(CommaNodeList(all_values))
  File "/app/bazarr/bazarr/../libs/peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 1651, in __sql__
    ctx.sql(self.nodes[n_nodes - 1])
  File "/app/bazarr/bazarr/../libs/peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 1649, in __sql__
    ctx.sql(self.nodes[i])
  File "/app/bazarr/bazarr/../libs/peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 1308, in __sql__
    return ctx.value(self.value, self.converter)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 613, in value
    value = converter(value)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 4893, in db_value
    return self.rel_field.db_value(value)
  File "/app/bazarr/bazarr/../libs/peewee.py", line 4290, in db_value
    return value if value is None else self.adapt(value)
ValueError: invalid literal for int() with base 10: 'Aladdin'
```

**Software (please complete the following information):**
 - Bazarr Version: 0.8.2.4
 - Sonarr Version: 2.0.0.5338
 - Radarr Version: 0.2.0.1358
 - Operating System: Linux-4.15.0-45-generic-x86_64-with
 - Python Version: 2.7.16

**Comment by morpheus65535** [comment]
Wait for 0.8.3 (actually in dev branch) and confirm if it's still an issue.

**Comment by morpheus65535** [comment]
I've just made a fix that will be in 0.8.3. Thank you for reporting!

**Comment by defcon84** [comment]
That was quick, thank you!

**Comment by defcon84** [comment]
Tested it, it's fixed.
