### ISSUE TITLE
Can't Acces WebUI (AttributeError: 'dict' object has no attribute 'code2')

### ISSUE THREAD

**Issue by Demo95** [morpheus65535/bazarr#662]
Clean install from source.
Did all the instructions and installed it as a service on windows.
Now when i open up the WebUI (wizard page) I get following traceback:

Traceback (most recent call last):
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "c:\bazarr\bazarr\bazarr\main.py", line 122, in wrapper
    return func(*a, **ka)
  File "c:\bazarr\bazarr\bazarr\main.py", line 220, in wizard
    base_url=base_url)
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "c:\bazarr\bazarr\views\wizard.tpl", line 114, in <module>
    % include('wizard_subtitles')
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 3386, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "c:\bazarr\bazarr\views\wizard_subtitles.tpl", line 108, in <module>
    <option value="{{language.code2}}">{{language.name}}</option>
AttributeError: 'dict' object has no attribute 'code2'

To Reproduce

Clean Bazarr installation
(Re-)start the service.
Open up localhost:6767

Running on Windows 10

**Comment by morpheus65535** [comment]
You are most certainly running 0.8.2.4. Please update to 0.8.3. Can be a `git pull origin master` from within the Bazarr directory.

**Comment by morpheus65535** [comment]
Fixed in dev branch. Will merge it to master before going to bed tonight.

**Comment by morpheus65535** [comment]
Merged to master. v0.8.3.1
