### ISSUE TITLE
Bazarr unable to adjust to new timezone

### ISSUE THREAD

**Issue by agneevX** [morpheus65535/bazarr#666]
I recently corrected the timezone on the machine to GMT +0530 and `bazarr` is throwing errors ever since...

```
agneev@server1:~$ python /opt/bazarr/bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/main.py", line 57, in <module>
    from scheduler import *
  File "/opt/bazarr/bazarr/scheduler.py", line 66, in <module>
    if str(get_localzone()) == "local":
  File "/opt/bazarr/bazarr/../libs/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/bazarr/bazarr/../libs/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/opt/bazarr/bazarr/../libs/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 0 != 19800. Please, check your config files.
^CTraceback (most recent call last):
  File "/opt/bazarr/bazarr.py", line 83, in <module>
    time.sleep(1)
KeyboardInterrupt
```

**To Reproduce**
1. Change the timezone. 
2. Launch `bazarr`. 

**Expected behavior**
Bazarr reads timezone from the system.

**Software:**
 - Bazarr:
 - OS: Ubuntu 18.04, AMD64

**Comment by morpheus65535** [comment]
What version of Bazarr?

**Comment by agneevX** [comment]
The latest IIRC. Unable to launch it, so I left it blank.

**Comment by morpheus65535** [comment]
You can open bazarr/bazarr/main.py in a text editor and you’ll see version number in the first lines.

**Comment by agneevX** [comment]
`bazarr_version = '0.8.3'`

**Comment by morpheus65535** [comment]
Could you force an update using `git pull origin master` while being in bazarr directory please?

**Comment by agneevX** [comment]
I did. The issue is still there. 

```
agneev@server1:~$ cd /opt/bazarr
agneev@server1:/opt/bazarr$ git pull origin master
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 35 (delta 28), reused 25 (delta 18), pack-reused 0
Unpacking objects: 100% (35/35), done.
From https://github.com/morpheus65535/bazarr
 * branch            master     -> FETCH_HEAD
   c442524..44ed1ba  master     -> origin/master
Updating c442524..44ed1ba
Fast-forward
 bazarr/check_update.py     |  2 +-
 bazarr/config.py           | 96 ++++++++++++++++++++++++++++---------------
 bazarr/get_episodes.py     |  2 +-
 bazarr/get_movies.py       |  4 +-
 bazarr/get_series.py       |  6 +--
 bazarr/init.py             | 13 +++---
 bazarr/main.py             | 65 +++++++++++++++--------------
 bazarr/utils.py            |  4 +-
 views/wizard_subtitles.tpl |  6 +--
 9 files changed, 115 insertions(+), 83 deletions(-)
agneev@server1:/opt/bazarr$ python bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "bazarr/main.py", line 56, in <module>
    from scheduler import *
  File "/opt/bazarr/bazarr/scheduler.py", line 66, in <module>
    if str(get_localzone()) == "local":
  File "/opt/bazarr/bazarr/../libs/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/bazarr/bazarr/../libs/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/opt/bazarr/bazarr/../libs/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 0 != 19800. Please, check your config files.
```

**Comment by morpheus65535** [comment]
Is your time zone set in /etc/timezone?

**Comment by agneevX** [comment]
What should it read?

**Comment by morpheus65535** [comment]
That depends of where do you live ;-)

What is the content of the file?

**Comment by agneevX** [comment]
Running `sudo dpkg-reconfigure tzdata` again fixed it. Thanks for your help.
