### ISSUE TITLE
Bazarr no such file or directory issue

### ISSUE THREAD

**Issue by eldudemeister** [morpheus65535/bazarr#667]
I am seeing a couple of errors in the bazarr log. 
The first is

Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 65, in get_video
  hash_from=hash_from)
 File "/app/bazarr/bazarr/../libs/subzero/video.py", line 60, in parse_video
  skip_hashing=skip_hashing, hash_from=hash_from)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 540, in scan_video
  video.size = os.path.getsize(hash_path)
 File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
  return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: \/tv/Videos/TV Shows/See/Season 1/See.S01E03.Fresh Blood WEBDL-1080p.mkv\

It looks as if it cannot see my mounted folders but sonarr or radarr do not have the same issue and bazarr is set up with the same permissions as them. I am running on docker compose on Ubuntu, 

I did also have this issue but I think it has been replced with the above.

Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 202, in download_subtitle
  path_decoder=force_unicode
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 867, in save_subtitles
  with open(subtitle_path, \w) as f:
IOError: [Errno 13] Permission denied: u/tv/Videos/TV Shows/Scrubs/Season 2/Scrubs.S02E07.My.First.Step.DVD.srt\

**Comment by eldudemeister** [comment]
I'm also seeing the permissions issue again as below:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 202, in download_subtitle
  path_decoder=force_unicode
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 867, in save_subtitles
  with open(subtitle_path, \w\) as f:
IOError: [Errno 13] Permission denied: u\/movies/Videos/Movies/Zack and Miri Make a Porno (2008)/Zack and Miri Make a Porno (2008).srt\

**Comment by morpheus65535** [comment]
You have permission issue with your Docker container (PUID/PGID) or your host filesystem permission. I bet you are running on Synology... 99.9% of the "issue" with Synology users are permission related.

Any way, it's unrelated to Bazarr itself. That's a configuration issue.

**Comment by eldudemeister** [comment]
Ok thanks for clarifying. Will look at the configuration but I'm not running on Synology, my media is stored on there and mounted to my Ubuntu server running docker.
