### ISSUE TITLE
It looks like with the latest development docker container bazaar breaks on load if you have basic authentication

### ISSUE THREAD

**Issue by cdemi** [morpheus65535/bazarr#686]
**Describe the bug**
After logging in with basic authentication to Bazaar, I immediately get an exception
**To Reproduce**
1. Log on to Bazaar
2. See error

This is the stack trace:
```
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 123, in wrapper
    if user is None or not check(user, password):
  File "/app/bazarr/bazarr/main.py", line 139, in check_credentials
    if hashlib.md5(pw).hexdigest() == password and user == username:
TypeError: Unicode-objects must be encoded before hashing
```

It looks like it might be due to upgrade to Python 3

**Comment by morpheus65535** [comment]
Thanks for #687. :-)
