### ISSUE TITLE
Issue to download subtitle with python 3.6.9

### ISSUE THREAD

**Issue by rjulie95** [morpheus65535/bazarr#707]
Hi,

I have this error when i try do download subtitle in develop branch : 

Traceback (most recent call last):
 File "/home/rjulie/bazarr/bazarr/get_subtitle.py", line 75, in get_video
  refine_from_ffprobe(original_path, video)
 File "/home/rjulie/bazarr/bazarr/get_subtitle.py", line 959, in refine_from_ffprobe
  data = parser.parseFfprobe(path)
 File "/home/rjulie/bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 42, in parseFfprobe
  fdict = self._executeFfprobe(inputFile)
 File "/home/rjulie/bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 73, in _executeFfprobe
  outputJson = self._executeParser(self._ffprobe, commandArgs, inputFile)
 File "/home/rjulie/bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 182, in _executeParser
  command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True
 File "/usr/lib/python3.6/subprocess.py", line 423, in run
  with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument \text\

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3977632/bazarr.log)

![image](https://user-images.githubusercontent.com/8410772/71073486-c56ce500-2180-11ea-9e9f-bca833adb025.png)

**Comment by morpheus65535** [comment]
Sorry, my bad. Should be fixed by this commit to dev branch.
