### ISSUE TITLE
Deathbycaptcha exception

### ISSUE THREAD

**Issue by defcon84** [morpheus65535/bazarr#739]
**Describe the bug**
While trying to login in Addic7ed, using Deathbycaptcha, i get an exception

**To Reproduce**
1. enable Addic7ed and Deathbycaptcha
2. search a subtitle

**Expected behavior**
Find a subtitle for Shameless (US) 10x9. Maybe it searches for a subtitle in the non-US show?

**Software (please complete the following information):**
- Docker images: linuxserver/bazarr:latest	
- Bazarr Version: 0.8.4
- Sonarr Version: 2.0.0.5338
- Radarr Version: 0.2.0.1450
- Operating System: Linux-4.15.0-72-generic-x86_64-with
- Python Version: 3.8.1

**Additional context**
_debug.log_
```

05/01/2020 20:34:53|INFO    |subliminal_patch.core           |Downloading best subtitles for <Episode ['Shameless', 2011, 10x9]>|
...
05/01/2020 20:34:54|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed': Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 101, in __getitem__    provider.initialize()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 133, in initialize    result = pitcher.throw()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 87, in throw    data = self._throw()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 216, in _throw    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 202, in decode    uploaded_captcha = self.upload(captcha, **kwargs)
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 475, in upload    response = self._call('upload', data)
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 413, in _call    self._call('login', self.userpwd.copy())
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 417, in _call    response = self._sendrecv(sock, request)
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 386, in _sendrecv    buf = buf[wrs[0].send(buf):]TypeError: a bytes-like object is required, not 'str'|Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 101, in __getitem__    provider.initialize()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 133, in initialize    result = pitcher.throw()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 87, in throw    data = self._throw()
  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 216, in _throw    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 202, in decode    uploaded_captcha = self.upload(captcha, **kwargs)
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 475, in upload    response = self._call('upload', data)
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 413, in _call    self._call('login', self.userpwd.copy())
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 417, in _call    response = self._sendrecv(sock, request)
  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 386, in _sendrecv    buf = buf[wrs[0].send(buf):]TypeError: a bytes-like object is required, not 'str'|
05/01/2020 20:34:54|INFO    |root                            |Throttling addic7ed for 10 minutes, until 20/01/05 20:44, because of: TypeError. Exception info: "a bytes-like object is required, not 'str'"|

```

**Comment by morpheus65535** [comment]
@pannal Could you take a look at this one please?

**Comment by defcon84** [comment]
Any update on this? Or do you need more information?

**Comment by pannal** [comment]
Is this still the case? Does this happen with other series?

**Comment by defcon84** [comment]
yes it is still the case. And yes, also happens with eg Band of Brothers 1x1:
```
18/01/2020 10:37:03|INFO    |subliminal_patch.core           |Listing subtitles for <Episode ['Band of Brothers', 2001, 1x10]>|
...
18/01/2020 10:37:03|DEBUG   |urllib3.connectionpool          |https://www.addic7ed.com:443 "GET /login.php HTTP/1.1" 200 None|
18/01/2020 10:37:03|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Solving captcha. This might take a couple of minutes, but should only happen once every so often|
18/01/2020 10:37:03|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed': Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 101, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 133, in initialize    result = pitcher.throw()  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 87, in throw    data = self._throw()  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 216, in _throw    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 202, in decode    uploaded_captcha = self.upload(captcha, **kwargs)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 475, in upload    response = self._call('upload', data)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 413, in _call    self._call('login', self.userpwd.copy())  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 417, in _call    response = self._sendrecv(sock, request)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 386, in _sendrecv    buf = buf[wrs[0].send(buf):]TypeError: a bytes-like object is required, not 'str'|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 101, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 133, in initialize    result = pitcher.throw()  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 87, in throw    data = self._throw()  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 216, in _throw    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 202, in decode    uploaded_captcha = self.upload(captcha, **kwargs)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 475, in upload    response = self._call('upload', data)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 413, in _call    self._call('login', self.userpwd.copy())  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 417, in _call    response = self._sendrecv(sock, request)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 386, in _sendrecv    buf = buf[wrs[0].send(buf):]TypeError: a bytes-like object is required, not 'str'|
18/01/2020 10:37:03|INFO    |root                            |Throttling addic7ed for 10 minutes, until 20/01/18 10:47, because of: TypeError. Exception info: "a bytes-like object is required, not 'str'"|
18/01/2020 10:37:03|INFO    |subliminal_patch.core           |Discarding provider addic7ed|
```

**Comment by zaggash** [comment]
https://github.com/morpheus65535/bazarr/issues/798

**Comment by morpheus65535** [comment]
Could you test dev branch? It now works for me.

**Comment by defcon84** [comment]
Works perfectly! Thanks!
