### ISSUE TITLE
Radarr import fails

### ISSUE THREAD

**Issue by Sharmii** [morpheus65535/bazarr#74]
**FYI**
Hi, I am using the dev branch and getting the following error when trying to import from Radarr.
## Message
Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2018-05-31 10:11:20 CEST)" raised an exception
## Exception
'Traceback (most recent call last):\n File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job\n retval = job.func(*job.args, **job.kwargs)\n File "/opt/Bazarr/bazarr/get_movies.py", line 48, in update_movies\n if \'sceneName\' in movie[\'movieFile\']:\nKeyError: \'movieFile\''

**Comment by morpheus65535** [comment]
From Bazarr, can you send me a screenshot of your Radarr settings tab please?

**Comment by Sharmii** [comment]
## Bazarr
The API key is correct: I tripple-checked.
![image](https://user-images.githubusercontent.com/15986704/40785371-a0969ff6-64e8-11e8-873a-15413176f9c9.png)
## Radarr
![image](https://user-images.githubusercontent.com/15986704/40785384-ab891ab0-64e8-11e8-8231-d5a0966108f1.png)

**Comment by morpheus65535** [comment]
Which version of Radarr are you using?

**Comment by Sharmii** [comment]
Radarr Ver. 0.2.0.1067
--> develop

**Comment by morpheus65535** [comment]
Ok, you got the same version has me.

From what I can deduct, the JSON returned from Radarr contain at least one movie that have "hasFile" to True but no "movieFile" sub-key. BTW, it make no sense...

Could you send me trough Discord (or other way) the JSON returned from: 
http://127.0.0.1:7878/api/movie?apikey=12345678901234567890123456789012

I'll try to see where's the problem. Thanks!
