### ISSUE TITLE
UnicodeEncodeError: \ascii\ codec can\t encode character \\\xf4\ in position 97: ordinal not in range(128)

### ISSUE THREAD

**Issue by MichaelTrip** [morpheus65535/bazarr#744]
**Describe the bug**
When i run certain tasks i get a ordinal not in range error. Seems that the cronjob can't be planned.

**Software (please complete the following information):**
 - Bazarr: 0.8.4
 - OS: Ubuntu 18.04

**Additional context**

Traceback from python:

`Traceback (most recent call last):
 File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/opt/bazarr/bazarr/get_episodes.py", line 18, in update_all_episodes
  series_full_scan_subtitles()
 File "/opt/bazarr/bazarr/list_subtitles.py", line 306, in series_full_scan_subtitles
  store_subtitles(episode[\path\], path_replace(episode[\path\]))
 File "/opt/bazarr/bazarr/list_subtitles.py", line 37, in store_subtitles
  if os.path.exists(reversed_path):
 File "/usr/lib/python3.6/genericpath.py", line 19, in exists
  os.stat(path)
UnicodeEncodeError: \ascii\ codec can\t encode character \\\xf4\ in position 97: ordinal not in range(128)`

`Traceback (most recent call last):
 File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/opt/bazarr/bazarr/get_movies.py", line 21, in update_all_movies
  movies_full_scan_subtitles()
 File "/opt/bazarr/bazarr/list_subtitles.py", line 318, in movies_full_scan_subtitles
  store_subtitles_movie(movie[\path\], path_replace_movie(movie[\path\]))
 File "/opt/bazarr/bazarr/list_subtitles.py", line 113, in store_subtitles_movie
  if os.path.exists(reversed_path):
 File "/usr/lib/python3.6/genericpath.py", line 19, in exists
  os.stat(path)
UnicodeEncodeError: \ascii\ codec can\t encode character \\\xe9\ in position 22: ordinal not in range(128)`

`Traceback (most recent call last):
 File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/opt/bazarr/bazarr/get_episodes.py", line 168, in sync_episodes
  store_subtitles(altered_episode[1], path_replace(altered_episode[1]))
 File "/opt/bazarr/bazarr/list_subtitles.py", line 37, in store_subtitles
  if os.path.exists(reversed_path):
 File "/usr/lib/python3.6/genericpath.py", line 19, in exists
  os.stat(path)
UnicodeEncodeError: \ascii\ codec can\t encode character \\\xf4\ in position 97: ordinal not in range(128)`

**Comment by morpheus65535** [comment]
Make sure you have configured utf-8 locale correctly: https://lintut.com/how-to-set-up-system-locale-on-ubuntu-18-04/

**Comment by morpheus65535** [comment]
Is it fixed?

**Comment by MichaelTrip** [comment]
> Is it fixed?

I did a clean install of bazarr, everything is working again :)

**Comment by morpheus65535** [comment]
Reopen this issue if you face the problem again.
