### ISSUE TITLE
IndentationError: legendasdivx.py

### ISSUE THREAD

**Issue by Foxcon84** [morpheus65535/bazarr#752]
**Describe the bug**
Currently when trying to start bazaar, it exits out with an `IndentationError`

**To Reproduce**
1. Start bazaar `python3 /Applications/bazarr/bazarr.py`

**Expected behavior**
Bazaar service start webserver

**Screenshots**
None

**Software (please complete the following information):**
 - Bazarr: v 0.8.1
 - OS: macOS 10.15.2
 - Python: 3.7.6

**Additional context**
Stacktrace:
Bazarr starting...
```
Traceback (most recent call last):
  File "/Applications/bazarr/bazarr/main.py", line 52, in <module>
    from get_providers import get_providers, get_providers_auth, list_throttled_providers
  File "/Applications/bazarr/bazarr/get_providers.py", line 5, in <module>
    import subliminal_patch
  File "/Applications/bazarr/bazarr/../libs/subliminal_patch/__init__.py", line 8, in <module>
    from .providers import Provider
  File "/Applications/bazarr/bazarr/../libs/subliminal_patch/providers/__init__.py", line 30, in <module>
    mod = importlib.import_module("subliminal_patch.providers.%s" % module_name.lower())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Applications/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 242
    except Exception as e:
         ^
IndentationError: expected an indented block
```

**Comment by morpheus65535** [comment]
@Foxcon84  I've made a quick fix but it will require a validation from @GermanG.

**Comment by GermanG** [comment]
@morpheus65535 Makes absolutely sense. Thanks!
