### ISSUE TITLE
python 3.8.1 issue (no startup)

### ISSUE THREAD

**Issue by nephaste** [morpheus65535/bazarr#771]
Hi Team

some users asked me to update Bazarr QPKG on Qnap NAS to Python3

but package remain in error when startup bazzar .. thanks for your help

[~] # /etc/init.d/QBazarr.sh start
[~] # Traceback (most recent call last):
  File "bazarr/main.py", line 36, in <module>
    from init import *
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/init.py", line 15, in <module>
    import subliminal
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/subliminal/core.py", line 30, in <module>
    from guessit import guessit
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/guessit/__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/guessit/api.py", line 151, in <module>
    default_api = GuessItApi(rebulk_builder())
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/guessit/rules/__init__.py", line 50, in rebulk_builder
    rebulk.rebulk(episodes())
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/guessit/rules/properties/episodes.py", line 139, in episodes
    rebulk.chain(formatter={'season': int, 'episode': int},
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/rebulk/chain.py", line 115, in regex
    pattern = self.rebulk.build_re(*pattern, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/rebulk/rebulk.py", line 133, in build_re
    return RePattern(*pattern, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/rebulk/pattern.py", line 378, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/rebulk/loose.py", line 50, in call
    return function(*call_args, **call_kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'abbreviations'

[~] #
[~] # /opt/QBazarr/bin/python3 --version
Python 3.8.1

**Comment by nephaste** [comment]
ok found .. regex is making mess

rm -rf /share/CACHEDEV1_DATA/.qpkg/QBazarr/lib/python3.8/site-packages/regex

did the trick
