### ISSUE TITLE
TypeError: not all arguments converted

### ISSUE THREAD

**Issue by Wireheadbe** [morpheus65535/bazarr#784]
When bazarr tries to add series to it's DB - it eventually fails with an error:

```
2020-01-29 17:47:32,401 - sqlite3worker                    (7f33497fa700) :  DEBUG (sqlite3worker:202) - execute: INSERT OR IGNORE INTO table_shows(title,path,tvdbId,languages,hearing_impaired,sonarrSeriesId,overview,poster,fanart,audio_language,sortTitle,year,alternateTitles,forced) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?), ('In Flanders Fields', '/app/series/In Vlaamse Velden/', 277314, "['nl']", 'False', 6, "The story of the Boesman family's attempt to survive in the city of Ghent during the first world war focusing on each of the five family member's different experiences", '', '/MediaCover/6/fanart.jpg', 'English', 'in flanders fields', 2014, '[]', 'False')
2020-01-29 17:47:32,401 - sqlite3worker                    (7f33497fa700) :  DEBUG (sqlite3worker:184) - Sleeping: 0.001 2cdc099a-9fc5-4a08-a94b-32c4c4dc328a
2020-01-29 17:47:32,401 - sqlite3worker                    (7f3369f53700) :  DEBUG (sqlite3worker:94) - sql_queue: 0
2020-01-29 17:47:32,401 - sqlite3worker                    (7f3369f53700) :  DEBUG (sqlite3worker:96) - run: INSERT OR IGNORE INTO table_shows(title,path,tvdbId,languages,hearing_impaired,sonarrSeriesId,overview,poster,fanart,audio_language,sortTitle,year,alternateTitles,forced) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?), ('In Flanders Fields', '/app/series/In Vlaamse Velden/', 277314, "['nl']", 'False', 6, "The story of the Boesman family's attempt to survive in the city of Ghent during the first world war focusing on each of the five family member's different experiences", '', '/MediaCover/6/fanart.jpg', 'English', 'in flanders fields', 2014, '[]', 'False')
2020-01-29 17:47:32,401 - sqlite3worker                    (7f3369f53700) :  DEBUG (sqlite3worker:104) - run: commit
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/user/bazarr/bazarr/get_series.py", line 158, in update_series
    logging.debug('BAZARR unable to insert this series into the database:',
Message: 'BAZARR unable to insert this series into the database:'
Arguments: ('/app/series/In Vlaamse Velden/',)
```

OS: ubuntu 18.04 lts - python 3.8 - using latest pull from github

**Comment by Wireheadbe** [comment]
Manually running:

```
sqlite> INSERT OR IGNORE INTO table_shows(title,path,tvdbId,languages,hearing_impaired,sonarrSeriesId,overview,poster,fanart,audio_language,sortTitle,year,alternateTitles,forced) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?), ('In Flanders Fields', '/app/series/In Vlaamse Velden/', 277314, "['nl']", 'False', 6, "The story of the Boesman family's attempt to survive in the city of Ghent during the first world war focusing on each of the five family member's different experiences", '', '/MediaCover/6/fanart.jpg', 'English', 'in flanders fields', 2014, '[]', 'False');
sqlite> select * from table_shows where sonarrSeriesId like '6';
277314|In Flanders Fields|/app/series/In Vlaamse Velden/|['nl']|False|6|The story of the Boesman family's attempt to survive in the city of Ghent during the first world war focusing on each of the five family member's different experiences||/MediaCover/6/fanart.jpg|English|in flanders fields|2014|[]|False
sqlite>
```

..Seems to work fine, so probably python related

**Comment by Wireheadbe** [comment]
Might have found another thing, possibly related. I'm also trying to add 'Zorro'. Bazarr generates its query as:

```
INSERT OR IGNORE INTO table_shows(title,path,tvdbId,languages,hearing_impaired,sonarrSeriesId,overview,poster,fanart,audio_language,sortTitle,year,alternateTitles,forced) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?), ('Zorro (1957)', '/app/series/Zorro (1957)', 74683, "['nl']", 'False', 9, 'Zorro, which is Spanish for "fox", is the story of a masked rider who battles the unjust rulers of the pueblo of Los Angeles during the days of Spanish rule. His real identity is that of Don Diego de la Vega, the son of a wealthy landowner. Diego returns from his studies in Spain and discovers that Los Angeles is under the command of Capitan Monastario, a cruel man who relishes in the misuse of his power for personal gain. Knowing that he cannot hope to single-handedly defeat Monastario and his troops,Diego resorts to subterfuge. He adopts the secret identity of Zorro, a sinister figure dressed in black, and rides to fight Monastario\'s injustice.', '/MediaCover/9/poster-250.jpg', '/MediaCover/9/fanart.jpg', 'English', 'zorro 1957', 1957, '[]', 'False');
```

Note that due to the `"fox" `string in the overview, the complete overview is single-quoted. Trying to execute this in sqlite3 doesn't work. It interprets this as the statement not being finished.

Changing that SQL statement into:
```
INSERT OR IGNORE INTO table_shows(title,path,tvdbId,languages,hearing_impaired,sonarrSeriesId,overview,poster,fanart,audio_language,sortTitle,year,alternateTitles,forced) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?), ('Zorro (1957)', '/app/series/Zorro (1957)', 74683, "['nl']", 'False', 9, "Zorro, which is Spanish for 'fox', is the story of a masked rider who battles the unjust rulers of the pueblo of Los Angeles during the days of Spanish rule. His real identity is that of Don Diego de la Vega, the son of a wealthy landowner. Diego returns from his studies in Spain and discovers that Los Angeles is under the command of Capitan Monastario, a cruel man who relishes in the misuse of his power for personal gain. Knowing that he cannot hope to single-handedly defeat Monastario and his troops, Diego resorts to subterfuge. He adopts the secret identity of Zorro, a sinister figure dressed in black, and rides to fight Monastario\'s injustice.", '/MediaCover/9/poster-250.jpg', '/MediaCover/9/fanart.jpg', 'English', 'zorro 1957', 1957, '[]', 'False');
```

Where we replace `"fox"` with `'fox'` and encapsulate the entire overview with double-quotes - that works from the sqlite3 command line.

**Comment by morpheus65535** [comment]
I've got a lot of series that include double quotes in overview and it works fine in Python. I haven't tested it in sqlite client but the important thing is that it work with Bazarr ;-)

From there I have no idea where to look as I can't reproduce your issue.
