### ISSUE TITLE
addic7ed gives error with Death by Captcha

### ISSUE THREAD

**Issue by Bouncy2020** [morpheus65535/bazarr#798]
by using death by capture with Addic7ed i get the following error;

**TypeError**
Throttling addic7ed for 10 minutes, until 20/02/03 16:18, because of: TypeError. Exception info: "a bytes-like object is required, not 'str'"

**Comment by morpheus65535** [comment]
I need a complete debug log to see the traceback. Please empty your log before reproducing the issue with debug log enabled.

**Comment by zaggash** [comment]
Same issue here.
you can find the relevant debug log below

```
07/02/2020 18:35:53|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed': Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 101, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 133, in initialize    result = pitcher.throw()  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 87, in throw    data = self._throw()  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 216, in _throw    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 202, in decode    uploaded_captcha = self.upload(captcha, **kwargs)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 475, in upload    response = self._call('upload', data)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 413, in _call    self._call('login', self.userpwd.copy())  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 417, in _call    response = self._sendrecv(sock, request)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 386, in _sendrecv    buf = buf[wrs[0].send(buf):]TypeError: a bytes-like object is required, not 'str'|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 101, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 133, in initialize    result = pitcher.throw()  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 87, in throw    data = self._throw()  File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 216, in _throw    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 202, in decode    uploaded_captcha = self.upload(captcha, **kwargs)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 475, in upload    response = self._call('upload', data)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 413, in _call    self._call('login', self.userpwd.copy())  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 417, in _call    response = self._sendrecv(sock, request)  File "/app/bazarr/bazarr/../libs/deathbycaptcha.py", line 386, in _sendrecv    buf = buf[wrs[0].send(buf):]TypeError: a bytes-like object is required, not 'str'|
07/02/2020 18:35:53|INFO    |root                            |Throttling addic7ed for 10 minutes, until 20/02/07 18:45, because of: TypeError. Exception info: "a bytes-like object is required, not 'str'"|
07/02/2020 18:35:53|INFO    |subliminal_patch.core           |Discarding provider addic7ed|
```

**Comment by zaggash** [comment]
https://github.com/morpheus65535/bazarr/issues/739

**Comment by morpheus65535** [comment]
Could you test dev branch? It now works for me.

**Comment by zaggash** [comment]
Actually I did test and the provider is still raising an exception.
I'm working toward a debug log extraction

**Comment by zaggash** [comment]
```
21/02/2020 16:38:18|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed': Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in l
ist_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__    provider.initialize()  File "/a
pp/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 136, in initialize    raise Exception("Addic7ed: Couldn't solve captcha!")Exception: Addic7ed: Couldn't solve captcha!|Traceback (most recent 
call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 136, in initialize    raise Exception("Addic7ed: Couldn't solve captcha!")Exception: Addic7ed: Couldn't solve captcha!|
```

**Comment by zaggash** [comment]
I'll actually open a new issue because this one looks different
