### ISSUE TITLE
Post Processing not working / audio_language broken with recent changes to radarr v3 API

### ISSUE THREAD

**Issue by crypto-vault** [morpheus65535/bazarr#851]
**Describe the bug**
Post processing fails

**To Reproduce**
enable post processing
set processing to "echo 0"
You should see in the  logs:
BAZARR Post-processing result for file /tv/xxx/xxx.mkv : 0

**Expected behavior**
Execute post processing with no problems

**Software (please complete the following information):**
 - Bazarr: [v0.8.4.2]
 - Radarr version [v3.0.0.2704]
 - OS: [Unraid]
 - Docker: linuxserver/bazarr

**Error logs **

06/03/2020 09:15:58|ERROR   |apscheduler.executors.default   |Job "Update Movie list from Radarr (trigger: interval[0:05:00], next run at: 2020-03-06 09:20:53 GMT)" raised an exception|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/app/bazarr/bazarr/get_movies.py", line 268, in update_movies\n    movies_download_subtitles(altered_movie[2])\n  File "/app/bazarr/bazarr/get_subtitle.py", line 649, in movies_download_subtitles\n    result = download_subtitle(path_replace_movie(movie[\'path\']),\n  File "/app/bazarr/bazarr/get_subtitle.py", line 238, in download_subtitle\n    command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,\n  File "/app/bazarr/bazarr/helper.py", line 108, in pp_replace\n    pp_command = pp_command.replace(\'{{episode_language}}\', episode_language)\nTypeError: replace() argument 2 must be str, not None'|

2020-03-06 09:57:15 GMT)" raised an exception|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/app/bazarr/bazarr/get_subtitle.py", line 649, in movies_download_subtitles    result = download_subtitle(path_replace_movie(movie['path']),  File "/app/bazarr/bazarr/get_subtitle.py", line 238, in download_subtitle    command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,  File "/app/bazarr/bazarr/helper.py", line 108, in pp_replace    pp_command = pp_command.replace('{{episode_language}}', episode_language)TypeError: replace() argument 2 must be str, not None|

**Comment by morpheus65535** [comment]
Can you try dev branch please?

**Comment by crypto-vault** [comment]
Tested and confirmed it's fixed

**Comment by morpheus65535** [comment]
Yes nothing to do for #309. The patch is to append `2>&1` at the end of your port-processing command.
