### ISSUE TITLE
Post-Processing throws an exception.

### ISSUE THREAD

**Issue by kneza23** [morpheus65535/bazarr#853]
**Description**

When i turn the post-processing ON with any command (the post-processing command can be blank) it downloads the subtitle but it throws an exception in the logs and do not give you success message.

My purpose and idea for using post processing is to execute mkvmerge script to insert the newly downloaded subtitle into the container as my TV won't read subtitles files that are not embedded into the container trough the MiniDLNA service - `mkvmerge -o "{{directory}}"/temp.mkv "{{episode}}" "{{subtitles}}" && rm -f "{{episode}}" && mv "{{directory}}"/temp.mkv "{{episode}}"`

But it is not probably the script fault as when you leave it blank or try any other command it gives you. the same error:

```
Job "movies_download_subtitles_8 (trigger: date[2020-03-07 07:07:17 CST], next run at: 
2020-03-07 07:07:17 CST)" raised an exception
```

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 649, in movies_download_subtitles
  result = download_subtitle(path_replace_movie(movie[\path\]),
 File "/app/bazarr/bazarr/get_subtitle.py", line 238, in download_subtitle
  command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,
 File "/app/bazarr/bazarr/helper.py", line 109, in pp_replace
  pp_command = pp_command.replace(\{{episode_language_code2}}\, episode_language_code2)
TypeError: replace() argument 2 must be str, not None
```

**To Reproduce**
1. Turn on the post-processing 
2. Write the command or leave the command input blank
3. Try to download the title for any movie
4. Go to the logs and check for error

**Expected behavior**
Post-processinng should not raise an exception.

**Software**
 - Bazarr: v0.8.4.2
 - Radarr version: 0.2.0.1480
 - OS: Raspian 

**Additional context**
I initialized the app with https://dockstarter.com/

**Comment by morpheus65535** [comment]
What is the language of the subtitles? Did you enable single language mode?

**Comment by kneza23** [comment]
> What is the language of the subtitles? Did you enable single language mode?

It is the same whatever i use single language mode or not. It is the English language.

**Comment by morpheus65535** [comment]
If you use `echo 0` as post-processing command, does it work?

**Comment by kneza23** [comment]
The same thing happens :(

**Comment by morpheus65535** [comment]
`echo 0` works fine for me with linuxserver image. I have no idea what's wrong with the image you are using.

**Comment by kneza23** [comment]
Any way you can help me maybe? Or throw some advice how to handle or debug this?
When i look at the exception it seams that variable `episode_language_code2` is not defined. Not sure what that has to do with post-processing commands though

**Comment by morpheus65535** [comment]
A Python traceback can be read from bottom-up:
```
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
```

```
 File "/app/bazarr/bazarr/get_subtitle.py", line 649, in movies_download_subtitles
  result = download_subtitle(path_replace_movie(movie[\path\]),
```
This is the original download function that should return a subtitles object with a 3 characters language code. If it's returning `None` as language, that's a provider issue.
```
 File "/app/bazarr/bazarr/get_subtitle.py", line 238, in download_subtitle
  command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,
```
This one is shortened but in fact it's calling the next function with `downloaded_language_code2` value set here: https://github.com/morpheus65535/bazarr/blob/fd339b5fffa14e0e92b9d8aa7ad3de91c3e7698b/bazarr/get_subtitle.py#L220
In fact, the value is the 3 characters language code associated to the `subtitles.language` here: https://github.com/morpheus65535/bazarr/blob/fd339b5fffa14e0e92b9d8aa7ad3de91c3e7698b/bazarr/get_subtitle.py#L218
Bazarr try to convert from 3 characters to 2 characters code using this function that return `None` if unable to find a code2 value for the provided code3 value: https://github.com/morpheus65535/bazarr/blob/fd339b5fffa14e0e92b9d8aa7ad3de91c3e7698b/bazarr/get_languages.py#L49
```
 File "/app/bazarr/bazarr/helper.py", line 109, in pp_replace
  pp_command = pp_command.replace(\{{episode_language_code2}}\, episode_language_code2)
```
This one got `episode_language_code2` value from previous function that was calling `pp_replace`.
```
TypeError: replace() argument 2 must be str, not None
```
Meaning the previous function was waiting for a language code of 2 character that should be a `string` but instead got a `None` value (meaning `null`).

I would say it either a provider issue, an unknown language code returned by subliminal_patch or a problem with your `table_settings_languages` database table.

**Comment by kneza23** [comment]
@morpheus65535Thanks for the explanation above. 

But i have downgraded my version with docker override to v0.8.4.1. This is the image https://github.com/linuxserver/docker-bazarr and now it seams that the problem is solved :), there is no more exception end with `echo 0` i get:
```
BAZARR Post-processing result for file .... : 0
```
That seems good now.

**Comment by morpheus65535** [comment]
Could be related to missing audio_language. Is this your case?

**Comment by morpheus65535** [comment]
I'm closing this issue for inactivity. Please reopen it if you still have the issue.

**Comment by kneza23** [comment]
Yeah i have fixed it with downgrading back one version for it to work

**Comment by morpheus65535** [comment]
But you're stuck there. That's not a real fix. :-/

**Comment by kneza23** [comment]
Yeah i know, probably there is something wrong with audio_language like you said on the last version

**Comment by morpheus65535** [comment]
Unless you help me debug your issue, there's no chance it get fixed soon.

**Comment by morpheus65535** [comment]
This fix should fix your issue.

**Comment by morpheus65535** [comment]
Confirmed fix by the user.
