### ISSUE TITLE
Unexpected error in provider 'legendastv':  FileNotFoundError.

### ISSUE THREAD

**Issue by danielsnipher** [morpheus65535/bazarr#878]
Error when downloading a subtitle from Legendas.Tv, TV Show Young Sheldon S03E16.

Full log attached: [bazarr.log](https://github.com/morpheus65535/bazarr/files/4365680/bazarr.log)

```
22/03/2020 14:18:37|DEBUG   |subliminal.providers.legendastv |Found 1 archives|
22/03/2020 14:18:37|INFO    |subliminal_patch.providers.legendastv|Releases not found in cache|
22/03/2020 14:18:37|INFO    |subliminal.providers.legendastv |Downloading archive 5e54ef076a508|
22/03/2020 14:18:38|DEBUG   |urllib3.connectionpool          |http://legendas.tv:80 "GET /downloadarquivo/5e54ef076a508 HTTP/1.1" 302 20|
22/03/2020 14:18:38|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): ltv-backup.ams3.cdn.digitaloceanspaces.com:443|
22/03/2020 14:18:38|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on ltv-backup.ams3.cdn.digitaloceanspaces.com|
22/03/2020 14:18:40|DEBUG   |urllib3.connectionpool          |https://ltv-backup.ams3.cdn.digitaloceanspaces.com:443 "GET /files/39/75/legendas_tv_20200225095524835.zip HTTP/1.1" 200 173059|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |SHIFT_JIS Japanese prober hit error at byte 84|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |EUC-JP Japanese prober hit error at byte 11|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |GB2312 Chinese prober hit error at byte 81|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |EUC-KR Korean prober hit error at byte 11|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |CP949 Korean prober hit error at byte 11|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |Big5 Chinese prober hit error at byte 80|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |EUC-TW Taiwan prober hit error at byte 11|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |windows-1251 confidence = 0.03809897696283319, below negative shortcut threshhold 0.05|
22/03/2020 14:18:40|DEBUG   |chardet.charsetprober           |KOI8-R confidence = 0.04393568058467977, below negative shortcut threshhold 0.05|
22/03/2020 14:18:41|DEBUG   |chardet.charsetprober           |ISO-8859-5 confidence = 0.03871892149443886, below negative shortcut threshhold 0.05|
22/03/2020 14:18:41|DEBUG   |chardet.charsetprober           |MacCyrillic confidence = 0.040165112942729585, below negative shortcut threshhold 0.05|
22/03/2020 14:18:42|DEBUG   |chardet.charsetprober           |IBM866 confidence = 0.033876995516456156, below negative shortcut threshhold 0.05|
22/03/2020 14:18:42|DEBUG   |chardet.charsetprober           |IBM855 confidence = 0.04114892423688727, below negative shortcut threshhold 0.05|
22/03/2020 14:18:43|DEBUG   |chardet.charsetprober           |ISO-8859-5 confidence = 0.03933978207299037, below negative shortcut threshhold 0.05|
22/03/2020 14:18:44|DEBUG   |chardet.charsetprober           |windows-1251 confidence = 0.039060321775763705, below negative shortcut threshhold 0.05|
22/03/2020 14:18:44|DEBUG   |chardet.charsetprober           |TIS-620 confidence = 0.048321412583934, below negative shortcut threshhold 0.05|
22/03/2020 14:18:45|DEBUG   |chardet.charsetprober           |windows-1255 confidence = 0.04178411305161667, below negative shortcut threshhold 0.05|
22/03/2020 14:18:45|DEBUG   |chardet.charsetprober           |windows-1255 confidence = 0.04212351469192763, below negative shortcut threshhold 0.05|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |windows-1251 not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |KOI8-R not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |ISO-8859-5 not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |MacCyrillic not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |IBM866 not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |IBM855 not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |ISO-8859-7 Greek confidence = 0.07059213624155208|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |windows-1253 Greek confidence = 0.07183352409459642|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |ISO-8859-5 not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |windows-1251 not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |TIS-620 not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |ISO-8859-9 Turkish confidence = 0.058607196469171154|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |windows-1255 Hebrew confidence = 0.0|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |windows-1255 not active|
22/03/2020 14:18:46|DEBUG   |chardet.charsetprober           |windows-1255 not active|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |no probers hit minimum threshold|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |utf-8  confidence = 0.010000000000000009|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |SHIFT_JIS Japanese confidence = 0.01|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |EUC-JP Japanese confidence = 0.01|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |GB2312 Chinese confidence = 0.01|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |EUC-KR Korean confidence = 0.01|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |CP949 Korean confidence = 0.01|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |Big5 Chinese confidence = 0.01|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |EUC-TW Taiwan confidence = 0.01|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |windows-1251 Russian confidence = 0.03809897696283319|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |KOI8-R Russian confidence = 0.04393568058467977|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |ISO-8859-5 Russian confidence = 0.03871892149443886|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |MacCyrillic Russian confidence = 0.040165112942729585|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |IBM866 Russian confidence = 0.033876995516456156|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |IBM855 Russian confidence = 0.04114892423688727|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |ISO-8859-7 Greek confidence = 0.07059213624155208|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |windows-1253 Greek confidence = 0.07183352409459642|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |ISO-8859-5 Bulgairan confidence = 0.03933978207299037|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |windows-1251 Bulgarian confidence = 0.039060321775763705|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |TIS-620 Thai confidence = 0.048321412583934|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |ISO-8859-9 Turkish confidence = 0.058607196469171154|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |windows-1255 Hebrew confidence = 0.0|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |windows-1255 Hebrew confidence = 0.04178411305161667|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |windows-1255 Hebrew confidence = 0.04212351469192763|
22/03/2020 14:18:46|DEBUG   |chardet.universaldetector       |windows-1255 Hebrew confidence = 0.04212351469192763|
22/03/2020 14:18:46|DEBUG   |subliminal.providers.legendastv |Identified zip archive|
22/03/2020 14:18:46|ERROR   |subliminal_patch.core           |Unexpected error in provider 'legendastv': Traceback (most recent call last):  File "C:\Bazarr\WinPython\python-3.8.0\lib\shutil.py", line 780, in move    os.rename(src, real_dst)FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\WINDOWS\\TEMP\\tmpfq8b2qh2' -> 'C:\\ProgramData\\Bazarr\\cache\\356535346566303736613530387c596f756e672e5368656c646f6e2e5330334531362e5b7765622e686474765d2e5b783236342e783236352e587669445d2d5356412d4146472d494f4e31302d4e54622d6d53442d4156532d5a4d4e542d414d434f4e2d4d694e582d414d5241502d62616d626f6f7a6c65'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "c:\bazarr\bazarr\../libs\subliminal_patch\core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "c:\bazarr\bazarr\../libs\subliminal_patch\providers\legendastv.py", line 250, in list_subtitles    subtitles = [s for l in languages for s in  File "c:\bazarr\bazarr\../libs\subliminal_patch\providers\legendastv.py", line 251, in <listcomp>    self.query(l, title, season=season, episode=episode, year=video.year, imdb_id=video.imdb_id)]  File "c:\bazarr\bazarr\../libs\subliminal_patch\providers\legendastv.py", line 229, in query    region.set(cache_key, releases)  File "c:\bazarr\bazarr\../libs\dogpile\cache\region.py", line 1030, in set    self.backend.set(key, self._value(value))  File "c:\bazarr\bazarr\../libs\subzero\cache_backends\file.py", line 26, in set    self._cache[key] = value  File "c:\bazarr\bazarr\../libs\fcache\cache.py", line 267, in __setitem__    self._write_to_file(filename, value)  File "c:\bazarr\bazarr\../libs\fcache\cache.py", line 249, in _write_to_file    rename(tmp, filename)  File "c:\bazarr\bazarr\../libs\fcache\posixemulation.py", line 80, in rename    shutil.move(src, dst)  File "C:\Bazarr\WinPython\python-3.8.0\lib\shutil.py", line 794, in move    copy_function(src, real_dst)  File "C:\Bazarr\WinPython\python-3.8.0\lib\shutil.py", line 426, in copy2    copyfile(src, dst, follow_symlinks=follow_symlinks)  File "C:\Bazarr\WinPython\python-3.8.0\lib\shutil.py", line 259, in copyfile    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Bazarr\\cache\\356535346566303736613530387c596f756e672e5368656c646f6e2e5330334531362e5b7765622e686474765d2e5b783236342e783236352e587669445d2d5356412d4146472d494f4e31302d4e54622d6d53442d4156532d5a4d4e542d414d434f4e2d4d694e582d414d5241502d62616d626f6f7a6c65'|Traceback (most recent call last):  File "C:\Bazarr\WinPython\python-3.8.0\lib\shutil.py", line 780, in move    os.rename(src, real_dst)FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\WINDOWS\\TEMP\\tmpfq8b2qh2' -> 'C:\\ProgramData\\Bazarr\\cache\\356535346566303736613530387c596f756e672e5368656c646f6e2e5330334531362e5b7765622e686474765d2e5b783236342e783236352e587669445d2d5356412d4146472d494f4e31302d4e54622d6d53442d4156532d5a4d4e542d414d434f4e2d4d694e582d414d5241502d62616d626f6f7a6c65'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "c:\bazarr\bazarr\../libs\subliminal_patch\core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "c:\bazarr\bazarr\../libs\subliminal_patch\providers\legendastv.py", line 250, in list_subtitles    subtitles = [s for l in languages for s in  File "c:\bazarr\bazarr\../libs\subliminal_patch\providers\legendastv.py", line 251, in <listcomp>    self.query(l, title, season=season, episode=episode, year=video.year, imdb_id=video.imdb_id)]  File "c:\bazarr\bazarr\../libs\subliminal_patch\providers\legendastv.py", line 229, in query    region.set(cache_key, releases)  File "c:\bazarr\bazarr\../libs\dogpile\cache\region.py", line 1030, in set    self.backend.set(key, self._value(value))  File "c:\bazarr\bazarr\../libs\subzero\cache_backends\file.py", line 26, in set    self._cache[key] = value  File "c:\bazarr\bazarr\../libs\fcache\cache.py", line 267, in __setitem__    self._write_to_file(filename, value)  File "c:\bazarr\bazarr\../libs\fcache\cache.py", line 249, in _write_to_file    rename(tmp, filename)  File "c:\bazarr\bazarr\../libs\fcache\posixemulation.py", line 80, in rename    shutil.move(src, dst)  File "C:\Bazarr\WinPython\python-3.8.0\lib\shutil.py", line 794, in move    copy_function(src, real_dst)  File "C:\Bazarr\WinPython\python-3.8.0\lib\shutil.py", line 426, in copy2    copyfile(src, dst, follow_symlinks=follow_symlinks)  File "C:\Bazarr\WinPython\python-3.8.0\lib\shutil.py", line 259, in copyfile    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Bazarr\\cache\\356535346566303736613530387c596f756e672e5368656c646f6e2e5330334531362e5b7765622e686474765d2e5b783236342e783236352e587669445d2d5356412d4146472d494f4e31302d4e54622d6d53442d4156532d5a4d4e542d414d434f4e2d4d694e582d414d5241502d62616d626f6f7a6c65'|
22/03/2020 14:18:46|INFO    |root                            |Throttling legendastv for 10 minutes, until 20/03/22 14:28, because of: FileNotFoundError. Exception info: 2|
22/03/2020 14:18:46|INFO    |subliminal_patch.core           |Discarding provider legendastv|
```

**Comment by morpheus65535** [comment]
It's working fine for me in manual or automatic search/download.

It looks like the file created by the cache mechanism have been deleted from temp directory and Bazarr is unable to move a missing file.

Something is interfering in your temp directory content.

**Comment by danielsnipher** [comment]
Some extra info:
OS: Windows 10 Home 1909
Running from Windows Installer

Renamed to TXT to upload here, the file exists in C:\Windows\Temp, but are not copying to Bazarr cache folder.
[tmpfq8b2qh2.txt](https://github.com/morpheus65535/bazarr/files/4369207/tmpfq8b2qh2.txt)

I made some tests and the difference between the archives are this archive with error has a TXT file on it, another archive that worked doesn't have the TXT file.

**Comment by morpheus65535** [comment]
@pannal something you can do about this one? I'm not that familiar with your cache provider.

**Comment by danielsnipher** [comment]
Hello, I have some extra info.

If I remove the txt extension from the variable below, the error disappear from Bazarr Log.

>subtitle.py
>
>SUBTITLE_EXTENSIONS = ('.srt', '.sub', '.smi', '.txt', '.ssa', '.ass', '.mpl')


See log attached. [bazarr.log](https://github.com/morpheus65535/bazarr/files/4399171/bazarr.log)


Instead the error below appear when calling manual_search page.
>http://192.168.0.228:6767/manual_search

>Form Data
>episodePath: F:\Seriados\Young Sheldon\Season 3\Young.Sheldon.S03E16.iNTERNAL.720p.WEB.H264.1-AMRAP.mkv
sceneName: Young.Sheldon.S03E16.iNTERNAL.720p.WEB.H264.1-AMRAP
language: ['pb', 'en']
hi: False
forced: False
sonarrSeriesId: 22
sonarrEpisodeId: 2927
title: Young Sheldon

DataTables warning: table id=search_result - Ajax error. For more information about this error, please see http://datatables.net/tn/7

Html with error attached.
[Html_error.txt](https://github.com/morpheus65535/bazarr/files/4399172/Html_error.txt)

**Comment by danielsnipher** [comment]
Found the problem, Windows has a 260 character maximum path limitation, doing the steps below fixes the issue, [How to Make Windows 10 Accept File Paths Over 260 Characters](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/).
