### ISSUE TITLE
supersubtitles IndexError

### ISSUE THREAD

**Issue by likeaRAINBOW** [morpheus65535/bazarr#882]
**Software (please complete the following information):**
 - Bazarr: [0.8.4.3]
 - OS: [ubuntu 18.04]
 - Python: [3.8.2]

**Log**
```
24/03/2020 11:17:50|ERROR   |subliminal_patch.core           |Unexpected error in provider 'supersubtitles': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 365, in list_subtitles    subs = self.query(title, video=video)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 278, in query    subtitle = self.process_subs(series, video, url)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 329, in process_subs    sub_english_name = re.findall(r'(?<=<div class="eredeti">).*?(?=\()', str(sub_english))[0]IndexError: list index out of range|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 365, in list_subtitles    subs = self.query(title, video=video)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 278, in query    subtitle = self.process_subs(series, video, url)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/supersubtitles.py", line 329, in process_subs    sub_english_name = re.findall(r'(?<=<div class="eredeti">).*?(?=\()', str(sub_english))[0]IndexError: list index out of range|
24/03/2020 11:17:50|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 20/03/24 11:27, because of: IndexError. Exception info: 'list index out of range'|
```

**Comment by morpheus65535** [comment]
I cannot reproduce your issue even for a movie that do not have subtitles available.

I'm going to need a complete debug log (emptied first) while reproducing this issue.

**Comment by likeaRAINBOW** [comment]
The only movie i get this error is The Gentleman, the new, Guy Ritchie one.

**Comment by morpheus65535** [comment]
Can you find it when doing a search on the website?

**Comment by likeaRAINBOW** [comment]
Yes, i can:

https://www.feliratok.info/index.php?search=the+gentlemen&soriSorszam=&nyelv=&tab=film

The first 2.

**Comment by morpheus65535** [comment]
There's only 2 matching and they've been added only yesterday. Can you test again to make sure it's really an issue?

**Comment by likeaRAINBOW** [comment]
Sorry for the late answer, just now had time for debug.
So, another movie drop fail, 28 weeks later, if you search on website, i get 15 found entry in eng and hub subs.

I dropped the log, and generate new one, i hope it makes easier to debug this.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4398938/bazarr.log)

**Comment by morpheus65535** [comment]
Is it still an issue? I still cannot reproduce it and, to be honest, almost 5000 subtitles have been downloaded from this provider yesterday alone...

**Comment by morpheus65535** [comment]
Closing issue, no answer.
