### ISSUE TITLE
OpenSubtitles - LanguageConvertError

### ISSUE THREAD

**Issue by nikolicjakov** [morpheus65535/bazarr#949]
**Describe the bug**
While using OpenSubtitles provider with VIP account i am getting LanguageConvertError. I have selected 3 languages Croatian, Serbian and Bosnian.

**To Reproduce**
1. Set OpenSubtitles as provider
2. Set languages Croatian, Serbian, Bosnian
3. Search for subtitles

**Expected behavior**
If language is found it should be downloaded and no LanguageConvertError should block OpenSubtitles provider.

**Screenshots**
https://imgur.com/pmVuymY

**Software (please complete the following information):**
 - Bazarr: 0.8.4.2
 - Radarr version 0.2.0.1480
 - Sonarr version 2.0.0.5344
 - OS: Alpine Linux Docker

**Debug Log**
```
2020-04-26 17:11:26,056 - subliminal_patch.providers.opensubtitles (7f31aa619b20) :  DEBUG (opensubtitles:155) - Logged in with token 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
bazarr           | 2020-04-26 17:11:26,058 - subliminal_patch.core            (7f31aa619b20) :  ERROR (core:196) - Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
bazarr           |   File "/app/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 157, in convert
bazarr           |     return self.to_symbol[alpha3]
bazarr           | KeyError: 'hbs'
bazarr           |
bazarr           | During handling of the above exception, another exception occurred:
bazarr           |
bazarr           | Traceback (most recent call last):
bazarr           |   File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider
bazarr           |     results = self[provider].list_subtitles(video, provider_languages)
bazarr           |   File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 237, in list_subtitles
bazarr           |     return self.query(languages, hash=video.hashes.get('opensubtitles'), size=video.size, imdb_id=video.imdb_id,
bazarr           |   File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 266, in query
bazarr           |     criterion['sublanguageid'] = ','.join(sorted(l.opensubtitles for l in languages))
bazarr           |   File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 266, in <genexpr>
bazarr           |     criterion['sublanguageid'] = ','.join(sorted(l.opensubtitles for l in languages))
bazarr           |   File "/app/bazarr/bazarr/../libs/subzero/language.py", line 112, in __getattr__
bazarr           |     ret = super(Language, self).__getattr__(name)
bazarr           |   File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 149, in __getattr__
bazarr           |     return language_converters[name].convert(alpha3, country, script)
bazarr           |   File "/app/bazarr/bazarr/../libs/babelfish/converters/opensubtitles.py", line 23, in convert
bazarr           |     alpha3b = self.alpha3b_converter.convert(alpha3, country, script)
bazarr           |   File "/app/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 159, in convert
bazarr           |     raise LanguageConvertError(alpha3, country, script)
bazarr           | babelfish.exceptions.LanguageConvertError: hbs
bazarr           | Traceback (most recent call last):
bazarr           |   File "/app/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 157, in convert
bazarr           |     return self.to_symbol[alpha3]
bazarr           | KeyError: 'hbs'
bazarr           |
bazarr           | During handling of the above exception, another exception occurred:
bazarr           |
bazarr           | Traceback (most recent call last):
bazarr           |   File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider
bazarr           |     results = self[provider].list_subtitles(video, provider_languages)
bazarr           |   File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 237, in list_subtitles
bazarr           |     return self.query(languages, hash=video.hashes.get('opensubtitles'), size=video.size, imdb_id=video.imdb_id,
bazarr           |   File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 266, in query
bazarr           |     criterion['sublanguageid'] = ','.join(sorted(l.opensubtitles for l in languages))
bazarr           |   File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/opensubtitles.py", line 266, in <genexpr>
bazarr           |     criterion['sublanguageid'] = ','.join(sorted(l.opensubtitles for l in languages))
bazarr           |   File "/app/bazarr/bazarr/../libs/subzero/language.py", line 112, in __getattr__
bazarr           |     ret = super(Language, self).__getattr__(name)
bazarr           |   File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 149, in __getattr__
bazarr           |     return language_converters[name].convert(alpha3, country, script)
bazarr           |   File "/app/bazarr/bazarr/../libs/babelfish/converters/opensubtitles.py", line 23, in convert
bazarr           |     alpha3b = self.alpha3b_converter.convert(alpha3, country, script)
bazarr           |   File "/app/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 159, in convert
bazarr           |     raise LanguageConvertError(alpha3, country, script)
bazarr           | babelfish.exceptions.LanguageConvertError: hbs
```

**Comment**
It points again to Serbo-Croatian language code 'hbs' but i dont have that language configured in Bazarr.

**Comment by nikolicjakov** [comment]
It points again to Serbo-Croatian language code 'hbs' but i dont have that language configured in Bazarr.

**Comment by morpheus65535** [comment]
Try to edit desired languages for that specific series/movie. I feel like that hbs is still desired for some series/movie. You can also provide me your bazarr.db and I'll take a look at it.
