### ISSUE TITLE
LegendasDivX - FeatureNotFound

### ISSUE THREAD

**Issue by JpF4E** [morpheus65535/bazarr#956]
**Describe the bug**
The bug is simple, when searching for subtitles in this provider, it fails with an error and stacktrace.

**To Reproduce**
1. I added the movie Jojo Rabbit
2. Searching subtitles for this movie in the provider fails with error

**Expected behavior**
To not fail.

**Screenshots**
Not needed.

**Software (please complete the following information):**
 - Bazarr: v 0.8.4.4
 - Radarr version: v 0.2.0.1480
 - OS: CentOS 8

**Additional context**
Logs:
```
28/04/2020 00:44:53|DEBUG   |urllib3.connectionpool          |https://www.legendasdivx.pt:443 "GET /forum/ucp.php?mode=login HTTP/1.1" 200 4336|
28/04/2020 00:44:53|ERROR   |subliminal_patch.core           |Unexpected error in provider 'legendasdivx': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__    provider.initialize()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 138, in initialize    self.login()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 149, in login    bsoup = ParserBeautifulSoup(res.content, ['lxml'])  File "/opt/bazarr/bazarr/../libs/subliminal/providers/__init__.py", line 52, in __init__    raise FeatureNotFoundbs4.FeatureNotFound|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__    provider.initialize()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 138, in initialize    self.login()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 149, in login    bsoup = ParserBeautifulSoup(res.content, ['lxml'])  File "/opt/bazarr/bazarr/../libs/subliminal/providers/__init__.py", line 52, in __init__    raise FeatureNotFoundbs4.FeatureNotFound|
28/04/2020 00:44:53|INFO    |root                            |Throttling legendasdivx for 10 minutes, until 20/04/28 00:54, because of: FeatureNotFound. Exception info: None|
28/04/2020 00:44:53|INFO    |subliminal_patch.core           |Discarding provider legendasdivx|
```

**Comment by morpheus65535** [comment]
@GermanG you have some time to look into this one please?

**Comment by GermanG** [comment]
@JpF4E can you please attach the whole log?

**Comment by halali** [comment]
He is missing lxml library

**Comment by JpF4E** [comment]
> He is missing lxml library

You were right!
