### ISSUE TITLE
Can't download subtitles

### ISSUE THREAD

**Issue by janmarco** [morpheus65535/bazarr#978]
**Describe the bug**
When I try to download subtitles I get this error:

Traceback (most recent call last):
 File "/app/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/get_subtitle.py", line 700, in movies_download_subtitles
  \movie\)
 File "/app/bazarr/get_subtitle.py", line 241, in download_subtitle
  audio_language_code2, audio_language_code3, subtitle.language.forced)
 File "/app/bazarr/helper.py", line 109, in pp_replace
  pp_command = pp_command.replace(\{{episode_language_code2}}\, episode_language_code2)
TypeError: replace() argument 2 must be str, not None

**Software (please complete the following information):**
 - Bazarr: 0.8.4.3
 - Radarr version 0.2.0.1480
 - Sonarr version 3.0.3.790
 - OS: Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-19.10-eoan

**Comment by morpheus65535** [comment]
You probably have an issue in your post-processing command. Let discuss this over Discord support channel.
