### ISSUE TITLE
Cannot change Sonarr host (HTTP → HTTPS)

### ISSUE THREAD

**Issue by wsw70** [morpheus65535/bazarr#982]
**Describe the bug**

Cannot change Sonarr host once it was successfully tested. Radarr is OK

**To Reproduce**

I had a working instance of Bazarr (running in a docker container). It was connecting to `sonarr.example.info` on port 80.

I then changed my Sonarr setup to move it to TLS, which also changed its URL:
- old URL: `http://sonarr.example.info`
- new URL: `https://sonarr.example.net` (two changes: the `s` is `https`, and the extension)

`https://sonarr.example.net` is correctly displayed in a browser.

**Expected behavior**

I expected that I would just need to change in the settings the hostname, the port (`80` → `443`) and flip the TLS switch.

The test of this new setup fails, it seems in the log below that the **hostname** is not changed during the test, while the other elements are:

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 600, in urlopen
  httplib_response = self._make_request(conn, method, url,
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 344, in _make_request
  self._validate_conn(conn)
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 843, in _validate_conn
  conn.connect()
 File "/app/bazarr/bazarr/../libs/urllib3/connection.py", line 362, in connect
  self.sock = ssl_wrap_socket(
 File "/app/bazarr/bazarr/../libs/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
  return context.wrap_socket(sock, server_hostname=server_hostname)
 File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
  return self.sslsocket_class._create(
 File "/usr/lib/python3.8/ssl.py", line 1040, in _create
  self.do_handshake()
 File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
  self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/requests/adapters.py", line 439, in send
  resp = conn.urlopen(
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 640, in urlopen
  retries = retries.increment(method, url, error=e, _pool=self,
 File "/app/bazarr/bazarr/../libs/urllib3/util/retry.py", line 399, in increment
  raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\sonarr.example.info\, port=443): Max retries exceeded with url: /api/series?apikey=57d224a7dc824657a5d2b40d0b3165cd (Caused by SSLError(SSLError(1, \[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1108)\)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_series.py", line 34, in update_series
  r = requests.get(url_sonarr_api_series, timeout=60, verify=False)
 File "/app/bazarr/bazarr/../libs/requests/api.py", line 75, in get
  return request(\get\, url, params=params, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/api.py", line 60, in request
  return session.request(method=method, url=url, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 533, in request
  resp = self.send(prep, **send_kwargs)
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 668, in send
  history = [resp for resp in gen] if allow_redirects else []
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 668, in
  history = [resp for resp in gen] if allow_redirects else []
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 239, in resolve_redirects
  resp = self.send(
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 646, in send
  r = adapter.send(request, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/adapters.py", line 514, in send
  raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host=\sonarr.example.info\, port=443): Max retries exceeded with url: /api/series?apikey=57d224a7dc824657a5d2b40d0b3165cd (Caused by SSLError(SSLError(1, \[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1108)\)))
```

Please note in the `requests` call that `HTTPSConnectionPool(host=\sonarr.example.info\, port=443)` → the host points to the **old** name, the port points to the **new** port.

On the other hand, the change for Radarr was accepted.

**Software (please complete the following information):**
 - Bazarr: `0.8.4.3`
 - Radarr version: `0.2.0.1480`
 - Sonarr version: `2.0.0.5344`
 - OS: docker container `linuxserver/bazarr`

**Comment by wsw70** [comment]
I digged a bit more into the problem.

As a starter, I enabled debug logging and I see in the logs that there is an attempt to connect to the new URL:

    13/05/2020 13:54:30|DEBUG   |urllib3.connectionpool          |https://sonarr.example.net:443 "GET /api/system/status?apikey=********cd HTTP/1.1" 401 29|

It looks like it returns a **401**.

Going into the container, I tried a `curl` call similar to the one above:

```
root@7713886d95d9:/# curl https://sonarr.example.net:443/api/system/status?apikey=57<rest of the key>
{
  "error": "Unauthorized"
}
```

Ha. 

It looks like there is a problem on sonarr end (the API key is correct). I will close that issue for now and go see with sonarr where the problem can be.

**Comment by morpheus65535** [comment]
Sounds good to me. Come back to Discord support channel if you need help!
