### ISSUE TITLE
BAZARR Error trying to get video information for this file

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#984]
Bazarr Version:
0.8.4.4
Sonarr Version:
2.0.0.5344
Radarr Version:
0.2.0.1480
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.2

newest docker development version 0.8.4.4

```
BAZARR Error trying to get video information for this file: /movies/Arkansas (2020) [Bluray-1080p, AC3, 5.1]/Arkansas.2020.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG[TGx].mkv
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/guessit/api.py", line 120, in guessit
  matches = self.rebulk.matches(string, options)
 File "/app/bazarr/bazarr/../libs/rebulk/rebulk.py", line 288, in matches
  self._execute_rules(matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rebulk.py", line 319, in _execute_rules
  rules.execute_all_rules(matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 318, in execute_all_rules
  when_response = execute_rule(rule, matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 343, in execute_rule
  rule.then(matches, when_response, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 122, in then
  cons.then(matches, next(iterator), context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 206, in then
  removed = self.remove.then(matches, when_response, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 140, in then
  matches.remove(match)
 File "/usr/lib/python3.8/_collections_abc.py", line 997, in remove
  del self[self.index(value)]
 File "/app/bazarr/bazarr/../libs/rebulk/match.py", line 565, in __delitem__
  self._remove_match(match)
 File "/app/bazarr/bazarr/../libs/rebulk/match.py", line 133, in _remove_match
  _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 71, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
 File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video
  return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 526, in scan_video
  guessed_result = guessit(guess_from, options=hints)
 File "/app/bazarr/bazarr/../libs/guessit/api.py", line 54, in guessit
  return default_api.guessit(string, options)
 File "/app/bazarr/bazarr/../libs/guessit/api.py", line 132, in guessit
  raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.4
string=Arkansas (2020) [Bluray-1080p, AC3, 5.1]/Arkansas.2020.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG.mkv
options={\title\: \Arkansas\, \type\: \movie\, \single_value\: True, \expected_title\: [\Arkansas\]}
--------------------------------------------------------------------
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/guessit/api.py", line 120, in guessit
  matches = self.rebulk.matches(string, options)
 File "/app/bazarr/bazarr/../libs/rebulk/rebulk.py", line 288, in matches
  self._execute_rules(matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rebulk.py", line 319, in _execute_rules
  rules.execute_all_rules(matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 318, in execute_all_rules
  when_response = execute_rule(rule, matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 343, in execute_rule
  rule.then(matches, when_response, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 122, in then
  cons.then(matches, next(iterator), context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 206, in then
  removed = self.remove.then(matches, when_response, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 140, in then
  matches.remove(match)
 File "/usr/lib/python3.8/_collections_abc.py", line 997, in remove
  del self[self.index(value)]
 File "/app/bazarr/bazarr/../libs/rebulk/match.py", line 565, in __delitem__
  self._remove_match(match)
 File "/app/bazarr/bazarr/../libs/rebulk/match.py", line 133, in _remove_match
  _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list`
```

i also have sent these issue on guessit:
[https://github.com/guessit-io/guessit/issues/645](url)

**Comment by morpheus65535** [comment]
How did you install Python 3.8.2 on QNAP? Is it by compiling sources? Looks like a conflict between the regex module included in Bazarr and the one installed on your system.

**Comment by lukjod** [comment]
nope only one included into docker from linuxserver, strange as those movies are on disc since a few weeks and this error came within last 2 versions from development. What info do You need from concole?

**Comment by morpheus65535** [comment]
Wait, you're running Bazarr using Docker or from source? You don't need to install Python if you are using a Docker image. Tell me more about how you setup your stuff.

**Comment by lukjod** [comment]
ok
in my setup for bazarr and jackett I use docker images from linuxserver.io.
For other aps like sonarr, radarr, jdownloader i use app center qpkg applications and some repositories also added from entware. Concerning Python bazarr use docker version and other apps 3.8.0 version from app center

**Comment by morpheus65535** [comment]
That's an issue with Guessit 2.1.4 that we have bundled in Bazarr. There's nothing to do other than update it on my side but it require a lot of work and testing. I'll add this issue to the list of justification to do it... :-/

Regarding this single movie, I suggest you download the subtitles from the provider website and upload it in Bazarr. It's not sexy but at least you missing count will get down.

With 2.1.4:
```
For: Arkansas (2020) [Bluray-1080p, AC3, 5.1]/Arkansas.2020.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG.mkv
GuessIt found: {
    "title": "Arkansas",
    "season": 20,
    "year": 2020,
    "format": "BluRay",
    "screen_size": "1080p",
    "audio_codec": "AC3",
    "audio_channels": "5.1",
    "size": "1400MB",
    "video_codec": "h264",
    "release_group": "GalaxyRG",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

With 3.1.1:
```
For: Arkansas (2020) [Bluray-1080p, AC3, 5.1]/Arkansas.2020.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG.mkv
GuessIt found: {
    "title": "Arkansas",
    "year": 2020,
    "source": "Blu-ray",
    "screen_size": "1080p",
    "audio_codec": "Dolby Digital",
    "audio_channels": "5.1",
    "size": "1400MB",
    "video_codec": "H.264",
    "release_group": "GalaxyRG",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "movie"
}
```

**Comment by lukjod** [comment]
ok thx for clarification

**Comment by morpheus65535** [comment]
@lukjod I've updated guessit in dev branch if you want to test it.

**Comment by lukjod** [comment]
ok I have downloaded it from docker.
Version 0.9 right?
will see if all is ok
btw
Very nice new look

**Comment by lukjod** [comment]
For now no more errors so probably all is ok now
thx
