### ISSUE TITLE
Bazarr crashes immediately after starting

### ISSUE THREAD

**Issue by neslinesli93** [morpheus65535/bazarr#995]
**Describe the bug**
Bazarr crashes immediately after start

**To Reproduce**
1. Launch `python3 bazarr.py`

**Expected behavior**
Should launch bazarr successfully

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: latest version from master
 - Radarr version 0.2.0.1450
 - Sonarr version 2.0.0.5343
 - OS: DietPi v6.28.0 on RPi 4 Model B (armv7l)

**Additional context**
Stacktrace:

```python
root@DietPi:/opt/bazarr# python3 bazarr.py 
Bazarr starting...
Traceback (most recent call last):
  File "bazarr/main.py", line 36, in <module>
    from init import *
  File "/opt/bazarr/bazarr/init.py", line 15, in <module>
    import subliminal
  File "/opt/bazarr/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/opt/bazarr/bazarr/../libs/subliminal/core.py", line 30, in <module>
    from guessit import guessit
  File "/opt/bazarr/bazarr/../libs/guessit/__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "/opt/bazarr/bazarr/../libs/guessit/api.py", line 151, in <module>
    default_api = GuessItApi(rebulk_builder())
  File "/opt/bazarr/bazarr/../libs/guessit/rules/__init__.py", line 50, in rebulk_builder
    rebulk.rebulk(episodes())
  File "/opt/bazarr/bazarr/../libs/guessit/rules/properties/episodes.py", line 150, in episodes
    validator={'__parent__': seps_before}).repeater('+') \
  File "/opt/bazarr/bazarr/../libs/rebulk/chain.py", line 115, in regex
    pattern = self.rebulk.build_re(*pattern, **kwargs)
  File "/opt/bazarr/bazarr/../libs/rebulk/rebulk.py", line 133, in build_re
    return RePattern(*pattern, **kwargs)
  File "/opt/bazarr/bazarr/../libs/rebulk/pattern.py", line 378, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/opt/bazarr/bazarr/../libs/rebulk/loose.py", line 50, in call
    return function(*call_args, **call_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'abbreviations'
Traceback (most recent call last):
  File "bazarr.py", line 86, in <module>
    os.wait()
ChildProcessError: [Errno 10] No child processes
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "bazarr.py", line 37, in <lambda>
    atexit.register(lambda: ep.kill())
  File "/usr/lib/python3.7/subprocess.py", line 1756, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.7/subprocess.py", line 1746, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
root@DietPi:/opt/bazarr# 

```

I've installed Bazarr using git, and my clone was done on ~ 3rd May 2020. I've tried poor man bisect, going to previous release, as well as going to 3rd May latest commit, but Bazarr keeps crashing

**Comment by morpheus65535** [comment]
Can you try to stop Bazarr, execute `git checkout development` and `git pull` then start Bazarr?

**Comment by neslinesli93** [comment]
Oh well, now it works... Thanks! Should I stay on development branch then? Also, is there a way to disable git auto-update? I guess development branch may break from time to time

**Comment by morpheus65535** [comment]
> Oh well, now it works... Thanks! Should I stay on development branch then? Also, is there a way to disable git auto-update? I guess development branch may break from time to time

You can stay on dev branch without any issue. It's quite stable so I wouldn't worry about disabling auto-update.
